### ISSUE TITLE
update RestClient.java to use HEAD /{index}/_mapping/{type} instead of deprecated HEAD /{index}/{type}

### ISSUE THREAD

**Issue by simonlucalandi** [elastic/elasticsearch-hadoop#1020]
### Issue description
ES 5.5.0 doesn't support anymore requests like HEAD /{index}/{type} , as used in method exists of org.elasticsearch.hadoop.rest.RestClient . Now it should be HEAD /{index}/_mapping/{type}
Description

### Steps to reproduce

Code:

```
val elasticSearchIndex = "spark/docs"
rdd.saveToEs(elasticSearchIndex)
```

Strack trace:

```
 org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: [HEAD] on [spark/docs] failed; server[172.31.7.214:9200] returned [400|Bad Request:]
        at org.elasticsearch.hadoop.rest.RestClient.checkResponse(RestClient.java:505)
        at org.elasticsearch.hadoop.rest.RestClient.executeNotFoundAllowed(RestClient.java:476)
        at org.elasticsearch.hadoop.rest.RestClient.exists(RestClient.java:547)
        at org.elasticsearch.hadoop.rest.InitializationUtils.checkIndexStatus(InitializationUtils.java:71)
        at org.elasticsearch.hadoop.rest.InitializationUtils.validateSettingsForReading(InitializationUtils.java:260)
        at org.elasticsearch.hadoop.rest.RestService.findPartitions(RestService.java:217)
        at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions$lzycompute(AbstractEsRDD.scala:73)
        at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions(AbstractEsRDD.scala:72)
        at org.elasticsearch.spark.rdd.AbstractEsRDD.getPartitions(AbstractEsRDD.scala:44)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
      ....
```

### Version Info

OS         :  Linux
JVM         :  openjdk version "1.8.0_111"
Hadoop/Spark:  2.2
ES-Hadoop   :  5.5
ES          :  5.5.0

**Comment by jbaiera** [comment]
@simonlucalandi Are you sure you are on the 5.5.0 release for ES-Hadoop on all nodes? This should be fixed with b8d265724364f2b66b58cdcd1d01176c39dd11c8 which is included in the 5.5.0 release.

**Comment by simonlucalandi** [comment]
The right question is: "are you sure that you are using the elasticsearch-hadoop-5.5.0.jar?" : we just found that the custom docker image we were using, while labeled "ES5.5", was not using the elasticsearch-hadoop-5.5.0.jar. 

Very sorry for raising a false issue

**Comment by jbaiera** [comment]
All good, cheers!

**Comment by fengzibs** [comment]
Hello,emmm... I have a question just like your post. I  use ES5.5.0 ,and I want to put  some data in  HDFS from ES , do I have to use elasticsearch-hadoop-5.5.0.jar? If I use elasticsearch-hadoop-5.5.0.jar ,all of my project would be fail,so I use elasticsearch-hadoop-5.0.0.jar , is that OK? (My English is very poor,Sorry,XD)
