### ISSUE TITLE
Backwards compatibility

### ISSUE THREAD

**Issue by adriancole** [elastic/elasticsearch-hadoop#1032]
### Issue description
We'd like to use the latest version (6.x) of the hadoop driver for Elasticsearch 2.x+. Currently, we can't because prior versions fail with `EsHadoopInvalidRequest` when running our spark job.

### Details
To keep things simple for users, zipkin has been using backwards compatibility to support a range of ES versions with one spark job. In using latest (6.0.0-alpha2), prior versions aren't able to work due to the following. Reverting to 5.5.1 works, but then 6.x doesn't :)

```
org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: [HEAD] on [test_zipkin_dependency-2017-08-07/span] failed; server[192.168.99.100:32787] returned [400|Bad Request:]
	at org.elasticsearch.hadoop.rest.RestClient.checkResponse(RestClient.java:505)
	at org.elasticsearch.hadoop.rest.RestClient.executeNotFoundAllowed(RestClient.java:476)
	at org.elasticsearch.hadoop.rest.RestClient.exists(RestClient.java:547)
	at org.elasticsearch.hadoop.rest.InitializationUtils.checkIndexStatus(InitializationUtils.java:71)
	at org.elasticsearch.hadoop.rest.InitializationUtils.validateSettingsForReading(InitializationUtils.java:260)
	at org.elasticsearch.hadoop.rest.RestService.findPartitions(RestService.java:217)
	at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions$lzycompute(AbstractEsRDD.scala:73)
	at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions(AbstractEsRDD.scala:72)
	at org.elasticsearch.spark.rdd.AbstractEsRDD.getPartitions(AbstractEsRDD.scala:44)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
```

PS We are using testcontainers now, to test a range of versions. Perhaps something like this could help prevent this type of issue (or at least indicate which version range is supported)

**Comment by jbaiera** [comment]
@adriancole This is already fixed in master with 2f4e3a5, and will be released with the 6.0.0-beta1 release soon. If you would like to test with this sooner, you can check out the nightly snapshot builds.

**Comment by adriancole** [comment]
this one's gone, thanks! I found something else affecting 2.x will get to the bottom of it and raise another issue if necessary.

**Comment by adriancole** [comment]
I think I found the other problem here: https://github.com/elastic/elasticsearch-hadoop/issues/1034

Happy to test any fix
