### ISSUE TITLE
Exception in thread "main" org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: [HEAD] on [spark/docs] failed; server[172.16.2.11:9200] returned [400|Bad Request:]

### ISSUE THREAD

**Issue by qi20088** [elastic/elasticsearch-hadoop#1037]
[                          main] Version                        INFO  Elasticsearch Hadoop v5.0.0-rc1 [9731edef2a]
Exception in thread "main" org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: [HEAD] on [spark/docs] failed; server[172.16.2.11:9200] returned [400|Bad Request:]
	at org.elasticsearch.hadoop.rest.RestClient.checkResponse(RestClient.java:488)
	at org.elasticsearch.hadoop.rest.RestClient.executeNotFoundAllowed(RestClient.java:459)
	at org.elasticsearch.hadoop.rest.RestClient.exists(RestClient.java:519)
	at org.elasticsearch.hadoop.rest.RestRepository.indexExists(RestRepository.java:388)
	at org.elasticsearch.hadoop.rest.RestService.findPartitions(RestService.java:225)
	at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions$lzycompute(AbstractEsRDD.scala:59)
	at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions(AbstractEsRDD.scala:58)
	at org.elasticsearch.spark.rdd.AbstractEsRDD.getPartitions(AbstractEsRDD.scala:26)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:248)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:246)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:246)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1913)
	at org.apache.spark.rdd.RDD.count(RDD.scala:1134)
	at spark.es.EsDemo$.readFromEs(EsRDD.scala:49)
	at spark.es.EsDemo$.main(EsRDD.scala:14)
	at spark.es.EsDemo.main(EsRDD.scala)

below one each of versions

OS: win8
ES : 5.5.0
es-hadoop :  elasticsearch-spark-20_2.11 /  5.0.0-rc1
spark : 2.02
scala : 2.11.2

**Comment by qi20088** [comment]
I can writing data to es !

**Comment by qi20088** [comment]
I have solved。the es-hadoop verion's broblem.
use  es-hadoop : elasticsearch-spark-20_2.11 / 5.5.0 it is ok!
