### ISSUE TITLE
Json serialization error

### ISSUE THREAD

**Issue by chaitujil** [elastic/elasticsearch-hadoop#1051]
```
    val newElasticItem: ElasticItem = elasticItem.copy(somefield = Option(newsomefield))
    val elasticItemJson: String = Json.toJson(newElasticItem).toString()
    Some(elasticItemJson)
...
...
```
 
which gives me an RDD[String] and then I do

`    EsSpark.saveJsonToEs(esRDD, esIndexNType)`

I get this below Exception. Obviously there's something wrong with the data. But instead of finding and fixing the data issue is there a way to ignore this Exception and move on? 

Strack trace:

```
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 8209 in stage 7.0 failed 4 times, most recent failure: Lost task 8209.3 in stage 7.0 (TID 8534, cdc-hpcblx026-21.bfd.walmart.com, executor 43): org.elasticsearch.hadoop.serialization.EsHadoopSerializationException: org.codehaus.jackson.JsonParseException: Invalid UTF-8 start byte 0xb7
 at [Source: [B@39bffd38; line: 1, column: 3196]
	at org.elasticsearch.hadoop.serialization.json.JacksonJsonParser.skipChildren(JacksonJsonParser.java:137)
	at org.elasticsearch.hadoop.serialization.ParsingUtils.doFind(ParsingUtils.java:222)
	at org.elasticsearch.hadoop.serialization.ParsingUtils.values(ParsingUtils.java:151)
	at org.elasticsearch.hadoop.serialization.field.JsonFieldExtractors.process(JsonFieldExtractors.java:201)
	at org.elasticsearch.hadoop.serialization.bulk.JsonTemplatedBulk.preProcess(JsonTemplatedBulk.java:64)
	at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.write(TemplatedBulk.java:54)
	at org.elasticsearch.hadoop.rest.RestRepository.writeToIndex(RestRepository.java:159)
	at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:67)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:107)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:107)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.codehaus.jackson.JsonParseException: Invalid UTF-8 start byte 0xb7
 at [Source: [B@39bffd38; line: 1, column: 3196]
	at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1432)
	at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:385)
	at org.codehaus.jackson.impl.Utf8StreamParser._reportInvalidInitial(Utf8StreamParser.java:2796)
	at org.codehaus.jackson.impl.Utf8StreamParser._reportInvalidChar(Utf8StreamParser.java:2790)
	at org.codehaus.jackson.impl.Utf8StreamParser._skipString(Utf8StreamParser.java:2046)
	at org.codehaus.jackson.impl.Utf8StreamParser.nextToken(Utf8StreamParser.java:435)
	at org.codehaus.jackson.impl.JsonParserMinimalBase.skipChildren(JsonParserMinimalBase.java:96)
	at org.elasticsearch.hadoop.serialization.json.JacksonJsonParser.skipChildren(JacksonJsonParser.java:135)
	... 15 more
``` 

### Version Info

scalaVersion := "2.11.8"

val sparkVersion = "2.2.0"

scalacOptions := Seq("-target:jvm-1.7")

libraryDependencies ++= Seq(
  "org.apache.spark" %% "spark-core" % sparkVersion % "provided",
  "org.apache.spark" %% "spark-sql" % sparkVersion % "provided",
  "com.datastax.spark" %% "spark-cassandra-connector" % "2.0.5",
  "org.apache.spark" % "spark-hive_2.11" % sparkVersion,
  "org.elasticsearch" % "elasticsearch-spark-20_2.11" % "5.5.1"
    excludeAll(
    ExclusionRule(organization = "org.apache.spark", artifact = "spark-core"),
    ExclusionRule(organization = "org.apache.spark", artifact = "spark-sql"),
    ExclusionRule(organization = "org.apache.spark", artifact = "spark-streaming"),
    ExclusionRule(organization = "org.apache.spark", artifact = "spark-unsafe"),
    ExclusionRule(organization = "org.apache.spark", artifact = "spark-sketch"),
    ExclusionRule(organization = "org.apache.spark", artifact = "spark-tags"),
    ExclusionRule(organization = "com.google.guava", artifact = "guava"),
    ExclusionRule(organization = "org.apache.spark", artifact = "spark-sketch"),
    ExclusionRule(organization = "org.apache.spark", artifact = "spark-catalyst"),
    ExclusionRule(organization = "org.glassfish.hk2.external", artifact = "javax.inject"),
    ExclusionRule(organization = "org.slf4j", artifact = "slf4j-log4j12"),
    ExclusionRule(organization = "log4j", artifact = "log4j")
  ),
  "com.typesafe.play" % "play-json_2.11" % "2.4.3" exclude("com.typesafe", "config"),
  "com.typesafe" % "config" % "1.2.1",
  "io.dropwizard.metrics" % "metrics-graphite" % "3.1.0",
  "commons-cli" % "commons-cli" % "1.2",
  "org.scalaj" %% "scalaj-http" % "2.3.0"
)

**Comment by chaitujil** [comment]
I am trying by explicitly ignoring writing non UTF8 json strings to ES as a workaround. It would have been nice if there's a config which would let me skip entities which cause JsonParseExceptions.
   
```
 private def convertStringToUTF8(input: String): String = {
    var utf8String = ""
    try {
      val byteArray = input.getBytes(Charset.forName("UTF-8"))
      utf8String = new String(byteArray)
    } catch {
      case e: Exception =>
      // Not doing anything on exception.
    }
    utf8String
  }
```

**Comment by jbaiera** [comment]
I think this aligns as a use case for #1038. I'm going to close this for now, but if you have any extra feedback, please feel free to document it on #1038.
