### ISSUE TITLE
Spark connector injecting query in dataframe schema as new field. 

### ISSUE THREAD

**Issue by avlahop** [elastic/elasticsearch-hadoop#1062]
### What kind an issue is this?

- [x] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 

### Issue description
When trying to use the elasticsearch-hadoop spark connector, the performed query is injected in the dataframe schema as mapping field.

Description

### Steps to reproduce
Sample code

Code:

```
df = spark.read.format('org.elasticsearch.spark.sql').load('index/type')
df.printSchema()
df.count()

 |-- path: string (nullable = true) # this exists
 |-- query: struct (nullable = true) # this shouldn't be here
 |    |-- match_all: struct (nullable = true)
```

Strack trace:

```
17/10/16 13:47:13 WARN TaskSetManager: Lost task 100.0 in stage 0.0 (TID 100, 10.0.2.132, executor 1): org.elasticsearch.hadoop.EsHadoopIllegalStateException: Field 'query.match_all' not found; typically this occurs with arrays which are not mapped as single value
	at org.elasticsearch.spark.sql.RowValueReader$class.rowColumns(RowValueReader.scala:51)
	at org.elasticsearch.spark.sql.ScalaRowValueReader.rowColumns(ScalaEsRowValueReader.scala:32)
	at org.elasticsearch.spark.sql.ScalaRowValueReader.createMap(ScalaEsRowValueReader.scala:69)
	at org.elasticsearch.hadoop.serialization.ScrollReader.map(ScrollReader.java:776)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:702)
	at org.elasticsearch.hadoop.serialization.ScrollReader.map(ScrollReader.java:812)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:702)
	at org.elasticsearch.hadoop.serialization.ScrollReader.map(ScrollReader.java:812)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:702)
	at org.elasticsearch.hadoop.serialization.ScrollReader.readHitAsMap(ScrollReader.java:468)
	at org.elasticsearch.hadoop.serialization.ScrollReader.readHit(ScrollReader.java:393)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:288)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:261)
	at org.elasticsearch.hadoop.rest.RestRepository.scroll(RestRepository.java:379)
	at org.elasticsearch.hadoop.rest.ScrollQuery.hasNext(ScrollQuery.java:112)
	at org.elasticsearch.spark.rdd.AbstractEsRDDIterator.hasNext(AbstractEsRDDIterator.scala:61)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.agg_doAggregateWithoutKey$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:395)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:108)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

``` 

### Version Info

OS:         :  Ubuntu 16.04
JVM         :  1.8.0_131 (Oracle Corporation)
Hadoop/Spark:  spark 2.2
ES-Hadoop   :  elasticsearch-spark-20_2.11-5.6.2.jar
ES          :  "5.6.3"

**Comment by jbaiera** [comment]
@avlahop Can you increase the logging level to `TRACE` and post the logs here from the run?

**Comment by avlahop** [comment]
Hello @jbaiera 

Attached you can find the logs from mesos  containing the sterr and stdout for the run. 


[stderr2.txt](https://github.com/elastic/elasticsearch-hadoop/files/1391020/stderr2.txt)
[stdout2.txt](https://github.com/elastic/elasticsearch-hadoop/files/1391024/stdout2.txt)

**Comment by avlahop** [comment]
2 comments on my initial issue: I can see that the mapping of the index has changed and added the "query" field, that's why it is included in the `printSchema()` expression. But I found out that in another index (same setup) the following was added after I used spark connector:
```
|-- query: struct (nullable = true)
 |    |-- bool: struct (nullable = true)
 |    |    |-- filter: struct (nullable = true)
 |    |    |    |-- exists: struct (nullable = true)
 |    |    |    |    |-- field: string (nullable = true)
 |    |    |    |-- term: struct (nullable = true)
 |    |    |    |    |-- http_user: string (nullable = true)
 |    |    |-- must: struct (nullable = true)
 |    |    |    |-- match_all: struct (nullable = true)
 |    |-- match_all: struct (nullable = true)
```
This happened after I tried filtering with `"pushdown": true` on the loaded dataframe. 
Unfortunatelly I am not able to reproduce it yet.

**Comment by jbaiera** [comment]
@avlahop - The most probable reason for this occurring is that something is running a query against the index using the `PUT` action instead of `GET` or `POST`. You can disable the dynamic mapping feature in Elasticsearch using the _[dynamic](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic.html)_ setting on your mapping.

This should highlight the location that is performing these requests and make it easier to track down.

**Comment by avlahop** [comment]
@jbaiera Thank you for takint time to answer my question.  Could you please elaborate more on what do you mean by something? Something else than spark? Only spark jobs were using the indexes. Also  please could you explain more about this: 
> Regardless of the value of this setting, types can still be added explicitly when creating an index or with the PUT mapping API.

This is on the bottom of this link [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/dynamic-mapping.html)

So I could have the same issue even if dynamic is disabled?

**Comment by jbaiera** [comment]
> Could you please elaborate more on what do you mean by something? Something else than spark? Only spark jobs were using the indexes. 

There is a call somewhere inserting those mappings. If those mappings don't exist on the index beforehand, then disabling dynamic mappings should either highlight where they are being inserted (as part of an indexing request) or confirm that it's going through the mapping API if there are no breaks in the job.

> Also please could you explain more about this:
>> Regardless of the value of this setting, types can still be added explicitly when creating an index or with the PUT mapping API.

You can set the mapping one of two ways: 1) by setting the mapping explicitly using the `_mapping` end points, or 2) indexing a document that contains new fields that are added dynamically to the mapping. My point above simply says that by setting `dynamic` to false, we can either confirm that it's one of these cases or the other based on if the job breaks or not.

**Comment by jbaiera** [comment]
Closing this for now as there has not been any new information on this in the past month. If more information comes up we can look into re-opening the issue.
