### ISSUE TITLE
Spark application completes with SUCCESS status when an exception is thrown

### ISSUE THREAD

**Issue by Mvpanswer7** [elastic/elasticsearch-hadoop#1079]
I am running a spark application on yarn, which my goal is do some ETL from jdbc to elasticsearch.
However, when I check the log ,there is some errors like :

`17/12/01 00:35:19 WARN scheduler.TaskSetManager: Lost task 1317.0 in stage 0.0 (TID 1381, worker50.hadoop, executor 1): org.apache.spark.util.TaskCompletionListenerException: Connection error (check network and/or proxy settings)- all nodes failed; tried [[192.168.200.154:8201, 192.168.200.156:9200, 192.168.200.155:8201]] 
at org.apache.spark.TaskContextImpl.invokeListeners(TaskContextImpl.scala:138)
at org.apache.spark.TaskContextImpl.markTaskCompleted(TaskContextImpl.scala:116)
at org.apache.spark.scheduler.Task.run(Task.scala:124)
at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)`
This means that connection failed and lost some data in this process.The job finalStatus should be failed, but spark returned me with` {"state":"FINISHED","finalStatus":"SUCCEEDED"}`
WHY? My spark version is 2.2.0

**Comment by jbaiera** [comment]
Github is reserved for feature requests and confirmed bug reports only. Please post questions like these on the [forums](https://discuss.elastic.co/c/elasticsearch-and-hadoop) in the future.

Most likely the task was rescheduled and succeeded on a different executor. If the task did not succeed elsewhere, you may be experiencing a Spark issue. Regarding the error logged here, make sure that all Spark executors can reach all of your available Spark nodes over the network using the node's published http address.
