### ISSUE TITLE
DefaultSource wrongly parses 'es.resource' (spark2.2)

### ISSUE THREAD

**Issue by Andygogo15** [elastic/elasticsearch-hadoop#1082]
### Version Info 
Spark:  2.2.0
ES-Hadoop   :  5.6.0
ES          :  5.6.0

### Problem:
I am using sparksql to access data in elasticsearch. I use the following statement to register an index as hive table:
```
create table student using org.elasticsearch.spark.sql options (resource 'student/info', nodes '10.xxx.xxx.xx:9200')
```
However, when I run query statement on table student, I always get  EsHadoopIllegalArgumentException:
```
org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot find mapping for hdfs://HACluster/home/work/hive/warehouse/gz_test.db/student - one is required before using Spark SQL
	at org.elasticsearch.spark.sql.SchemaUtils$.discoverMappingAndGeoFields(SchemaUtils.scala:120)
	at org.elasticsearch.spark.sql.SchemaUtils$.discoverMapping(SchemaUtils.scala:91)
	at org.elasticsearch.spark.sql.ElasticsearchRelation.lazySchema$lzycompute(DefaultSource.scala:112)
	at org.elasticsearch.spark.sql.ElasticsearchRelation.lazySchema(DefaultSource.scala:112)
	at org.elasticsearch.spark.sql.ElasticsearchRelation.buildScan(DefaultSource.scala:174)
	at org.elasticsearch.spark.sql.ElasticsearchRelation.buildScan(DefaultSource.scala:106)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$11.apply(DataSourceStrategy.scala:277)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$11.apply(DataSourceStrategy.scala:277)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:321)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy$$anonfun$pruneFilterProject$1.apply(DataSourceStrategy.scala:320)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy.pruneFilterProjectRaw(DataSourceStrategy.scala:401)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy.pruneFilterProject(DataSourceStrategy.scala:316)
	at org.apache.spark.sql.execution.datasources.DataSourceStrategy.apply(DataSourceStrategy.scala:273)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:62)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$1.apply(QueryPlanner.scala:62)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:439)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:92)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:77)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2$$anonfun$apply$2.apply(QueryPlanner.scala:74)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
	at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1336)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:74)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner$$anonfun$2.apply(QueryPlanner.scala:66)
	at scala.collection.Iterator$$anon$12.nextCur(Iterator.scala:434)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.plan(QueryPlanner.scala:92)
	at org.apache.spark.sql.execution.QueryExecution.sparkPlan$lzycompute(QueryExecution.scala:84)
	at org.apache.spark.sql.execution.QueryExecution.sparkPlan(QueryExecution.scala:80)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan$lzycompute(QueryExecution.scala:89)
	at org.apache.spark.sql.execution.QueryExecution.executedPlan(QueryExecution.scala:89)
	at org.apache.spark.sql.execution.QueryExecution.hiveResultString(QueryExecution.scala:118)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLDriver.run(SparkSQLDriver.scala:76)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.processCmd(SparkSQLCLIDriver.scala:340)
	at org.apache.hadoop.hive.cli.CliDriver.processLine(CliDriver.java:379)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver$.main(SparkSQLCLIDriver.scala:248)
	at org.apache.spark.sql.hive.thriftserver.SparkSQLCLIDriver.main(SparkSQLCLIDriver.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```
Since es-hadoop works well with spark1.6 on my machine, I think there must be some differences between spark1.6 and spark2.2. After digging into this problem, I find that the elements order in map type parameter which  passed to ```createRelation``` method of ```DefaultSource``` is different:
#### spark1.6
Map(
path->hdfs://HACluster/home/work/hive/warehouse/gz_test.db/student,
nodes->10.xxx.xxx.xx:9200
resource->student/info
serialization.format->1
)
#### spark2.2
Map(
nodes->10.xxx.xxx.xx:9200
resource->student/info
serialization.format->1,
path->hdfs://HACluster/home/work/hive/warehouse/gz_test.db/student
)

Because *path* comes after *resource* in spark2.2, when this map type parameter parsed by ```params``` function in ```DefaultSource```, the value of  *path* will be wrongly parsed as ```es.resource``` and then EsHadoopIllegalArgumentException occurred. 
```
es.resource->student/info     //spark1.6
es.resource->hdfs://HACluster/home/work/hive/warehouse/gz_test.db/student     //spark2.2
```
Here is what ```params```function looks like:
```scala
private def params(parameters: Map[String, String]) = {
    // '.' seems to be problematic when specifying the options
    val params = parameters.map { case (k, v) => (k.replace('_', '.'), v)}. map { case (k, v) =>
      if (k.startsWith("es.")) (k, v)
      else if (k == "path" && !parameters.get("resource").isDefined) (ConfigurationOptions.ES_RESOURCE, v)
      else if (k == "pushdown") (Utils.DATA_SOURCE_PUSH_DOWN, v)
      else if (k == "strict") (Utils.DATA_SOURCE_PUSH_DOWN_STRICT, v)
      else if (k == "double.filtering") (Utils.DATA_SOURCE_KEEP_HANDLED_FILTERS, v)
      else ("es." + k, v)
    }
    // validate path
    params.getOrElse(ConfigurationOptions.ES_RESOURCE_READ, 
        params.getOrElse(ConfigurationOptions.ES_RESOURCE, throw new EsHadoopIllegalArgumentException("resource must be specified for Elasticsearch resources.")))
        
    params
  }
```
Should this be a bug of es-hadoop? Though I am not using the latest version of es-hadoop, I believe it has the same problem.

**Comment by jbaiera** [comment]
@Andygogo15 thanks for opening an issue about this. We do not currently test the Spark integration through the Hive bindings. Could you elaborate on your statement above:

> spark1.6
Map(
path->hdfs://HACluster/home/work/hive/warehouse/gz_test.db/student,
nodes->10.xxx.xxx.xx:9200
resource->student/info
serialization.format->1
)
spark2.2
Map(
nodes->10.xxx.xxx.xx:9200
resource->student/info
serialization.format->1,
path->hdfs://HACluster/home/work/hive/warehouse/gz_test.db/student
)

Are these configuration lines that you've seen within the ES-Hadoop project or are they lines from your project? I'll see if I can reproduce the erroneous settings parsing. The order of the configuration terms in the map should not affect the final result. If it does, I'd consider it a bug.

**Comment by Andygogo15** [comment]
@jbaiera I am sorry I didn't make it clear. The configurations in the map is what spark passed to ES-Hadoop when create relation (which finally accepted by method `params`). Because the elements of the map come in different order in spark2.2, ES-Hadoop wrongly parses `hdfs://HACluster/home/work/hive/warehouse/gz_test.db/student` as `es-resource`.  I have fixed this in my work and now it works well with spark2.2. And I would love to work on this problem.

**Comment by Swat2325** [comment]
I am getting a similar issue when trying to query elasticsearch managed table in hive. es.resource works fine with temporary table but not with managed table where it points to the hdfs path.

Can you please confirm which elasticsearch-hadoop version should be used to fix this or if there is any other workaround.I have already tried with v6.2.2,6.2.3,6.3.0
Error - EsHadoopInvalidRequest: Head on hdfs failed 
....returned 403 forbidden
In logs I can see es.resource pointing to hdfs path which could be causing this issue
