### ISSUE TITLE
Invalid port error when using IPv6 endpoint

### ISSUE THREAD

**Issue by adriancole** [elastic/elasticsearch-hadoop#1092]
### What kind an issue is this?

- [x] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

It appears that Ipv6 address is being mistaken for an Ipv4 address.

### Steps to reproduce

Code:

This is using latest [zipkin-dependencies](https://github.com/openzipkin/zipkin-dependencies/tree/master/elasticsearch) which uses version 6.1.0
```
SPARK_LOCAL_HOSTNAME=localhost STORAGE_TYPE=elasticsearch ES_HOSTS=elastic.server java -Djava.net.preferIPv6Addresses=true -jar zipkin-dependencies.jar
```

Stack trace:

```
user@server ~ $ SPARK_LOCAL_HOSTNAME=localhost STORAGE_TYPE=elasticsearch ES_HOSTS=elastic.server java -Djava.net.preferIPv6Addresses=true -jar zipkin-dependencies.jar
18/01/09 11:24:12 INFO ElasticsearchDependenciesJob: Processing spans from zipkin-2018-01-09/span                                     
18/01/09 11:24:12 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable                                                                                                                              
18/01/09 11:24:13 WARN Java7Support: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added              
Exception in thread "main" org.elasticsearch.hadoop.rest.EsHadoopTransportException: Invalid target URI 2a00:1:2:3:0:0:0:1       
        at org.elasticsearch.hadoop.rest.commonshttp.CommonsHttpTransport.<init>(CommonsHttpTransport.java:178)                       
        at org.elasticsearch.hadoop.rest.commonshttp.CommonsHttpTransportFactory.create(CommonsHttpTransportFactory.java:39)          
        at org.elasticsearch.hadoop.rest.NetworkClient.selectNextNode(NetworkClient.java:99)                                          
        at org.elasticsearch.hadoop.rest.NetworkClient.<init>(NetworkClient.java:82)                                                  
        at org.elasticsearch.hadoop.rest.NetworkClient.<init>(NetworkClient.java:59)                                                  
        at org.elasticsearch.hadoop.rest.RestClient.<init>(RestClient.java:92)                                                        
        at org.elasticsearch.hadoop.rest.InitializationUtils.checkIndexStatus(InitializationUtils.java:69)                            
        at org.elasticsearch.hadoop.rest.InitializationUtils.validateSettingsForReading(InitializationUtils.java:271)                 
        at org.elasticsearch.hadoop.rest.RestService.findPartitions(RestService.java:218)                                             
        at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions$lzycompute(AbstractEsRDD.scala:73)                                  
        at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions(AbstractEsRDD.scala:72)                                             
        at org.elasticsearch.spark.rdd.AbstractEsRDD.getPartitions(AbstractEsRDD.scala:44)                                            
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
        at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
        at scala.Option.getOrElse(Option.scala:121)
        at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
        at org.apache.spark.Partitioner$$anonfun$defaultPartitioner$2.apply(Partitioner.scala:66)
        at org.apache.spark.Partitioner$$anonfun$defaultPartitioner$2.apply(Partitioner.scala:66)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.immutable.List.map(List.scala:285)
        at org.apache.spark.Partitioner$.defaultPartitioner(Partitioner.scala:66)
        at org.apache.spark.rdd.RDD$$anonfun$groupBy$1.apply(RDD.scala:688)
        at org.apache.spark.rdd.RDD$$anonfun$groupBy$1.apply(RDD.scala:688)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
        at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
        at org.apache.spark.rdd.RDD.groupBy(RDD.scala:687)
        at org.apache.spark.api.java.JavaRDDLike$class.groupBy(JavaRDDLike.scala:243)
        at org.apache.spark.api.java.AbstractJavaRDDLike.groupBy(JavaRDDLike.scala:45)
        at zipkin.dependencies.elasticsearch.ElasticsearchDependenciesJob.run(ElasticsearchDependenciesJob.java:207)
        at zipkin.dependencies.elasticsearch.ElasticsearchDependenciesJob.run(ElasticsearchDependenciesJob.java:166)
        at zipkin.dependencies.ZipkinDependenciesJob.main(ZipkinDependenciesJob.java:72)
Caused by: org.apache.commons.httpclient.URIException: invalid port number
        at org.apache.commons.httpclient.URI.parseAuthority(URI.java:2248)
        at org.apache.commons.httpclient.URI.parseUriReference(URI.java:1978)
        at org.apache.commons.httpclient.URI.<init>(URI.java:167)
        at org.elasticsearch.hadoop.rest.commonshttp.CommonsHttpTransport.<init>(CommonsHttpTransport.java:176)
        ... 34 more
``` 

### Version Info

@pznamensky please fill this in if you can 
OS:         :  
JVM         :  
Hadoop/Spark:  
ES-Hadoop   :  
ES          :  

### Feature description

See https://github.com/openzipkin/zipkin-dependencies/issues/97#issuecomment-356215766

**Comment by pznamensky** [comment]
OS:
```
~ $ cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)CentOS Linux release 7.4.1708 (Core)
```
JVM: 
```
~ $ java -version
java version "1.8.0_151"
Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
```
ES: 2.4.5

**Comment by adriancole** [comment]
Wild guess is putting ipv6 into this CommonsHttpTransport unit test might reproduce the issue

**Comment by jbaiera** [comment]
Thanks for reporting this. I'll see about getting a reproduction.

**Comment by adriancole** [comment]
thanks for looking at this!

**Comment by jbaiera** [comment]
Grooming the backlog - the issues for this are captured in issue #1105. I'll close this out to keep everything in one place.
