### ISSUE TITLE
" java.lang.NoSuchMethodError: org.elasticsearch.spark.sql.package$.sparkDataFrameFunctions

### ISSUE THREAD

**Issue by Protocol-X** [elastic/elasticsearch-hadoop#1093]
### What kind an issue is this?

- [x] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 

### Issue description

Description
NoSuchMethodError when calling DataFrame.saveToEs("String")

### Steps to reproduce

Code:

```
def getSQLContext : (SparkSession) = {

    SparkSession.builder().getOrCreate();
]

enriched_df = getSQLContext.read.json(dataseq);
enriched_df.saveToEs("config_item/ci")
```

Strack trace:

```
Exception in thread "streaming-job-executor-1" java.lang.NoSuchMethodError: org.elasticsearch.spark.sql.package$.sparkDataFrameFunctions(Lorg/apache/spark/sql/Dataset;)Lorg/elasticsearch/spark/sql/package$SparkDataFrameFunctions;
	at com.test.app.Consumer$$anonfun$execute$5.apply(Consumer.scala:277)
	at com.test.app.Consumer$$anonfun$execute$5.apply(Consumer.scala:213)
	at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3.apply(DStream.scala:627)
	at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3.apply(DStream.scala:627)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ForEachDStream.scala:51)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:51)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:51)
	at org.apache.spark.streaming.dstream.DStream.createRDDWithLocalProperties(DStream.scala:415)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply$mcV$sp(ForEachDStream.scala:50)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:50)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:50)
	at scala.util.Try$.apply(Try.scala:191)
	at org.apache.spark.streaming.scheduler.Job.run(Job.scala:39)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply$mcV$sp(JobScheduler.scala:256)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:256)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:256)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler.run(JobScheduler.scala:255)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
``` 

### Version Info

OS:         :  Windows 10
JVM         :  1.8.0-131
Hadoop/Spark:  2.2.1
Scala: 2.11
ES-Hadoop   :  2.4.5
ES          :  2.4.5

**Comment by Protocol-X** [comment]
All libraries are using Scala 2.11 compiles

**Comment by jbaiera** [comment]
> Hadoop/Spark: 2.2.1
> ES-Hadoop : 2.4.5

ES-Hadoop 2.x does not support Spark 2.0 and up. To support Spark 2.2.1 you should upgrade to ES-Hadoop 5.6.6 (The latest version in the 5.x branch).
