### ISSUE TITLE
EsHadoopIllegalStateException: Field not found; typically this occurs with arrays which are not mapped as single value

### ISSUE THREAD

**Issue by pramodvspk** [elastic/elasticsearch-hadoop#1117]
Hi,

I am trying to load a ES index into a DataFrame, but when I load the data and print its count it throws the following exception.

```
org.elasticsearch.hadoop.EsHadoopIllegalStateException: Field 'extra_tags' not found; typically this occurs with arrays which are not mapped as single value
	at org.elasticsearch.spark.sql.RowValueReader$class.rowColumns(RowValueReader.scala:51)
	at org.elasticsearch.spark.sql.ScalaRowValueReader.rowColumns(ScalaEsRowValueReader.scala:32)
	at org.elasticsearch.spark.sql.ScalaRowValueReader.createMap(ScalaEsRowValueReader.scala:69)
	at org.elasticsearch.hadoop.serialization.ScrollReader.map(ScrollReader.java:770)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:696)
	at org.elasticsearch.hadoop.serialization.ScrollReader.map(ScrollReader.java:806)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:696)
	at org.elasticsearch.hadoop.serialization.ScrollReader.readHitAsMap(ScrollReader.java:466)
	at org.elasticsearch.hadoop.serialization.ScrollReader.readHit(ScrollReader.java:391)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:286)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:259)
	at org.elasticsearch.hadoop.rest.RestRepository.scroll(RestRepository.java:365)
	at org.elasticsearch.hadoop.rest.ScrollQuery.hasNext(ScrollQuery.java:92)
	at org.elasticsearch.spark.rdd.AbstractEsRDDIterator.hasNext(AbstractEsRDDIterator.scala:61)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.agg_doAggregateWithoutKey$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:377)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:126)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:322)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745) 
```

The schema for the index as inferred by Spark looks like this

```
root
 |-- centroid: struct (nullable = true)
 |    |-- lat: double (nullable = true)
 |    |-- lon: double (nullable = true)
 |-- extra_tags: struct (nullable = true)
 |-- id: long (nullable = true)
 |-- lat: double (nullable = true)
 |-- lon: double (nullable = true)
 |-- tags: struct (nullable = true)
 |    |-- addr:city: string (nullable = true)
 |    |-- addr:country: string (nullable = true)
```

A sample of my data looks like

`"centroid":{"lat":"41.937957","lon":"-87.652424"},"extra_tags":{"highway":"footway"}}`
`"centroid":{"lat":"41.786177","lon":"-87.599858"},"extra_tags":{"highway":"footway","surface":"paved"}}`

In much of my data the extra_tags variable is no present. I have followed few issues on Github and tried to implement such as `es.read.field.as.array.include` but it did not solve the issue.

Spark Version - 2.1.1
ES-Hadoop jar - elasticsearch-spark-20_2.11-5.2.2.jar
ES Version - 5.2.2

**Comment by jbaiera** [comment]
Could you include the mapping from Elasticsearch?

**Comment by pramodvspk** [comment]
Hi @jbaiera the mapping for extra_tags is 

`"extra_tags": { "type": "object", "enabled": false },`

**Comment by jbaiera** [comment]
@pramodvspk The issue here is that when `enabled` is set to false, Elasticsearch does not persist any information about the field, and thus does not list any child fields under the object in the mapping. The lack of child fields causes issues in the connector when it encounters the `extra_tags` field, since it is about to read a piece of data and that data must be added to the `extra_tags` structure, but it does not know where to place the data in the row's field order because there is no information about any child fields under it.

This may require some thought about how best to handle unmapped data fields. There is an [open issue](https://github.com/elastic/elasticsearch-hadoop/issues/1131) right now discussing the use cases and approaches for handling un-mapped fields in ES-Hadoop. I will add this case on there and close this. If you could take any further feedback or suggestions to the new issue while we figure out the best route to take on this, that would be wonderful!
