### ISSUE TITLE
ES hadoop does not support date math

### ISSUE THREAD

**Issue by yangjiajun2014** [elastic/elasticsearch-hadoop#1118]
Does ES hadoop support date math in index names?I am trying to use this feature to read es index as spark rdd but I get errors.If not support,can you add this?

**Comment by jbaiera** [comment]
ES-Hadoop does not yet officially support the [date math in index names](https://www.elastic.co/guide/en/elasticsearch/reference/current/date-math-index-names.html). Since this seems to be mostly handled on the Elasticsearch side, it makes sense that we could look into supporting something like this.

Could you include the error message that you are getting when running your job? It might help target the needed code changes and testing for when we add this feature.

**Comment by yangjiajun2014** [comment]
Thanks.
My test code is like this:
JavaPairRDD<String, Map<String, Object>> esRDD =
                JavaEsSpark.esRDD(jsc, "<test-{now/d}>/test","queryString");
The error is:
Exception in thread "main" org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Index [<test-{now/d}>/test] missing and settings [es.index.read.missing.as.empty] is set to false
	at org.elasticsearch.hadoop.rest.RestService.findPartitions(RestService.java:238)
	at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions$lzycompute(AbstractEsRDD.scala:73)
	at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions(AbstractEsRDD.scala:72)
	at org.elasticsearch.spark.rdd.AbstractEsRDD.getPartitions(AbstractEsRDD.scala:44)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:253)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:251)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:251)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2092)
	at org.apache.spark.rdd.RDD.count(RDD.scala:1162)
	at org.apache.spark.api.java.JavaRDDLike$class.count(JavaRDDLike.scala:455)
	at org.apache.spark.api.java.AbstractJavaRDDLike.count(JavaRDDLike.scala:45)

**Comment by ekampf** [comment]
When trying to write to index: `<events-{now/d}/event>` I get the error below.
The problem seems to be in `AbstractIndexExtractor.compile` where you split by "/" to find the entity name. The fix would split by the last / character...

```
Caused by: org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: invalid pattern given <events-{now/d}/event>
	at org.elasticsearch.hadoop.util.Assert.isTrue(Assert.java:60)
	at org.elasticsearch.hadoop.serialization.field.AbstractIndexExtractor.compile(AbstractIndexExtractor.java:53)
	at org.elasticsearch.hadoop.rest.RestService.createWriter(RestService.java:598)
	at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:58)
	at org.elasticsearch.spark.sql.streaming.EsStreamQueryWriter.run(EsStreamQueryWriter.scala:41)
	at org.elasticsearch.spark.sql.streaming.EsSparkSqlStreamingSink$$anonfun$addBatch$2$$anonfun$2.apply(EsSparkSqlStreamingSink.scala:52)
	at org.elasticsearch.spark.sql.streaming.EsSparkSqlStreamingSink$$anonfun$addBatch$2$$anonfun$2.apply(EsSparkSqlStreamingSink.scala:51)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ekampf** [comment]
We also tried `<events-{now/d}>/event` and `<events-{now%2Fd}>/event` and `<events-{now{YYYY.MM.dd}}>/event` with no luck
