### ISSUE TITLE
NullPointerException when overwriting data to an empty index

### ISSUE THREAD

**Issue by ctojang** [elastic/elasticsearch-hadoop#1158]
### What kind an issue is this?

- [X] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

Description

When writing data into an empty index in overwrite mode, NullPointerException occurs and it comes from flush() of RestRepository.java

When overwriting, RestRepository::delete() method scans data and tries to iterate the scan query result.
But if there is no result, the iteration does not happened.
This is the root cause of NullPointerException because writeProcessedToIndex(entry) is called only if there are any result from scan query.
And writeProcessedToIndex(entry) is the only way to initialize "bulkProcessor".
So when finish or skip the iteration, RestRepository::delete() calls flush(), and the flush() calls bulkProcessor.flush().
At this time, NullPointerException of bulkProcessor happends.

So why don't you initialize bulkProcessor regardless of scan result, or at flush() method if it's null.

### Steps to reproduce

Detal steps are here: https://docs.databricks.com/spark/latest/data-sources/elasticsearch.html

1. create an empty index
2. create df with given csv file
```
wget -O /tmp/akc_breed_info.csv https://query.data.world/s/msmjhcmdjslsvjzcaqmtreu52gkuno
```

3. write the df to the empty index
```
val esURL = "<my>.elasticsearch.com"
val df = spark.read.option("header","true").csv("/mnt/data/akc_breed_info.csv")

df.write
  .format("org.elasticsearch.spark.sql")
  .option("es.nodes.wan.only","true")
  .option("es.port","443")
  .option("es.net.ssl","true")
  .option("es.nodes", esURL)
  .mode("Overwrite")
  .save("index/dogs")
```

Code: org.elasticsearch.hadoop.rest.RestRepository

```
public void delete() {
            ...
            String scanQuery = sb.toString();
            ScrollReaderConfig readerConf = new ScrollReaderConfig(true, new JdkValueReader());
            ScrollReader scrollReader = new ScrollReader(readerConf);

            // start iterating
            ScrollQuery sq = scanAll(scanQuery, null, scrollReader);
            try {
                BytesArray entry = new BytesArray(0);

                // delete each retrieved batch, keep routing in mind:
                String baseFormat = "{\"delete\":{\"_id\":\"%s\"}}\n";
                String routedFormat = "{\"delete\":{\"_id\":\"%s\", \"_routing\":\"%s\"}}\n";
                while (sq.hasNext()) {
                    entry.reset();
                    Object[] kv = sq.next();
                    @SuppressWarnings("unchecked")
                    Map<String, Object> value = (Map<String, Object>) kv[1];
                    @SuppressWarnings("unchecked")
                    Map<String, Object> metadata = (Map<String, Object>) value.get("_metadata");
                    String routing = (String) metadata.get("_routing");
                    if (StringUtils.hasText(routing)) {
                        entry.add(StringUtils.toUTF(String.format(routedFormat, kv[0], routing)));
                    } else {
                        entry.add(StringUtils.toUTF(String.format(baseFormat, kv[0])));
                    }
                    writeProcessedToIndex(entry);
                }

                flush();
                // once done force a refresh
                client.refresh(resources.getResourceWrite());
            } finally {
                stats.aggregate(sq.stats());
                sq.close();
            }
        }
    }
```

Strack trace:

```
java.lang.NullPointerException was thrown.
java.lang.NullPointerException
    at org.elasticsearch.hadoop.rest.RestRepository.flush(RestRepository.java:196)
    at org.elasticsearch.hadoop.rest.RestRepository.delete(RestRepository.java:414)
    at org.elasticsearch.spark.sql.ElasticsearchRelation.insert(DefaultSource.scala:606)
    at org.elasticsearch.spark.sql.DefaultSource.createRelation(DefaultSource.scala:104)
    at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
    at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
    at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
    at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:86)
    at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
    at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
    at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
    at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
    at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
    at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:80)
    at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:80)
    at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:654)
    at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:654)
    at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:77)
    at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:654)
    at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:273)
    at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:267)
    at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:225)
    at dsp.bb.batch.Driver$.testWrite(Driver.scala:108)
    at EsTest$$anonfun$1.apply$mcV$sp(EsTest.scala:10)
    at EsTest$$anonfun$1.apply(EsTest.scala:10)
    at EsTest$$anonfun$1.apply(EsTest.scala:10)
    at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
    at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
    at org.scalatest.Transformer.apply(Transformer.scala:22)
    at org.scalatest.Transformer.apply(Transformer.scala:20)
    at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
    at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
    at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
    at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
    at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
    at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
    at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
    at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
    at org.scalatest.FunSuite.runTest(FunSuite.scala:1560)
    at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
    at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
    at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
    at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
    at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
    at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
    at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
    at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
    at org.scalatest.Suite$class.run(Suite.scala:1147)
    at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
    at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
    at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
    at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
    at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
    at org.scalatest.FunSuite.run(FunSuite.scala:1560)
    at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
    at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1346)
    at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1340)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1340)
    at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1011)
    at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1010)
    at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1506)
    at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
    at org.scalatest.tools.Runner$.run(Runner.scala:850)
    at org.scalatest.tools.Runner.run(Runner.scala)
    at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:131)
    at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)

``` 

### Version Info

OS:         :  macOS High Siera 10.13.4
JVM         :  1.8.x
Hadoop/Spark:  2.3.0
ES-Hadoop   :  6.2.4
ES          :  6.2.4

**Comment by EbadAE** [comment]
Is there any updates about this bug?

In the meantime, here is a workaround that helped me:
Depending on the specific situation, it might be possible to use upsert mode instead. 
The downside of upsert mode is that it will fail if the index does not exist at all. 
So,  thatif you have an existing index could be empty in some cases, then an upsert may work.

**Comment by koertkuipers** [comment]
we ran into this as well today
