### ISSUE TITLE
NullPointerException if index pattern field is null in json document

### ISSUE THREAD

**Issue by Freds72AtWork** [elastic/elasticsearch-hadoop#1166]
### Issue description

NullPointerException if field referenced in an index pattern (ex: "transactions/{date}") is set to null in json document.
Aggravating factor is that bulk error handler does not catch such error.

Probable root cause: the EsHadoop code fails to detect missing field in AbstractIndexExtractor:append
```
Object field = ((FieldExtractor)object).field(target);
// indeed...
if (field == NOT_FOUND) {
  throw new EsHadoopIllegalArgumentException(String.format("Cannot find match for %s", this.pattern));
}
// NPE exception here
sb.append(StringUtils.jsonEncoding(field.toString()));
```

### Steps to reproduce

ES Spark Conf:
spark.es.nodes.wan.only=true
spark.es.input.json=true
spark.es.batch.write.refresh=false

Code:

```
val json1 = """{"reason" : "business", "airport" : "SFO", "optional_field" : null}"""      
val json2 = """{"participants" : 5, "airport" : "OTP", "optional_field" : null}"""

new SparkContext(conf).makeRDD(Seq(json1, json2))
                      .saveJsonToEs("spark/{optional_field}")
```

Strack trace:

```
java.lang.NullPointerException
        at org.elasticsearch.hadoop.serialization.field.AbstractIndexExtractor.append(AbstractIndexExtractor.java:119)
        at org.elasticsearch.hadoop.serialization.field.AbstractIndexExtractor.field(AbstractIndexExtractor.java:132)
        at org.elasticsearch.hadoop.serialization.bulk.AbstractBulkFactory$FieldWriter.write(AbstractBulkFactory.java:103)
        at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.writeTemplate(TemplatedBulk.java:80)
        at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.write(TemplatedBulk.java:56)
        at org.elasticsearch.hadoop.rest.RestRepository.writeToIndex(RestRepository.java:168)
        at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:67)
        at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:107)
        at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:107)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:88)
        at org.apache.spark.scheduler.Task.run(Task.scala:100)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:317)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
``` 

### Version Info

OS:         :   CentOS 7
JVM         :  OpenJDK 1.8
Hadoop/Spark:  2.1
ES-Hadoop   :  6.3
ES          :  5.6

**Comment by jbaiera** [comment]
> Aggravating factor is that bulk error handler does not catch such error.

The bulk error handler is not set up to intercept all errors in the connector; Only those that are returned from Elasticsearch when inserting a bulk entry. In 6.4 we will be adding both a Serialization and a Deserialization Handler API that should cover this code.

> Probable root cause: the EsHadoop code fails to detect missing field in AbstractIndexExtractor:append

The issue here is that the code _was_ able to locate the field and extract its value. The problem is that the value was null. I'm not sure I'm ok with marking a field that is set of null as "NOT_FOUND" in the case that someone is depending on null values for their script parameters (should be a considered a glaring antipattern, but it's still a breaking change). I'll look at making sure these values are null checked, but that will lead to the connector only throwing a different (albeit hopefully more helpful) error in this case.
