### ISSUE TITLE
Invalid format error on date for index pattern during index write

### ISSUE THREAD

**Issue by spjegan** [elastic/elasticsearch-hadoop#1188]
### What kind an issue is this?

- [ ] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

This is similar to #624. The difference is, I am facing this error during the index write operation when using index_pattern  (`es.resource.write`) with a timestamp on it. My index pattern is `something-{something}-hourly-{@timestamp|yyyy-MM-dd-HH}`. And My dataframe has a `timestamp` field (String type) with value as, for instance `2016-07-21T05:00:00`. I get the below error when it tries to resolve the `timestamp` field in the index_pattern.

I was not sure if the suggestion provided in #624 applies here, but still tried disabling rich date mapping and it did not help. And the other approach of extending ES classes seem fine, but I couldn't find what classes to extend etc in the docs for this scenario. I did go through the code and try extending `DateIndexFormatter` and overriding `format` method, but by the time, the value comes there, it is already a `toString` representation of the field, `java.lang.Object@76d188e` in this case.

Would be great if there are any other options. I would ideally like to avoid extending ES classes, but if there are no other options, I am fine doing that. Thanks for your help.

Strack trace:

```
Caused by: org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot invoke method public org.joda.time.DateTime org.joda.time.format.DateTimeFormatter.parseDateTime(java.lang.String)
	at org.elasticsearch.hadoop.util.ReflectionUtils.invoke(ReflectionUtils.java:93)
	at org.elasticsearch.hadoop.util.DateUtils$JodaTime.parseDate(DateUtils.java:105)
	at org.elasticsearch.hadoop.util.DateUtils.parseDate(DateUtils.java:122)
	at org.elasticsearch.hadoop.serialization.field.DateIndexFormatter.format(DateIndexFormatter.java:72)
	at org.elasticsearch.hadoop.serialization.field.AbstractIndexExtractor$1.field(AbstractIndexExtractor.java:106)
	at org.elasticsearch.hadoop.serialization.field.AbstractIndexExtractor.append(AbstractIndexExtractor.java:114)
	at org.elasticsearch.hadoop.serialization.field.AbstractIndexExtractor.field(AbstractIndexExtractor.java:133)
	at org.elasticsearch.hadoop.serialization.bulk.AbstractBulkFactory$FieldWriter.write(AbstractBulkFactory.java:103)
	at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.writeTemplate(TemplatedBulk.java:80)
	at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.write(TemplatedBulk.java:56)
	at org.elasticsearch.hadoop.rest.RestRepository.writeToIndex(RestRepository.java:168)
	at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:67)
	at org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1.apply(EsSparkSQL.scala:101)
	at org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1.apply(EsSparkSQL.scala:101)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.elasticsearch.hadoop.util.ReflectionUtils.invoke(ReflectionUtils.java:91)
	... 19 more
Caused by: java.lang.IllegalArgumentException: Invalid format: "java.lang.Object@76d188e"
	at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:945)
	... 24 more
``` 

### Version Info
Hadoop/Spark:  2.3.1
ES-Hadoop   :  6.3.2
ES          :  5.5

**Comment by tigerinus** [comment]
experiencing the same issue.

I have:
```
 es_write_conf['es.resource.write'] =        \
     args.index_prefix + '-web-{@properties.datestamp|yyyy-MM-dd}'
```

where `properties.datestamp` comes from

```
def get_datestamp(time_in_utc):
    """convert time in "%Y-%m-%dT%H:%M:%S.%fZ" to "%Y-%m-%d string"."""
    return time.strftime(
        '%Y-%m-%d',
        datetime.strptime(time_in_utc, "%Y-%m-%dT%H:%M:%S.%fZ").timetuple()
    )
```
and got error

```
Caused by: java.lang.IllegalArgumentException: Invalid format: "java.lang.Object@4f506189"
        at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:945)
```

**Comment by spjegan** [comment]
There is a work-around for this issue. Not sure if this applies to other cases. Configuring template without `@` seem to resolve the issue. For instance, below index template works.

`something-{something}-hourly-{timestamp|yyyy-MM-dd-HH}` works.

Note the missing `@`.

**Comment by wfxxh** [comment]
> 
> 
> There is a work-around for this issue. Not sure if this applies to other cases. Configuring template without `@` seem to resolve the issue. For instance, below index template works.
> 
> `something-{something}-hourly-{timestamp|yyyy-MM-dd-HH}`
> 
> Note the missing `@`.

Thank You.
I use es v6.2.4 . Base on the elasticsearch-hadoop Configuration document, it tell me we can ''index the documents based on their date'' specify the configuration `es.resource.write = my-collection/{@timestamp|yyyy.MM.dd}` but it does not work.
I use your tips it worked. Thank You.
