### ISSUE TITLE
AbstractScalaEsScalaSparkSQL.testEsDataFrame3WriteDecimalType

### ISSUE THREAD

**Issue by cbuescher** [elastic/elasticsearch-hadoop#1193]
Copy from https://github.com/elastic/elasticsearch/issues/33982

Build: https://elasticsearch-ci.elastic.co/job/elastic+elasticsearch-hadoop+6.4+periodic/10/console

Couldn't find a Reproduce line in the logs so far, but the failure looks like:

```
06:45:10     [2018-09-24T04:40:28,674][ERROR][org.apache.spark.executor.Executor] Exception in task 0.0 in stage 9132.0 (TID 9332)
06:45:10     org.elasticsearch.hadoop.serialization.EsHadoopSerializationException: Decimal types are not supported by Elasticsearch - consider using a different type (such as string)
06:45:10     	at org.elasticsearch.spark.sql.DataFrameValueWriter.writePrimitive(DataFrameValueWriter.scala:178) ~[main/:?]
06:45:10     	at org.elasticsearch.spark.sql.DataFrameValueWriter.write(DataFrameValueWriter.scala:104) ~[main/:?]
06:45:10     	at org.elasticsearch.spark.sql.DataFrameValueWriter$$anonfun$writeStruct$1.apply(DataFrameValueWriter.scala:83) ~[main/:?]
06:45:10     	at org.elasticsearch.spark.sql.DataFrameValueWriter$$anonfun$writeStruct$1.apply(DataFrameValueWriter.scala:78) ~[main/:?]
06:45:10     	at scala.collection.Iterator$class.foreach(Iterator.scala:891) ~[scala-library-2.11.12.jar:?]
06:45:10     	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334) ~[scala-library-2.11.12.jar:?]
06:45:10     	at scala.collection.IterableViewLike$Transformed$class.foreach(IterableViewLike.scala:44) ~[scala-library-2.11.12.jar:?]
06:45:10     	at scala.collection.SeqViewLike$AbstractTransformed.foreach(SeqViewLike.scala:37) ~[scala-library-2.11.12.jar:?]
06:45:10     	at org.elasticsearch.spark.sql.DataFrameValueWriter.writeStruct(DataFrameValueWriter.scala:78) ~[main/:?]
06:45:10     	at org.elasticsearch.spark.sql.DataFrameValueWriter.write(DataFrameValueWriter.scala:70) ~[main/:?]
06:45:10     	at org.elasticsearch.spark.sql.DataFrameValueWriter.write(DataFrameValueWriter.scala:53) ~[main/:?]
06:45:10     	at org.elasticsearch.hadoop.serialization.builder.ContentBuilder.value(ContentBuilder.java:53) ~[elasticsearch-hadoop-mr-6.4.2-SNAPSHOT.jar:6.4.2-SNAPSHOT]
06:45:10     	at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.doWriteObject(TemplatedBulk.java:71) ~[elasticsearch-hadoop-mr-6.4.2-SNAPSHOT.jar:6.4.2-SNAPSHOT]
06:45:10     	at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.write(TemplatedBulk.java:58) ~[elasticsearch-hadoop-mr-6.4.2-SNAPSHOT.jar:6.4.2-SNAPSHOT]
06:45:10     	at org.elasticsearch.hadoop.serialization.bulk.BulkEntryWriter.writeBulkEntry(BulkEntryWriter.java:68) ~[elasticsearch-hadoop-mr-6.4.2-SNAPSHOT.jar:6.4.2-SNAPSHOT]
06:45:10     	at org.elasticsearch.hadoop.rest.RestRepository.writeToIndex(RestRepository.java:170) ~[elasticsearch-hadoop-mr-6.4.2-SNAPSHOT.jar:6.4.2-SNAPSHOT]
06:45:10     	at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:67) ~[main/:?]
06:45:10     	at org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1.apply(EsSparkSQL.scala:101) ~[main/:?]
06:45:10     	at org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1.apply(EsSparkSQL.scala:101) ~[main/:?]
06:45:10     	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87) ~[spark-core_2.11-2.3.0.jar:2.3.0]
06:45:10     	at org.apache.spark.scheduler.Task.run(Task.scala:109) ~[spark-core_2.11-2.3.0.jar:2.3.0]
06:45:10     	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345) [spark-core_2.11-2.3.0.jar:2.3.0]
06:45:10     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
06:45:10     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
06:45:10     	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
06:45:10     [2018-09-24T04:40:28,676][WARN ][org.apache.spark.scheduler.TaskSetManager] Lost task 0.0 in stage 9132.0 (TID 9332, localhost, executor driver): org.elasticsearch.hadoop.serialization.EsHadoopSerializationException: Decimal types are not supported by Elasticsearch - consider using a different type (such as string)
06:45:10     	at org.elasticsearch.spark.sql.DataFrameValueWriter.writePrimitive(DataFrameValueWriter.scala:178)
06:45:10     	at org.elasticsearch.spark.sql.DataFrameValueWriter.write(DataFrameValueWriter.scala:104)
06:45:10     	at org.elasticsearch.spark.sql.DataFrameValueWriter$$anonfun$writeStruct$1.apply(DataFrameValueWriter.scala:83)
06:45:10     	at org.elasticsearch.spark.sql.DataFrameValueWriter$$anonfun$writeStruct$1.apply(DataFrameValueWriter.scala:78)
06:45:10     	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
06:45:10     	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
06:45:10     	at scala.collection.IterableViewLike$Transformed$class.foreach(IterableViewLike.scala:44)
06:45:10     	at scala.collection.SeqViewLike$AbstractTransformed.foreach(SeqViewLike.scala:37)
06:45:10     	at org.elasticsearch.spark.sql.DataFrameValueWriter.writeStruct(DataFrameValueWriter.scala:78)
06:45:10     	at org.elasticsearch.spark.sql.DataFrameValueWriter.write(DataFrameValueWriter.scala:70)
06:45:10     	at org.elasticsearch.spark.sql.DataFrameValueWriter.write(DataFrameValueWriter.scala:53)
06:45:10     	at org.elasticsearch.hadoop.serialization.builder.ContentBuilder.value(ContentBuilder.java:53)
06:45:10     	at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.doWriteObject(TemplatedBulk.java:71)
06:45:10     	at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.write(TemplatedBulk.java:58)
06:45:10     	at org.elasticsearch.hadoop.serialization.bulk.BulkEntryWriter.writeBulkEntry(BulkEntryWriter.java:68)
06:45:10     	at org.elasticsearch.hadoop.rest.RestRepository.writeToIndex(RestRepository.java:170)
06:45:10     	at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:67)
06:45:10     	at org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1.apply(EsSparkSQL.scala:101)
06:45:10     	at org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1.apply(EsSparkSQL.scala:101)
06:45:10     	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
06:45:10     	at org.apache.spark.scheduler.Task.run(Task.scala:109)
06:45:10     	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
06:45:10     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
06:45:10     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
06:45:10     	at java.lang.Thread.run(Thread.java:748)
06:45:10 
```

**Comment by jbaiera** [comment]
This was in the middle of a regular test execution when it looks like something on the jenkins machine went very wrong and crashed:

```
00:45:10 org.elasticsearch.spark.integration.SparkSQLScalaSuite > org.elasticsearch.spark.integration.AbstractScalaEsScalaSparkSQL.testEsDataFrame4WriteConflictingData[40] STANDARD_OUT
00:45:10     [2018-09-24T04:40:30,265][INFO ][org.elasticsearch.spark.sql.EsDataFrameWriter] Writing to [withmetastrict_בְּדִיק_sparksql-test-scala-error-handler-es/data]
00:45:10     [2018-09-24T04:40:30,341][INFO ][org.elasticsearch.hadoop.handler.impl.elasticsearch.ElasticsearchHandler] Elasticsearch Error Handler inheriting root configuration
00:45:10     [2018-09-24T04:40:30,424][INFO ][org.elasticsearch.spark.sql.EsDataFrameWriter] Writing to [withmetastrict_בְּדִיק_sparksql-test-scala-error-handler-es/data]
00:45:14     [2018-09-24T04:40:30,429][INFO ][org.elasticsearch.hadoop.handler.impl.elasticsearch.ElasticsearchHandler] Elasticsearch Error Handler inheriting root configuration
00:45:19     [2018-09-24T04:40:30,433][INFO ][org.elasticsearch.hadoop.handler.impl.elasticsearch.ElasticsearchHandler] Writing to [withmetastrict_בְּדִיק_sparksql-test-scala-error-handler-es-errors/data]
00:45:30 FATAL: command execution failed
00:45:30 java.nio.channels.ClosedChannelException
00:45:30 	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:209)
00:45:30 	at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:222)
00:45:30 	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:832)
00:45:30 	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:287)
00:45:30 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:181)
00:45:30 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.switchToNoSecure(SSLEngineFilterLayer.java:283)
00:45:30 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processWrite(SSLEngineFilterLayer.java:503)
00:45:30 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processQueuedWrites(SSLEngineFilterLayer.java:248)
00:45:30 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doSend(SSLEngineFilterLayer.java:200)
00:45:30 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doCloseSend(SSLEngineFilterLayer.java:213)
00:45:30 	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doCloseSend(ProtocolStack.java:800)
00:45:30 	at org.jenkinsci.remoting.protocol.ApplicationLayer.doCloseWrite(ApplicationLayer.java:173)
00:45:30 	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer$ByteBufferCommandTransport.closeWrite(ChannelApplicationLayer.java:314)
00:45:30 	at hudson.remoting.Channel.close(Channel.java:1450)
00:45:30 	at hudson.remoting.Channel.close(Channel.java:1403)
00:45:30 	at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:821)
00:45:30 	at hudson.slaves.SlaveComputer.access$800(SlaveComputer.java:105)
00:45:30 	at hudson.slaves.SlaveComputer$3.run(SlaveComputer.java:737)
00:45:30 	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
00:45:30 	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
00:45:30 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
00:45:30 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
00:45:30 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
00:45:30 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
00:45:30 	at java.lang.Thread.run(Thread.java:748)
00:45:30 Caused: java.io.IOException: Backing channel 'JNLP4-connect connection from ec2-34-220-18-148.us-west-2.compute.amazonaws.com/34.220.18.148:47532' is disconnected.
00:45:30 	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:214)
00:45:30 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:283)
00:45:30 	at com.sun.proxy.$Proxy78.isAlive(Unknown Source)
00:45:30 	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1143)
00:45:30 	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1135)
00:45:30 	at hudson.tasks.CommandInterpreter.join(CommandInterpreter.java:155)
00:45:30 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:109)
00:45:30 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
00:45:30 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
00:45:30 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
00:45:30 	at hudson.model.Build$BuildExecution.build(Build.java:206)
00:45:30 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
00:45:30 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
00:45:30 	at hudson.model.Run.execute(Run.java:1815)
00:45:30 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
00:45:30 	at hudson.model.ResourceController.execute(ResourceController.java:97)
00:45:30 	at hudson.model.Executor.run(Executor.java:429)
00:45:30 FATAL: Unable to delete script file /tmp/jenkins2437550314333313657.sh
00:45:30 java.nio.channels.ClosedChannelException
00:45:30 	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer.onReadClosed(ChannelApplicationLayer.java:209)
00:45:30 	at org.jenkinsci.remoting.protocol.ApplicationLayer.onRecvClosed(ApplicationLayer.java:222)
00:45:30 	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.onRecvClosed(ProtocolStack.java:832)
00:45:30 	at org.jenkinsci.remoting.protocol.FilterLayer.onRecvClosed(FilterLayer.java:287)
00:45:30 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.onRecvClosed(SSLEngineFilterLayer.java:181)
00:45:30 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.switchToNoSecure(SSLEngineFilterLayer.java:283)
00:45:30 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processWrite(SSLEngineFilterLayer.java:503)
00:45:30 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.processQueuedWrites(SSLEngineFilterLayer.java:248)
00:45:30 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doSend(SSLEngineFilterLayer.java:200)
00:45:30 	at org.jenkinsci.remoting.protocol.impl.SSLEngineFilterLayer.doCloseSend(SSLEngineFilterLayer.java:213)
00:45:30 	at org.jenkinsci.remoting.protocol.ProtocolStack$Ptr.doCloseSend(ProtocolStack.java:800)
00:45:30 	at org.jenkinsci.remoting.protocol.ApplicationLayer.doCloseWrite(ApplicationLayer.java:173)
00:45:30 	at org.jenkinsci.remoting.protocol.impl.ChannelApplicationLayer$ByteBufferCommandTransport.closeWrite(ChannelApplicationLayer.java:314)
00:45:30 	at hudson.remoting.Channel.close(Channel.java:1450)
00:45:30 	at hudson.remoting.Channel.close(Channel.java:1403)
00:45:30 	at hudson.slaves.SlaveComputer.closeChannel(SlaveComputer.java:821)
00:45:30 	at hudson.slaves.SlaveComputer.access$800(SlaveComputer.java:105)
00:45:30 	at hudson.slaves.SlaveComputer$3.run(SlaveComputer.java:737)
00:45:30 	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
00:45:30 	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
00:45:30 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
00:45:30 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
00:45:30 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
00:45:30 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
00:45:30 	at java.lang.Thread.run(Thread.java:748)
00:45:30 Caused: hudson.remoting.ChannelClosedException: Channel "unknown": Remote call on JNLP4-connect connection from ec2-34-220-18-148.us-west-2.compute.amazonaws.com/34.220.18.148:47532 failed. The channel is closing down or has closed down
00:45:30 	at hudson.remoting.Channel.call(Channel.java:948)
00:45:30 	at hudson.FilePath.act(FilePath.java:1070)
00:45:30 	at hudson.FilePath.act(FilePath.java:1059)
00:45:30 	at hudson.FilePath.delete(FilePath.java:1563)
00:45:30 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:123)
00:45:30 	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
00:45:30 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
00:45:30 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
00:45:30 	at hudson.model.Build$BuildExecution.build(Build.java:206)
00:45:30 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
00:45:30 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
00:45:30 	at hudson.model.Run.execute(Run.java:1815)
00:45:30 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
00:45:30 	at hudson.model.ResourceController.execute(ResourceController.java:97)
00:45:30 	at hudson.model.Executor.run(Executor.java:429)```

Otherwise, this looks transient. Closing.
