### ISSUE TITLE
: Illegal unquoted character ((CTRL-CHAR, code 9)): has to be escaped using backslash to be 

### ISSUE THREAD

**Issue by grachit** [elastic/elasticsearch-hadoop#1198]
I was saving my dataframe to es using es-hadoop connector:

Dataframe code was like this:
    val someData = Seq(
      Row(8, "Däniken			12Erich von"),
      Row(64, "mouse12"),
      Row(-27, "horse12"))

    val someSchema = List(
      StructField("number", IntegerType, true),
      StructField("key", StringType, true))

    val someDF = sparkSession.createDataFrame(
      sparkSession.sparkContext.parallelize(someData),
      StructType(someSchema))
      someDF

Thereafter, changed dataframe to add additional field to the document.

val someData = Seq(
      Row(8, "Dniken	12Erich von", " " ),
      Row(64, "mouse12", " "),
      Row(-27, "horse12", " "))

    val someSchema = List(
      StructField("number", IntegerType, true),
      StructField("key", StringType, true),StructField("key1", StringType, true))

    val someDF = sparkSession.createDataFrame(
      sparkSession.sparkContext.parallelize(someData),
      StructType(someSchema))
      someDF

Getting following exception:

Exception in thread "main" org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: Illegal unquoted character ((CTRL-CHAR, code 9)): has to be escaped using backslash to be included in string value
 at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@712a668e; line: 1, column: 26]
	at org.elasticsearch.hadoop.rest.RestClient.checkResponse(RestClient.java:424)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:382)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:364)
	at org.elasticsearch.hadoop.rest.RestClient.bulk(RestClient.java:216)
	at org.elasticsearch.hadoop.rest.bulk.BulkProcessor.tryFlush(BulkProcessor.java:185)
	at org.elasticsearch.hadoop.rest.bulk.BulkProcessor.flush(BulkProcessor.java:460)
	at org.elasticsearch.hadoop.rest.RestRepository.flush(RestRepository.java:196)
	at org.elasticsearch.hadoop.rest.RestRepository.delete(RestRepository.java:402)
	at org.elasticsearch.spark.sql.ElasticsearchRelation.insert(DefaultSource.scala:582)
	at org.elasticsearch.spark.sql.DefaultSource.createRelation(DefaultSource.scala:104)
	at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:426)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:215)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:198)

OS:         :  
JVM         :  1.8
Hadoop/Spark: 2.1  
ES-Hadoop   :  6.2.1
ES          :  6.2.4

Note: This happen when i have defined "es.mapping.id" as "KEY"

**Comment by jbaiera** [comment]
Can you provide trace level logs from the `org.elasticsearch.hadoop.rest.commonshttp` package?

**Comment by grachit** [comment]
018-10-08 09:29:02,541 DEBUG commonshttp.CommonsHttpTransportFactory - Creating new CommonsHttpTransport
2018-10-08 09:29:02,575 TRACE commonshttp.CommonsHttpTransport - Opening HTTP transport to 1xx.xx.xxx.xxx:9200
2018-10-08 09:29:02,583 TRACE commonshttp.CommonsHttpTransport - Tx [GET]@[1xx.xx.xxx.xxx:9200][]?[null] w/ payload [null]
2018-10-08 09:29:03,101 TRACE commonshttp.CommonsHttpTransport - Rx @[xxx.xx.xxx.xxx] [200-OK] [{
  "name" : "elasticsearch-271802973-19-393763619.p.com-data",
  "cluster_name" : "test-cluster",
  "cluster_uuid" : "iD02rOP8R72VK-mr-jltWw",
  "version" : {
    "number" : "6.2.4",
    "build_hash" : "ccec39f",
    "build_date" : "2018-04-12T20:37:28.497551Z",
    "build_snapshot" : false,
    "lucene_version" : "7.2.1",
    "minimum_wire_compatibility_version" : "5.6.0",
    "minimum_index_compatibility_version" : "5.0.0"
  },
  "tagline" : "You Know, for Search"
}
]
2018-10-08 09:29:03,133 TRACE commonshttp.CommonsHttpTransport - Closing HTTP transport to 1xx.xx.xxx.xxx:9200
2018-10-08 09:29:03,138 DEBUG commonshttp.CommonsHttpTransportFactory - Creating new CommonsHttpTransport
2018-10-08 09:29:03,138 TRACE commonshttp.CommonsHttpTransport - Opening HTTP transport to 1xx.xx.xxx.xxx:9200
2018-10-08 09:29:03,139 TRACE commonshttp.CommonsHttpTransport - Tx [HEAD]@[1xx.xx.xxx.xxx:9200][index]?[null] w/ payload [null]
2018-10-08 09:29:03,661 TRACE commonshttp.CommonsHttpTransport - Rx @[xxx.xx.xxx.xxx] [200-OK] [null]
2018-10-08 09:29:03,662 TRACE commonshttp.CommonsHttpTransport - Tx [HEAD]@[1xx.xx.xxx.xxx:9200][index/_mapping/docs]?[null] w/ payload [null]
2018-10-08 09:29:03,912 TRACE commonshttp.CommonsHttpTransport - Rx @[xxx.xx.xxx.xxx] [200-OK] [null]
2018-10-08 09:29:03,914 TRACE commonshttp.CommonsHttpTransport - Tx [DELETE]@[1xx.xx.xxx.xxx:9200][index/docs/_query]?[q=*] w/ payload [null]
2018-10-08 09:29:04,164 TRACE commonshttp.CommonsHttpTransport - Rx @[xxx.xx.xxx.xxx] [400-Bad Request] [{"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"request [/index/docs/_query] contains unrecognized parameter: [q]"}],"type":"illegal_argument_exception","reason":"request [/index/docs/_query] contains unrecognized parameter: [q]"},"status":400}]
2018-10-08 09:29:04,176 INFO  rest.RestRepository - Skipping delete by query as the plugin is not installed...
2018-10-08 09:29:04,183 TRACE commonshttp.CommonsHttpTransport - Tx [POST]@[1xx.xx.xxx.xxx:9200][index/docs/_search]?[scroll=10m&_source=false&size=500&sort=_doc] w/ payload [null]
2018-10-08 09:29:04,437 TRACE commonshttp.CommonsHttpTransport - Rx @[xxx.xx.xxx.xxx] [200-OK] [{"_scroll_id":"DnF1ZXJ5VGhlbkZldGNoBQAAAAAAAAOWFjJJWWxPY3c1VHBhTFJOb3FTYXZzakEAAAAAAAADwRY0RnZjMFlRcVItMjU4RVl1UjlhZXJ3AAAAAAAAAsoWaGh2MHV0LTNRYVdaMS03SEx5OUM5dwAAAAAAAALLFmI0c2M2NjAtUlRtcmg0R294X2RNOGcAAAAAAAAFrhZNU3NSM1IxY1JOeTlNTHZDMzBSMDdB","took":4,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"hits":{"total":3,"max_score":null,"hits":[{"_index":"index","_type":"docs","_id":"mouse12","_score":null,"sort":[0]},{"_index":"index","_type":"docs","_id":"Däniken\t12Erich von","_score":null,"sort":[0]},{"_index":"index","_type":"docs","_id":"horse12","_score":null,"sort":[1]}]}}]
2018-10-08 09:29:04,474 TRACE commonshttp.CommonsHttpTransport - Tx [POST]@[1xx.xx.xxx.xxx:9200][_search/scroll]?[scroll=5m] w/ payload [{"scroll_id":"DnF1ZXJ5VGhlbkZldGNoBQAAAAAAAAOWFjJJWWxPY3c1VHBhTFJOb3FTYXZzakEAAAAAAAADwRY0RnZjMFlRcVItMjU4RVl1UjlhZXJ3AAAAAAAAAsoWaGh2MHV0LTNRYVdaMS03SEx5OUM5dwAAAAAAAALLFmI0c2M2NjAtUlRtcmg0R294X2RNOGcAAAAAAAAFrhZNU3NSM1IxY1JOeTlNTHZDMzBSMDdB"}]
2018-10-08 09:29:04,732 TRACE commonshttp.CommonsHttpTransport - Rx @[xxx.xx.xxx.xxx] [200-OK] [{"_scroll_id":"DnF1ZXJ5VGhlbkZldGNoBQAAAAAAAAOWFjJJWWxPY3c1VHBhTFJOb3FTYXZzakEAAAAAAAADwRY0RnZjMFlRcVItMjU4RVl1UjlhZXJ3AAAAAAAAAsoWaGh2MHV0LTNRYVdaMS03SEx5OUM5dwAAAAAAAALLFmI0c2M2NjAtUlRtcmg0R294X2RNOGcAAAAAAAAFrhZNU3NSM1IxY1JOeTlNTHZDMzBSMDdB","took":8,"timed_out":false,"_shards":{"total":5,"successful":5,"skipped":0,"failed":0},"hits":{"total":3,"max_score":null,"hits":[]}}]
2018-10-08 09:29:04,734 TRACE commonshttp.CommonsHttpTransport - Tx [PUT]@[1xx.xx.xxx.xxx:9200][index/docs/_bulk]?[null] w/ payload [{"delete":{"_id":"mouse12"}}
{"delete":{"_id":"Däniken	12Erich von"}}
{"delete":{"_id":"horse12"}}
]
2018-10-08 09:29:04,993 TRACE commonshttp.CommonsHttpTransport - Rx @[xxx.xx.xxx.xxx] [500-Internal Server Error] [{"error":{"root_cause":[{"type":"json_parse_exception","reason":"Illegal unquoted character ((CTRL-CHAR, code 9)): has to be escaped using backslash to be included in string value\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@28f84893; line: 1, column: 28]"}],"type":"json_parse_exception","reason":"Illegal unquoted character ((CTRL-CHAR, code 9)): has to be escaped using backslash to be included in string value\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@28f84893; line: 1, column: 28]"},"status":500}]
2018-10-08 09:29:04,993 TRACE commonshttp.CommonsHttpTransport - Tx [DELETE]@[1xx.xx.xxx.xxx:9200][_search/scroll]?[null] w/ payload [{"scroll_id":["DnF1ZXJ5VGhlbkZldGNoBQAAAAAAAAOWFjJJWWxPY3c1VHBhTFJOb3FTYXZzakEAAAAAAAADwRY0RnZjMFlRcVItMjU4RVl1UjlhZXJ3AAAAAAAAAsoWaGh2MHV0LTNRYVdaMS03SEx5OUM5dwAAAAAAAALLFmI0c2M2NjAtUlRtcmg0R294X2RNOGcAAAAAAAAFrhZNU3NSM1IxY1JOeTlNTHZDMzBSMDdB"]}]
2018-10-08 09:29:05,243 TRACE commonshttp.CommonsHttpTransport - Rx @[xxx.xx.xxx.xxx] [200-OK] [{"succeeded":true,"num_freed":5}]
2018-10-08 09:29:05,246 INFO  spark.SparkContext - Invoking stop() from shutdown hook
2018-10-08 09:29:05,255 INFO  server.ServerConnector - Stopped ServerConnector@6f7923a5{HTTP/1.1}{0.0.0.0:4040}
2018-10-08 09:29:05,257 INFO  handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@302f7971{/stages/stage/kill,null,UNAVAILABLE}
2018-10-08 09:29:05,257 INFO  handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@13d4992d{/jobs/job/kill,null,UNAVAILABLE}
2018-10-08 09:29:05,257 INFO  handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@5082d622{/api,null,UNAVAILABLE}
2018-10-08 09:29:05,257 INFO  handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@18e36d14{/,null,UNAVAILABLE}
2018-10-08 09:29:05,257 INFO  handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@418c5a9c{/static,null,UNAVAILABLE}
2018-10-08 09:29:05,257 INFO  handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@5a5338df{/executors/threadDump/json,null,UNAVAILABLE}
2018-10-08 09:29:05,257 INFO  handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@6ee4d9ab{/executors/threadDump,null,UNAVAILABLE}
2018-10-08 09:29:05,258 INFO  handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@1fb19a0{/executors/json,null,UNAVAILABLE}
2018-10-08 09:29:05,258 INFO  handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@732d0d24{/executors,null,UNAVAILABLE}
2018-10-08 09:29:05,258 INFO  handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@5e3d57c7{/environment/json,null,UNAVAILABLE}
2018-10-08 09:29:05,258 INFO  handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@6bf08014{/environment,null,UNAVAILABLE}
2018-10-08 09:29:05,258 INFO  handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@4416d64f{/storage/rdd/json,null,UNAVAILABLE}
2018-10-08 09:29:05,258 INFO  handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@50dfbc58{/storage/rdd,null,UNAVAILABLE}
2018-10-08 09:29:05,258 INFO  handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@73a8da0f{/storage/json,null,UNAVAILABLE}
2018-10-08 09:29:05,258 INFO  handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@10f7f7de{/storage,null,UNAVAILABLE}
2018-10-08 09:29:05,258 INFO  handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@11f0a5a1{/stages/pool/json,null,UNAVAILABLE}
2018-10-08 09:29:05,258 INFO  handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@1b45c0e{/stages/pool,null,UNAVAILABLE}
2018-10-08 09:29:05,258 INFO  handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@5026735c{/stages/stage/json,null,UNAVAILABLE}
2018-10-08 09:29:05,258 INFO  handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@1672fe87{/stages/stage,null,UNAVAILABLE}
2018-10-08 09:29:05,259 INFO  handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@7cbd9d24{/stages/json,null,UNAVAILABLE}
2018-10-08 09:29:05,259 INFO  handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@6676f6a0{/stages,null,UNAVAILABLE}
2018-10-08 09:29:05,259 INFO  handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@147a5d08{/jobs/job/json,null,UNAVAILABLE}
2018-10-08 09:29:05,259 INFO  handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@1bae316d{/jobs/job,null,UNAVAILABLE}
2018-10-08 09:29:05,259 INFO  handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@2ce6c6ec{/jobs/json,null,UNAVAILABLE}
2018-10-08 09:29:05,259 INFO  handler.ContextHandler - Stopped o.s.j.s.ServletContextHandler@5c45d770{/jobs,null,UNAVAILABLE}
2018-10-08 09:29:05,260 INFO  ui.SparkUI - Stopped Spark web UI at http://xxx.xx.xxx.xxx:4040

**Comment by jbaiera** [comment]
Looks like the code path responsible for clearing out an index before writing when choosing to overwrite in Spark was not properly encoding the id and routing values from documents before sending them. Should be fixed now.
