### ISSUE TITLE
mapping inconsistency when using dots in field name

### ISSUE THREAD

**Issue by j040p3d20** [elastic/elasticsearch-hadoop#1199]
Hi, 

I seem to be experiencing a bug with ScrollReader.

I'm using ES 5.6.1 and my pom has the following dependencies

elasticsearch-spark-20_2.11
5.6.12 ( also happens with 6.1.2 )
spark-sql_2.11
2.3.2
spark-core_2.11
2.3.2

this snippet

```
SparkSession sc = SparkSession.builder()
				.config(ConfigurationOptions.ES_NODES, "127.0.0.1:9200")
				.config(ConfigurationOptions.ES_SCROLL_SIZE, 250)
				.config(ConfigurationOptions.ES_READ_FIELD_INCLUDE, "article.datepublication")
				.master("local[*]")
				.appName("sample-structured-streaming").getOrCreate();

		ArrayList<StructField> list = new ArrayList<>();
		list.add(DataTypes.createStructField("article.datepublication", DataTypes.LongType, true));
		StructType structType = DataTypes.createStructType(list);
		
		Dataset<Row> load = sc.read().format("es").schema(structType).load("2018*/document");
		load.count();
```

produces the following stacktrace

```
18/10/08 16:28:35 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
org.elasticsearch.hadoop.EsHadoopIllegalStateException: Position for 'article.datepublication' not found in row; typically this is caused by a mapping inconsistency
	at org.elasticsearch.spark.sql.RowValueReader$class.addToBuffer(RowValueReader.scala:60)
	at org.elasticsearch.spark.sql.ScalaRowValueReader.addToBuffer(ScalaEsRowValueReader.scala:32)
	at org.elasticsearch.spark.sql.ScalaRowValueReader.addToMap(ScalaEsRowValueReader.scala:118)
	at org.elasticsearch.hadoop.serialization.ScrollReader.map(ScrollReader.java:865)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:708)
	at org.elasticsearch.hadoop.serialization.ScrollReader.readHitAsMap(ScrollReader.java:474)
	at org.elasticsearch.hadoop.serialization.ScrollReader.readHit(ScrollReader.java:399)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:294)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:267)
	at org.elasticsearch.hadoop.rest.RestRepository.scroll(RestRepository.java:367)
	at org.elasticsearch.hadoop.rest.ScrollQuery.hasNext(ScrollQuery.java:92)
	at org.elasticsearch.spark.rdd.AbstractEsRDDIterator.hasNext(AbstractEsRDDIterator.scala:61)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.agg_doAggregateWithoutKey_0$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$10$$anon$1.hasNext(WholeStageCodegenExec.scala:614)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:125)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```
I've debugged the process and the value "article.datepublication" is read correctly ( an int value is read from elasticsearch and correctly mapped to a Date value ) . I'm not able to debug the scala part but i get the impression that ```parser.nextToken()``` is being called too many times.

Please let me know if you need me to provide any aditional info.

**Comment by j040p3d20** [comment]
BTW the mapping for this field is
```
          "article": {
            "properties": {
              "datepublication": {
                "type": "date",
                "format": "yyyy/MM/dd HH:mm:ss||yyyy/MM/dd||epoch_millis"
              }
            }
          }
```

and the data coming from ES looks like this

```
{
	"_index": "287_2018_10_en_1",
	"_type": "document",
	"_id": "257583039",
	"_score": 1,
	"_source": {
		"article.datepublication": 1538651144000
	}
}
```

**Comment by jbaiera** [comment]
Thanks for opening an issue. This is definitely the same case as #853. I'm inclined to close this as a duplicate since #853 has more triaging info in it. Unfortunately, the work to fix this hasn't been a priority compared to other project initiatives, so be sure to +1 the original issue for visibility.
