### ISSUE TITLE
Defined date type field value can't parse in ES6.2.4

### ISSUE THREAD

**Issue by 478632418** [elastic/elasticsearch-hadoop#1201]
### Issue description
- The date type field defined in ElastricSearch6.2.4 as 
`insert_time":{"type":"date","format":"yyyy-MM-dd HH:mm:ss"},

### Steps to reproduce
Code:
```
Test/code snippet
```
-But when I run the code 
`spark.read().format("org.elasticsearch.spark.sql") //
				.option("es.nodes", "my elastricsearch ip")//
				.option("es.port", 9200)//
				.option("pushdown", "true")//
				.option("es.index.auto.create", "true")//
				.option("es.nodes.wan.only", "true")//
				.option("es.query", "{\"query\":{\"term\":{\"type\":\"my row type\"}}}")//
				.load("/myindex/mytype/");`
One error was thrown:
Strack trace:
```
Stack trace goes here
``` 
`18/10/26 15:34:33 ERROR scheduler.TaskSetManager: Task 0 in stage 0.0 failed 4 times; aborting job
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3, CDH-147, executor 1): org.elasticsearch.hadoop.rest.EsHadoopParsingException: Cannot parse value [2018-10-26 11:30:03] for field [insert_time]
        at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:727)
        at org.elasticsearch.hadoop.serialization.ScrollReader.map(ScrollReader.java:871)
        at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:714)
        at org.elasticsearch.hadoop.serialization.ScrollReader.readHitAsMap(ScrollReader.java:480)
        at org.elasticsearch.hadoop.serialization.ScrollReader.readHit(ScrollReader.java:405)
        at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:300)
        at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:273)
        at org.elasticsearch.hadoop.rest.RestRepository.scroll(RestRepository.java:301)
        at org.elasticsearch.hadoop.rest.ScrollQuery.hasNext(ScrollQuery.java:92)
        at org.elasticsearch.spark.rdd.AbstractEsRDDIterator.hasNext(AbstractEsRDDIterator.scala:61)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:408)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:395)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:234)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$2.apply(SparkPlan.scala:228)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:827)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$25.apply(RDD.scala:827)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:108)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot invoke method public org.joda.time.DateTime org.joda.time.format.DateTimeFormatter.parseDateTime(java.lang.String)
        at org.elasticsearch.hadoop.util.ReflectionUtils.invoke(ReflectionUtils.java:93)
        at org.elasticsearch.hadoop.util.DateUtils$JodaTime.parseDate(DateUtils.java:105)
        at org.elasticsearch.hadoop.util.DateUtils.parseDate(DateUtils.java:122)
        at org.elasticsearch.spark.serialization.ScalaValueReader.createDate(ScalaValueReader.scala:182)
        at org.elasticsearch.spark.serialization.ScalaValueReader.parseDate(ScalaValueReader.scala:173)
        at org.elasticsearch.spark.serialization.ScalaValueReader$$anonfun$date$1.apply(ScalaValueReader.scala:166)
        at org.elasticsearch.spark.serialization.ScalaValueReader$$anonfun$date$1.apply(ScalaValueReader.scala:166)
        at org.elasticsearch.spark.serialization.ScalaValueReader.checkNull(ScalaValueReader.scala:120)
        at org.elasticsearch.spark.serialization.ScalaValueReader.date(ScalaValueReader.scala:166)
        at org.elasticsearch.spark.serialization.ScalaValueReader.readValue(ScalaValueReader.scala:96)
        at org.elasticsearch.spark.sql.ScalaRowValueReader.readValue(ScalaEsRowValueReader.scala:46)
        at org.elasticsearch.hadoop.serialization.ScrollReader.parseValue(ScrollReader.java:774)
        at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:724)
        ... 26 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.elasticsearch.hadoop.util.ReflectionUtils.invoke(ReflectionUtils.java:91)
        ... 38 more
Caused by: java.lang.IllegalArgumentException: Invalid format: "2018-10-26 11:30:03" is malformed at " 11:30:03"
        at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:945)
        ... 43 more
`

### Version Info

OS:         :  CentOS6.5+
JVM         :  JDK8
Hadoop/Spark:  Spark2.2.0
ES-Hadoop   :  6.2.4+6.4.2
ES          :  6.2.4

**Comment by 478632418** [comment]
set "es.mapping.date.rich=false"
or 
set  "spark.es.mapping.date.rich=false" 

See: https://elasticsearch.cn/question/584

**Comment by 478632418** [comment]
Or the other way，See https://blog.csdn.net/ltliyue/article/details/80021058?utm_source=blogxgwz6

**Comment by jbaiera** [comment]
This is an incorrectly formatted date for the joda libraries to parse. The date must be in the format of `yyyy-MM-dd'T'HH:mm:ss.SSSZZ` in order to be parsed correctly.

**Comment by Heltman** [comment]
> set "es.mapping.date.rich=false"
> or
> set "spark.es.mapping.date.rich=false"
> 
> See: https://elasticsearch.cn/question/584

it's no use, i use it like below：
spark.conf.set("es.mapping.date.rich","false");
spark.conf.set("spark.es.mapping.date.rich","false");
