### ISSUE TITLE
NoSuchAlgorithmException while reading keystore

### ISSUE THREAD

**Issue by renjith7189** [elastic/elasticsearch-hadoop#1234]
### What kind an issue is this?

- [ ] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 

### Issue description
Generated keystore and added key successfully. But while reading the same key from same jvm, 
NoSuchAlgorithmException is thrown.
Description
```
Test/code snippet
```

Strack trace:

```
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.saveAsNewAPIHadoopFile.
: org.elasticsearch.hadoop.EsHadoopException: Could not read secure setting [es.net.http.auth.pass]
	at org.elasticsearch.hadoop.security.SecureSettings.getSecureProperty(SecureSettings.java:67)
	at org.elasticsearch.hadoop.rest.commonshttp.CommonsHttpTransport.addHttpAuth(CommonsHttpTransport.java:235)
	at org.elasticsearch.hadoop.rest.commonshttp.CommonsHttpTransport.<init>(CommonsHttpTransport.java:192)
	at org.elasticsearch.hadoop.rest.commonshttp.CommonsHttpTransportFactory.create(CommonsHttpTransportFactory.java:40)
	at org.elasticsearch.hadoop.rest.NetworkClient.selectNextNode(NetworkClient.java:102)
	at org.elasticsearch.hadoop.rest.NetworkClient.<init>(NetworkClient.java:85)
	at org.elasticsearch.hadoop.rest.NetworkClient.<init>(NetworkClient.java:61)
	at org.elasticsearch.hadoop.rest.RestClient.<init>(RestClient.java:94)
	at org.elasticsearch.hadoop.rest.InitializationUtils.discoverEsVersion(InitializationUtils.java:317)
	at org.elasticsearch.hadoop.mr.EsOutputFormat.init(EsOutputFormat.java:260)
	at org.elasticsearch.hadoop.mr.EsOutputFormat.checkOutputSpecs(EsOutputFormat.java:233)
	at org.apache.spark.internal.io.HadoopMapReduceWriteConfigUtil.assertConf(SparkHadoopWriter.scala:387)
	at org.apache.spark.internal.io.SparkHadoopWriter$.write(SparkHadoopWriter.scala:71)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1.apply$mcV$sp(PairRDDFunctions.scala:1083)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1.apply(PairRDDFunctions.scala:1081)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopDataset$1.apply(PairRDDFunctions.scala:1081)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.PairRDDFunctions.saveAsNewAPIHadoopDataset(PairRDDFunctions.scala:1081)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopFile$2.apply$mcV$sp(PairRDDFunctions.scala:1000)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopFile$2.apply(PairRDDFunctions.scala:991)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsNewAPIHadoopFile$2.apply(PairRDDFunctions.scala:991)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.PairRDDFunctions.saveAsNewAPIHadoopFile(PairRDDFunctions.scala:991)
	at org.apache.spark.api.python.PythonRDD$.saveAsNewAPIHadoopFile(PythonRDD.scala:549)
	at org.apache.spark.api.python.PythonRDD.saveAsNewAPIHadoopFile(PythonRDD.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.elasticsearch.hadoop.security.EsHadoopSecurityException: Could not read alias [es.net.http.auth.pass] from keystore
	at org.elasticsearch.hadoop.security.KeystoreWrapper.getSecureSetting(KeystoreWrapper.java:99)
	at org.elasticsearch.hadoop.security.SecureSettings.getSecureProperty(SecureSettings.java:65)
	... 39 more
Caused by: java.security.UnrecoverableKeyException: Get Key failed: AES SecretKeyFactory not available
	at sun.security.pkcs12.PKCS12KeyStore.engineGetKey(PKCS12KeyStore.java:410)
	at sun.security.pkcs12.PKCS12KeyStore.engineGetEntry(PKCS12KeyStore.java:1282)
	at java.security.KeyStore.getEntry(KeyStore.java:1521)
	at org.elasticsearch.hadoop.security.KeystoreWrapper.getSecureSetting(KeystoreWrapper.java:93)
	... 40 more
Caused by: java.security.NoSuchAlgorithmException: AES SecretKeyFactory not available
	at javax.crypto.SecretKeyFactory.<init>(SecretKeyFactory.java:122)
	at javax.crypto.SecretKeyFactory.getInstance(SecretKeyFactory.java:160)
	at sun.security.pkcs12.PKCS12KeyStore.engineGetKey(PKCS12KeyStore.java:387)
	... 43 more``` 

### Version Info

OS:         :  Linux
JVM         :  java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)
Hadoop/Spark:  2.3.1
ES-Hadoop   :  6.4.1
ES          :  6.4.1

https://bugs.java.com/bugdatabase/view_bug.do?bug_id=7022467

**Comment by jbaiera** [comment]
Related: https://bugs.openjdk.java.net/browse/JDK-8149411

**Comment by jbaiera** [comment]
@renjith7189 Can you try this on a more recent version of Java. It looks like this is a bug with how the JVM's implementation of the PKCS12 Keystore retrieves algorithms for decrypting their entries. According to the above link, it looks like this fix has been backported to 8u111, 8u102, 7u181, amongst other versions.

**Comment by renjith7189** [comment]
java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)
Tried on lower java versions as well, doesn't seem working.

**Comment by jbaiera** [comment]
@renjith7189 You will need to try running this on java 8u111 or higher. You currently have java 8u73. Trying lower java versions will not help since this is a bug in Java that is fixed in higher versions.

**Comment by jbaiera** [comment]
Closing this since the issue author has not responded. If this is still an issue after upgrading to Java 8u111 or higher, please let us know and we can re-open.
