### ISSUE TITLE
Address already in use (Bind failed)

### ISSUE THREAD

**Issue by ov7a** [elastic/elasticsearch-hadoop#1236]
### What kind an issue is this?

- [X ] Bug report. 

### Issue description

Sometimes under high load I get ''Address already in use (Bind failed)"
What addressed does elasticsearch-hadoop tries to bind? How do I diagnose this issue?

I also suspect that this issue is related to connection leak (see #1212) - the app is the same, but the error differs.

Strack trace:

```
2019-01-24 15:55:13 INFO HttpMethodDirector: I/O exception (java.net.BindException) caught when processing request: Address already in use (Bind failed)
2019-01-24 15:55:13 INFO HttpMethodDirector: Retrying request
2019-01-24 15:55:13 INFO HttpMethodDirector: I/O exception (java.net.BindException) caught when processing request: Address already in use (Bind failed)
2019-01-24 15:55:13 INFO HttpMethodDirector: Retrying request
2019-01-24 15:55:13 INFO HttpMethodDirector: I/O exception (java.net.BindException) caught when processing request: Address already in use (Bind failed)
2019-01-24 15:55:13 INFO HttpMethodDirector: Retrying request
2019-01-24 15:55:13 WARN BlockManager: Putting block rdd_5655_3 failed due to exception org.elasticsearch.hadoop.rest.EsHadoopTransportException: java.net.BindException: Address already in use (Bind failed).
2019-01-24 15:55:13 WARN BlockManager: Block rdd_5655_3 could not be removed as it was not found on disk or in memory
2019-01-24 15:55:13 INFO HttpMethodDirector: I/O exception (java.net.BindException) caught when processing request: Address already in use (Bind failed)
2019-01-24 15:55:13 INFO HttpMethodDirector: Retrying request
2019-01-24 15:55:13 INFO HttpMethodDirector: I/O exception (java.net.BindException) caught when processing request: Address already in use (Bind failed)
2019-01-24 15:55:13 INFO HttpMethodDirector: Retrying request
2019-01-24 15:55:13 INFO HttpMethodDirector: I/O exception (java.net.BindException) caught when processing request: Address already in use (Bind failed)
2019-01-24 15:55:13 INFO HttpMethodDirector: Retrying request
2019-01-24 15:55:13 ERROR TaskContextImpl: Error in TaskCompletionListener
org.elasticsearch.hadoop.rest.EsHadoopTransportException: java.net.BindException: Address already in use (Bind failed)
	at org.elasticsearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:129) ~[elasticsearch-spark-20_2.11-5.5.0.jar:5.5.0]
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:461) ~[elasticsearch-spark-20_2.11-5.5.0.jar:5.5.0]
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:425) ~[elasticsearch-spark-20_2.11-5.5.0.jar:5.5.0]
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:429) ~[elasticsearch-spark-20_2.11-5.5.0.jar:5.5.0]
	at org.elasticsearch.hadoop.rest.RestClient.get(RestClient.java:155) ~[elasticsearch-spark-20_2.11-5.5.0.jar:5.5.0]
	at org.elasticsearch.hadoop.rest.request.GetAliasesRequestBuilder.execute(GetAliasesRequestBuilder.java:51) ~[elasticsearch-spark-20_2.11-5.5.0.jar:5.5.0]
	at org.elasticsearch.hadoop.rest.RestService.createReader(RestService.java:460) ~[elasticsearch-spark-20_2.11-5.5.0.jar:5.5.0]
	at org.elasticsearch.spark.rdd.AbstractEsRDDIterator.reader$lzycompute(AbstractEsRDDIterator.scala:49) ~[elasticsearch-spark-20_2.11-5.5.0.jar:5.5.0]
	at org.elasticsearch.spark.rdd.AbstractEsRDDIterator.reader(AbstractEsRDDIterator.scala:42) ~[elasticsearch-spark-20_2.11-5.5.0.jar:5.5.0]
	at org.elasticsearch.spark.rdd.AbstractEsRDDIterator.close(AbstractEsRDDIterator.scala:81) ~[elasticsearch-spark-20_2.11-5.5.0.jar:5.5.0]
	at org.elasticsearch.spark.rdd.AbstractEsRDDIterator.closeIfNeeded(AbstractEsRDDIterator.scala:74) ~[elasticsearch-spark-20_2.11-5.5.0.jar:5.5.0]
	at org.elasticsearch.spark.rdd.AbstractEsRDDIterator$$anonfun$1.apply$mcV$sp(AbstractEsRDDIterator.scala:54) ~[elasticsearch-spark-20_2.11-5.5.0.jar:5.5.0]
	at org.elasticsearch.spark.rdd.AbstractEsRDDIterator$$anonfun$1.apply(AbstractEsRDDIterator.scala:54) ~[elasticsearch-spark-20_2.11-5.5.0.jar:5.5.0]
	at org.elasticsearch.spark.rdd.AbstractEsRDDIterator$$anonfun$1.apply(AbstractEsRDDIterator.scala:54) ~[elasticsearch-spark-20_2.11-5.5.0.jar:5.5.0]
	at org.elasticsearch.spark.rdd.CompatUtils$1.onTaskCompletion(CompatUtils.java:112) ~[elasticsearch-spark-20_2.11-5.5.0.jar:5.5.0]
	at org.apache.spark.TaskContextImpl$$anonfun$markTaskCompleted$1.apply(TaskContextImpl.scala:118) ~[spark-core_2.11-2.3.1.jar:2.3.1]
	at org.apache.spark.TaskContextImpl$$anonfun$markTaskCompleted$1.apply(TaskContextImpl.scala:118) ~[spark-core_2.11-2.3.1.jar:2.3.1]
	at org.apache.spark.TaskContextImpl$$anonfun$invokeListeners$1.apply(TaskContextImpl.scala:131) [spark-core_2.11-2.3.1.jar:2.3.1]
	at org.apache.spark.TaskContextImpl$$anonfun$invokeListeners$1.apply(TaskContextImpl.scala:129) [spark-core_2.11-2.3.1.jar:2.3.1]
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59) [json-event-layout-assembly-1.0.0.jar:1.0.0]
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48) [json-event-layout-assembly-1.0.0.jar:1.0.0]
	at org.apache.spark.TaskContextImpl.invokeListeners(TaskContextImpl.scala:129) [spark-core_2.11-2.3.1.jar:2.3.1]
	at org.apache.spark.TaskContextImpl.markTaskCompleted(TaskContextImpl.scala:117) [spark-core_2.11-2.3.1.jar:2.3.1]
	at org.apache.spark.scheduler.Task.run(Task.scala:119) [spark-core_2.11-2.3.1.jar:2.3.1]
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345) [spark-core_2.11-2.3.1.jar:2.3.1]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.net.BindException: Address already in use (Bind failed)
	at java.net.PlainSocketImpl.socketBind(Native Method) ~[?:1.8.0_121]
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387) ~[?:1.8.0_121]
	at java.net.Socket.bind(Socket.java:644) ~[?:1.8.0_121]
	at java.net.Socket.<init>(Socket.java:433) ~[?:1.8.0_121]
	at java.net.Socket.<init>(Socket.java:286) ~[?:1.8.0_121]
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:80) ~[commons-httpclient-3.1.jar:?]
	at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:122) ~[commons-httpclient-3.1.jar:?]
	at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707) ~[commons-httpclient-3.1.jar:?]
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387) ~[commons-httpclient-3.1.jar:?]
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171) ~[commons-httpclient-3.1.jar:?]
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397) ~[commons-httpclient-3.1.jar:?]
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323) ~[commons-httpclient-3.1.jar:?]
	at org.elasticsearch.hadoop.rest.commonshttp.CommonsHttpTransport.execute(CommonsHttpTransport.java:478) ~[elasticsearch-spark-20_2.11-5.5.0.jar:5.5.0]
	at org.elasticsearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:112) ~[elasticsearch-spark-20_2.11-5.5.0.jar:5.5.0]
	... 27 more
2019-01-24 15:55:13 ERROR Executor: Exception in task 3.0 in stage 2033.0 (TID 41658)
``` 

### Version Info

OS:         :   Debian 8
JVM         :   1.8.0_121
Hadoop/Spark:  park-2.3.1-bin-hadoop2.7
ES-Hadoop   :  5.6.10
ES          :  5.6.10

**Comment by jbaiera** [comment]
This is almost definitely related to your other issue of connection exhaustion (#1212). The Bind Exceptions here are most likely due to exhausting the number of usable ephemeral ports on the local OS. When a connection is closed it goes into Timed Wait to allow any lingering data to drain out and avoid polluting a future connection on that port. If there is enough connection turnover, the ports on the machine to be used for outgoing requests can be temporarily exhausted while they finish their waits.

I'm going to go ahead and close this in favor of #1212 to keep everything consolidated. The current plan is to convert over to the Elasticsearch Java Low Level Rest Client as the main client for this library. Hopefully this will give us a chance to more carefully evaluate our connection pooling code.
