### ISSUE TITLE
Consistency of search queries while running MR jobs

### ISSUE THREAD

**Issue by aritratony** [elastic/elasticsearch-hadoop#124]
Environment: ES 0.90.7, es-hadoop - master snapshot.

I created a test index in ES as follows:

<pre>
curl -XPOST localhost:9200/tdm/test -d ' {"id":1, "bad":1, "text":"this is a dummy text"}'
curl -XPOST localhost:9200/tdm/test -d ' {"id":2, "bad":0, "text":"this is second dummy text"}'
curl -XPOST localhost:9200/tdm/test -d ' {"id":3, "bad":1, "text":"this is third dummy text"}'
curl -XPOST localhost:9200/tdm/test -d ' {"id":4, "bad":1, "text":"this is fourth dummy text"}'
</pre>

On running the word count job with
<pre>conf.set("es.resource", "tdm/test/_search")</pre>
the following exception is encountered:

<pre>
Exception in thread "main" org.codehaus.jackson.JsonParseException: Unrecognized token 'Nohnlrfudfrui': was expecting 'null', 'true', 'false' or NaN
 at [Source: org.apache.commons.httpclient.AutoCloseInputStream@43ee148b; line: 1, column: 27]
	at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1291)
	at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:385)
	at org.codehaus.jackson.impl.Utf8StreamParser._reportInvalidToken(Utf8StreamParser.java:1788)
	at org.codehaus.jackson.impl.Utf8StreamParser._matchToken(Utf8StreamParser.java:1748)
	at org.codehaus.jackson.impl.Utf8StreamParser._handleUnexpectedValue(Utf8StreamParser.java:1565)
	at org.codehaus.jackson.impl.Utf8StreamParser._nextTokenNotInObject(Utf8StreamParser.java:437)
	at org.codehaus.jackson.impl.Utf8StreamParser.nextToken(Utf8StreamParser.java:323)
	at org.codehaus.jackson.map.ObjectMapper._initForReading(ObjectMapper.java:2439)
	at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2377)
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1094)
	at org.elasticsearch.hadoop.rest.RestClient.parseContent(RestClient.java:106)
	at org.elasticsearch.hadoop.rest.RestClient.targetShards(RestClient.java:169)
	at org.elasticsearch.hadoop.rest.RestRepository.getTargetShards(RestRepository.java:181)
	at org.elasticsearch.hadoop.mr.ESInputFormat.getSplits(ESInputFormat.java:363)
	at org.elasticsearch.hadoop.mr.ESInputFormat.getSplits(ESInputFormat.java:340)
	at org.apache.hadoop.mapred.JobClient.writeNewSplits(JobClient.java:1054)
	at org.apache.hadoop.mapred.JobClient.writeSplits(JobClient.java:1071)
	at org.apache.hadoop.mapred.JobClient.access$700(JobClient.java:179)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:983)
	at org.apache.hadoop.mapred.JobClient$2.run(JobClient.java:936)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:416)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1190)
	at org.apache.hadoop.mapred.JobClient.submitJobInternal(JobClient.java:936)
	at org.apache.hadoop.mapreduce.Job.submit(Job.java:550)
	at org.apache.hadoop.mapreduce.Job.waitForCompletion(Job.java:580)
	at elasticsearch.test.TestESHadoop.main(TestESHadoop.java:91)
</pre>

The error goes away when <pre>conf.set("es.resource", "tdm/test")</pre> is used.

This behavior is different from a normal REST query to ES, and is not intuitive.

**Comment by costin** [comment]
Closing this long standing bug. The resource has been retrofitted to remove the search into `es.query` since previously it created too many conflicts on whether somebody defines a query vs a resource + query.
The two are now separate and further more, the query can be query dsl or uri.
