### ISSUE TITLE
EsHadoopIllegalArgumentException: Cannot find node with id in version 2.0.2

### ISSUE THREAD

**Issue by pammusankolli** [elastic/elasticsearch-hadoop#1243]
Hi,
I have written a simple MR Job to push the data to ES using ES-Hadoop connector on MAC. When I run the job below error is coming. Please help me to resolve this.  

java.lang.Exception: org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot find node with id [eZIQkDKwQVGRSxuJU_wjJg]
	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:492)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:559)
Caused by: org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot find node with id [eZIQkDKwQVGRSxuJU_wjJg]
	at org.elasticsearch.hadoop.util.Assert.notNull(Assert.java:40)
	at org.elasticsearch.hadoop.rest.RestRepository.getWriteTargetPrimaryShards(RestRepository.java:252)
	at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.initSingleIndex(EsOutputFormat.java:216)
	at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.init(EsOutputFormat.java:199)
	at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.write(EsOutputFormat.java:157)
	at org.apache.hadoop.mapred.ReduceTask$OldTrackingRecordWriter.write(ReduceTask.java:494)
	at org.apache.hadoop.mapred.ReduceTask$3.collect(ReduceTask.java:423)
	at org.apache.hadoop.mapred.lib.IdentityReducer.reduce(IdentityReducer.java:45)
	at org.apache.hadoop.mapred.ReduceTask.runOldReducer(ReduceTask.java:445)
	at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:393)
	at org.apache.hadoop.mapred.LocalJobRunner$Job$ReduceTaskRunnable.run(LocalJobRunner.java:347)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by jbaiera** [comment]
Can you confirm if `eZIQkDKwQVGRSxuJU_wjJg` is a valid node in your cluster? Could you include the `TRACE` level logs from the `org.elasticsearch.hadoop.rest.commonshttp` library here as well?

**Comment by jbaiera** [comment]
Closing this as there has been no further feedback
