### ISSUE TITLE
Weird DNS Resolution on elasticsearch-hadoop

### ISSUE THREAD

**Issue by rodmaz** [elastic/elasticsearch-hadoop#1252]
### What kind an issue is this?

- [x] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

Is it possible that `elasticsearch-hadoop` uses the Spark driver to resolve DNS and not Spark workers? 
I have a Spark cluster running on a Docker Swarm. Spark workers are able to resolve DNS names inside the Docker Swarm correctly w/o any problem. `elasticsearch-hadoop` however is unable to resolve the DNS for `elasticsearch` (single node) server in my Docker Swarm.

```
2019-02-15 18:07:26.068 DEBUG CommonsHttpTransportFactory: Creating new CommonsHttpTransport
2019-02-15 18:07:26.137 TRACE CommonsHttpTransport: Opening HTTP transport to elasticsearch:9200
2019-02-15 18:07:26.151 DEBUG HeaderProcessor: Added HTTP Headers to method: [Content-Type: application/json
, Accept: application/json
]
2019-02-15 18:07:26.151 TRACE CommonsHttpTransport: Tx [GET]@[elasticsearch:9200][]?[null] w/ payload [null]
2019-02-15 18:07:26.163 TRACE NetworkClient: Caught exception while performing request [elasticsearch:9200][] - falling back to the next node in line...
java.net.UnknownHostException: elasticsearch
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at java.net.Socket.<init>(Socket.java:434)
        at java.net.Socket.<init>(Socket.java:286)
        at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:80)
        at org.apache.commons.httpclient.protocol.ControllerThreadSocketFactory$1.doit(ControllerThreadSocketFactory.java:91)
        at org.apache.commons.httpclient.protocol.ControllerThreadSocketFactory$SocketTask.run(ControllerThreadSocketFactory.java:158)
        at java.lang.Thread.run(Thread.java:748)
2019-02-15 18:07:26.168 ERROR NetworkClient: Node [elasticsearch:9200] failed (elasticsearch); no other nodes left - aborting...
2019-02-15 18:07:26.171 TRACE CommonsHttpTransport: Closing HTTP transport to elasticsearch:9200
2019-02-15 18:07:26.259 ERROR MyApp: org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot detect ES version - typically this happens if the network/Elasticsearch cluster is not accessible or when targeting a WAN/Cloud instance without the proper setting 'es.nodes.wan.only'
```

My ES container has `elasticsearch` as its hostname and **all containers in Docker are able to solve its name, including all Spark workers**. So how come `elasticsearch-hadoop` cannot solve it?

It turns out that by setting my `/etc/hosts` in my development machine fixes the problem:

```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1 localhost
127.0.0.1 elasticsearch
```

**So apparently Spark driver (running on my development machine) is solving this DNS and not the the Spark workers.**

I have also attempted to set the parameters `es.nodes.resolve.hostname` and `es.nodes.wan.only` to all possible values, but the behaviour is pretty much the same. 

```
        spark_session_singleton = SparkSession \
            .builder \
            .config(conf=spark_conf) \
            .config('spark.sql.session.timeZone', 'UTC') \
            .config('es.index.auto.create', 'true') \
            .config('es.nodes', 'elasticsearch') \
            .config('es.port', '9200') \
            .config('es.nodes.resolve.hostname', 'false') \
            .config('es.nodes.wan.only', 'true') \
            .getOrCreate()
```

### Version Info

OS:       Linux Alpine  : 3.8
JVM        Linux x64 :  8.202.08
Hadoop/Spark:  2.4.0
ES-Hadoop   :  6.6.0
ES          :  6.6.0

**Comment by jbaiera** [comment]
ES-Hadoop will attempt to connect to Elasticsearch in both the driver and from the workers. The connections that are made in the worker processes are obviously to collect or write the data for the job, but the connections made in the driver process are used to discover information about the cluster, the indices being targeted, where their shards are located, and how to best slice up the job for reading and writing.

Also, we use the issue list as a bug tracker. In the future, might I recommend asking these sorts of questions on [our forums](https://discuss.elastic.co/c/elasticsearch-and-hadoop)?

**Comment by rodmaz** [comment]
Thanks @jbaiera for the quick answer.
