### ISSUE TITLE
Impossible to write exemple from scala compile project

### ISSUE THREAD

**Issue by kiwy42** [elastic/elasticsearch-hadoop#1258]
Env:
Sprak 2.3.2
ES-Hadoop 6.6.0
ElasticSearch 6.3.2

I have setup Spark with those value in spark-default.conf: 
```
spark.es.nodes node1.com, node2.com, node3.com
spark.es.index.auto.create true
spark.es.nodes.wan.only true
spark.es.nodes.client.only false
spark.es.nodes.discovery false
spark.es.port 9200
spark.es.net.ssl true
spark.es.net.http.auth.user myuser
spark.es.net.http.auth.pass mypasswd
```
Using `spark-shell` or Zepellin, I'm able to write inside Elastic search without any issue with a quiet good rate.
However I've tried to set up a sbt project to compile my spark project here's my `build.sbt`:

```
name := "Project"
version := "1.0"
scalaVersion := "2.11.12"
val sparkVersion = "2.3.2"
libraryDependencies += "org.apache.spark" %% "spark-core" % sparkVersion
libraryDependencies += "org.apache.spark" %% "spark-sql" % sparkVersion 
```
In my project I added `elasticsearch-spark-20_2.11-6.6.0.jar` to lib and my Scala code is simple : 

```
import org.apache.spark.SparkConf
import org.apache.spark.SparkContext
import org.elasticsearch.spark._
 object Project {
    def main(args: Array[String]) {
        val conf = new SparkConf()
conf.set("spark.es.nodes","node1.com, node2.com, node3.com")
        conf.set("spark.es.port","9200")
        conf.set("spark.es.net.ssl","true")
        conf.set("spark.es.nodes.wan.only","true")
        conf.set("spark.es.nodes.discovery","false")
        conf.set("spark.es.index.auto.create","true")
        conf.set("spark.es.nodes.client.only","false")
        conf.set("spark.es.net.http.auth.user","myuser")
        conf.set("spark.es.net.http.auth.pass","mypasswd")
        val sc = new SparkContext(conf)
        println("spark Context set")
        val numbers = Map("seven" -> 17, "eight" -> 18, "nine" -> 19)
        val airports = Map("arrival" -> "test", "FRI" -> "yolo")
        sc.makeRDD(Seq(numbers, airports)).saveToEs("index/testtype")
    }
```

When using this simple project compile in a `jar` file I always end up with the following error: 
```

2019-03-04 11:27:30 WARN  HttpMethodDirector:697 - Unable to respond to any of these challenges: {negotiate=Negotiate}
Exception in thread "main" org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot detect ES version - typically this happens if the network/Elasticsearch cluster is not accessible or when targeting a WAN/Cloud instance without the proper setting 'es.nodes.wan.only'
	at org.elasticsearch.hadoop.rest.InitializationUtils.discoverEsVersion(InitializationUtils.java:328)
	at org.elasticsearch.spark.rdd.EsSpark$.doSaveToEs(EsSpark.scala:103)
	at org.elasticsearch.spark.rdd.EsSpark$.saveToEs(EsSpark.scala:79)
	at org.elasticsearch.spark.rdd.EsSpark$.saveToEs(EsSpark.scala:74)
	at org.elasticsearch.spark.package$SparkRDDFunctions.saveToEs(package.scala:55)
	at Project.main(Project.scala:28)
	at Project.main(Project.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: org.elasticsearch.hadoop.rest.EsHadoopRemoteException: {header={WWW-Authenticate=Negotiate}}
null
	at org.elasticsearch.hadoop.rest.RestClient.checkResponse(RestClient.java:443)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:400)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:362)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:366)
	at org.elasticsearch.hadoop.rest.RestClient.get(RestClient.java:161)
	at org.elasticsearch.hadoop.rest.RestClient.remoteEsVersion(RestClient.java:619)
	at org.elasticsearch.hadoop.rest.InitializationUtils.discoverEsVersion(InitializationUtils.java:321)
	... 16 more
```
I have tried with several options and it seems only `es.nodes.wan.only` is not handle properly, if I change host or other option I'm able to have different errors like timeouts or cannot connect host.
I hop esomeone will be able to point me toward the right direction because I'm a bit puzzled about that behaviour.

**Comment by kiwy42** [comment]
My bad, I've been using the wrong jar for 2 days now.
Everything works properly.
