### ISSUE TITLE
Unable to save a JSON document with an _id containing a MD5 hash

### ISSUE THREAD

**Issue by jbenoit2011** [elastic/elasticsearch-hadoop#1263]
### What kind an issue is this?

- [x ] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 

### Issue description

Saving a document serialized in JSON by specifying metadata with `_id` containing a MD5 hash fail.
But it works when `_id` is an int enclosed in string (e.g: `"1"`)

### Steps to reproduce

Code:

```
import org.elasticsearch.hadoop.cfg.ConfigurationOptions.{ES_INPUT_JSON, ES_NODES}
import org.elasticsearch.spark._
import org.elasticsearch.spark.sql._
import spark.implicits._

val rdd = sc.makeRDD(Seq(("f2cd3174546ecd57220da387e93ad97d", "{\"foo\":\"bar\"}")))  
rdd.saveToEsWithMeta("myindex/mytype", Map(ES_NODES -> "localhost", ES_INPUT_JSON -> true.toString))
```

Stack trace:

```
org.apache.spark.util.TaskCompletionListenerException: org.elasticsearch.hadoop.rest.EsHadoopRemoteException: json_parse_exception: Unrecognized token 'f2cd3174546ecd57220da387e93ad97d': was expecting 'null', 'true', 'false' or NaN
 at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@4db4c74; line: 1, column: 50]
	at org.apache.spark.TaskContextImpl.invokeListeners(TaskContextImpl.scala:138)
	at org.apache.spark.TaskContextImpl.markTaskCompleted(TaskContextImpl.scala:116)
	at org.apache.spark.scheduler.Task.run(Task.scala:137)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:402)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:408)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
``` 

### Version Info

OS         :  EMR 5.21
JVM         :  8
Hadoop/Spark:  2.4.0
ES-Hadoop   :  6.6.2
ES          :  6.4

**Comment by jbaiera** [comment]
This is most likely a known issue related to #913. Closing this issue as a duplicate.
