### ISSUE TITLE
Saving dataframe with array column resulted in org.elasticsearch.hadoop.serialization.EsHadoopSerializationException

### ISSUE THREAD

**Issue by aalinazar** [elastic/elasticsearch-hadoop#1280]
### What kind an issue is this?

- [ ] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description
Description

0

I have a dataframe with array in the column. I want to save this dataframe to Elasticsearch. but I got exception on the executer when saving the dataframe

If there is no column as array, I'm able to save the dataframe. Error occurs only when any of the column is in array / nested / json format

### Steps to reproduce

Code:

```
from pyspark.sql.types import *
schema = StructType([  # schema
    StructField("id", StringType(), True),
    StructField("email", ArrayType(StringType()), True)])

df = spark.createDataFrame([{"id": "id3","email": ["email1@gmail.com"]},
                            {"id": "id4", "email": ["email1@gmail.com", "email2@gmail.com"]}],
                           schema=schema)
df.show(truncate=False)

df.write.format("org.elasticsearch.spark.sql") \
                .mode('append') \
                .option("es.input.json", "yes") \
                .option("es.resource", "test/test") \
                .option("es.nodes", "10.1.129.80:9200") \
                .option("es.net.ssl", "true") \
                .option("es.net.ssl.cert.allow.self.signed", "false") \
                .option("es.net.http.auth.user", "username") \
                .option("es.net.http.auth.pass", "password") \
                .option("es.net.ssl.truststore.location", "file:///home/hdfs/truststore.jks") \
                .option("es.net.ssl.truststore.pass", "xxxx") \
                .option("es.net.ssl.keystore.location", "file:///home.hdfs/keystore.jks") \
                .option("es.net.ssl.keystore.pass", "xxxx") \
                .option("es.net.ssl.protocol","TLS") \
                .option("es.write.operation", "upsert") \
        .option("es.spark.dataframe.write.null","true")\
                .save()

```

Strack trace:

```
19/04/28 13:14:15 ERROR Executor: Exception in task 0.0 in stage 1.0 (TID 1)
org.elasticsearch.hadoop.serialization.EsHadoopSerializationException: org.codehaus.jackson.JsonParseException: Unexpected character ('(' (code 40)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: [B@25a91b8c; line: 1, column: 2]
	at org.elasticsearch.hadoop.serialization.json.JacksonJsonParser.nextToken(JacksonJsonParser.java:95)
	at org.elasticsearch.hadoop.serialization.ParsingUtils.doFind(ParsingUtils.java:165)
	at org.elasticsearch.hadoop.serialization.ParsingUtils.values(ParsingUtils.java:151)
	at org.elasticsearch.hadoop.serialization.field.JsonFieldExtractors.process(JsonFieldExtractors.java:213)
	at org.elasticsearch.hadoop.serialization.bulk.JsonTemplatedBulk.preProcess(JsonTemplatedBulk.java:64)
	at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.write(TemplatedBulk.java:54)
	at org.elasticsearch.hadoop.rest.RestRepository.writeToIndex(RestRepository.java:187)
	at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:67)
	at org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1.apply(EsSparkSQL.scala:101)
	at org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1.apply(EsSparkSQL.scala:101)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:411)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
``` 

### Version Info

OS:         :  Centos 7
JVM         :  
Hadoop/Spark:  2.4.2
ES-Hadoop   :  spark-2.4.0-bin-hadoop2.6.tgz
ES          :  6.1.2

**Comment by jbaiera** [comment]
I was able to reproduce this and found that the main issue here is that you are using the `es.input.json`  setting to ingest data that is in Spark SQL Row format. Removing that setting should make this example work (though if you are using `upsert` you will still need to provide a value for `es.mapping.id`). Looking into the issue further, it seems that SparkSQL does not handle JSON input data at all. If you are trying to ingest raw JSON data, you should use the RDD api.
