### ISSUE TITLE
Exception with 4 byte UTF-8 characters

### ISSUE THREAD

**Issue by Freds72AtWork** [elastic/elasticsearch-hadoop#1389]
### Issue description

Client-side exception when sending data from Spark to Elasticsearch via EsHadoop lib (RDD API).
The data contains a 4 byte UTF-8 char: 💓 (U+1F493 / f0 9f 92 93)

### Steps to reproduce

Code:

```
// define a case class
case class Trip(departure: String, arrival: String)               
val upcomingTrip = Trip("OTP", "SFO💓")
val lastWeekTrip = Trip("MUC🐄", "OTP")
val rdd = sc.makeRDD(Seq(upcomingTrip, lastWeekTrip))  
EsSpark.saveJsonToEs(rdd, "spark/docs")
```

Strack trace:

```
org.elasticsearch.hadoop.serialization.EsHadoopSerializationException: org.codehaus.jackson.JsonParseException: Invalid UTF-8 start byte 0x93
 at [Source: [B@3e4b9709; line: 1, column: 1216]
        at org.elasticsearch.hadoop.serialization.json.JacksonJsonParser.skipChildren(JacksonJsonParser.java:137)
        at org.elasticsearch.hadoop.serialization.ParsingUtils.doFind(ParsingUtils.java:217)
        at org.elasticsearch.hadoop.serialization.ParsingUtils.values(ParsingUtils.java:151)
        at org.elasticsearch.hadoop.serialization.field.JsonFieldExtractors.process(JsonFieldExtractors.java:213)
        at org.elasticsearch.hadoop.serialization.bulk.JsonTemplatedBulk.preProcess(JsonTemplatedBulk.java:64)
        at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.write(TemplatedBulk.java:54)
        at org.elasticsearch.hadoop.rest.RestRepository.writeToIndex(RestRepository.java:168)
        at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:67)
        at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:107)
        at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:107)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:109)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.codehaus.jackson.JsonParseException: Invalid UTF-8 start byte 0x93
 at [Source: [B@3e4b9709; line: 1, column: 1216]
        at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1432)
        at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:385)
        at org.codehaus.jackson.impl.Utf8StreamParser._reportInvalidInitial(Utf8StreamParser.java:2796)
        at org.codehaus.jackson.impl.Utf8StreamParser._reportInvalidChar(Utf8StreamParser.java:2790)
        at org.codehaus.jackson.impl.Utf8StreamParser._skipString(Utf8StreamParser.java:2046)
        at org.codehaus.jackson.impl.Utf8StreamParser.nextToken(Utf8StreamParser.java:435)
        at org.codehaus.jackson.impl.JsonParserMinimalBase.skipChildren(JsonParserMinimalBase.java:96)
        at org.elasticsearch.hadoop.serialization.json.JacksonJsonParser.skipChildren(JacksonJsonParser.java:135)
        ... 15 more

``` 

### Version Info

OS:         :   RHEL 7.7
JVM         :  Openjdk 1.8
Hadoop/Spark:  2.7.0 / 2.3.1
ES-Hadoop   :  6.3.0
ES          :  6.4

**Comment by Freds72AtWork** [comment]
Reproduced on:
ES-Hadoop : 6.4.3

Reproduced using a RDD of bytes (to avoid any bogus in-library conversion):
```
EsSpark.saveJsonToEs(rdd.map(_.getBytes(StandardCharsets.UTF_8)), target, Map(
            ES_MAPPING_ID -> conf.recordIdByIndex(group)
        ))
```

**Comment by Freds72AtWork** [comment]
Root cause was a runtime jar conflicts - the Spark java context was loading HIVE libraries with a *much* newer version of org.codehaus.jackson libraries.
That resulted in incorrect code execution (and incorrect decoding of UTF chars).
