### ISSUE TITLE
OutOfMemoryError for terms query, guidance on max number of terms

### ISSUE THREAD

**Issue by mayya-sharipova** [elastic/elasticsearch-hadoop#1476]
In elasticsearch [terms query ](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-terms-query.html) supports up to 65,536 terms. 

Using a terms query in the spark connector with around 10K terms leads to OutOfMemoryError:

```sh
: java.lang.OutOfMemoryError: Java heap space
at java.util.Arrays.copyOfRange(Arrays.java:3664)
at java.lang.StringBuffer.toString(StringBuffer.java:669)
at java.util.Properties.saveConvert(Properties.java:652)
at java.util.Properties.store0(Properties.java:839)
at java.util.Properties.store(Properties.java:771)
at org.elasticsearch.hadoop.util.IOUtils.propsToString(IOUtils.java:98)
at org.elasticsearch.hadoop.cfg.Settings.save(Settings.java:763)
at org.elasticsearch.hadoop.rest.PartitionDefinition.(PartitionDefinition.java:70)
at org.elasticsearch.hadoop.rest.PartitionDefinition.(PartitionDefinition.java:50)
at org.elasticsearch.hadoop.rest.RestService.findShardPartitions(RestService.java:312)
at org.elasticsearch.hadoop.rest.RestService.findPartitions(RestService.java:272)
```

What is the way to know the upper bound for terms query and guard against it?

**Comment by jbaiera** [comment]
Looking at the code, its possible that targeting a sufficiently large index could lead to this problem. We create a PartitionDefinition for each shard we are working with. For each PartitionDefinition we save the connector settings and mappings as strings for serialization. If we're creating hundreds of partitions, that's duplicating settings and mappings hundreds of times in memory. I'll open a fix so that we serialize this data only once and flyweight it between the Partition Definitions since they do not mutate it.
