### ISSUE TITLE
Can't use a trustore/keystore with empty password

### ISSUE THREAD

**Issue by fpompermaier** [elastic/elasticsearch-hadoop#1506]
### What kind an issue is this?

- [X] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

Can't connect to ES if the trustore/keystore has an empty password. If this is a JDK problem it should be highlighted in the docs at least.

### Steps to reproduce

Generate elastic certificates using elasticsearch-certutil but using an empty password:

`elasticsearch-certutil cert -out elastic-certificates.p12 -pass ""`

Within elastic and set in elasticsearch.yml:

```
xpack.security.enabled: true

xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.verification_mode: certificate
xpack.security.http.ssl.client_authentication: optional
xpack.security.http.ssl.keystore.path: elastic-certificates.p12
xpack.security.http.ssl.truststore.path: elastic-certificates.p12

xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: elastic-certificates.p12
```

Run the following code:

```
EsInputFormat<Text, LinkedMapWritable> kvEsInputFormat = new EsInputFormat<>();

HadoopInputFormat<Text, LinkedMapWritable> hadoopInputFormat =
        new HadoopInputFormat<>(kvEsInputFormat, Text.class, LinkedMapWritable.class);

final org.apache.hadoop.conf.Configuration cfg = hadoopInputFormat.getConfiguration();
cfg.set(ConfigurationOptions.ES_RESOURCE, "test");
cfg.set(ConfigurationOptions.ES_QUERY, "?q=*");
cfg.set(ConfigurationOptions.ES_READ_FIELD_INCLUDE, "name,someid");
cfg.set(ConfigurationOptions.ES_NODES, "https://localhost");
cfg.set(ConfigurationOptions.ES_PORT, "9200");
cfg.set(ConfigurationOptions.ES_NET_HTTP_AUTH_USER, "elastic");
cfg.set(ConfigurationOptions.ES_NET_HTTP_AUTH_PASS, "elastic");
cfg.set(ConfigurationOptions.ES_NET_USE_SSL, "true");
cfg.set(ConfigurationOptions.ES_NET_SSL_PROTOCOL, "SSL");
cfg.set(ConfigurationOptions.ES_NET_USE_SSL_DEFAULT, "true");
cfg.set(ConfigurationOptions.ES_HTTP_TIMEOUT, "5m");
cfg.set(ConfigurationOptions.ES_SCROLL_KEEPALIVE, "10m");

cfg.set(ConfigurationOptions.ES_NET_SSL_CERT_ALLOW_SELF_SIGNED, "true");
cfg.set(ConfigurationOptions.ES_NET_SSL_KEYSTORE_TYPE, "PKCS12);

cfg.set(ConfigurationOptions.ES_NET_SSL_TRUST_STORE_LOCATION, "elastic-certificates.p12");
cfg.set(ConfigurationOptions.ES_NET_SSL_TRUST_STORE_PASS, "");
cfg.set(ConfigurationOptions.ES_NET_SSL_KEYSTORE_LOCATION, "elastic-certificates.p12");
cfg.set(ConfigurationOptions.ES_NET_SSL_KEYSTORE_PASS, "");
```

Strack trace:

```
Caused by: org.elasticsearch.hadoop.rest.EsHadoopTransportException: javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at org.elasticsearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:128)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:432)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:428)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:388)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:392)
	at org.elasticsearch.hadoop.rest.RestClient.get(RestClient.java:168)
	at org.elasticsearch.hadoop.rest.RestClient.mainInfo(RestClient.java:745)
	at org.elasticsearch.hadoop.rest.InitializationUtils.discoverClusterInfo(InitializationUtils.java:330)
	... 27 more
Caused by: javax.net.ssl.SSLException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:133)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:326)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:269)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
	at java.base/sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1576)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:453)
	at java.base/sun.security.ssl.SSLSocketImpl.ensureNegotiated(SSLSocketImpl.java:814)
	at java.base/sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1184)
	at java.base/java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:81)
	at java.base/java.io.BufferedOutputStream.flush(BufferedOutputStream.java:142)
	at org.apache.commons.httpclient.HttpConnection.flushRequestOutputStream(HttpConnection.java:828)
	at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2116)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at org.elasticsearch.hadoop.rest.commonshttp.CommonsHttpTransport.doExecute(CommonsHttpTransport.java:685)
	at org.elasticsearch.hadoop.rest.commonshttp.CommonsHttpTransport.execute(CommonsHttpTransport.java:664)
	at org.elasticsearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:116)
	... 34 more
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:102)
	at java.base/sun.security.validator.Validator.getInstance(Validator.java:181)
	at java.base/sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:300)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:176)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:189)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:110)
	at org.elasticsearch.hadoop.rest.commonshttp.SSLSocketFactory$TrustManagerDelegate.checkServerTrusted(SSLSocketFactory.java:76)
	at java.base/sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:1510)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1323)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1214)
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1157)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:444)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:422)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:183)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1403)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1309)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:440)
	... 48 more
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
	at java.base/java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
	at java.base/java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
	at java.base/java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
	at java.base/sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:99)
	... 66 more
``` 

### Version Info

OS:         Ubuntu 18.04 LTS
JVM:         OpenJDK 11
Hadoop/Spark:  2.6.0
ES-Hadoop   :  7.8.0
ES          :  7.8.0

**Comment by jbaiera** [comment]
```
cfg.set(ConfigurationOptions.ES_NET_SSL_TRUST_STORE_LOCATION, "elastic-certificates.p12");
```

Is this file available on the job's classpath? If not, the trust store will not be picked up. Often times that is the issue that leads to "trustAnchors" parameter being empty.

**Comment by jbaiera** [comment]
Closing since no further feedback was received.
