### ISSUE TITLE
Can not login as kerberos on spark worker

### ISSUE THREAD

**Issue by wenyangchou** [elastic/elasticsearch-hadoop#1607]
### Issue description

When the job committed at executor , it reported "Could not locate Kerberos Principal on currently logged in user."

Description

Log on driver :

> 2021/02/18 18:10:09.612 DEBUG UserGroupInformation: [] hadoop login
2021/02/18 18:10:09.614 DEBUG UserGroupInformation: [] hadoop login commit
2021/02/18 18:10:09.617 DEBUG UserGroupInformation: [] using local user:UnixPrincipal: tss
2021/02/18 18:10:09.618 DEBUG UserGroupInformation: [] Using user: "UnixPrincipal: tss" with name tss
2021/02/18 18:10:09.618 DEBUG UserGroupInformation: [] User entry: "tss"
2021/02/18 18:10:09.622 DEBUG UserGroupInformation: [] Reading credentials from location set in HADOOP_TOKEN_FILE_LOCATION: /srv/BigData/hadoop/data1/nm/localdir/usercache/tss/appcache/application_1611987488531_0743/container_e13_1611987488531_0743_02_000001/container_tokens
2021/02/18 18:10:09.635 DEBUG UserGroupInformation: [] Loaded 2 tokens
2021/02/18 18:10:09.636 DEBUG UserGroupInformation: [] UGI loginUser:tss (auth:SIMPLE)
2021/02/18 18:10:09.637 INFO AMCredentialRenewer: [] Attempting to login to KDC using principal: tss@HADOOP.COM
2021/02/18 18:10:09.727 DEBUG UserGroupInformation: [] hadoop login
2021/02/18 18:10:09.728 DEBUG UserGroupInformation: [] hadoop login commit
2021/02/18 18:10:09.728 DEBUG UserGroupInformation: [] using kerberos user:tss@HADOOP.COM
2021/02/18 18:10:09.729 DEBUG UserGroupInformation: [] Using user: "tss@HADOOP.COM" with name tss@HADOOP.COM
2021/02/18 18:10:09.729 DEBUG UserGroupInformation: [] User entry: "tss@HADOOP.COM"
2021/02/18 18:10:09.730 INFO AMCredentialRenewer: [] Successfully logged into KDC.
2021/02/18 18:10:09.733 DEBUG UserGroupInformation: [] PrivilegedAction as:tss@HADOOP.COM (auth:KERBEROS) 

Log on executor:

> 2021/02/18 18:10:19.426 DEBUG UserGroupInformation: [] hadoop login
2021/02/18 18:10:19.427 DEBUG UserGroupInformation: [] hadoop login commit
2021/02/18 18:10:19.428 DEBUG UserGroupInformation: [] using local user:UnixPrincipal: tss
2021/02/18 18:10:19.429 DEBUG UserGroupInformation: [] Using user: "UnixPrincipal: tss" with name tss
2021/02/18 18:10:19.429 DEBUG UserGroupInformation: [] User entry: "tss"
2021/02/18 18:10:19.432 DEBUG UserGroupInformation: [] Reading credentials from location set in HADOOP_TOKEN_FILE_LOCATION: /srv/BigData/hadoop/data1/nm/localdir/usercache/tss/appcache/application_1611987488531_0743/container_e13_1611987488531_0743_02_000002/container_tokens
2021/02/18 18:10:19.448 DEBUG UserGroupInformation: [] Loaded 2 tokens
2021/02/18 18:10:19.449 DEBUG UserGroupInformation: [] UGI loginUser:tss (auth:SIMPLE)
2021/02/18 18:10:19.449 DEBUG UserGroupInformation: [] PrivilegedAction as:tss (auth:SIMPLE) from:org.apache.spark.deploy.SparkHadoopUtil.runAsSparkUser(SparkHadoopUtil.scala:64)

In driver ,am would renew the token ,ugi can login as kerberos. While in executor ,the ugi login simple that ugi 
method hasKerberosCredentials() return a false. As as result , a exception has been throwed which reports "Could not locate Kerberos Principal on currently logged in user."

I have tried for a long time but not success .  

### Steps to reproduce

Code:

```
spark-submit --class cn.zwy.SparkWordCount \
--master yarn --deploy-mode cluster --conf 'spark.es.nodes=fusioninsight02:24100' \
--jars ~/elasticsearch-hadoop-7.10.2.jar \
--conf 'spark.es.ssl.enabled=true' \
--conf 'spark.es.net.ssl=true' \
--conf 'spark.es.resource=22lastk_eoi_2020_02_05' \
--conf 'es.net.ssl=true' \
--conf 'spark.es.security.authentication=kerberos' \
--conf 'es.security.authentication=kerberos' \
--conf 'spark.es.net.spnego.auth.elasticsearch.principal=elasticsearch/hadoop.hadoop.com@HADOOP.COM' \
--conf spark.yarn.submit.waitAppCompletion=false \
--conf spark.driver.extraJavaOptions="-Djava.security.krb5.conf=/opt/huawei/Bigdata/FusionInsight_BASE_6.5.1/3_49_KerberosClient/etc/kdc.conf"  \
--conf spark.executor.extraJavaOptions="-Djava.security.krb5.conf=/opt/huawei/Bigdata/FusionInsight_BASE_6.5.1/3_49_KerberosClient/etc/kdc.conf"  \
--conf spark.yarn.credentials.file=/tmp \
--principal tss@HADOOP.COM \
--keytab /data01/jax1.0/jax/user.keytab \
--conf 'hadoop.security.authentication=kerberos' \
~/spark-test-1.0-SNAPSHOT.jar 
```

Strack trace:

```
2021/02/18 18:10:24.613 ERROR TaskContextImpl: [] Error in TaskCompletionListener
org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Could not locate Kerberos Principal on currently logged in user.
 at org.elasticsearch.hadoop.rest.commonshttp.CommonsHttpTransport.addHttpAuth(CommonsHttpTransport.java:346)
 at org.elasticsearch.hadoop.rest.commonshttp.CommonsHttpTransport.<init>(CommonsHttpTransport.java:231)
 at org.elasticsearch.hadoop.rest.commonshttp.CommonsHttpTransportFactory.create(CommonsHttpTransportFactory.java:40)
 at org.elasticsearch.hadoop.rest.NetworkClient.selectNextNode(NetworkClient.java:99)
 at org.elasticsearch.hadoop.rest.NetworkClient.<init>(NetworkClient.java:82)
 at org.elasticsearch.hadoop.rest.NetworkClient.<init>(NetworkClient.java:58)
 at org.elasticsearch.hadoop.rest.RestClient.<init>(RestClient.java:101)
 at org.elasticsearch.hadoop.rest.RestRepository.<init>(RestRepository.java:129)
 at org.elasticsearch.hadoop.rest.RestService.createReader(RestService.java:422)
 at org.elasticsearch.spark.rdd.AbstractEsRDDIterator.reader$lzycompute(AbstractEsRDDIterator.scala:49)
 at org.elasticsearch.spark.rdd.AbstractEsRDDIterator.reader(AbstractEsRDDIterator.scala:42)
 at org.elasticsearch.spark.rdd.AbstractEsRDDIterator.close(AbstractEsRDDIterator.scala:81)
 at org.elasticsearch.spark.rdd.AbstractEsRDDIterator.closeIfNeeded(AbstractEsRDDIterator.scala:74)
 at org.elasticsearch.spark.rdd.AbstractEsRDDIterator$$anonfun$1.apply$mcV$sp(AbstractEsRDDIterator.scala:54)
 at org.elasticsearch.spark.rdd.AbstractEsRDDIterator$$anonfun$1.apply(AbstractEsRDDIterator.scala:54)
 at org.elasticsearch.spark.rdd.AbstractEsRDDIterator$$anonfun$1.apply(AbstractEsRDDIterator.scala:54)
 at org.elasticsearch.spark.rdd.CompatUtils$1.onTaskCompletion(CompatUtils.java:112)
 at org.apache.spark.TaskContextImpl$$anonfun$markTaskCompleted$1.apply(TaskContextImpl.scala:118)
 at org.apache.spark.TaskContextImpl$$anonfun$markTaskCompleted$1.apply(TaskContextImpl.scala:118)
 at org.apache.spark.TaskContextImpl$$anonfun$invokeListeners$1.apply(TaskContextImpl.scala:131)
 at org.apache.spark.TaskContextImpl$$anonfun$invokeListeners$1.apply(TaskContextImpl.scala:129)
 at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
 at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
 at org.apache.spark.TaskContextImpl.invokeListeners(TaskContextImpl.scala:129)
 at org.apache.spark.TaskContextImpl.markTaskCompleted(TaskContextImpl.scala:117)
 at org.apache.spark.scheduler.Task.run(Task.scala:119)
 at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)
``` 

### Version Info

OS:         :  centos 7
JVM         :  oracle 1.8
Hadoop/Spark:  3.0/2.3
ES-Hadoop   :  7.1
ES          :  6.7

platform: Huawei Fusionsight

**Comment by wenyangchou** [comment]
@jbaiera

**Comment by jbaiera** [comment]
@wenyangchou Have you [updated the yarn site](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/kerberos.html#kerberos-hadoop) configuration to have kerberos authentication enabled as well?

**Comment by jbaiera** [comment]
Closing this as there hasn't been any further feedback
