### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by ekhc** [elastic/elasticsearch-hadoop#1966]
### What kind an issue is this?

- [X] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

Using elasticsearch-hadoop to ingest data from HDFS clusters into Elasticsearch using Spark 3.1.2 and Scala 2.12 and Elasticsearch 7.10.1 I get a NoSuchMethodError. I can't upgrade Elasticsearch because of license issues. Is the error because the ES version is so low?

### Steps to reproduce

Code:

```
object DLtoESJob {
  private val config = ConfigFactory.load()

  private val master = config.getString("spark.master")
  private val appName = config.getString("spark.app.name")

  private val pathToJSONResource = config.getString("spark.json.resource.path")

  private val elasticsearchUser = config.getString("spark.elasticsearch.username")
  private val elasticsearchPass = config.getString("spark.elasticsearch.password")
  private val elasticsearchHost = config.getString("spark.elasticsearch.host")
  private val elasticsearchPort = config.getString("spark.elasticsearch.port")

  private val outputMode = config.getString("spark.elasticsearch.output.mode")
  private val destination = config.getString("spark.elasticsearch.data.source")
  private val checkpointLocation = config.getString("spark.elasticsearch.checkpoint.location")
  private val index = config.getString("spark.elasticsearch.index")
  private val docType = config.getString("spark.elasticsearch.doc.type")
  private val indexAndDocType = s"$index/$docType"

  /** Our main function where the action happens */
  def main(args: Array[String]) {

    // Set the log level to only print errors
    Logger.getLogger("org").setLevel(Level.ERROR)

    val spark = SparkSession.builder
      .config(ConfigurationOptions.ES_NET_HTTP_AUTH_USER, elasticsearchUser)
      .config(ConfigurationOptions.ES_NET_HTTP_AUTH_PASS, elasticsearchPass)
      .config(ConfigurationOptions.ES_NODES, elasticsearchHost)
      .config(ConfigurationOptions.ES_PORT, elasticsearchPort)
      .appName(appName)
      .master(master)
      .getOrCreate()

    val jsonSchema = StructType(
      Seq(
        StructField("api", StringType, true),
        StructField("caller", StringType, true),
        StructField("total_response_time", StringType, true),
        StructField("timestamp", StringType, true),
        StructField("session_id", IntegerType, true),
        StructField("log_version", StringType, true),
        StructField(
          "metadata",
          StructType(
            Array(
              StructField("is_usage_agreed", BooleanType, true),
              StructField("lang_detect_raw", StringType, true),
              StructField("source", StringType, true),
              StructField("target", StringType, true),
              StructField("pivot", NullType, true),
              StructField("replace_info", StringType, true),
              StructField("is_honorific", BooleanType, true),
              StructField("batch_size", IntegerType, true),
              StructField("domain_type", StringType, true),
              StructField("requested_page_url", StringType, true)
            )
          )
        ),
        StructField(
          "messages",
          StructType(
            Array(
              StructField("actual_translation_type", StringType, true),
              StructField("input_text", StringType, true),
              StructField("output_text", StringType, true),
              StructField("model_version", StringType, true),
              StructField("translate_elapsed", StringType, true)
            )
          )
        )
      )
    )

    val streamingDF: DataFrame = spark.readStream
      .schema(jsonSchema)
      .format("org.apache.spark.sql.execution.datasources.json.JsonFileFormat")
      .load(pathToJSONResource)

    streamingDF.writeStream
      .outputMode(outputMode)
      .format(destination)
      .option("checkpointLocation", checkpointLocation)
      .start(indexAndDocType)
      .awaitTermination()

    // Stop the session
    spark.stop()
  }

}
```

Strack trace:

```
Logical Plan:
FileStreamSource[hdfs://pct/user/papago-mlops-datalake/raw/mt-log/engine=n2mt/year=2022/date=0430/hour=00]
        at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:356)
        at org.apache.spark.sql.execution.streaming.StreamExecution$$anon$1.run(StreamExecution.scala:244)
Caused by: java.lang.NoSuchMethodError: org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(Lorg/apache/spark/sql/SparkSession;Lorg/apache/spark/sql/execution/QueryExecution;Lscala/Function0;)Ljava/lang/Object;
        at org.elasticsearch.spark.sql.streaming.EsSparkSqlStreamingSink.addBatch(EsSparkSqlStreamingSink.scala:62)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runBatch$16(MicroBatchExecution.scala:586)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
        at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
        at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runBatch$15(MicroBatchExecution.scala:584)
        at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken(ProgressReporter.scala:357)
        at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken$(ProgressReporter.scala:355)
        at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:68)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runBatch(MicroBatchExecution.scala:584)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runActivatedStream$2(MicroBatchExecution.scala:226)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken(ProgressReporter.scala:357)
        at org.apache.spark.sql.execution.streaming.ProgressReporter.reportTimeTaken$(ProgressReporter.scala:355)
        at org.apache.spark.sql.execution.streaming.StreamExecution.reportTimeTaken(StreamExecution.scala:68)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution.$anonfun$runActivatedStream$1(MicroBatchExecution.scala:194)
        at org.apache.spark.sql.execution.streaming.ProcessingTimeExecutor.execute(TriggerExecutor.scala:57)
        at org.apache.spark.sql.execution.streaming.MicroBatchExecution.runActivatedStream(MicroBatchExecution.scala:188)
        at org.apache.spark.sql.execution.streaming.StreamExecution.$anonfun$runStream$1(StreamExecution.scala:334)
        at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
        at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
        at org.apache.spark.sql.execution.streaming.StreamExecution.org$apache$spark$sql$execution$streaming$StreamExecution$$runStream(StreamExecution.scala:317)
        ... 1 more

         ApplicationMaster host: ac3d0x2103.bdp.bdata.ai
         ApplicationMaster RPC port: 35716
         queue: batch
         start time: 1654569776147
         final status: FAILED
         tracking URL: https://gemini-rm1.bdp.bdata.ai:9090/proxy/application_1648605534398_12546425/
         user: papago-mlops-datalake
Exception in thread "main" org.apache.spark.SparkException: Application application_1648605534398_12546425 finished with failed status
        at org.apache.spark.deploy.yarn.Client.run(Client.scala:1269)
        at org.apache.spark.deploy.yarn.YarnClusterApplication.start(Client.scala:1627)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:904)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
2022-06-07 11:44:41,714 INFO util.ShutdownHookManager: Shutdown hook called
2022-06-07 11:44:41,715 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-321ae99e-1b02-4a05-848d-09aa70ce4a16
2022-06-07 11:44:41,717 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-932811bb-ee8f-438b-bf17-6fa6160c92e1
``` 

### Version Info

OS:         :  Centos7
JVM         :  
Hadoop/Spark:  Hadoop 3.1.1.3.1.2-50, Spark 3.1.2, Scala 2.12
ES-Hadoop   :  7.10.1
ES          :  7.10.1

**Comment by masseyke** [comment]
Support for spark 3.0 wasn't added until es-hadoop 7.12.0 unfortunately -- https://www.elastic.co/guide/en/elasticsearch/hadoop/7.17/eshadoop-7.12.0.html.
