### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Aangbaeck** [elastic/elasticsearch-hadoop#2035]
### What kind an issue is this?
- [ x] Bug report.

### Issue description
I try to run my spark/scala code against ES 7.16.2. I can't wrap my head around why I get this error. I'm pretty certain I have compatible versions. Can someone help me?

### Steps to reproduce
Running my code with spark on YARN.

import org.elasticsearch.spark._
var df = spark.read.format("avro").load(...)
df.saveToEs("test")

Failing on the YARN-Cluster
Strack trace:
org.apache.spark.SparkException: Job aborted due to stage failure: Task 14 in stage 4.0 failed 4 times, most recent failure: Lost task 14.3 in stage 4.0 (TID 272) (server_name executor 4): java.lang.NoSuchMethodError: scala.Predef$.refArrayOps([Ljava/lang/Object;)Lscala/collection/mutable/ArrayOps;
	at org.elasticsearch.spark.sql.DataFrameValueWriter.writeStruct(DataFrameValueWriter.scala:78)
	at org.elasticsearch.spark.sql.DataFrameValueWriter.write(DataFrameValueWriter.scala:70)
	at org.elasticsearch.spark.sql.DataFrameValueWriter.write(DataFrameValueWriter.scala:53)
	at org.elasticsearch.hadoop.serialization.builder.ContentBuilder.value(ContentBuilder.java:53)
	at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.doWriteObject(TemplatedBulk.java:71)
	at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.write(TemplatedBulk.java:58)
	at org.elasticsearch.hadoop.serialization.bulk.BulkEntryWriter.writeBulkEntry(BulkEntryWriter.java:68)
	at org.elasticsearch.hadoop.rest.RestRepository.writeToIndex(RestRepository.java:170)
	at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:83)
	at org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1.apply(EsSparkSQL.scala:103)
	at org.elasticsearch.spark.sql.EsSparkSQL$$anonfun$saveToEs$1.apply(EsSparkSQL.scala:103)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:131)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:498)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:501)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

### Version Info
OS:     Red Hat 7.9  :  
JVM       1.8.0_345 :  
Hadoop/Spark:  3.1.3
ES-Hadoop: 7.16.2:
ES        7.16.2: 
Scala:   2.12.10

**Comment by Aangbaeck** [comment]
I have come a bit further. I can write the datatype "org.apache.spark.rdd.ParallelCollectionRDD" to Elastic, but not org.apache.spark.rdd.MapPartitionsRDD that you would get from creating a RDD from org.apache.spark.sql.Dataset iva ".rdd"
I get the error:
"org.elasticsearch.hadoop.serialization.EsHadoopSerializationException: org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Spark SQL types are not handled through basic RDD saveToEs() calls; typically this is a mistake(as the SQL schema will be ignored). Use 'org.elasticsearch.spark.sql' package instead"

but I'm importing 
import org.elasticsearch.spark.sql._

**Comment by masseyke** [comment]
Which es-spark jar are you using? You have to use the one that is compatible with your spark version _and_ your scala version (both spark and scala frequently have breaking changes between versions). Since you are on spark 3.1.3 with scala 2.12.10 you want to be using [elasticsearch-spark-30_2.12](https://search.maven.org/artifact/org.elasticsearch/elasticsearch-spark-30_2.12/7.16.2/jar).

**Comment by masseyke** [comment]
Oh I just noticed that you said "Hadoop/Spark" 3.1.3. Hadoop and spark are versioned independently. Is it possible that you have Hadoop 3.1.3 and some other Spark version?

**Comment by Aangbaeck** [comment]
I didn't get it to work with Spark DF but I made it work by serializing the DF myself and then using the Hadoop connector. It is still pretty fast. I will do some more testing but here is the code for anyone wanting to do the same.

val mapped = df.collect.map(r => Map(df.columns.zip(r.toSeq):_*))
sc.makeRDD(mapped).saveToEs("test/_doc")

**Comment by masseyke** [comment]
Just curious -- did you try the correct jar for your spark and scala?

**Comment by Aangbaeck** [comment]
Yes, using the correct one. It's the spark version I'm mentioning. Have tried different versions (higher) of the jar and get the same error when trying to use .saveToEs on my DF. They all work on Seq data though.
