### ISSUE TITLE
Invalid major version [2.4.1] when trying to write Avro files to OpenSearch

### ISSUE THREAD

**Issue by mt256** [elastic/elasticsearch-hadoop#2062]
### What kind an issue is this?

- [x] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

Trying to bulk load Avro documents to Aiven-hosted OpenSearch, which is an open source fork of Elasticsearch, compatible with v7.10. Using Databricks for that.

### Steps to reproduce

Code:

```
import org.apache.spark.sql.avro._
data = spark.read.format("avro").load(PATH)
val options = Map(
    "es.port" -> ES_CREDENTIALS("ES_PORT"),
    "es.index.auto.create" -> "false",
    "es.net.ssl" -> "true",
    "es.nodes.wan.only" -> "true",
    "es.net.ssl.cert.allow.self.signed" -> "true",
    "es.nodes" -> ES_CREDENTIALS("ES_HOST"),
    "es.mapping.id" -> "id",
    "es.net.http.auth.user" -> ES_CREDENTIALS("ES_USER"),
    "es.net.http.auth.pass" -> ES_CREDENTIALS("ES_PWD"),
    "es.write.operation" -> "upsert",
    "es.spark.dataframe.write.null" -> "true"
  )
data.write
  .format("org.elasticsearch.spark.sql")
  .options(options)
  .mode("append")
  .save(ES_CREDENTIALS("ES_INDEX"))
```

Strack trace:

```
EsHadoopIllegalArgumentException: Cannot detect ES version - typically this happens if the network/Elasticsearch cluster is not accessible or when targeting a WAN/Cloud instance without the proper setting 'es.nodes.wan.only'
Caused by: EsHadoopIllegalStateException: Invalid major version [2.4.1]. Version is lower than minimum required version [6.x].
	at org.elasticsearch.hadoop.rest.InitializationUtils.discoverClusterInfo(InitializationUtils.java:403)
	at org.elasticsearch.spark.sql.EsSparkSQL$.saveToEs(EsSparkSQL.scala:99)
	at org.elasticsearch.spark.sql.ElasticsearchRelation.insert(DefaultSource.scala:629)
	at org.elasticsearch.spark.sql.DefaultSource.createRelation(DefaultSource.scala:107)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:49)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.$anonfun$sideEffectResult$1(commands.scala:80)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:78)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:77)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:89)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.$anonfun$applyOrElse$2(QueryExecution.scala:247)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$8(SQLExecution.scala:245)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:424)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:190)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1035)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:144)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:374)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.$anonfun$applyOrElse$1(QueryExecution.scala:247)
	at org.apache.spark.sql.execution.QueryExecution.org$apache$spark$sql$execution$QueryExecution$$withMVTagsIfNecessary(QueryExecution.scala:232)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.applyOrElse(QueryExecution.scala:245)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.applyOrElse(QueryExecution.scala:238)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:519)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:106)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:519)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:268)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:264)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:495)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$eagerlyExecuteCommands$1(QueryExecution.scala:238)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:324)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:238)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:192)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:183)
	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:295)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:964)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:429)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:396)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:250)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-47492:5)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-47492:77)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-47492:79)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-47492:81)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-47492:83)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-47492:85)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-47492:87)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-47492:89)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-47492:91)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-47492:93)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-47492:95)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-47492:97)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-47492:99)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-47492:101)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw$$iw.<init>(command-47492:103)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw.<init>(command-47492:105)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw.<init>(command-47492:107)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw.<init>(command-47492:109)
	at $line63811d5bb667486dbff0a25476ac733d123.$read.<init>(command-47492:111)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$.<init>(command-47492:115)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$.<clinit>(command-47492)
	at $line63811d5bb667486dbff0a25476ac733d123.$eval$.$print$lzycompute(<notebook>:7)
	at $line63811d5bb667486dbff0a25476ac733d123.$eval$.$print(<notebook>:6)
	at $line63811d5bb667486dbff0a25476ac733d123.$eval.$print(<notebook>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:747)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1020)
	at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:568)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:36)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:116)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:41)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:567)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:594)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:564)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:223)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.$anonfun$repl$1(ScalaDriverLocal.scala:227)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:1258)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:1211)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:227)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$execute$23(DriverLocal.scala:867)
	at com.databricks.unity.EmptyHandle$.runWith(UCSHandle.scala:103)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$execute$20(DriverLocal.scala:850)
	at com.databricks.logging.UsageLogging.$anonfun$withAttributionContext$1(UsageLogging.scala:407)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:158)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:405)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:402)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:69)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:450)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:435)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:69)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:827)
	at com.databricks.backend.daemon.driver.DriverWrapper.$anonfun$tryExecutingCommand$1(DriverWrapper.scala:659)
	at scala.util.Try$.apply(Try.scala:213)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:651)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommandAndGetError(DriverWrapper.scala:570)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:605)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:447)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:388)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:246)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.elasticsearch.hadoop.EsHadoopIllegalStateException: Invalid major version [2.4.1]. Version is lower than minimum required version [6.x].
	at org.elasticsearch.hadoop.rest.RestClient.mainInfo(RestClient.java:770)
	at org.elasticsearch.hadoop.rest.InitializationUtils.discoverClusterInfo(InitializationUtils.java:393)
	at org.elasticsearch.spark.sql.EsSparkSQL$.saveToEs(EsSparkSQL.scala:99)
	at org.elasticsearch.spark.sql.ElasticsearchRelation.insert(DefaultSource.scala:629)
	at org.elasticsearch.spark.sql.DefaultSource.createRelation(DefaultSource.scala:107)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:49)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.$anonfun$sideEffectResult$1(commands.scala:80)
	at com.databricks.spark.util.FrameProfiler$.record(FrameProfiler.scala:80)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:78)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:77)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.executeCollect(commands.scala:89)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.$anonfun$applyOrElse$2(QueryExecution.scala:247)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$8(SQLExecution.scala:245)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:424)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withCustomExecutionEnv$1(SQLExecution.scala:190)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:1035)
	at org.apache.spark.sql.execution.SQLExecution$.withCustomExecutionEnv(SQLExecution.scala:144)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:374)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.$anonfun$applyOrElse$1(QueryExecution.scala:247)
	at org.apache.spark.sql.execution.QueryExecution.org$apache$spark$sql$execution$QueryExecution$$withMVTagsIfNecessary(QueryExecution.scala:232)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.applyOrElse(QueryExecution.scala:245)
	at org.apache.spark.sql.execution.QueryExecution$$anonfun$$nestedInanonfun$eagerlyExecuteCommands$1$1.applyOrElse(QueryExecution.scala:238)
	at org.apache.spark.sql.catalyst.trees.TreeNode.$anonfun$transformDownWithPruning$1(TreeNode.scala:519)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:106)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDownWithPruning(TreeNode.scala:519)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.org$apache$spark$sql$catalyst$plans$logical$AnalysisHelper$$super$transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning(AnalysisHelper.scala:268)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper.transformDownWithPruning$(AnalysisHelper.scala:264)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.plans.logical.LogicalPlan.transformDownWithPruning(LogicalPlan.scala:31)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:495)
	at org.apache.spark.sql.execution.QueryExecution.$anonfun$eagerlyExecuteCommands$1(QueryExecution.scala:238)
	at org.apache.spark.sql.catalyst.plans.logical.AnalysisHelper$.allowInvokingTransformsInAnalyzer(AnalysisHelper.scala:324)
	at org.apache.spark.sql.execution.QueryExecution.eagerlyExecuteCommands(QueryExecution.scala:238)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted$lzycompute(QueryExecution.scala:192)
	at org.apache.spark.sql.execution.QueryExecution.commandExecuted(QueryExecution.scala:183)
	at org.apache.spark.sql.execution.QueryExecution.assertCommandExecuted(QueryExecution.scala:295)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:964)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:429)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:396)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:250)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-47492:5)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-47492:77)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-47492:79)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-47492:81)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-47492:83)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-47492:85)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-47492:87)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-47492:89)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-47492:91)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-47492:93)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-47492:95)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-47492:97)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-47492:99)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-47492:101)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw$$iw.<init>(command-47492:103)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw$$iw.<init>(command-47492:105)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw$$iw.<init>(command-47492:107)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$$iw.<init>(command-47492:109)
	at $line63811d5bb667486dbff0a25476ac733d123.$read.<init>(command-47492:111)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$.<init>(command-47492:115)
	at $line63811d5bb667486dbff0a25476ac733d123.$read$.<clinit>(command-47492)
	at $line63811d5bb667486dbff0a25476ac733d123.$eval$.$print$lzycompute(<notebook>:7)
	at $line63811d5bb667486dbff0a25476ac733d123.$eval$.$print(<notebook>:6)
	at $line63811d5bb667486dbff0a25476ac733d123.$eval.$print(<notebook>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:747)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1020)
	at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:568)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:36)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:116)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:41)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:567)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:594)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:564)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:223)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.$anonfun$repl$1(ScalaDriverLocal.scala:227)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:1258)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:1211)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:227)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$execute$23(DriverLocal.scala:867)
	at com.databricks.unity.EmptyHandle$.runWith(UCSHandle.scala:103)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$execute$20(DriverLocal.scala:850)
	at com.databricks.logging.UsageLogging.$anonfun$withAttributionContext$1(UsageLogging.scala:407)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:158)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:405)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:402)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:69)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:450)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:435)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:69)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:827)
	at com.databricks.backend.daemon.driver.DriverWrapper.$anonfun$tryExecutingCommand$1(DriverWrapper.scala:659)
	at scala.util.Try$.apply(Try.scala:213)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:651)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommandAndGetError(DriverWrapper.scala:570)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:605)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:447)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:388)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:246)
	at java.base/java.lang.Thread.run(Thread.java:829)
``` 

### Version Info

OS:         :  
JVM         :  
Hadoop/Spark: 
ES-Hadoop   :  org.elasticsearch:elasticsearch-spark-30_2.12:8.6.0
ES          :  OpenSearch 2.4.1 (hosted by Aiven)

ElasticSearch info:
```
{
	"name": "",
	"cluster_name": "",
	"cluster_uuid": "",
	"version": {
		"distribution": "opensearch",
		"number": "2.4.1",
		"build_type": "unknown",
		"build_hash": "unknown",
		"build_date": "2022-12-24T15:41:30.002083Z",
		"build_snapshot": false,
		"lucene_version": "9.4.2",
		"minimum_wire_compatibility_version": "7.10.0",
		"minimum_index_compatibility_version": "7.0.0"
	},
	"tagline": "The OpenSearch Project: https://opensearch.org/"
}
```

**Comment by masseyke** [comment]
Opensearch is a completely separate product form Elasticsearch at this point. Es-hadoop is not tested or supported on Opensearch. You probably want to reach out to the Opensearch community to see if there is a way to use Spark with Opensearch. It might be available with https://github.com/opensearch-project/opensearch-hadoop.
