### ISSUE TITLE
Nodes without http_address cause exceptions

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch-hadoop#210]
Nodes with http disabled cause a parsing error despite using the "_nodes/http" api.

see #99

**Comment by marcelopaesrech** [comment]
Hi Costin, I'm having this problem in the 2.1.0-BUILD 444 and the 2.1.0 RC1. My cluster has 2 nodes with no data enable but the http enabled and other two with the inverse configuration.
I did a debug here and in the end just the nodes with shards were selected to query ES resulting in a NullPointerException (nodeIp= null, nodePort = 0). The error follows:
java.lang.NullPointerException
        at java.io.DataOutputStream.writeUTF(DataOutputStream.java:347)
        at java.io.DataOutputStream.writeUTF(DataOutputStream.java:323)
        at org.elasticsearch.hadoop.mr.EsInputFormat$ShardInputSplit.write(EsInputFormat.java:108)
        at org.elasticsearch.hadoop.hive.EsHiveInputFormat$EsHiveSplit.write(EsHiveInputFormat.java:77)
        at org.apache.hadoop.hive.ql.io.HiveInputFormat$HiveInputSplit.write(HiveInputFormat.java:177)
        at org.apache.hadoop.mapreduce.split.JobSplitWriter.writeOldSplits(JobSplitWriter.java:164)
        at org.apache.hadoop.mapreduce.split.JobSplitWriter.createSplitFiles(JobSplitWriter.java:92)
        at org.apache.hadoop.mapreduce.JobSubmitter.writeOldSplits(JobSubmitter.java:353)
        at org.apache.hadoop.mapreduce.JobSubmitter.writeSplits(JobSubmitter.java:323)
        at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:199)
        at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1290)
        at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1287)
...
Regards.

**Comment by costin** [comment]
@marcelopaesrech This is a closed issue; please open a new one with more information about your environment and in particular your Hive script/configuration and the connector logs (turn on logging to TRACE level). Thanks!
