### ISSUE TITLE
grant access to original JSON

### ISSUE THREAD

**Issue by joesane** [elastic/elasticsearch-hadoop#251]
Hi,

it would be incredibly useful to have access to the original JSON returned by ElasticSearch. Could you please provide a way to do this?

Thanks!

**Comment by b0c1** [comment]
Hi dude... I try to put a lot of document and get it. result:
```
15/03/02 23:49:41 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
java.lang.IllegalArgumentException: Invalid position given=154612 -1
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:234)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:165)
	at org.elasticsearch.hadoop.rest.RestRepository.scroll(RestRepository.java:403)
	at org.elasticsearch.hadoop.rest.ScrollQuery.hasNext(ScrollQuery.java:76)
	at org.elasticsearch.spark.rdd.AbstractEsRDDIterator.hasNext(AbstractEsRDDIterator.scala:46)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at org.apache.spark.rdd.RDD$$anonfun$foreach$1.apply(RDD.scala:782)
	at org.apache.spark.rdd.RDD$$anonfun$foreach$1.apply(RDD.scala:782)
	at org.apache.spark.SparkContext$$anonfun$runJob$4.apply(SparkContext.scala:1353)
	at org.apache.spark.SparkContext$$anonfun$runJob$4.apply(SparkContext.scala:1353)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:56)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:200)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
15/03/02 23:49:41 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0, localhost): java.lang.IllegalArgumentException: Invalid position given=154612 -1
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:234)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:165)
	at org.elasticsearch.hadoop.rest.RestRepository.scroll(RestRepository.java:403)
	at org.elasticsearch.hadoop.rest.ScrollQuery.hasNext(ScrollQuery.java:76)
	at org.elasticsearch.spark.rdd.AbstractEsRDDIterator.hasNext(AbstractEsRDDIterator.scala:46)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at org.apache.spark.rdd.RDD$$anonfun$foreach$1.apply(RDD.scala:782)
	at org.apache.spark.rdd.RDD$$anonfun$foreach$1.apply(RDD.scala:782)
	at org.apache.spark.SparkContext$$anonfun$runJob$4.apply(SparkContext.scala:1353)
	at org.apache.spark.SparkContext$$anonfun$runJob$4.apply(SparkContext.scala:1353)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:56)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:200)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```
jsonPointers: doc = [154447,159056], fragments = 0, if you want I can send you the input. (ipls send a mail to boci.boci at gmail dot com)

**Comment by costin** [comment]
@b0c1 please create a separate issue since this thread is long enough already. And there's always gist - please use that to post the problematic document and the snippet of code you are using.

Thanks!

**Comment by costin** [comment]
Closing the issue - Beta4 is out.
