### ISSUE TITLE
ArrayIndexOutOfBoundsException on Spark on 'pining' tasks

### ISSUE THREAD

**Issue by bzz** [elastic/elasticsearch-hadoop#272]
Code that used to work and save data to ES from Spark now, on Spark 1.1.0 and  2.1.0.BUILD-SNAPSHOT results in 

```
14/09/18 21:47:22 ERROR Executor: Exception in task 12.2 in stage 2.0 (TID 7007)
java.lang.ArrayIndexOutOfBoundsException: -1
    at java.util.ArrayList.elementData(ArrayList.java:400)
    at java.util.ArrayList.get(ArrayList.java:413)
    at org.elasticsearch.hadoop.rest.RestService.createWriter(RestService.java:351)
    at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.init(EsOutputFormat.java:173)
    at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.write(EsOutputFormat.java:149)
    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$12.apply(PairRDDFunctions.scala:922)
    at org.apache.spark.rdd.PairRDDFunctions$$anonfun$12.apply(PairRDDFunctions.scala:903)
    at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:62)
    at org.apache.spark.scheduler.Task.run(Task.scala:54)
    at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:177)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
```

Might be related to #256 or could it be a ES cluster mis-configuration? Looks like  [RestService.java#L349 SettingsUtils.discoveredOrDeclaredNodes()](https://github.com/elasticsearch/elasticsearch-hadoop/blame/master/mr/src/main/java/org/elasticsearch/hadoop/rest/RestService.java#L349) returns empty list.

ES configuration looks like

```
discovery.zen.ping.multicast.enabled = false
discovery.zen.ping.unicast.hosts: ["list", "of", "hosts"]
```

**Comment by dan-blanchard** [comment]
I'm experiencing this problem with 2.0.2, because b17ebb95e96cff35a4fd6b0 adds [this line](https://github.com/elastic/elasticsearch-hadoop/blob/v2.0.2/mr/src/main/java/org/elasticsearch/hadoop/mr/EsOutputFormat.java#L185), which includes the portion `nodes.get(currentInstance % nodes.size())`, which will lead to the above error when currentInstance is set to `NO_TASK_ID` (-1).

For reasons that aren't clear to me, this commit is not present in the 2.1.x beta versions, so this problem doesn't manifest there.
