### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: org/elasticsearch/spark/package$ 

### ISSUE THREAD

**Issue by lairdnote** [elastic/elasticsearch-hadoop#295]
Exception in thread "main" java.lang.NoClassDefFoundError: org/elasticsearch/spark/package$
    at spark.c4hcdn.KafkaNetWork$.main(KafkaNetWork.scala:52)
    at spark.c4hcdn.KafkaNetWork.main(KafkaNetWork.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.apache.spark.deploy.SparkSubmit$.launch(SparkSubmit.scala:303)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:55)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.spark.package$
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 9 more

```
val esRDD = lines.flatMap(_.split("\\n"))
              .map(x => p.parseRecord(x))
              .map(x => Map("clientIpAddress" -> Utils.clientIpAddress(x), "dateTime" -> Utils.dateTime(x), "request" -> Utils.request(x), "httpStatusCode" -> Utils.httpStatusCode(x), "bytesSent"-> Utils.bytesSent(x), "referer"-> Utils.referer(x), "userAgent" -> Utils.userAgent(x), "hit"-> Utils.hit(x), "origintime"-> Utils.origintime(x)))

 sc.makeRDD(Seq(esRDD)).saveToEs("spark/docs")
```

```
import org.elasticsearch.spark._ 
```

where are error?

**Comment by dweinheimer** [comment]
Costin,
Can you please instruct me as to how to correctly make the es-hadoop 2.1.Beta3 jar available in the classpath?

Here is what I have:
HADOOP_CLASSPATH = /location/of/elasticsearch-hadoop-2.1.0.Beta3.jar
HADOOP_PREFIX= /location/of/hadoop/installation

Thanks!

**Comment by liusztc09** [comment]
Hi Costin,

I got the same problem using elasticsearch.spark. It seems that the jar elasticsearch-spark_2.10_Beta4 includes both es hadoop and es spark. Also, the cause of my problem is due to the call of rdd.saveToEs()

Exception in thread "main" java.lang.NoClassDefFoundError: org/elasticsearch/spark/package$
        at com.hearst.sample.LoadJsonToEs$.main(LoadJsonToEs.scala:28)
        at com.hearst.sample.LoadJsonToEs.main(LoadJsonToEs.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:569)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:166)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:189)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:110)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.spark.package$
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 11 more

Could you please have look at the problem?

Thanks,

**Comment by costin** [comment]
@liusztc09 es-hadoop is not part of the classpath. This is not a bug but a configuration issue on your side. This has been explained in the bug above as well as the fact that this is an issue tracker and for questions and such you should try the <s>mailing list</s>  the forum.

**Comment by liusztc09** [comment]
@costin Thanks a lot for the explanation.
