### ISSUE TITLE
EsSpark.esJsonRDD error

### ISSUE THREAD

**Issue by b0c1** [elastic/elasticsearch-hadoop#385]
Hi dude... I try to put a lot of document and get it. result:
```
15/03/02 23:49:41 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
java.lang.IllegalArgumentException: Invalid position given=154612 -1
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:234)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:165)
	at org.elasticsearch.hadoop.rest.RestRepository.scroll(RestRepository.java:403)
	at org.elasticsearch.hadoop.rest.ScrollQuery.hasNext(ScrollQuery.java:76)
	at org.elasticsearch.spark.rdd.AbstractEsRDDIterator.hasNext(AbstractEsRDDIterator.scala:46)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at org.apache.spark.rdd.RDD$$anonfun$foreach$1.apply(RDD.scala:782)
	at org.apache.spark.rdd.RDD$$anonfun$foreach$1.apply(RDD.scala:782)
	at org.apache.spark.SparkContext$$anonfun$runJob$4.apply(SparkContext.scala:1353)
	at org.apache.spark.SparkContext$$anonfun$runJob$4.apply(SparkContext.scala:1353)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:56)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:200)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
15/03/02 23:49:41 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0, localhost): java.lang.IllegalArgumentException: Invalid position given=154612 -1
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:234)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:165)
	at org.elasticsearch.hadoop.rest.RestRepository.scroll(RestRepository.java:403)
	at org.elasticsearch.hadoop.rest.ScrollQuery.hasNext(ScrollQuery.java:76)
	at org.elasticsearch.spark.rdd.AbstractEsRDDIterator.hasNext(AbstractEsRDDIterator.scala:46)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at org.apache.spark.rdd.RDD$$anonfun$foreach$1.apply(RDD.scala:782)
	at org.apache.spark.rdd.RDD$$anonfun$foreach$1.apply(RDD.scala:782)
	at org.apache.spark.SparkContext$$anonfun$runJob$4.apply(SparkContext.scala:1353)
	at org.apache.spark.SparkContext$$anonfun$runJob$4.apply(SparkContext.scala:1353)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:56)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:200)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```
jsonPointers: doc = [154447,159056], fragments = 0, if you want I can send you the input. 
the input contain the following data:
https://gist.githubusercontent.com/b0c1/486a7bea069e26d54b43/raw/a9a23bdbbbaf1a9b86918d302c3a838839b3a566/gistfile1.txt

**Comment by costin** [comment]
I need the input - your gist contains the scroll results which is not really useful in narrowing down the data. Also what are you trying to do - what does your code look like?

**Comment by b0c1** [comment]
Here is my code. I using a lot of data (6257 row in the database)

```scala
    //Load demo data to local ES
    loadAsString("test", "enriched", "data.json")

    //Spark test
    val sparkConfig = new SparkConf().setAppName("Trendensity aggregator").setMaster("local[2]")
    sparkConfig.set("spark.serializer", "org.apache.spark.serializer.KryoSerializer")
    val sc = new SparkContext(sparkConfig)

    val params = Map(
      ConfigurationOptions.ES_NODES -> "localhost",
      ConfigurationOptions.ES_PORT -> httpPort.toString,
      ConfigurationOptions.ES_MAPPING_ID -> "id",
      ConfigurationOptions.ES_BATCH_SIZE_BYTES -> "10mb",
      ConfigurationOptions.ES_QUERY -> "",
      ConfigurationOptions.ES_INPUT_JSON -> "true",
      ConfigurationOptions.ES_RESOURCE_READ -> s"*/enriched"
    )
    val result=client.execute( count from "*/enriched").await.getCount
    println(result)

    val rdd = EsSpark.esJsonRDD(sc, params)
    rdd.map(item => {
      println(item._1)
      println(item._2)
      item._2
    }).foreach(result => {
      println(result)
    })
```

Now I want to simply test the raw json reading capability

**Comment by b0c1** [comment]
Can I help to inspect/solve this problem?

**Comment by costin** [comment]
Yes, as I mentioned above:
>I need the input - your gist contains the scroll results which is not really useful in narrowing down the data. Also what are you trying to do - what does your code look like?

**Comment by b0c1** [comment]
Here is the sample data file https://gist.github.com/b0c1/8005c7933aad557ffef8

**Comment by costin** [comment]
Dropbox/box/s3?

**Comment by b0c1** [comment]
https://www.dropbox.com/s/b4x0k76yzcmkt8q/data.7z?dl=0

**Comment by b0c1** [comment]
in the ```loadAsString``` I load the data into elasticsearch. in the data.json each line is es document.

**Comment by costin** [comment]
great - thanks! I'll look into it shortly.

**Comment by b0c1** [comment]
thanks a lot

**Comment by b0c1** [comment]
Hi dude, can you reproduce the error? Can I help you to solve this?

**Comment by costin** [comment]
@b0c1 Not to worry, I haven't forgotten about this. However with Elasticon and Spark Summit I've been mainly on the road and didn't have enough time to look at it just yet.

Cheers,

**Comment by b0c1** [comment]
@costin Thanks dude, If you need my help just write.

**Comment by mjrvandorth** [comment]
I have found the exact same problem, but have been able to narrow it down a bit. Using the following code snippet I get the same exception (the second argument for position being -1):

	val query =
	  """
	    |{
	    |   "query": {
	    |      "match_all": {}
	    |   },
	    |   "partial_fields": {
	    |      "partial": {
	    |         "include": [
	    |            "location"
	    |         ]
	    |      }
	    |   }
	    |}
	  """.stripMargin

	val rdd = sc.esJsonRDD("eventlog/event", query)
	rdd.foreach(f => println(f))

A part of the result I get is:

	(AUwvH25CcZYE9kzNldAM,{"partial":[{"location":"Darmstadt"}]})
	(AUwvH25xcZYE9kzNldA5,{"partial":[{"location":"Würzburg"}]}})
	(AUwvHoP9cZYE9kzNlc5u,{partial":[{"location":"Hamburg"}]}})
	(AUwvIUMrcZYE9kzNldLa,{partial":[{"location":"München"}]}}})
	(AUwvIUO4cZYE9kzNldNc,{artial":[{"location":"Bremen"}]}}})
	(AUwvIxhEcZYE9kzNldap,{artial":[{"location":"Würzburg"}]}},})
	(AUwvIi1icZYE9kzNldRS,{rtial":[{"location":"Siegen"}]}},})

As you can see, as soon as a special character (such as "ü") is encountered, the whole printed string shifts to the right one character. Using different fields in the partial_fields that don't contain these special characters in their value results in working EsJsonRDD just fine.

@b0c1 Can you check if this is the case with your data as well?

**Comment by b0c1** [comment]
@mjrvandorth possible, my text (as you see) it's multilingual so it's contain text like this: ```"Dogecoin (/ËdoĘĘkÉÉŞn/ dohjkoyn, code: DOGE, symbol: Ă and D), is a Litecoin-derived cryptocurrency featuring a Shiba Inu from the Doge Internet meme."``` and other special characters.

**Comment by b0c1** [comment]
@costin You need any other information?

**Comment by b0c1** [comment]
I think this code process raw text result, and read each block. Just an idea but Jackson have Streaming API...

**Comment by b0c1** [comment]
@costin Can we help to solve this issue?

**Comment by b0c1** [comment]
any progress with these issue?

**Comment by costin** [comment]
Hi folks,

I haven't forgotten about this issue; I spent some time trying to debug it but couldn't find anything useful.
@mjrvandorth that's very useful information - it might very well be that the 'special' chars are not properly counted resulting in invalid JSON.
I'll try it and see whether I'm able to reproduce it.

Cheers!

**Comment by b0c1** [comment]
@costin thanks your work. I think my data package (which I shared with you) contain a lot of special char.. I want to help, because I think it's will be a great feature (ex. I can use json4s to convert the item to JValue and extract objects from it)..

**Comment by b0c1** [comment]
Ok I got a string to reproduce the error:
```لَيسَ كُل مَ آكتُبه حِكَآيةة عَنْ وَٱقِعِي إنَمَآ هِيآ كَلِمآت رَاقَت لِي .. ❤```

**Comment by b0c1** [comment]
@costin ok I think I found the problem core... maybe...
You split the json to block in the ```ScrollReader.readHitAsJson``` method. 
When you get the charStop position from the parser and the internal data contain chars like ```لَيسَ كُل مَ آكتُبه حِكَآيةة عَنْ وَٱقِعِي إنَمَآ هِيآ كَلِمآت رَاقَت لِي .. ❤``` the Jackson parser come back with wrong position sample internal source position start (charStart): 295
```
{"source":"لَيسَ كُل مَ آكتُبه حِكَآيةة عَنْ وَٱقِعِي إنَمَآ هِيآ كَلِمآت رَاقَت لِي .. ❤"}
```
position end (charStop): 448, expected 386

Can you check this?

**Comment by costin** [comment]
@b0c1 @mjrvandorth Guys, I've pushed a fix - I've uploaded the artifacts; can you please report back?
Thanks,

**Comment by b0c1** [comment]
Thanks dude... this is work perferctly... @mjrvandorth can you confirm?

**Comment by mjrvandorth** [comment]
I just ran some test and can indeed confirm that this now works. @costin Thanks a lot!

**Comment by b0c1** [comment]
ok in this case I close the issue, thnx a lot
