### ISSUE TITLE
Which column causes issue in MapperParsingException

### ISSUE THREAD

**Issue by ruvikal** [elastic/elasticsearch-hadoop#395]
I came across this error 

Caused by: org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: Found unrecoverable error [Bad Request(400) - [MapperParsingException[failed to parse]; nested: NumberFormatException[For input string: "NULL"]; ]]; Bailing out..
        at org.elasticsearch.hadoop.rest.RestClient.retryFailedEntries(RestClient.java:199)
        at org.elasticsearch.hadoop.rest.RestClient.bulk(RestClient.java:165)
        at org.elasticsearch.hadoop.rest.RestRepository.sendBatch(RestRepository.java:170)
        at org.elasticsearch.hadoop.rest.RestRepository.doWriteToIndex(RestRepository.java:152)
        at org.elasticsearch.hadoop.rest.RestRepository.writeProcessedToIndex(RestRepository.java:146)
        at org.elasticsearch.hadoop.hive.EsHiveOutputFormat$EsHiveRecordWriter.write(EsHiveOutputFormat.java:63)
        at org.apache.hadoop.hive.ql.exec.FileSinkOperator.processOp(FileSinkOperator.java:621)
        at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:793)
        at org.apache.hadoop.hive.ql.exec.LimitOperator.processOp(LimitOperator.java:51)
        at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:793)
        at org.apache.hadoop.hive.ql.exec.ExtractOperator.processOp(ExtractOperator.java:45)
        at org.apache.hadoop.hive.ql.exec.mr.ExecReducer.reduce(ExecReducer.java:262)

when loading data into elasticsearch from hive using the elasticsearch-hadoop-2.0.2.jar.
The error doesn't reveal which column is causing the issue. It would be nice to have such information in the error.

**Comment by costin** [comment]
I'm closing this issue as there's not much a client (such as ES-Hadoop) can do. The error above is thrown by Elasticsearch about a mapping error between the data sent and the mapping inside ES. The error is returned as is to the user for full diagnostic; the client can't do much about it.
