### ISSUE TITLE
SparkSQL fails inserting data into Elasticsearch index

### ISSUE THREAD

**Issue by fdmitriy** [elastic/elasticsearch-hadoop#406]
Hi,

I am trying to insert into Elasticsearch and getting an Exception below.

Environment:
elasticsearch-hadoop 2.1.0.BUILD_SNAPSHOT
spark 1.2.0

Exception in thread "main" java.lang.AssertionError: assertion failed: No plan for InsertIntoTable (Relation[ColumnName#0,DataStore#1,Day#2,DbName#3,Hour#4,Interval#5,Month#6,ResponseCount#7,SchemaName#8,TableName#9,User#10,Year#11] ElasticsearchRelation(Map(es.resource -> s@s/intervals))), Map(), false
 Project [1 AS c0#18,2 AS c1#19,3 AS c2#20,4 AS c3#21,5 AS c4#22,6 AS c5#23,7 AS c6#24,8 AS c7#25,9 AS c8#26,10 AS c9#27,11 AS c10#28,12 AS c11#29]
  NoRelation$ 

	at scala.Predef$.assert(Predef.scala:179)
	at org.apache.spark.sql.catalyst.planning.QueryPlanner.apply(QueryPlanner.scala:59)
	at org.apache.spark.sql.SQLContext$QueryExecution.sparkPlan$lzycompute(SQLContext.scala:418)
	at org.apache.spark.sql.SQLContext$QueryExecution.sparkPlan(SQLContext.scala:416)
	at org.apache.spark.sql.SQLContext$QueryExecution.executedPlan$lzycompute(SQLContext.scala:422)
	at org.apache.spark.sql.SQLContext$QueryExecution.executedPlan(SQLContext.scala:422)
	at org.apache.spark.sql.SQLContext$QueryExecution.toRdd$lzycompute(SQLContext.scala:425)
	at org.apache.spark.sql.SQLContext$QueryExecution.toRdd(SQLContext.scala:425)
	at org.apache.spark.sql.SchemaRDDLike$class.$init$(SchemaRDDLike.scala:58)
	at org.apache.spark.sql.SchemaRDD.<init>(SchemaRDD.scala:108)
	at org.apache.spark.sql.SQLContext.sql(SQLContext.scala:303)

Code:

    ...
    val sparkConf = new SparkConf().setAppName("Percolator")
    val sc =  new SparkContext(sparkConf)
    val sqlContext = new SQLContext(sc)
    ...    
    sqlContext.sql("CREATE TEMPORARY TABLE INTERVALS    " +
                   "USING org.elasticsearch.spark.sql " +
                   "OPTIONS (resource 'events/intervals') " )

    val insertRDD = sqlContext.sql("INSERT INTO INTERVALS SELECT '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'");

Can you please advise if INSERT INTO feature is supported with elasticsearch-hadoop 2.1.0.BUILD_SNAPSHOT and Spark 1.2?

Thanks,
Dmitriy Fingerman

**Comment by costin** [comment]
Which is expected; data sources in Spark 1.2 do not support data insertion. This has been introduced in 1.3 which is currently wip (since it breaks backwards compatibility it's a big step to introduce it in master which I somehow hope to avoid).

**Comment by costin** [comment]
Closing the issue. As I've mentioned we might support this feature with the Spark 1.3 support.
