### ISSUE TITLE
unable to write to a resource using a dynamic index name and type

### ISSUE THREAD

**Issue by shaunsenecal** [elastic/elasticsearch-hadoop#410]
I'm using version 2.0.2, and implemented a simple Mapper to feed data to my ES cluster using a dynamic index name and type using the {} notation in es.resource.write

```
conf.set("es.resource.write","{index-name}/{type}");
```

The problem I'm having is that the EsOutputFormat attempts to verify the index exists before the job starts, but there is no way for it to know what the index name is.  Here is the call stack I'm seeing:

```
15/03/31 11:06:55 ERROR rest.NetworkClient: Node [Invalid target URI HEAD@null/{index-name}/{type}] failed (server.example.com:9200); no other nodes left - aborting...
Exception in thread "main" org.elasticsearch.hadoop.rest.EsHadoopNoNodesLeftException: Connection error (check network and/or proxy settings)- all nodes failed; tried [[server.example.com:9200]] 
        at org.elasticsearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:123)
        at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:300)
        at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:292)
        at org.elasticsearch.hadoop.rest.RestClient.exists(RestClient.java:349)
        at org.elasticsearch.hadoop.rest.RestRepository.indexExists(RestRepository.java:279)
        at org.elasticsearch.hadoop.rest.InitializationUtils.checkIndexExistence(InitializationUtils.java:108)
        at org.elasticsearch.hadoop.mr.EsOutputFormat.init(EsOutputFormat.java:342)
        at org.elasticsearch.hadoop.mr.EsOutputFormat.checkOutputSpecs(EsOutputFormat.java:312)
        at org.apache.hadoop.mapreduce.JobSubmitter.checkSpecs(JobSubmitter.java:456)
        at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:342)
        at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1268)
        at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1265)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1491)
        at org.apache.hadoop.mapreduce.Job.submit(Job.java:1265)
        at org.apache.hadoop.mapreduce.Job.waitForCompletion(Job.java:1286)
        at com.example.feeder.FeederTool.run(FeederTool.java:125)
        at com.example.feeder.FeederTool.main(FeederTool.java:138)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:212)
```

It looks like the issue is that EsOutputFormat.init() calls InitializationUtils.checkIndexExistence() without first verifying if the index name and/or type are dynamic or not.

Is this not supported?  As far as I can tell from the docs, I think its supported.

I have verified that changing es.resource.write to a valid index name and valid type allows the job to start executing.

**Comment by costin** [comment]
Try disabling the index existence through `es.index.auto.create` setting (see the configuration chapter).

**Comment by shaunsenecal** [comment]
Sorry, I should have included more of my job config.  I am already disabling auto create:

```
        conf.set("es.nodes", this.args.host);
        conf.set("es.port", Integer.toString(this.args.port));
        conf.set("es.resource.write","{index-name}/{type}");
        conf.set("es.input.json", "yes");
        conf.set("es.write.operation", "index");
        conf.set("es.index.auto.create", "no");
        conf.set("es.nodes.discovery", "true");
        conf.set("es.batch.write.refresh", "true");
```

**Comment by shaunsenecal** [comment]
I think I may have misunderstood you.  I think you were suggesting that I -enable- auto create to avoid the index existence check.  In this case, yes, I am able to run the job.  However, shouldn't it be possible to run the job with auto creation disabled?

**Comment by costin** [comment]
Right, currently we need the index in order to determine the partitions needed. In case of a dynamic index, we can't figure this out before hand which leads to various things being tripped off. You might be able to get around this by enabling index creation though I doubt it (the current exception seems to be triggered due to the various checks applied to the non existing index).

So in short, currently this scenario is not supported through we could look again at it.

**Comment by costin** [comment]
It should work. In the end this is a configuration switch that should in the worst case scenario give you a message not lead to an unexpected exception. 
Looking briefly at the code path, it seems the fix should be fairly straight-forward.

**Comment by shaunsenecal** [comment]
It looks like I need to enable index auto creation -and- ensure the indices exist before running the job in order to make it work.  If the indices dont exist, exceptions are thrown even though auto create is enabled.  I didnt look into the thrown exceptions though, so its possible that I simply have something misconfigured.

I have yet to verify the content of the indices, but I can see the document count is increasing, so it does appear that something is being written to the cluster.

**Comment by shaunsenecal** [comment]
see issue #412.  In the end, there were problems I couldn't work around, so a custom OutputFormat was required.
