### ISSUE TITLE
internal.es.yarn.file default configuration not present in YARN/cfg.properties

### ISSUE THREAD

**Issue by ArafathC** [elastic/elasticsearch-hadoop#411]
Abnormal execution:Es-YARN.jar is not set and could not be detected...
java.lang.IllegalArgumentException: Es-YARN.jar is not set and could not be detected...
	at org.elasticsearch.hadoop.yarn.util.Assert.hasText(Assert.java:29)
	at org.elasticsearch.hadoop.yarn.cfg.Config.downloadedEsYarn(Config.java:168)
	at org.elasticsearch.hadoop.yarn.cli.YarnBootstrap.installEsYarn(YarnBootstrap.java:126)
	at org.elasticsearch.hadoop.yarn.cli.YarnBootstrap.run(YarnBootstrap.java:91)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:70)
	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:84)
	at org.elasticsearch.hadoop.yarn.cli.YarnBootstrap.main(YarnBootstrap.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:208)

**Comment by costin** [comment]
Could you be a bit more specific?
The exception above occurs due to a misconfiguration on your part. See the [usage](http://www.elastic.co/guide/en/elasticsearch/hadoop/master/ey-usage.html) chapter.

If you think that is not the case, then please provide some background, what are you trying to achieve, what are your expectations, what fails, etc... as described [here](http://www.elastic.co/guide/en/elasticsearch/hadoop/master/troubleshooting.html).
My guessing capability only goes so far...

**Comment by ArafathC** [comment]
I had to solve this by manually specifying the property like below 
sudo -u hdfs hadoop jar elasticsearch-yarn-2.1.0.Beta3.jar -install internal.es.yarn.file=elasticsearch-yarn-2.1.0.Beta3.jar

it worked when i executed the above command .
when i checked for internal.es.yarn.file configuration in cfg/cfg.properties , i couldnt find it.

**Comment by costin** [comment]
I think your usage of sudo might be interfering with the execution. Just tried Beta3 and SNAPSHOT on two new hadoop VMs and they work fine.
```
[cloudera@quickstart yarn-test]$ sudo hadoop jar elasticsearch-yarn-2.1.0.BUILD-SNAPSHOT.jar -install
Uploaded /tmp/yarn-test/elasticsearch-yarn-2.1.0.BUILD-SNAPSHOT.jar to HDFS at hdfs://quickstart.cloudera:8020/apps/elasticsearch/elasticsearch-yarn-2.1.0.BUILD-SNAPSHOT.jar
```
```
[cloudera@quickstart yarn-test]$ sudo hadoop jar elasticsearch-yarn-2.1.0.BUILD-SNAPSHOT.jar -install-es es.version=1.5.0
Uploaded /tmp/yarn-test/./downloads/elasticsearch-1.5.0.zip to HDFS at hdfs://quickstart.cloudera:8020/apps/elasticsearch/elasticsearch-1.5.0.zip
```
The full log is available as a Gist [here](https://gist.github.com/costin/a4bc76de422b5538a804)
