### ISSUE TITLE
using EsOutputFormat with dynamic resources and a strict mapping

### ISSUE THREAD

**Issue by shaunsenecal** [elastic/elasticsearch-hadoop#412]
I am trying to use the EsOutputFormat to write to a dynamic index and type by setting

```
conf.set("es.resource.write","{index_name}/{type}");
```

It seems that the bulk updates are formed correctly (targeting the correct index and type), but when the update is fired to the index I end up getting exceptions

```
org.elasticsearch.index.mapper.StrictDynamicMappingException: mapping set to strict, dynamic introduction of [index_name] within [action] is not allowed
        at org.elasticsearch.index.mapper.object.ObjectMapper.parseDynamicValue(ObjectMapper.java:721)
        at org.elasticsearch.index.mapper.object.ObjectMapper.serializeValue(ObjectMapper.java:711)
        at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:500)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:542)
        at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:491)
        at org.elasticsearch.index.shard.service.InternalIndexShard.prepareIndex(InternalIndexShard.java:413)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:435)
        at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:150)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:512)
        at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:419)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

It looks like what is happening is that the values I have injected into the JSON (ie: index_name and type) are not being removed from the JSON before being shipped to ES, so the strict mapping chokes on the unexpected values.

I took a look at the JsonFieldExtractors, but it doesn't look like I can extend it in any way myself, plus the AbstractBulkFactory only supports using JsonFieldExtractors so I suspect there is no way to write my own extractor which removes the value from the JSON.  Is there another way around this?

**Comment by shaunsenecal** [comment]
After looking into this more, I convinced myself there would be no easy way to accomplish this using EsOutputFormat.  Instead, I wrote a custom OutputFormat which uses a custom Writable that contains the dynamic field values as well as the document data and then wrote the bulk inserts to ES using the RestClient.  The end result was that I didnt need to inject values into the JSON to support dynamic index names, types, and ids
