### ISSUE TITLE
Hive Runtime Error while Writting into ES table

### ISSUE THREAD

**Issue by maha543** [elastic/elasticsearch-hadoop#432]
Hi all,
I am new to ES, I am using the ES1.5.1 with elasticsearch-hadoop-2.1.0.Beta3.jar. and hive-0.12.0-cdh5.1.3 version for Hive integration.

I have an external table with twitter data and is fromatted as ROW FORMAT SERDE 'com.cloudera.hive.serde.JSONSerDe'. I want to use the ES over that table.

I have created an index as
 curl -XPUT "http://localhost:9200/twitter/" -d '{"settings" : {"number_of_shards" : 2, "number_of_replicas" : 1}}'

and my ES table is of :
CREATE EXTERNAL TABLE twitter (id BIGINT, text STRING) 
STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler' TBLPROPERTIES('es.resource' = 'twitter/tweet');

and when i run
 INSERT OVERWRITE TABLE twitter 
SELECT s.date,s.location FROM summary_location s ;

I get the following error as : 

----
Diagnostic Messages for this Task:
Error: java.lang.RuntimeException: org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while processing row (tag=0) {"key":{},"value":{"_col0":"10-04-2015 15:00:00","_col1":"Beijing"}}
        at org.apache.hadoop.hive.ql.exec.mr.ExecReducer.reduce(ExecReducer.java:270)
        at org.apache.hadoop.mapred.ReduceTask.runOldReducer(ReduceTask.java:444)
        at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:392)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:167)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:422)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1554)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:162)
Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: Hive Runtime Error while processing row (tag=0) {"key":{},"value":{"_col0":"10-04-2015 15:00:00","_col1":"Beijing"}}
        at org.apache.hadoop.hive.ql.exec.mr.ExecReducer.reduce(ExecReducer.java:258)
        ... 7 more

FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask
MapReduce Jobs Launched: 
Job 0: Map: 1  Reduce: 1   Cumulative CPU: 0.85 sec   HDFS Read: 4874 HDFS Write: 0 FAIL
Total MapReduce CPU Time Spent: 850 msec

I followed the DOC from ES and placed the JARs too. But still the error persists after the REDUCE phase.

**Comment by costin** [comment]
In general table definitions are not swappable since their data format is tied to the `SerDe`. What you typically want to do is move the data from one table, with a certain data format, to another.
In this case from your custom `SerDe` to the one backed by the elasticsearch connector one and vice-versa.
If the table data is in JSON format already, you could potentially just point the connector to it and indicate that the data is in JSON - as explained in the documentation [here](http://www.elastic.co/guide/en/elasticsearch/hadoop/master/hive.html#writing-json-hive) - I highly recommend you read the entire chapter.

Last but not least, this is an issue tracker - for questions and discussions, please use the mailing list.
http://www.elastic.co/guide/en/elasticsearch/hadoop/master/troubleshooting.html#help
