### ISSUE TITLE
Saving filed with list of values triggers exception

### ISSUE THREAD

**Issue by bobrik** [elastic/elasticsearch-hadoop#464]
I have field `tag` where arbitrary list of strings could live. Saving it to parquet triggers an error:

```
java.lang.ClassCastException: scala.collection.convert.Wrappers$JListWrapper cannot be cast to java.lang.String
	at org.apache.spark.sql.parquet.MutableRowWriteSupport.consumeType(ParquetTableSupport.scala:352)
	at org.apache.spark.sql.parquet.MutableRowWriteSupport.write(ParquetTableSupport.scala:338)
	at org.apache.spark.sql.parquet.MutableRowWriteSupport.write(ParquetTableSupport.scala:324)
	at parquet.hadoop.InternalParquetRecordWriter.write(InternalParquetRecordWriter.java:120)
	at parquet.hadoop.ParquetRecordWriter.write(ParquetRecordWriter.java:81)
	at parquet.hadoop.ParquetRecordWriter.write(ParquetRecordWriter.java:37)
	at org.apache.spark.sql.parquet.ParquetRelation2.org$apache$spark$sql$parquet$ParquetRelation2$$writeShard$1(newParquet.scala:671)
	at org.apache.spark.sql.parquet.ParquetRelation2$$anonfun$insert$2.apply(newParquet.scala:689)
	at org.apache.spark.sql.parquet.ParquetRelation2$$anonfun$insert$2.apply(newParquet.scala:689)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:64)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Schema:
```
root
 |-- tag: string (nullable = true)
```

Spark 1.3.1, elasticsearch-spark SNAPSHOT.

**Comment by costin** [comment]
The issue here is that in Elastic a field can contain one or multiple values and yet it is represented in the mapping in the same way. As such, the connector doesn't really know until it actually processes the data, whether there's only one or multiple values. We could treat every field as a list but then that would be not just ineffective but also annoying - a list/array with only one value.

A quick _hack_ would be to change the schema manually. A proper solution long term would be to have a configuration option to tell the connector a field is an array not just a single value. This would also reflect in the schema sent to Spark SQL.

I'd like to get this in for 2.1 but first, I'd like to wrap up the current issues (as in bugs) before adding a new feature. In other words, it might take a couple of days until I can get to it...

**Comment by bobrik** [comment]
No rush, I'm waiting for Spark 1.4 to try out ORC anyways.

Since elasticsearch now has min and max values for terms, maybe we can also have min and max cardinality for fields? @martijnvg what do you think?

**Comment by costin** [comment]
@bobrik I'm finally closing the issue since the array support is now in (through #484). Cheers,

**Comment by bobrik** [comment]
:+1:
