### ISSUE TITLE
Load error from elasticsearch using Pig and the elasticsearch connector

### ISSUE THREAD

**Issue by YonoloX** [elastic/elasticsearch-hadoop#499]
Hello,

I'm trying to use the new version (2.1) of the Elasticsearch For Hadoop (elasticsearch-hadoop-2.1.0.jar, elasticsearch-hadoop-pig-2.1.0.jar) to get data from Elasticsearch using Pig, while loadind data I get the error : 
```
java.lang.Exception: java.lang.IncompatibleClassChangeError: Found interface org.apache.hadoop.mapreduce.TaskAttemptContext, but class was expected
        at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:462)
        at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:522)
Caused by: java.lang.IncompatibleClassChangeError: Found interface org.apache.hadoop.mapreduce.TaskAttemptContext, but class was expected
        at org.elasticsearch.hadoop.pig.EsPigInputFormat.createRecordReader(EsPigInputFormat.java:110)
        at org.elasticsearch.hadoop.pig.EsPigInputFormat.createRecordReader(EsPigInputFormat.java:33)
        at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigRecordReader.initNextRecordReader(PigRecordReader.java:250)
        at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigRecordReader.<init>(PigRecordReader.java:121)
        at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigInputFormat.createRecordReader(PigInputFormat.java:114)
        at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.<init>(MapTask.java:512)
        at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:755)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
        at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:243)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```
To know that I do a simple script : 
```sql
REGISTER ./libs/elasticsearch-hadoop-pig-2.1.0.jar; 
DEFINE EsStorage org.elasticsearch.hadoop.pig.EsStorage('es.nodes = localhost', 'es.http.timeout = 1m', 'es.index.auto.create = true');
a = LOAD 'facebook/handle' using EsStorage;
```

The version used are : 
elasticsearch 1.5.0
Pig 0.14

Is there any possible solution ?
Thanks in advance

**Comment by costin** [comment]
_added minimal formatting to your post to make it readable (please do so yourself in the future)_

The exception occurs when the incorrect linking was done using the incorrect Hadoop version. Typically this should not occur - What distro/version of Hadoop are you using?

**Comment by costin** [comment]
@YonoloX Looks like a bug that sneaked in. I've solved this in master (2.2.0.BUILD-SNAPSHOT) and 2.x (2.1.1.BUILD-SNAPSHOT) and published the artifacts. 
Can you please try them out (see the Install section in the docs).

Cheers!

**Comment by YonoloX** [comment]
Hello,

I've tested 2.1.1.BUILD-SNAPSHOT of elasticsearch-hadoop-2.1.1.BUILD-20150713.160034-21 and 2.2.0.BUILD-SNAPSHOT of elasticsearch-hadoop-2.2.0.BUILD-20150713.154541-20 and both work well.

Thanks !

**Comment by costin** [comment]
Cheers. Thanks for confirming. And btw, try to use the latest Elastic for best results/performance.
