### ISSUE TITLE
EsHadoopInvalidRequest: [Bad Request(400) - Invalid JSON fragment received[""]...

### ISSUE THREAD

**Issue by 759803573** [elastic/elasticsearch-hadoop#507]
job:ESTest

```java
    public static void main(String[] args) throws Exception {

        Configuration conf = new Configuration();
        conf.set("es.nodes", "localhost:9200");
        conf.set("es.resource", "test/test");
        conf.set("mapred.reduce.tasks", "0");
        conf.setBoolean("mapred.map.tasks.speculative.execution", false);
        conf.setBoolean("mapred.reduce.tasks.speculative.execution", false);

        Job job= new Job(conf);
        job.setMapperClass(ESTestMapper.class);
        job.setOutputFormatClass(EsOutputFormat.class);
        job.setMapOutputValueClass(MapWritable.class);

        FileInputFormat.addInputPath(job, new Path(args[0]));
        job.waitForCompletion(true);
    }
```

map:ESTestMapper

```java
    public class ESTestMapper extends Mapper {
    protected void map(LongWritable key, Text value, Context context)
            throws IOException, InterruptedException {
        MapWritable doc = new MapWritable();
        //doc.put(new Text("index"),new Text("test"));
        //doc.put(new Text("type"),new Text("test"));
        doc.put(new Text("message"),new Text("trying out Elasticsearch"));
        context.write(NullWritable.get(), doc);
    }
```

input file: test.txt (it contains some blank lines)

I received this error

    15/07/16 17:21:16 INFO mapred.LocalJobRunner: map task executor complete.
    15/07/16 17:21:16 WARN mapred.LocalJobRunner: job_local48419099_0001
    java.lang.Exception: org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: Found unrecoverable     error [Bad Request(400) - Invalid JSON fragment received[""][MapperParsingException[failed to  parse]; nested: ElasticsearchParseException[Failed to derive xcontent from (offset=13, length=2):   [123, 34, 105, 110, 100, 101, 120, 34, 58, 123, 125, 125, 10, 34, 34, 10, 123, 34, 105, 110, 100, 101,  120, 34, 58, 123, 125, 125, 10, 34, 34, 10, 123, 34, 105, 110, 100, 101, 120, 34, 58, 123, 125, 125, 10,  34, 34, 10]]; ]]; Bailing out..
    at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:462)
    at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:522)
    Caused by: org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: Found unrecoverable error [Bad Request(400) - Invalid JSON fragment received[""][MapperParsingException[failed to parse]; nested: ElasticsearchParseException[Failed to derive xcontent from (offset=13, length=2): [123, 34, 105, 110, 100, 101, 120, 34, 58, 123, 125, 125, 10, 34, 34, 10, 123, 34, 105, 110, 100, 101, 120, 34, 58, 123, 125, 125, 10, 34, 34, 10, 123, 34, 105, 110, 100, 101, 120, 34, 58, 123, 125, 125, 10, 34, 34, 10]]; ]]; Bailing out..
    at org.elasticsearch.hadoop.rest.RestClient.retryFailedEntries(RestClient.java:203)
    at org.elasticsearch.hadoop.rest.RestClient.bulk(RestClient.java:167)
        at org.elasticsearch.hadoop.rest.RestRepository.tryFlush(RestRepository.java:209)
        at org.elasticsearch.hadoop.rest.RestRepository.flush(RestRepository.java:232)
        at org.elasticsearch.hadoop.rest.RestRepository.close(RestRepository.java:245)
        at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.doClose(EsOutputFormat.java:214)
        at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.close(EsOutputFormat.java:196)
        at org.apache.hadoop.mapred.MapTask$NewDirectOutputCollector.close(MapTask.java:667)
        at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:790)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
        at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:243)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
    15/07/16 17:21:16 INFO mapreduce.Job: Job job_local48419099_0001 failed with state FAILED due to: NA

CLI：`hadoop ESTest test.txt `

hadoop version:`2.6.0`
elasticsearch version:`1.6.0` 
es-hadoop version :`2.1.0` 
  
hadoop is Pseudo-Distributed Operation

**Comment by shenzb** [comment]
how could you solve the problem?
