### ISSUE TITLE
Pig-Joda-Date Format Error

### ISSUE THREAD

**Issue by ayanguha** [elastic/elasticsearch-hadoop#519]
Hi

I have following mapping in ES
```
"eta" : {
            "type" : "date",
            "format" : "yyyy/MM/dd HH:mm:ss||yyyy/MM/dd"
```
Data:
```json
{"took":3,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":19,"max_score":1.0,"hits":[{"_index":"dem","_type":"getShipmentById","_id":"4674034279","_score":1.0,"fields":{"eta":["2015/05/07"]}},{"_index":"dem","_type":"getShipmentById","_id":"4674008539","_score":1.0,"fields":{"eta":["2015/05/05"]}},{"_index":"dem","_type":"getShipmentById","_id":"2915573617","_score":1.0,"fields":{"eta":["2015/05/13"]}},{"_index":"dem","_type":"getShipmentById","_id":"813005232690","_score":1.0,"fields":{"eta":["2014/04/1"]}},{"_index":"dem","_type":"getShipmentById","_id":"4080264628","_score":1.0,"fields":{"eta":["2012/12/20"]}},{"_index":"dem","_type":"getShipmentById","_id":"4974603120","_score":1.0,"fields":{"eta":["2015/06/18"]}},{"_index":"dem","_type":"getShipmentById","_id":"2572776826","_score":1.0,"fields":{"eta":["14052015"]}},{"_index":"dem","_type":"getShipmentById","_id":"2940712623","_score":1.0,"fields":{"eta":["2015/05/14"]}},{"_index":"dem","_type":"getShipmentById","_id":"4938753854","_score":1.0,"fields":{"eta":["2015/05/11"]}},{"_index":"dem","_type":"getShipmentById","_id":"4820267599","_score":1.0,"fields":{"eta":["2015/06/06"]}}]}}
```
I am trying to load the data using pig.

```
register /home/hadoop/ayan/elasticsearch-hadoop-2.1.1.BUILD-SNAPSHOT/dist/elasticsearch-hadoop-2.1.1.BUILD-SNAPSHOT.jar;

DEFINE EsStorage org.elasticsearch.hadoop.pig.EsStorage('es.nodes=xxxxxxxx','es.port=xxxx');

a = load '/dem/getShipmentById/' using EsStorage('es.query=?fields=destination,carrier') as
(pickupDate:chararray,shipmentDate:chararray,subStatus:chararray,carrierContact:chararray,clientIndusrty:chararray,senderName:chararray,totalWeights:chararray,
receiverRefNo:chararray,senderRefNo:chararray,receiverName:chararray,lifeCycleDetails:tuple(status:chararray,dateTimeStamp:chararray,noOfItems:chararray,legETA:chararra
y,destination:chararray,sequenceNo:chararray,subStatus:chararray,srcLat:chararray,location:chararray,srcLong:chararray,totalItems:chararray),
carrier:chararray,truckNo:chararray,status:chararray,
serviceType:chararray,deliverydaydetails:tuple(vehicleType:chararray,driverName:chararray,deliverySchedule:chararray),
watchStatus:chararray,deliveryLocation:chararray,pickupLocation:chararray,transitType:chararray,
shipmentItems:chararray,transitId:chararray,modeType:chararray,eta:chararray,shipmentRefNo:chararray,totalVolume:chararray);
b = limit a 3;
dump b;
```
Error: 
ERROR 2999: Unexpected internal error. Invalid format: "2015/05/07" is malformed at "/05/07"

```
java.lang.IllegalArgumentException: Invalid format: "2015/05/07" is malformed at "/05/07"
        at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:873)
        at org.elasticsearch.hadoop.pig.PigUtils$Pig11OrHigherConverter.convertFromES(PigUtils.java:103)
        at org.elasticsearch.hadoop.pig.PigUtils.convertDateFromES(PigUtils.java:66)
        at org.elasticsearch.hadoop.pig.PigValueReader.parseDate(PigValueReader.java:46)
        at org.elasticsearch.hadoop.serialization.builder.JdkValueReader.date(JdkValueReader.java:339)
        at org.elasticsearch.hadoop.serialization.builder.JdkValueReader.readValue(JdkValueReader.java:73)
        at org.elasticsearch.hadoop.serialization.ScrollReader.parseValue(ScrollReader.java:580)
        at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:568)
        at org.elasticsearch.hadoop.serialization.ScrollReader.map(ScrollReader.java:636)
        at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:559)
        at org.elasticsearch.hadoop.serialization.ScrollReader.readHitAsMap(ScrollReader.java:358)
        at org.elasticsearch.hadoop.serialization.ScrollReader.readHit(ScrollReader.java:293)
        at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:188)
        at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:167)
        at org.elasticsearch.hadoop.rest.RestRepository.scroll(RestRepository.java:403)
        at org.elasticsearch.hadoop.rest.ScrollQuery.hasNext(ScrollQuery.java:76)
        at org.elasticsearch.hadoop.mr.EsInputFormat$ShardRecordReader.next(EsInputFormat.java:298)
        at org.elasticsearch.hadoop.mr.EsInputFormat$ShardRecordReader.nextKeyValue(EsInputFormat.java:232)
        at org.elasticsearch.hadoop.pig.EsStorage.getNext(EsStorage.java:267)
        at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigRecordReader.nextKeyValue(PigRecordReader.java:211)
        at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.nextKeyValue(MapTask.java:542)
        at org.apache.hadoop.mapreduce.task.MapContextImpl.nextKeyValue(MapContextImpl.java:80)
        at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.nextKeyValue(WrappedMapper.java:91)
        at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:151)
        at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:773)
        at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:175)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
```

Looks like format is not passed in convertDateFormatter. Please give me a resolution :)  

Using 2.1.1 snapshot build (as shown in register)

**Comment by costin** [comment]
_I have added formatting to your post to make it readable, please do so in the future_

See this section in the docs, [here](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/mapping.html#mapping-date).

**Comment by costin** [comment]
As there hasn't been any update, closing the issue.

**Comment by eprochasson** [comment]
I have a similar problem loading data from ES to Spark. My mapping in ES contains

```json
...
"created_at":{"type":"date","format":"yyyy/MM/dd HH:mm:ss"}
...
```

When I try to load data from this index/mapping I get the following error `java.lang.IllegalArgumentException: Invalid format: "2015/11/09 15:55:58" is malformed at "/11/09 15:55:58"`. In this case, it seems the custom mapping (described in the doc you point) is properly defined on ES, yet it fails when loading the data to Spark. I couldn't find any way of specifying a mapping when loading the data.

Any pointer very welcome.
