### ISSUE TITLE
EsRecordWriter causes Bad Request(400) on geo_point fields in some cases

### ISSUE THREAD

**Issue by aewhite** [elastic/elasticsearch-hadoop#530]
I have a job that is coping documents from one index to another, nothing fancy. 

```
        this.hadoopConfiguration.set("es.resource.read", sourceIndex + "/doc");
        this.hadoopConfiguration.set("es.resource.write", destinationIndex + "/doc");
```

Recently we starting using the array form of the geo_type datapoint. So, documents may have one of the following...

```
            "geo": [ 50.90395,-1.40428]
```

OR 

```
            "geo": ["lat":  50.90395,"lon": -1.40428]
```

The M/R job now fails with...

```
org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: Found unrecoverable error [Bad Request(400) - [MapperParsingException[failed to parse]; nested: ElasticsearchIllegalArgumentException[the character '.' is not a valid geohash character]; ]]; Bailing out..
    at org.elasticsearch.hadoop.rest.RestClient.retryFailedEntries(RestClient.java:199)
    at org.elasticsearch.hadoop.rest.RestClient.bulk(RestClient.java:165)
    at org.elasticsearch.hadoop.rest.RestRepository.sendBatch(RestRepository.java:170)
    at org.elasticsearch.hadoop.rest.RestRepository.close(RestRepository.java:189)
    at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.doClose(EsOutputFormat.java:293)
    at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.close(EsOutputFormat.java:275)
    at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:611)
    at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:444)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:268)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:415)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1408)
    at org.apache.hadoop.mapred.Child.main(Child.java:262)
```

We are using elasticsearch-hadoop-mr:2.0.2 and ES 1.4.3

**Comment by costin** [comment]
Note the error is actually coming from Elasticsearch - the connector simply reports it.

P.S. Considering upgrading to 2.1

**Comment by costin** [comment]
Closing the issue as there hasn't been any update in a while. Please open a new issue if needed. Thanks.
