### ISSUE TITLE
org.elasticsearch.hadoop.rest.EsHadoopNoNodesLeftException

### ISSUE THREAD

**Issue by raghuprodhutoori** [elastic/elasticsearch-hadoop#562]
I am trying to write the map reduce output to the elastic search and i am struck with the below exception. I am just trying to write 10 records to ES,but i am able to see only 7 records in the elasticsearch and the program is throwing this exception. The same thing is working with spark savetoes method. I want to achieve it using map reduce for my application.

Error: org.elasticsearch.hadoop.rest.EsHadoopNoNodesLeftException: Connection error (check network and/or proxy settings)- all nodes failed; tried
        at org.elasticsearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:123)
        at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:316)
        at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:312)
        at org.elasticsearch.hadoop.rest.RestClient.bulk(RestClient.java:149)
        at org.elasticsearch.hadoop.rest.RestRepository.tryFlush(RestRepository.java:209)
        at org.elasticsearch.hadoop.rest.RestRepository.flush(RestRepository.java:232)
        at org.elasticsearch.hadoop.rest.RestRepository.close(RestRepository.java:245)
        at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.doClose(EsOutputFormat.java:214)
        at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.close(EsOutputFormat.java:196)
        at org.apache.hadoop.mapred.ReduceTask$NewTrackingRecordWriter.close(ReduceTask.java:550)
        at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:629)
        at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:389)
        at org.apache.hadoop.mapred.YarnChild$2.run(YarnChild.java:168)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.security.auth.Subject.doAs(Subject.java:415)
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1566)
        at org.apache.hadoop.mapred.YarnChild.main(YarnChild.java:163)

**Comment by costin** [comment]
There are many reasons why you are seeing the exception and unfortunately your post doesn't offer enough information. See [this page](https://www.elastic.co/guide/en/elasticsearch/hadoop/master/troubleshooting.html#help) in the manual for what is needed.

**Comment by raghuprodhutoori** [comment]
There is no problem with cluster resources,version and all other things as it is working with spark. And also i am just writings 10 records which will be very small amount of data.Can you specifically specify what details you need for helping me in sorting out this issue.

**Comment by costin** [comment]
@raghuprodhutoori I've already mentioned that in the link behind "this page" in the post above.

**Comment by costin** [comment]
Since there hasn't been any update closing this as invalid. please open a new issue if this occurs again.
