### ISSUE TITLE
Is it possible to write to Amazon Elasticsearch Service using elasticsearch-hadoop?

### ISSUE THREAD

**Issue by fblundun** [elastic/elasticsearch-hadoop#565]
I have been trying to write to AWS's new Amazon Elasticsearch Service from a Scalding job using elasticsearch-hadoop (via [scalding-taps](https://github.com/scalding-io/scalding-taps)).

This job has previously worked using Elasticsearch manually installed on an EC2 instance, implying that the problem is specific to Amazon Elasticsearch Service.

The first time I tried I got this error:

```
Caused by: org.elasticsearch.hadoop.EsHadoopIllegalStateException: Cluster state volatile; cannot find node backing shards - please check whether your cluster is stable
        at org.elasticsearch.hadoop.rest.RestRepository.getWriteTargetPrimaryShards(RestRepository.java:370)
        at org.elasticsearch.hadoop.rest.RestService.initSingleIndex(RestService.java:425)
        at org.elasticsearch.hadoop.rest.RestService.createWriter(RestService.java:393)
        at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.init(EsOutputFormat.java:173)
        at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.write(EsOutputFormat.java:149)
        at org.apache.hadoop.mapred.MapTask$DirectMapOutputCollector.collect(MapTask.java:844)
        at org.apache.hadoop.mapred.MapTask$OldOutputCollector.collect(MapTask.java:596)
        at cascading.tap.hadoop.util.MeasuredOutputCollector.collect(MeasuredOutputCollector.java:69)
        at org.elasticsearch.hadoop.cascading.EsHadoopScheme.sink(EsHadoopScheme.java:212)
        at cascading.tuple.TupleEntrySchemeCollector.collect(TupleEntrySchemeCollector.java:153)
        ... 21 more
```

I then tried setting `es.nodes.client.only` to `true` and instead got this error:

```
Caused by: org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Client-only routing specified but no client nodes with HTTP-enabled were found in the cluster...
        at org.elasticsearch.hadoop.rest.InitializationUtils.filterNonClientNodesIfNeeded(InitializationUtils.java:82)
        at org.elasticsearch.hadoop.rest.RestService.createWriter(RestService.java:373)
        at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.init(EsOutputFormat.java:173)
        at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.write(EsOutputFormat.java:149)
        at org.apache.hadoop.mapred.MapTask$DirectMapOutputCollector.collect(MapTask.java:844)
        at org.apache.hadoop.mapred.MapTask$OldOutputCollector.collect(MapTask.java:596)
        at cascading.tap.hadoop.util.MeasuredOutputCollector.collect(MeasuredOutputCollector.java:69)
        at org.elasticsearch.hadoop.cascading.EsHadoopScheme.sink(EsHadoopScheme.java:212)
        at cascading.tuple.TupleEntrySchemeCollector.collect(TupleEntrySchemeCollector.java:153)
        ... 21 more
```

I haven't made any changes to Amazon's default Elasticsearch configuration. Does anybody have any idea how to make this work?

**Comment by costin** [comment]
Yes you just need to properly configure Elasticsearch (I need to add a section about this in the docs).
The issue lies with how Amazon configures its network namely Elasticsearch is running on private IPs but its reacheable through public ones.
When connector reaches ES, it only knows about the private IPs by default and since it cannot reach them, throws the exception above.

The solution is simple - use the [AWS plugin](https://github.com/elastic/elasticsearch-cloud-aws) which enables proper discovery in EC2/Amazon and also allows Elasticsearch to use the Amazon public IP for broadcast namely EC2 as explained [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html#modules-network).

Hope this helps,

**Comment by fblundun** [comment]
Thanks very much @costin ! I will try using the plugin.

**Comment by fblundun** [comment]
The [Amazon Elasticsearch Service Limits page](http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-limits.html) says that only a few specific plugins are supported. Further investigation is needed but I'm not sure it's actually possible to enable the AWS Cloud Plugin...

**Comment by costin** [comment]
Now I see that you are referring to the Amazon Elasticsearch service. I'm not familiar with that but I expect this to be issue (private vs public). Is there anyway to configure the published/advertised IP?
If not that's quite an oversight since it means the nodes in Amazon cannot be accessed directly.
A workaround to this would be to install a proxy that is accessible form outside and has visibility into the private IPs.
The connector can use it thus to route its calls - it kills parallelism (all connections go through only one node) but it's should work.

Have you tried raising this with Amazon?

Cheers,

**Comment by malpani** [comment]
@costin Is discovery via cloud-aws mandatory for the connection to work? 
Amazon Elasticsearch service currently does not expose private IPs or allow other nodes to join the cluster for security purposes. There is an ELB fronting the cluster nodes whose endpoint (listening on port 80 and not 9200) is exposed for access via REST APIs. TCP is not supported currently. 

Having taken these into consideration, would users of elastic-hadoop be able to talk to the service using something like below or do you foresee problems with this approach?
```
 es.nodes = foo.us-east-1.es.amazonaws.com 
 es.port = 80
 es.nodes.discovery = false
```
SigV4 for signing request will probably not work and users can restrict access to theor Amazon ES cluster via IP based access control?

**Comment by fblundun** [comment]
Update: I tried this using port 80 with "es.nodes.discovery" set to "false" but got the same error from my first attempt:

```
Caused by: org.elasticsearch.hadoop.EsHadoopIllegalStateException: Cluster state volatile; cannot find node backing shards - please check whether your cluster is stable
        at org.elasticsearch.hadoop.rest.RestRepository.getWriteTargetPrimaryShards(RestRepository.java:370)
        at org.elasticsearch.hadoop.rest.RestService.initSingleIndex(RestService.java:425)
        at org.elasticsearch.hadoop.rest.RestService.createWriter(RestService.java:393)
        at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.init(EsOutputFormat.java:173)
        at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.write(EsOutputFormat.java:149)
        at org.apache.hadoop.mapred.MapTask$DirectMapOutputCollector.collect(MapTask.java:844)
        at org.apache.hadoop.mapred.MapTask$OldOutputCollector.collect(MapTask.java:596)
        at cascading.tap.hadoop.util.MeasuredOutputCollector.collect(MeasuredOutputCollector.java:69)
        at org.elasticsearch.hadoop.cascading.EsHadoopScheme.sink(EsHadoopScheme.java:212)
        at cascading.tuple.TupleEntrySchemeCollector.collect(TupleEntrySchemeCollector.java:153)
        ... 21 more
```

**Comment by malpani** [comment]
Access to some of the internal cluster management APIs ( like _cluster/state) are also currently restricted, is the connector trying to sniff shard placements for optimization? Is that causing this.  

Current list of supported operations - http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-gsg-supported-operations.html

**Comment by costin** [comment]
@malpani the connector doesn't rely on `_cluster/state` but it does use `search_shard` API which is not exposed by Amazon. This alone eliminates the whole premise behind the connector which is to use parallelism to connect Hadoop/Spark to ES efficiently.
Sorry...

**Comment by costin** [comment]
@fblundun  @malpani  I've added a new feature in master (and published the [new builds](https://www.elastic.co/guide/en/elasticsearch/hadoop/master/install.html#download-dev) - namely `2.2.0.BUILD-SNAPSHOT`) which allows the connector to work with restricted cloud-like ES environments.
By setting `es.nodes.wan.only` to `true`, the connector will disable discovery and its typical peer-to-peer connections and use _only_ the nodes indicates in `es.nodes`. For Amazon or Found for example this would be the publicly accessible gateway.
All connections to and from ES will be made through this node - clearly it won't be as efficient as connecting to each shard/node directly but it's also the only possible way.

Can you please try it out and report back how it works for you? 

Cheers,

**Comment by fblundun** [comment]
Thanks very much @costin! I will try it out tomorrow and report the results.

**Comment by fblundun** [comment]
Great news! The test run with the latest build succeeded. Thanks @malpani and @costin for all your help!

**Comment by alexanderdean** [comment]
Thanks so much everybody!

**Comment by malpani** [comment]
Thats great to hear! Thank you @costin , @fblundun  and @alexanderdean

**Comment by costin** [comment]
Thanks for the feedback. This feature remains 2.2 only - please use the dev build until M2 is released (in short order).

**Comment by stettix** [comment]
Thanks for this fix, it was essential for my current project as well. Hoping it gets into a full release soon!

**Comment by Paul424** [comment]
Thank you for this fix; just got a first spark job running with es.nodes.wan.only set to true.

Just to help others out; we are using the following dependencies in the pom:

`        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-core_2.10</artifactId>
            <version>1.6.1</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.scala-lang</groupId>
            <artifactId>scala-library</artifactId>
            <version>2.10.6</version>
        </dependency>
        <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch-spark_2.10</artifactId>
            <version>2.3.1</version>
        </dependency>
`

**Comment by nfx** [comment]
As of 2020, it's not possible to write to AWS managed ElasticSearch due to #1140

**Comment by mixja** [comment]
Another option that may come about (hopefully soon) for AWS Elasticsearch deployments is to use the OpenDistro SQL JDBC drivers.

From my early investigation there are some blockers on this, particularly around the SQL dialect that is supported, but at the very least today you can use the OpenDistro SQL JDBC driver with request signing and print schema of an index using Spark (this example is using AWS Glue, but Spark under the hood):

```
>>> import sys
>>> from awsglue.transforms import *
>>> from awsglue.utils import getResolvedOptions
>>> from pyspark.context import SparkContext
>>> from awsglue.context import GlueContext
>>> from awsglue.dynamicframe import DynamicFrame
>>> 
>>> glueContext = GlueContext(SparkContext.getOrCreate())
>>> jdbc_driver_name = "com.amazon.opendistroforelasticsearch.jdbc.Driver"
>>> db_url = "jdbc:elasticsearch://https://xxxxxx.ap-southeast-2.es.amazonaws.com?auth=aws_sigv4"
>>> table_name = "location"
>>> df = glueContext.read.format("jdbc").option("driver", jdbc_driver_name).option("url", db_url).option("dbtable", table_name).load()
>>> df.printSchema()
root
 |-- parent: integer (nullable = true)
 |-- aliases: string (nullable = true)
 |-- suggest_text: string (nullable = true)
 |-- tie_breaker: string (nullable = true)
 |-- type: integer (nullable = true)
 |-- modified: timestamp (nullable = true)
 |-- id: integer (nullable = true)
 |-- text: string (nullable = true)
 |-- ontology_autocomplete: string (nullable = true)
 |-- lat: double (nullable = true)
 |-- slug: string (nullable = true)
 |-- lng: double (nullable = true)
 |-- created: timestamp (nullable = true)
 |-- neighboring_locations: integer (nullable = true)
 |-- location_type: integer (nullable = true)
 |-- location_autocomplete: string (nullable = true)
 |-- name: string (nullable = true)
 |-- suggestions: string (nullable = true)
```

At the moment you would need to create a custom dialect for anything useful to work.
