### ISSUE TITLE
InitializationUtils throws an unexpected(?) exception while running against a 1.5.0 ElasticSearch cluster: Unsupported/Unknown Elasticsearch version 1.5.0

### ISSUE THREAD

**Issue by fucema** [elastic/elasticsearch-hadoop#571]
Looks like a recent change to the version string comparison from "1." to "1.x" causes this Exception to be thrown. 

https://github.com/elastic/elasticsearch-hadoop/blob/master/mr/src/main/java/org/elasticsearch/hadoop/rest/InitializationUtils.java#L171

Running: Elasticsearch Hadoop v2.2.0.BUILD-SNAPSHOT with an ElasticSearch cluster version 1.5.0

Full stacktrace:
```
12 Oct 2015 17:16:17,709 INFO  Version        : Elasticsearch Hadoop v2.2.0.BUILD-SNAPSHOT [96c682d103]
Exception in thread "main" org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Unsupported/Unknown Elasticsearch version 1.5.0
	at org.elasticsearch.hadoop.rest.InitializationUtils.discoverEsVersion(InitializationUtils.java:172)
	at org.elasticsearch.hadoop.rest.RestService.findPartitions(RestService.java:229)
	at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions$lzycompute(AbstractEsRDD.scala:61)
	at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions(AbstractEsRDD.scala:60)
	at org.elasticsearch.spark.rdd.AbstractEsRDD.getPartitions(AbstractEsRDD.scala:27)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.Partitioner$$anonfun$2.apply(Partitioner.scala:58)
	at org.apache.spark.Partitioner$$anonfun$2.apply(Partitioner.scala:58)
	at scala.math.Ordering$$anon$5.compare(Ordering.scala:122)
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:324)
	at java.util.TimSort.sort(TimSort.java:189)
	at java.util.TimSort.sort(TimSort.java:173)
	at java.util.Arrays.sort(Arrays.java:659)
	at scala.collection.SeqLike$class.sorted(SeqLike.scala:615)
	at scala.collection.AbstractSeq.sorted(Seq.scala:40)
	at scala.collection.SeqLike$class.sortBy(SeqLike.scala:594)
	at scala.collection.AbstractSeq.sortBy(Seq.scala:40)
	at org.apache.spark.Partitioner$.defaultPartitioner(Partitioner.scala:58)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$leftOuterJoin$2.apply(PairRDDFunctions.scala:615)
	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$leftOuterJoin$2.apply(PairRDDFunctions.scala:615)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
	at org.apache.spark.rdd.PairRDDFunctions.leftOuterJoin(PairRDDFunctions.scala:614)
	at org.apache.spark.api.java.JavaPairRDD.leftOuterJoin(JavaPairRDD.scala:572)
	at com.comcast.psp.elasticsearch.spark.SparkRunner.main(SparkRunner.java:126)
```

**Comment by costin** [comment]
Oops. Fixed in master and pushed already a build for it. Can you please try it out and report back?

Thanks

**Comment by fucema** [comment]
It's working again, thanks for the quick fix.

Grabbed the latest snapshot using this maven dependency (I am using maven for this particular project):
        <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch-spark_2.10</artifactId>
            <version>2.2.0.BUILD-SNAPSHOT</version> 
        </dependency>
