### ISSUE TITLE
Can not create a Path from an empty string (Hive MapRed job with ES)

### ISSUE THREAD

**Issue by marcelopaesrech** [elastic/elasticsearch-hadoop#59]
When I try to run a mapred job by Hive. 
Environment Mac OS or Linux, hive 0.11, hadoop 1.2 or 0.23, ES 0.90.2.

My "test" entity hava just three fields (userid, name and type), and have just one record on ES.

hive> select count(userid) from test;  
Total MapReduce jobs = 1
Launching Job 1 out of 1
Number of reduce tasks determined at compile time: 1
In order to change the average load for a reducer (in bytes):
  set hive.exec.reducers.bytes.per.reducer=<number>
In order to limit the maximum number of reducers:
  set hive.exec.reducers.max=<number>
In order to set a constant number of reducers:
  set mapred.reduce.tasks=<number>
Starting Job = job_201307081651_0001, Tracking URL = http://localhost:50030/jobdetails.jsp?jobid=job_201307081651_0001
Kill Command = /Users/developergvt/servers/hadoop-1.2.0/libexec/../bin/hadoop job  -kill job_201307081651_0001
Hadoop job information for Stage-1: number of mappers: 5; number of reducers: 1
2013-07-08 16:57:39,056 Stage-1 map = 0%,  reduce = 0%
2013-07-08 16:58:01,154 Stage-1 map = 100%,  reduce = 100%
Ended Job = job_201307081651_0001 with errors
Error during job, obtaining debugging information...
Job Tracking URL: http://localhost:50030/jobdetails.jsp?jobid=job_201307081651_0001
Examining task ID: task_201307081651_0001_m_000006 (and more) from job job_201307081651_0001
## Task with the most failures(4): 

Task ID:
  task_201307081651_0001_m_000000

URL:
##   http://localhost:50030/taskdetails.jsp?jobid=job_201307081651_0001&tipid=task_201307081651_0001_m_000000

Diagnostic Messages for this Task:
java.lang.IllegalArgumentException: Can not create a Path from an empty string
    at org.apache.hadoop.fs.Path.checkPathArg(Path.java:82)
    at org.apache.hadoop.fs.Path.<init>(Path.java:90)
    at org.apache.hadoop.hive.ql.io.HiveInputFormat$HiveInputSplit.getPath(HiveInputFormat.java:106)
    at org.apache.hadoop.mapred.MapTask.updateJobWithSplit(MapTask.java:451)
    at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:409)
    at org.apache.hadoop.mapred.MapTask.run(MapTask.java:366)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:255)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:396)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1190)
    at org.apache.hadoop.mapred.Child.main(Child.java:249)

FAILED: Execution Error, return code 2 from org.apache.hadoop.hive.ql.exec.MapRedTask
MapReduce Jobs Launched: 
Job 0: Map: 5  Reduce: 1   HDFS Read: 0 HDFS Write: 0 FAIL
Total MapReduce CPU Time Spent: 0 msec

**Comment by chandrakar** [comment]
Counters:
Stage-4 is filtered out by condition resolver.
Stage-3 is selected by condition resolver.
Stage-5 is filtered out by condition resolver.
Launching Job 3 out of 3
Number of reduce tasks is set to 0 since there's no reduce operator
java.lang.NullPointerException
        at org.apache.hadoop.hive.ql.exec.ExecDriver.addInputPath(ExecDriver.java:843)
        at org.apache.hadoop.hive.ql.exec.ExecDriver.addInputPaths(ExecDriver.java:1149)
        at org.apache.hadoop.hive.ql.exec.ExecDriver.execute(ExecDriver.java:445)
        at org.apache.hadoop.hive.ql.exec.MapRedTask.execute(MapRedTask.java:138)
        at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:144)
        at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:57)
        at org.apache.hadoop.hive.ql.exec.TaskRunner.run(TaskRunner.java:47)
Job Submission failed with exception 'java.lang.NullPointerException(null)'
java.lang.IllegalArgumentException: Can not create a Path from an empty string
        at org.apache.hadoop.fs.Path.checkPathArg(Path.java:127)
        at org.apache.hadoop.fs.Path.<init>(Path.java:135)
        at org.apache.hadoop.hive.ql.exec.Utilities.getHiveJobID(Utilities.java:418)
        at org.apache.hadoop.hive.ql.exec.Utilities.clearMapRedWork(Utilities.java:209)
        at org.apache.hadoop.hive.ql.exec.ExecDriver.execute(ExecDriver.java:508)
        at org.apache.hadoop.hive.ql.exec.MapRedTask.execute(MapRedTask.java:138)
        at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:144)
        at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:57)
        at org.apache.hadoop.hive.ql.exec.TaskRunner.run(TaskRunner.java:47)
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.MapRedTask
MapReduce Jobs Launched:
Job 0: Map: 1   Cumulative CPU: 6.31 sec   HDFS Read: 280 HDFS Write: 0 SUCCESS
Total MapReduce CPU Time Spent: 6 seconds 310 msec
Info : 10:13:29 : 1

**Comment by chandrakar** [comment]
@costin Please help to resolve the below issues .

i am using hive 0.11 

Counters:
Stage-4 is filtered out by condition resolver.
Stage-3 is selected by condition resolver.
Stage-5 is filtered out by condition resolver.
Launching Job 3 out of 3
Number of reduce tasks is set to 0 since there's no reduce operator
java.lang.NullPointerException
        at org.apache.hadoop.hive.ql.exec.ExecDriver.addInputPath(ExecDriver.java:843)
        at org.apache.hadoop.hive.ql.exec.ExecDriver.addInputPaths(ExecDriver.java:1149)
        at org.apache.hadoop.hive.ql.exec.ExecDriver.execute(ExecDriver.java:445)
        at org.apache.hadoop.hive.ql.exec.MapRedTask.execute(MapRedTask.java:138)
        at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:144)
        at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:57)
        at org.apache.hadoop.hive.ql.exec.TaskRunner.run(TaskRunner.java:47)
Job Submission failed with exception 'java.lang.NullPointerException(null)'
java.lang.IllegalArgumentException: Can not create a Path from an empty string
        at org.apache.hadoop.fs.Path.checkPathArg(Path.java:127)
        at org.apache.hadoop.fs.Path.<init>(Path.java:135)
        at org.apache.hadoop.hive.ql.exec.Utilities.getHiveJobID(Utilities.java:418)
        at org.apache.hadoop.hive.ql.exec.Utilities.clearMapRedWork(Utilities.java:209)
        at org.apache.hadoop.hive.ql.exec.ExecDriver.execute(ExecDriver.java:508)
        at org.apache.hadoop.hive.ql.exec.MapRedTask.execute(MapRedTask.java:138)
        at org.apache.hadoop.hive.ql.exec.Task.executeTask(Task.java:144)
        at org.apache.hadoop.hive.ql.exec.TaskRunner.runSequential(TaskRunner.java:57)
        at org.apache.hadoop.hive.ql.exec.TaskRunner.run(TaskRunner.java:47)
FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.MapRedTask
MapReduce Jobs Launched:
Job 0: Map: 1   Cumulative CPU: 6.31 sec   HDFS Read: 280 HDFS Write: 0 SUCCESS
Total MapReduce CPU Time Spent: 6 seconds 310 msec
Info : 10:13:29 : 1

**Comment by costin** [comment]
@chandrakar Please don't highjack an old issue. Use the mailing list or IRC for questions, not the issue tracker.

**Comment by chandrakar** [comment]
Thanks @costin  i will take care of this things from next time .

and i will Use the mailing list or IRC for questions.


Thanks

**Comment by DeeeFOX** [comment]
* Description

	When using hive dealing data, whenever mapred job is submitted, Error of this happen:

		Launching Job 1 out of 3
		Number of reduce tasks is set to 0 since there's no reduce operator
		java.lang.IllegalArgumentException: Can not create a Path from an empty string
			at org.apache.hadoop.fs.Path.checkPathArg(Path.java:126)
			...
			at org.apache.hadoop.util.RunJar.main(RunJar.java:136)
		Job Submission failed with exception 'java.lang.IllegalArgumentException(Can not create a Path from an empty string)'
		FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask. Can not create a Path from an empty string

* Why it happen
	
	* It is not caused by 
	
		* user prividlege/right of the hadoop/local path of hadoop/hive
		* yarn resourge/node manager problem
		* hadoop/hive/java version
	
	* It is because
		
		* file ```${HIVE_HOME}/conf/hive-site.sh``` didn't config right like this:

				...
				# Folder containing extra ibraries required for hive compilation/execution can be controlled by:
				export HIVE_AUX_JARS_PATH=/home/gzzhaozongfei/soft/mongodb:${HIVE_AUX_JARS_PATH}

			The problem is caused by the part: ```${HIVE_AUX_JARS_PATH}```

* Solution

	* config the ```${HIVE_HOME}/conf/hive-site.sh``` right then it sovled:

			...
			# Folder containing extra ibraries required for hive compilation/execution can be controlled by:
			export HIVE_AUX_JARS_PATH=/home/gzzhaozongfei/soft/mongodb
