### ISSUE TITLE
ES 2.0 SSL problem

### ISSUE THREAD

**Issue by pricecarl** [elastic/elasticsearch-hadoop#608]
Hey,

I'm having trouble writing data from hive to ES 2.0 I'm using the  elasticsearch-hadoop-hive-2.2.0-beta1.jar file but am getting the below error:

    Caused by: org.elasticsearch.hadoop.rest.EsHadoopTransportException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.elasticsearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:116)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:383)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:363)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:367)
	at org.elasticsearch.hadoop.rest.RestClient.get(RestClient.java:121)
	at org.elasticsearch.hadoop.rest.RestClient.getHttpDataNodes(RestClient.java:336)
	at org.elasticsearch.hadoop.rest.InitializationUtils.filterNonDataNodesIfNeeded(InitializationUtils.java:121)
	at org.elasticsearch.hadoop.rest.RestService.createWriter(RestService.java:381)
	at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.init(EsOutputFormat.java:173)
	at org.elasticsearch.hadoop.hive.EsHiveOutputFormat$EsHiveRecordWriter.write(EsHiveOutputFormat.java:58)
	at org.apache.hadoop.hive.ql.exec.FileSinkOperator.processOp(FileSinkOperator.java:638)
	at org.apache.hadoop.hive.ql.exec.Operator.process(Operator.java:504)
	at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:847)
	at org.apache.hadoop.hive.ql.exec.SelectOperator.processOp(SelectOperator.java:87)
	at org.apache.hadoop.hive.ql.exec.Operator.process(Operator.java:504)
	at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:847)
	at org.apache.hadoop.hive.ql.exec.FilterOperator.processOp(FilterOperator.java:136)
	at org.apache.hadoop.hive.ql.exec.Operator.process(Operator.java:504)
	at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:847)
	at org.apache.hadoop.hive.ql.exec.TableScanOperator.processOp(TableScanOperator.java:91)
	at org.apache.hadoop.hive.ql.exec.Operator.process(Operator.java:504)
	at org.apache.hadoop.hive.ql.exec.Operator.forward(Operator.java:847)
	at org.apache.hadoop.hive.ql.exec.MapOperator.process(MapOperator.java:519)  
    ... 9 more
    Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1884)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:276)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:270)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1341)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:153)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:868)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:804)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1016)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1312)
	at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:702)
	at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:122)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	at org.apache.commons.httpclient.HttpConnection.flushRequestOutputStream(HttpConnection.java:828)
	at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2116)
	at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096)
	at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398)
	at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
	at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
	at org.elasticsearch.hadoop.rest.commonshttp.CommonsHttpTransport.execute(CommonsHttpTransport.java:430)
	at org.elasticsearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:104)
	... 31 more
    Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:385)
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
	at sun.security.validator.Validator.validate(Validator.java:260)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:326)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:126)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1323)
	... 49 more
    Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:196)
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:268)
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:380)
    	... 55 more

Neither my Hadoop or ES 2.0 cluster uses SSL so I don't know why its asking for certs. According to the docs SSL is defaulted to false but I have put it in my table properties again in case:

...
STORED BY 'org.elasticsearch.hadoop.hive.EsStorageHandler'
TBLPROPERTIES ('es.resource' = 'proxylog-2015-11-02/event',
               'es.index.auto.create' = 'true',
               'es.nodes' = 'calhdb08.cyber.lab',
               'es.port' = '9200',
               'es.field.read.empty.as.null' ='true',
               'es.net.ssl' = 'false',
               'es.batch.size.entries' = '10000',
               'es.batch.size.bytes' = '128mb',
               'es.mapping.names' = 'Time
...

Any ideas would be greatly appreciated.

I have also raised this with ES support.

**Comment by costin** [comment]
Something is definitely is using SSL otherwise this won't show in the stack trace. Based on the strack trace is looks like the initial call to ES is successful but the subsequent call ends being _wrapped_ through SSL. Can you please enable `TRACE` [logging](https://www.elastic.co/guide/en/elasticsearch/hadoop/master/logging.html) on the `rest` package and upload the gist somewhere?

Additionally, please double check your configuration - the SSL won't appear out of nowhere; maybe you have a transparent proxy defined or maybe the ES nodes communicate between each other using SSL. Does `curl` works without SSL? Since ES is accessible as REST, you should be able to simply point the browser to it as well.
Anything special in the ES logs?

**Comment by pricecarl** [comment]
Hi Costin,

Forgive me I'm not great with the whole hadoop setup and I'm not sure how to enable logging.

I was however able to successfully run curl commands against the cluster:

    curl -XGET http://calhdb08.cyber.lab:9200
    {
      "name" : "calhdb08-es-ClientNode",
      "cluster_name" : "ucp-incubator-proxy",
      "version" : {
    "number" : "2.0.0",
    "build_hash" : "de54438d6af8f9340d50c5c786151783ce7d6be5",
    "build_timestamp" : "2015-10-22T08:09:48Z",
    "build_snapshot" : false,
    "lucene_version" : "5.2.1"
      },
      "tagline" : "You Know, for Search"
     }
and:

    curl -XPUT http://calhdb08.cyber.lab:9200/carltest2_index/carltest_type/1 -d '{"Hello" : "world"}'

    {"_index":"carltest2_index","_type":"carltest_type","_id":"1","_version":1,"_shards":{"total":2,"successful":1,"failed":0},"created":true}

Also I've been doing some digging and found this option:

security.manager.enabled: false

Which I put into my elasticsearch.yml file, now I get this error:

**Comment by pricecarl** [comment]
Hi Costin,

I changed a setting in the elasticsearch.yml file to use the nodes IP instead of its hostname for publishing and this has fixed the issue.

I can't seem to replicate the SSL issue though but I definitely do not use SSL anywhere on this cluster, so a bit of a strange one.

**Comment by costin** [comment]
Closing this one since it seems to be fixed. If that's not the case, please reopen it.
