### ISSUE TITLE
SparkSQL schema not inferred correctly when using Elastichsearch "nested" type

### ISSUE THREAD

**Issue by fjavieralba** [elastic/elasticsearch-hadoop#616]
Hi,

If I create an Elasticsearch index containing a [nested](https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html) datatype, I get a wrong schema in SparkSQL.

For example, this is my elasticsearch index:

    curl -XPUT 'localhost:9200/companies/?pretty=1' -d '{
      "mappings": {
        "company": {
          "properties": {
            "name": { "type": "string"},
            "description": {"type": "string"},
            "employees": {
              "type": "nested",
              "properties": {
                "name": {"type": "string"},
                "salary": {"type": "long"}
              }
            }
          }
        }
      }
    }'

And this is how I index one example document:

    curl -XPUT 'localhost:9200/companies/company/1' -d '{
      "name": "mycompany",
      "employees": [
        { "name": "anne",
          "salary": 6},
        { "name": "bob",
          "salary": 100},
        { "name": "charlie",
          "salary": 15
        }],
      "description": "a cool tech startup"
    }'

Then, inside `spark shell`:

    scala> val options = Map("pushdown" -> "true", "es.field.read.as.array.include" -> "employees")
    scala> val esDf = sqlContext.read.format("org.elasticsearch.spark.sql").options(options).load("companies/company")
    scala> esDf.printSchema
    root
     |-- description: string (nullable = true)
     |-- employees: array (nullable = true)
     |    |-- element: string (containsNull = true)
     |-- name: string (nullable = true)

 expected schema is:
 
     root
      |-- description: string (nullable = true)
      |-- employees: array (nullable = true)
      |    |-- element: struct (containsNull = true)
      |    |    |-- name: string (nullable = true)
      |    |    |-- salary: long (nullable = true)
      |-- name: string (nullable = true)

  This also causes NullPointerException errors when querying the table:

      scala> esDf.registerTempTable("companies")
      scala> val res = sqlContext.sql("SELECT * from companies")

      scala> res.count
      15/11/26 13:40:18 ERROR Executor: Managed memory leak detected; size = 4194304 bytes, TID = 23
      15/11/26 13:40:18 ERROR Executor: Exception in task 3.0 in stage 4.0 (TID 23)
      java.lang.NullPointerException
        at org.elasticsearch.spark.sql.RowValueReader$class.addToBuffer(RowValueReader.scala:38)
        at org.elasticsearch.spark.sql.ScalaRowValueReader.addToBuffer(ScalaEsRowValueReader.scala:13)
        at org.elasticsearch.spark.sql.ScalaRowValueReader.addToMap(ScalaEsRowValueReader.scala:85)
        at org.elasticsearch.hadoop.serialization.ScrollReader.map(ScrollReader.java:661)
        at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:588)
        at org.elasticsearch.hadoop.serialization.ScrollReader.list(ScrollReader.java:625)
        at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:583)
        at org.elasticsearch.hadoop.serialization.ScrollReader.map(ScrollReader.java:661)
        at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:588)
        at org.elasticsearch.hadoop.serialization.ScrollReader.readHitAsMap(ScrollReader.java:383)
        at org.elasticsearch.hadoop.serialization.ScrollReader.readHit(ScrollReader.java:318)
        at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:213)
        at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:186)
        at org.elasticsearch.hadoop.rest.RestRepository.scroll(RestRepository.java:438)
        at org.elasticsearch.hadoop.rest.ScrollQuery.hasNext(ScrollQuery.java:86)
        at org.elasticsearch.spark.rdd.AbstractEsRDDIterator.hasNext(AbstractEsRDDIterator.scala:43)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at org.apache.spark.sql.execution.aggregate.TungstenAggregate$$anonfun$doExecute$1.org$apache$spark$sql$execution$aggregate$TungstenAggregate$$anonfun$$executePartition$1(TungstenAggregate.scala:97)
        at org.apache.spark.sql.execution.aggregate.TungstenAggregate$$anonfun$doExecute$1$$anonfun$2.apply(TungstenAggregate.scala:119)
        at org.apache.spark.sql.execution.aggregate.TungstenAggregate$$anonfun$doExecute$1$$anonfun$2.apply(TungstenAggregate.scala:119)
        at org.apache.spark.rdd.MapPartitionsWithPreparationRDD.compute(MapPartitionsWithPreparationRDD.scala:64)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
        at org.apache.spark.scheduler.Task.run(Task.scala:88)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
  
elasticsearch-hadoop version used is `elasticsearch-hadoop-2.2.0.BUILD-SNAPSHOT.jar` built from master branch

Spark version is 1.5.2

**Comment by ThadGholston** [comment]
@fjavieralba I'm having similar issues. Were you ever able to resolve the problem? If so how?

**Comment by nrstott** [comment]
Nested types end up going through this if statement: https://github.com/elastic/elasticsearch-hadoop/blob/a70a9ea03b08ec7bd6fa038885425a0fa84fd7ae/mr/src/main/java/org/elasticsearch/hadoop/serialization/dto/mapping/Field.java#L130

It looks like they should not?

**Comment by fjavieralba** [comment]
@ThadGholston no, I could not invest more time, still unresolved for me

**Comment by costin** [comment]
Guys, I've pushed a fix for `nested` types in master and also a [dev build](https://www.elastic.co/guide/en/elasticsearch/hadoop/master/install.html#download-dev). Can you please try it out and report back?

Thanks,

**Comment by costin** [comment]
And @fjavieralba , thanks for an excellent bug report. If only most issues would be like this one...

**Comment by fjavieralba** [comment]
Your welcome, @costin. Thanks to you for all the hard work in this amazing project!

I've tested with a build from master and it worked like a charm!

Following the same steps in spark-shell, now schema is as expected and the query executes correctly:

    scala> val options = Map("pushdown" -> "true", "es.field.read.as.array.include" -> "employees")
    scala> val esDf = sqlContext.read.format("org.elasticsearch.spark.sql").options(options).load("companies/company")
    scala> esDf.printSchema
    root
     |-- description: string (nullable = true)
     |-- employees: array (nullable = true)
     |    |-- element: struct (containsNull = true)
     |    |    |-- name: string (nullable = true)
     |    |    |-- salary: long (nullable = true)
     |-- name: string (nullable = true)

    scala> esDf.registerTempTable("companies")
    scala> val res = sqlContext.sql("SELECT * from companies")
    scala> res.count
    scala> res.collect().foreach(println)
    [a cool tech startup,WrappedArray([anne,6], [bob,100], [charlie,15]),mycompany]

Thanks!

**Comment by costin** [comment]
By the way you don't need the `es.field.read` option any more (which has changed by the way to be aligned with the rest of the options (`es.read.field...`).

Again, thanks for the bug report and the patience until it was solved.

**Comment by prabhushrikant** [comment]
GIves me error when trying to read nested.nested schema like this.
```
{"userId": 402885,
            "userUuid": "F2896A1F1A7D411A69",
            "affiliations": [
                {
                    "org": {
                        "orgName": "Dick's Sporting Goods",
                        "categories": [
                            65,
                            68,
                            85
                        ],
                    },
}
],
}
```
