### ISSUE TITLE
Custom DateTimeFormat "yyyy-MM-dd HH:mm:ss" in the mapping cannot be parsed

### ISSUE THREAD

**Issue by dialtahi** [elastic/elasticsearch-hadoop#624]
I'm getting this error parsing date time:

```
15/12/15 16:02:40 ERROR Executor: Exception in task 4.0 in stage 4.0 (TID 10)
org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot invoke method public org.joda.time.DateTime org.joda.time.format.DateTimeFormatter.parseDateTime(java.lang.String)
	at org.elasticsearch.hadoop.util.ReflectionUtils.invoke(ReflectionUtils.java:93)
	at org.elasticsearch.hadoop.util.DateUtils$JodaTime.parseDate(DateUtils.java:105)
	at org.elasticsearch.hadoop.util.DateUtils.parseDate(DateUtils.java:122)
	at org.elasticsearch.spark.serialization.ScalaValueReader.createDate(ScalaValueReader.scala:134)
	at org.elasticsearch.spark.serialization.ScalaValueReader.parseDate(ScalaValueReader.scala:125)
	at org.elasticsearch.spark.serialization.ScalaValueReader$$anonfun$date$1.apply(ScalaValueReader.scala:118)
	at org.elasticsearch.spark.serialization.ScalaValueReader$$anonfun$date$1.apply(ScalaValueReader.scala:118)
	at org.elasticsearch.spark.serialization.ScalaValueReader.checkNull(ScalaValueReader.scala:70)
	at org.elasticsearch.spark.serialization.ScalaValueReader.date(ScalaValueReader.scala:118)
	at org.elasticsearch.spark.serialization.ScalaValueReader.readValue(ScalaValueReader.scala:58)
	at org.elasticsearch.spark.sql.ScalaRowValueReader.readValue(ScalaEsRowValueReader.scala:27)
	at org.elasticsearch.hadoop.serialization.ScrollReader.parseValue(ScrollReader.java:604)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:592)
	at org.elasticsearch.hadoop.serialization.ScrollReader.map(ScrollReader.java:660)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:587)
	at org.elasticsearch.hadoop.serialization.ScrollReader.readHitAsMap(ScrollReader.java:382)
	at org.elasticsearch.hadoop.serialization.ScrollReader.readHit(ScrollReader.java:317)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:212)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:186)
	at org.elasticsearch.hadoop.rest.RestRepository.scroll(RestRepository.java:408)
	at org.elasticsearch.hadoop.rest.ScrollQuery.hasNext(ScrollQuery.java:86)
	at org.elasticsearch.spark.rdd.AbstractEsRDDIterator.hasNext(AbstractEsRDDIterator.scala:43)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.insertAll(BypassMergeSortShuffleWriter.java:99)
	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:73)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.elasticsearch.hadoop.util.ReflectionUtils.invoke(ReflectionUtils.java:91)
	... 33 more
Caused by: java.lang.IllegalArgumentException: Invalid format: "1990-10-11 00:00:00" is malformed at " 00:00:00"
	at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:873)
	... 38 more
```

I have followed the documentation of elasticsearch that supports custom date time formats:
https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-date-format.html

The mapping for the field in the type is as follows:

```
"ACCOUNTS_Date_Created": {
  "type": "date",
  "format": "yyyy-MM-dd HH:mm:ss"
}
```

I'm reading the type as follows:

```
val accounts = EsSparkSQL.esDF(sqlContext, "myindex/ACCOUNTS")
```

**Comment by ebuildy** [comment]
Got this too ;-( The weird thing is I just want to count documents ...

But I am not sure mapping is taken in account by ES-Hadoop, look like a Joda error, I am digging

**Comment by dialtahi** [comment]
Yes, it is. Looks like only supports ISO 8601 date time formats.

I can't change the mapping in the type that I'm trying to read so what can I do? Is planned to implement custom formats?

**Comment by nsphung** [comment]
Hello,

I'm working with Spark 1.5.2.

I have a similar issue with elasticsearch-spark 2.2.0-rc1

```
16/01/21 16:26:33 ERROR Executor: Exception in task 2.0 in stage 0.0 (TID 2)
org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot invoke method public org.joda.time.DateTime org.joda.time.format.DateTimeFormatter.parseDateTime(java.lang.String)
	at org.elasticsearch.hadoop.util.ReflectionUtils.invoke(ReflectionUtils.java:93)
	at org.elasticsearch.hadoop.util.DateUtils$JodaTime.parseDate(DateUtils.java:105)
	at org.elasticsearch.hadoop.util.DateUtils.parseDate(DateUtils.java:122)
	at org.elasticsearch.spark.serialization.ScalaValueReader.createDate(ScalaValueReader.scala:134)
	at org.elasticsearch.spark.serialization.ScalaValueReader.parseDate(ScalaValueReader.scala:125)
	at org.elasticsearch.spark.serialization.ScalaValueReader$$anonfun$date$1.apply(ScalaValueReader.scala:118)
	at org.elasticsearch.spark.serialization.ScalaValueReader$$anonfun$date$1.apply(ScalaValueReader.scala:118)
	at org.elasticsearch.spark.serialization.ScalaValueReader.checkNull(ScalaValueReader.scala:70)
	at org.elasticsearch.spark.serialization.ScalaValueReader.date(ScalaValueReader.scala:118)
	at org.elasticsearch.spark.serialization.ScalaValueReader.readValue(ScalaValueReader.scala:58)
	at org.elasticsearch.spark.sql.ScalaRowValueReader.readValue(ScalaEsRowValueReader.scala:27)
	at org.elasticsearch.hadoop.serialization.ScrollReader.parseValue(ScrollReader.java:604)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:592)
	at org.elasticsearch.hadoop.serialization.ScrollReader.map(ScrollReader.java:660)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:587)
	at org.elasticsearch.hadoop.serialization.ScrollReader.readHitAsMap(ScrollReader.java:382)
	at org.elasticsearch.hadoop.serialization.ScrollReader.readHit(ScrollReader.java:317)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:212)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:186)
	at org.elasticsearch.hadoop.rest.RestRepository.scroll(RestRepository.java:408)
	at org.elasticsearch.hadoop.rest.ScrollQuery.hasNext(ScrollQuery.java:86)
	at org.elasticsearch.spark.rdd.AbstractEsRDDIterator.hasNext(AbstractEsRDDIterator.scala:43)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at scala.collection.Iterator$$anon$14.hasNext(Iterator.scala:388)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
	at org.apache.spark.sql.execution.aggregate.TungstenAggregate$$anonfun$doExecute$1.org$apache$spark$sql$execution$aggregate$TungstenAggregate$$anonfun$$executePartition$1(TungstenAggregate.scala:97)
	at org.apache.spark.sql.execution.aggregate.TungstenAggregate$$anonfun$doExecute$1$$anonfun$2.apply(TungstenAggregate.scala:119)
	at org.apache.spark.sql.execution.aggregate.TungstenAggregate$$anonfun$doExecute$1$$anonfun$2.apply(TungstenAggregate.scala:119)
	at org.apache.spark.rdd.MapPartitionsWithPreparationRDD.compute(MapPartitionsWithPreparationRDD.scala:64)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:300)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:264)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:88)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.elasticsearch.hadoop.util.ReflectionUtils.invoke(ReflectionUtils.java:91)
	... 40 more
Caused by: java.lang.IllegalArgumentException: Invalid format: "20151123T012640.093+0100" is malformed at "2640.093+0100"
	at org.joda.time.format.DateTimeFormatter.parseDateTime(DateTimeFormatter.java:899)
	... 45 more
```

I tried the latest SNAPSHOT today too with 2.2.0.BUILD-SNAPSHOT and got another stack error

```
16/01/21 17:00:23 WARN MetricsSystem: Using default name DAGScheduler for source because spark.app.id is not set.
Exception in thread "main" org.apache.spark.sql.AnalysisException: cannot resolve 'UDF(date)' due to data type mismatch: argument 1 requires string type, however, 'date' is of array<timestamp> type.;
	at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$2.applyOrElse(CheckAnalysis.scala:61)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1$$anonfun$apply$2.applyOrElse(CheckAnalysis.scala:53)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:293)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformUp$1.apply(TreeNode.scala:293)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:51)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:292)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$5.apply(TreeNode.scala:290)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$5.apply(TreeNode.scala:290)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:249)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
	at scala.collection.AbstractIterator.to(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:252)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1157)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformChildren(TreeNode.scala:279)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformUp(TreeNode.scala:290)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpressionUp$1(QueryPlan.scala:107)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$2(QueryPlan.scala:117)
	at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$2$1.apply(QueryPlan.scala:121)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.org$apache$spark$sql$catalyst$plans$QueryPlan$$recursiveTransform$2(QueryPlan.scala:121)
	at org.apache.spark.sql.catalyst.plans.QueryPlan$$anonfun$2.apply(QueryPlan.scala:125)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
	at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:48)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:103)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:47)
	at scala.collection.TraversableOnce$class.to(TraversableOnce.scala:273)
	at scala.collection.AbstractIterator.to(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toBuffer(TraversableOnce.scala:265)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1157)
	at scala.collection.TraversableOnce$class.toArray(TraversableOnce.scala:252)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1157)
	at org.apache.spark.sql.catalyst.plans.QueryPlan.transformExpressionsUp(QueryPlan.scala:125)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:53)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$$anonfun$checkAnalysis$1.apply(CheckAnalysis.scala:49)
	at org.apache.spark.sql.catalyst.trees.TreeNode.foreachUp(TreeNode.scala:103)
	at org.apache.spark.sql.catalyst.analysis.CheckAnalysis$class.checkAnalysis(CheckAnalysis.scala:49)
	at org.apache.spark.sql.catalyst.analysis.Analyzer.checkAnalysis(Analyzer.scala:44)
	at org.apache.spark.sql.SQLContext$QueryExecution.assertAnalyzed(SQLContext.scala:914)
	at org.apache.spark.sql.DataFrame.<init>(DataFrame.scala:132)
	at org.apache.spark.sql.DataFrame.org$apache$spark$sql$DataFrame$$logicalPlanToDataFrame(DataFrame.scala:154)
	at org.apache.spark.sql.DataFrame.select(DataFrame.scala:691)
	at org.apache.spark.sql.DataFrame.withColumn(DataFrame.scala:1150)
```

The mapping of my date field is like this :

```
        "date": {
          "type": "date",
          "format": "basic_date_time"
        }
```

With 2.2.0-rc1 when date is a string type, the job works as expected. It seems there's an issue with the date type.

**Comment by costin** [comment]
ES-Hadoop can work only with ISO8601 dates. The Joda library is picked up and used since it is available from Spark and has better parsing then the JDK 7 classes. Once ES-Hadoop will move to JDK 8, the whole parsing might be improved - however there are some fundamental changes between the two, in particular the fact that Joda allows multiple formats to be chained while JDK7 does not.

**Comment by nsphung** [comment]
@sophiewachs & @ogirardot find a pretty way for us to work on our date format `"format": "basic_date_time"` with `"elasticsearch-spark" % "2.2.0-rc1"`


First, you declare a custom  ScalaRowValueReader
```scala
import org.elasticsearch.hadoop.serialization.Parser
import org.elasticsearch.spark.sql.ScalaRowValueReader
import org.joda.time.format.ISODateTimeFormat

/**
* Custom reader that has the same behavior than the elasticsearch-spark reader except for the field date
* The elasticsearch-spark reader does not take into account the schema of ES especially the format of dates.
* All dates are considered "date_optional_time"
**/
class SpecificBasicDateTimeReader extends ScalaRowValueReader {
  override def date(value: String, parser: Parser): AnyRef = {
    parser.currentName() match {
      case "date" =>
        new java.sql.Timestamp(ISODateTimeFormat.basicDateTime().parseDateTime(value).getMillis).asInstanceOf[AnyRef]
      case x =>
        super.date(value, parser)
    }
  }
}
```

Then you just have to register it via `ConfigurationOptions.ES_SERIALIZATION_READER_VALUE_CLASS`

```scala
    val df = EsSparkSQL.esDF(sqlContext,
      Map(
        ConfigurationOptions.ES_RESOURCE_READ -> s"index/doc",
        ConfigurationOptions.ES_INDEX_READ_MISSING_AS_EMPTY -> "true",
        "es.read.field.include" -> "meta,id,date,source",
        // Option to specify a serialization reader
        ConfigurationOptions.ES_SERIALIZATION_READER_VALUE_CLASS -> classOf[SpecificBasicDateTimeReader].getCanonicalName
      ))
```
This works for us. I hope it helps.

**Comment by costin** [comment]
@nsphung A valid approach - the only downside is that it requires writing custom code. Disabling [rich date mapping](https://www.elastic.co/guide/en/elasticsearch/hadoop/master/mapping.html) so it gets returned as a String and then converting the field would have the same effect however it would not tie the code to ES-Hadoop classes which are likely to change in the future.

**Comment by costin** [comment]
Guys since there are several solutions in the last comment, I'm closing this one down.

Cheers,

**Comment by Heltman** [comment]
it's so bad
