### ISSUE TITLE
multi index data frame causes OOM

### ISSUE THREAD

**Issue by costin** [elastic/elasticsearch-hadoop#634]
Reported on the [forums](https://discuss.elastic.co/t/crash-when-es-hadoop-access-multiple-index-with-dataframe/37452).
```scala
import com.typesafe.config.{Config, ConfigFactory}
import org.apache.spark._
import org.apache.spark.SparkContext
import org.apache.spark.SparkContext._
import org.apache.spark.SparkConf
import org.apache.spark.sql.SQLContext
import org.apache.spark.sql.SQLContext._
import org.apache.spark.sql.Row
import org.apache.spark.sql.types.{StructType,StructField,StringType}
import scala.util.Try
import org.elasticsearch.spark.sql._

val sqlContext = new SQLContext(sc)
val tablename ="rtyan";
val querySql="select count(*) FROM rtyan limit 5";

//register table to sqlContext
val options = Map("pushdown" -> "true", "es.port" -> "9200")
val df=sqlContext.read.format("org.elasticsearch.spark.sql").options(options).load("rtyan1,rtyan2/rtyan")
df.registerTempTable(tablename)

//run sql statement with sqlContext
val ret=sqlContext.sql(querySql)
ret.show()
```
results in:

```
Exception in thread "dag-scheduler-event-loop" java.lang.OutOfMemoryError: GC overhead limit exceeded
    at org.elasticsearch.hadoop.rest.ShardSorter$PowerSet$1.get(ShardSorter.java:232)
    at org.elasticsearch.hadoop.rest.ShardSorter$PowerSet$1.get(ShardSorter.java:229)
    at org.elasticsearch.hadoop.rest.ShardSorter$ReverseIndexedListIterator.next(ShardSorter.java:339)
    at java.util.AbstractCollection.toArray(AbstractCollection.java:141)
    at java.util.ArrayList.<init>(ArrayList.java:164)
    at org.elasticsearch.hadoop.rest.ShardSorter.powerList(ShardSorter.java:202)
    at org.elasticsearch.hadoop.rest.ShardSorter.checkCombo(ShardSorter.java:89)
    at org.elasticsearch.hadoop.rest.ShardSorter.find(ShardSorter.java:85)
    at org.elasticsearch.hadoop.rest.RestRepository.doGetReadTargetShards(RestRepository.java:347)
    at org.elasticsearch.hadoop.rest.RestRepository.getReadTargetShards(RestRepository.java:290)
    at org.elasticsearch.hadoop.rest.RestService.findPartitions(RestService.java:252)
    at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions$lzycompute(AbstractEsRDD.scala:61)
    at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions(AbstractEsRDD.scala:60)
    at org.elasticsearch.spark.rdd.AbstractEsRDD.getPartitions(AbstractEsRDD.scala:27)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
    at scala.Option.getOrElse(Option.scala:120)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
    at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
    at scala.Option.getOrElse(Option.scala:120)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
    at org.apache.spark.rdd.MapPartitionsWithPreparationRDD.getPartitions(MapPartitionsWithPreparationRDD.scala:40)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
    at scala.Option.getOrElse(Option.scala:120)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
    at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
    at scala.Option.getOrElse(Option.scala:120)
```

**Comment by jicaiyan** [comment]
'rtyan' is an alias point to index 'rtyan1' and 'rtyan2'
it seems that when es-haddop access an alias that point to multiple indices, OOM appear,and i can not see any job on spark ui for this driver application,it seems that ES-HADOOP has already OOM before submit any job to spark cluster.
i will provide more detail information if needed

**Comment by costin** [comment]
@jicaiyan I fail to reproduce this problem. And looking at the stacktrace, it doesn't look like a traditional OOM - that is there are no runaway, nested calls that keep on eating memory - the error shows up right away which suggests that you are running the program under very tight memory.

I've tried the following code on ES 1.7 and 2.1.1 and in all cases it works just fine. In fact, it's part of the test suite (over 1800 tests):

```scala
val jsonDoc = """{"artist" : "buckethead", "album": "mirror realms" }"""
val index1 = wrapIndex("sparksql-multi-index-1/doc")
val index2 = wrapIndex("sparksql-multi-index-2/doc")
sc.makeRDD(Seq(jsonDoc)).saveJsonToEs(index1)
sc.makeRDD(Seq(jsonDoc)).saveJsonToEs(index2)
// refresh the index just in case
RestUtils.refresh(wrapIndex("sparksql-multi-index-1"))
RestUtils.refresh(wrapIndex("sparksql-multi-index-2"))
val multiIndex = wrapIndex("sparksql-multi-index-1,") + index2
// load the df
val df = sqc.read.format("es").load(multiIndex)
println(df.schema.treeString)
// take 10 items
df.show
// count it
println(df.count())
// do count as a selection
println(df.selectExpr("count(*)").show())
```

**Comment by costin** [comment]
Cannot reproduce and without a follow-up, closing the issue.

**Comment by elastic10** [comment]
Hello,
I have the same error, i needs help please!

**163654 [refresh-connections-timer] ERROR backtype.storm.daemon.worker - Error when processing event
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at backtype.storm.daemon.common$to_task__GT_node_PLUS_port$fn__1383$iter__1385__1389$fn__1390$fn__1391.invoke(common.clj:353) ~[storm-core-0.9.4.jar:0.9.4]
	at backtype.storm.daemon.common$to_task__GT_node_PLUS_port$fn__1383$iter__1385__1389$fn__1390.invoke(common.clj:353) ~[storm-core-0.9.4.jar:0.9.4]
	at clojure.lang.LazySeq.sval(LazySeq.java:42) ~[clojure-1.5.1.jar:na]
	at clojure.lang.LazySeq.seq(LazySeq.java:60) ~[clojure-1.5.1.jar:na]
	at clojure.lang.RT.seq(RT.java:484) ~[clojure-1.5.1.jar:na]
	at clojure.core$seq.invoke(core.clj:133) ~[clojure-1.5.1.jar:na]
	at clojure.core$concat$cat__3925$fn__3926.invoke(core.clj:687) ~[clojure-1.5.1.jar:na]
	at clojure.lang.LazySeq.sval(LazySeq.java:42) ~[clojure-1.5.1.jar:na]
	at clojure.lang.LazySeq.seq(LazySeq.java:67) ~[clojure-1.5.1.jar:na]
	at clojure.lang.ChunkedCons.chunkedNext(ChunkedCons.java:59) ~[clojure-1.5.1.jar:na]
	at clojure.core$chunk_next.invoke(core.clj:660) ~[clojure-1.5.1.jar:na]
	at clojure.core.protocols$fn__6041.invoke(protocols.clj:101) ~[clojure-1.5.1.jar:na]
	at clojure.core.protocols$fn__6005$G__6000__6014.invoke(protocols.clj:19) ~[clojure-1.5.1.jar:na]
	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31) ~[clojure-1.5.1.jar:na]
	at clojure.core.protocols$fn__6026.invoke(protocols.clj:54) ~[clojure-1.5.1.jar:na]
	at clojure.core.protocols$fn__5979$G__5974__5992.invoke(protocols.clj:13) ~[clojure-1.5.1.jar:na]
	at clojure.core$reduce.invoke(core.clj:6177) ~[clojure-1.5.1.jar:na]
	at clojure.core$into.invoke(core.clj:6229) ~[clojure-1.5.1.jar:na]
	at backtype.storm.daemon.common$to_task__GT_node_PLUS_port.invoke(common.clj:353) ~[storm-core-0.9.4.jar:0.9.4]
	at backtype.storm.daemon.worker$mk_refresh_connections$this__4568.invoke(worker.clj:268) ~[storm-core-0.9.4.jar:0.9.4]
	at backtype.storm.daemon.worker$mk_refresh_connections$this__4568.invoke(worker.clj:257) ~[storm-core-0.9.4.jar:0.9.4]
	at backtype.storm.timer$schedule_recurring$this__1647.invoke(timer.clj:99) ~[storm-core-0.9.4.jar:0.9.4]
	at backtype.storm.timer$mk_timer$fn__1630$fn__1631.invoke(timer.clj:50) ~[storm-core-0.9.4.jar:0.9.4]
	at backtype.storm.timer$mk_timer$fn__1630.invoke(timer.clj:42) [storm-core-0.9.4.jar:0.9.4]
	at clojure.lang.AFn.run(AFn.java:24) [clojure-1.5.1.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.7.0_85]**

**Comment by costin** [comment]
@elastic10 There's no ES-Hadoop code in your stacktrace (if I read it correctly). Also, please open up your own tickets in the future, commenting on tickets closed just because you found a couple of similar words is far from ideal.

**Comment by gaoshui87** [comment]
it is the erro of  powerList,when the set size is biiger than 20 (or the clouser node is more than 20 ).the  powerlist methor call the  set.toArray will case a oom .for the size of is  1 << set.size .
now i have some method to it.


  /**
     * 当把set 放到list里面时，会调用toArray，会调用size，然后一个一个进行对象的复制，这
     * 里的size 是  2 的set.size 次方，对象会很大
     * 如果set.size = 27 ,刚element有 134217728
     *
     *
     * slpit atMode 实时toArray的数据分片
     * @param <E>
     */
    private static class PowerSet<E> extends AbstractSet<Set<E>> {
        private final Map<E, Integer> input;
        private final List<E> elements;
        private final int split;//取这么多mode
        private final int atMode;// 余数
        PowerSet(Set<E> set) {
            this(set ,-1 ,0 );
        }

        PowerSet(Set<E> set ,int split ,int atMode) {
            Assert.isTrue(set.size() <= 30, "Too many elements to create a power set " + set.size());

            input = new LinkedHashMap<E, Integer>(set.size());
            this.split = split;
            this.atMode = atMode;
            int i = set.size();
            for (E e : set) {
                input.put(e, Integer.valueOf(i--));
            }
            elements =  new ArrayList<E>(input.keySet());
        }

        @Override
        public Iterator<Set<E>> iterator() {
            return new ReverseIndexedListIterator<Set<E>>(size()) {
                /**
                 * 当前的size的对应位置的index
                 * @param setBits
                 * @return
                 */
                @Override
                protected Set<E> get(final int setBits) {
                    return new SubSet<E>(input, setBits ,elements);
                }
            };
        }

        //这里往左移动 相当于1 往左移动了 input.size()  相当于  2 的 (input.size() -1) 次方
        @Override
        public int size() {
            return 1 << input.size();
        }

        @Override
        public boolean isEmpty() {
            return false;
        }

        @Override
        public boolean contains(Object o) {
            if (o instanceof Set) {
                Set<?> set = (Set<?>) o;
                return input.keySet().containsAll(set);
            }
            return false;
        }

        @Override
        public boolean equals(Object o) {
            if (o instanceof PowerSet) {
                PowerSet<?> that = (PowerSet<?>) o;
                return input.equals(that.input);
            }
            return super.equals(o);
        }
        @Override
        public int hashCode() {
            return input.keySet().hashCode() << (input.size() - 1);
        }

        /**
         * 下面进行复制对象的优化，进行数据的分片复制
         * @return
         */
        @Override
        public Object[] toArray() {
            // Estimate size of array; be prepared to see more or fewer elements
            int startEle = 0 ;
            int endEle  = 0;
            int eleLeng = 0;

            Object[] r ;
            if(split <= 0 ) {
                eleLeng = size();
                r = new Object[eleLeng];
                //拿所有的数据
                Iterator it = iterator();
                int eleIndex = 0;
                for (int i = 0; i <  eleLeng; i++) {
                    if (!it.hasNext()) // fewer elements than expected
                        return Arrays.copyOf(r, eleIndex);

                    r[eleIndex] = it.next();
                    eleIndex++;
                }
            } else {
                int perSplitEle = size() / split;
                startEle = perSplitEle * atMode;
                endEle =  perSplitEle * (atMode + 1)  ;
                if(atMode == split - 1 ){
                    endEle = size();
                }
                eleLeng = endEle - startEle;
                r = new Object[eleLeng];

                //进行截取区间数据
                ReverseIndexedListIterator it = (ReverseIndexedListIterator)iterator();
                int eleIndex = 0;
                for (int i = startEle; i <  endEle; i++) {
                    r[eleIndex] = it.get(i);
                    eleIndex++;
                }
            }

            return  r ;
        }
