### ISSUE TITLE
 org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: [GET] on [_nodes/http] failed; server[hostname/XXX.XXX.XXX.XXX:Ports] returned [400|Bad Request:]

### ISSUE THREAD

**Issue by gingi99** [elastic/elasticsearch-hadoop#638]
Hi. We have used elasticsearch 2.1.0 ver.

I use ela

```
$ /usr/local/share/spark/bin/pyspark --driver-class-path=elasticsearch-hadoop-2.1.2/dist/elasticsearch-spark-1.2_2.11-2.1.2.jar
<snip>
>>> conf = {"es.nodes" : "XXX.XXX.XXX.XXX:PortNo", "es.resource" : "INDEX/TYPE"}
>>> rdd = sc.newAPIHadoopRDD("org.elasticsearch.hadoop.mr.EsInputFormat","org.apache.hadoop.io.NullWritable", "org.elasticsearch.hadoop.mr.LinkedMapWritable", conf=conf)
<snip>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/share/spark/python/pyspark/context.py", line 621, in newAPIHadoopRDD
    jconf, batchSize)
  File "/usr/local/share/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
  File "/usr/local/share/spark/python/pyspark/sql/utils.py", line 36, in deco
    return f(*a, **kw)
  File "/usr/local/share/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 300, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.newAPIHadoopRDD.
: org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: [GET] on [_nodes/http] failed; server[hostname/XXX.XXX.XXX.XXX:Ports] returned [400|Bad Request:]
	at org.elasticsearch.hadoop.rest.RestClient.checkResponse(RestClient.java:427)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:385)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:363)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:367)
	at org.elasticsearch.hadoop.rest.RestClient.get(RestClient.java:121)
	at org.elasticsearch.hadoop.rest.RestClient.getHttpDataNodes(RestClient.java:336)
	at org.elasticsearch.hadoop.rest.InitializationUtils.filterNonDataNodesIfNeeded(InitializationUtils.java:121)
	at org.elasticsearch.hadoop.rest.RestService.findPartitions(RestService.java:233)
	at org.elasticsearch.hadoop.mr.EsInputFormat.getSplits(EsInputFormat.java:457)
	at org.elasticsearch.hadoop.mr.EsInputFormat.getSplits(EsInputFormat.java:438)
	at org.apache.spark.rdd.NewHadoopRDD.getPartitions(NewHadoopRDD.scala:115)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.RDD$$anonfun$take$1.apply(RDD.scala:1281)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:310)
	at org.apache.spark.rdd.RDD.take(RDD.scala:1276)
	at org.apache.spark.api.python.SerDeUtil$.pairRDDToPython(SerDeUtil.scala:202)
	at org.apache.spark.api.python.PythonRDD$.newAPIHadoopRDD(PythonRDD.scala:530)
	at org.apache.spark.api.python.PythonRDD.newAPIHadoopRDD(PythonRDD.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:207)
	at java.lang.Thread.run(Thread.java:745)
```

I don't know what to do.

**Comment by ebuildy** [comment]
Hello, I believe elasticsearch-hadoop 2.1 is not compatible with ES 2.1, you should use the elasticsearch-hadoop 2.2-beta for that.

**Comment by gingi99** [comment]
Sorry. I have used "elasticsearch-hadoop 2.2-beta1". However, I happened this error. What should I do ?

**Comment by gingi99** [comment]
I'm sorry. I solved it myself. The cause was the network settings on our Elasticsearch. Thanks.

**Comment by ufo22940268** [comment]
@gingi99 
How i face the same problem. Could you tell me what's wrong with network settings.

**Comment by ebuildy** [comment]
@ufo22940268 use forum to describe your settings / configuration, I'll be glad to help you.
