### ISSUE TITLE
'org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: No data nodes with HTTP-enabled available' on AWS Elasticsearch connection

### ISSUE THREAD

**Issue by shamak** [elastic/elasticsearch-hadoop#660]
Elasticsearch on AWS has a URL of the form 'https://example.com' with no port specified. Using Apache pig to configure the cluster URL as shown:

`STORE foo INTO 'bar/baz' USING org.elasticsearch.hadoop.pig.EsStorage('es.nodes=https://example.com');`

The stack trace is shown below:
```
Caused by: org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: No data nodes with HTTP-enabled available at org.elasticsearch.hadoop.rest.InitializationUtils.filterNonDataNodesIfNeeded(InitializationUtils.java:123)
	at org.elasticsearch.hadoop.rest.RestService.createWriter(RestService.java:378)
	at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.init(EsOutputFormat.java:173)
	at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.write(EsOutputFormat.java:149)
	at org.elasticsearch.hadoop.pig.EsStorage.putNext(EsStorage.java:192)
```
Any idea on what I should be doing to resolve this? Or is this a bug?

**Comment by costin** [comment]
Are you using the [wan/cloud](https://www.elastic.co/guide/en/elasticsearch/hadoop/master/cloud.html) feature?
The issue is very cryptic, please provide more information as mentioned [here](https://www.elastic.co/guide/en/elasticsearch/hadoop/master/troubleshooting.html). 
Also for help, it's best to use the [forum](http://discuss.elastic.co) rather than the issue tracker as the former has more eyes available.

**Comment by shamak** [comment]
No, the cluster is accessible to the specific IP. The issue is simple, the elasticsearch-hadoop plugin when used in a pig script cannot connect to the AWS Elasticsearch cluster. What version of elasticsearch-hadoop library should I be using?

**Comment by shamak** [comment]
Looks like I was using the stable version 2.1.2, I switched to 2.2.0 daily build and got the error for the URL https://example.com.

`org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot resolve ip for hostname: example.com
	at org.elasticsearch.hadoop.util.SettingsUtils.resolveHostToIpIfNecessary(SettingsUtils.java:78)
	at org.elasticsearch.hadoop.util.SettingsUtils.qualifyNodes(SettingsUtils.java:40)
	at org.elasticsearch.hadoop.util.SettingsUtils.declaredNodes(SettingsUtils.java:118)
	at org.elasticsearch.hadoop.util.SettingsUtils.discoveredOrDeclaredNodes(SettingsUtils.java:124)
	at org.elasticsearch.hadoop.rest.NetworkClient.<init>(NetworkClient.java:58)
	at org.elasticsearch.hadoop.rest.RestClient.<init>(RestClient.java:84)
	at org.elasticsearch.hadoop.rest.InitializationUtils.discoverEsVersion(InitializationUtils.java:174)
	at org.elasticsearch.hadoop.rest.RestService.createWriter(RestService.java:378)
	at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.init(EsOutputFormat.java:173)
	at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.write(EsOutputFormat.java:149)
	at org.elasticsearch.hadoop.pig.EsStorage.putNext(EsStorage.java:192)`

This is the part of the code that is resolving the IP. You should be resolving the IP based on the entire URL (https://example.com) and not on the sliced URL (example.com) only. I can't really submit a pull request right now but if you could put in a quick fix it would be appreciated. 

`private static String resolveHostToIpIfNecessary(String host) {
        String schemaDelimiter = "://";
        String schema = StringUtils.EMPTY;

        if (host.contains(schemaDelimiter)) {
            int index = host.indexOf(schemaDelimiter);
            schema = host.substring(0, index);
            host = host.substring(index + schemaDelimiter.length());
        }
        int index = host.lastIndexOf(':');
        String name = index > 0 ? host.substring(0, index) : host;
        // if the port is specified, include the ":"
        String port = index > 0 ? host.substring(index) : "";
        if (StringUtils.hasLetter(name)) {
            try {
                String hostAddress = InetAddress.getByName(name).getHostAddress() + port;
                return StringUtils.hasText(schema) ? schema + schemaDelimiter + hostAddress : hostAddress;
            } catch (UnknownHostException ex) {
                throw new EsHadoopIllegalArgumentException("Cannot resolve ip for hostname: " + name);
            }
        }
        return host;
    }`

**Comment by costin** [comment]
```
You should be resolving the IP based on the entire URL (https://example.com) and not on the sliced URL (example.com) only
```
No. A hostname is a DNS alias that points to an IP. The fact that you use one protocol or the other, indicates the service/port to use not the host.

**Comment by costin** [comment]
P.S. I've updated your posts to add proper formatting. Please use \`\`\` instead of ` when posting snippets of code (see the markdown code).

**Comment by shamak** [comment]
Cool. Any idea why it's unable to resolve the hostname then?

**Comment by costin** [comment]
You haven't provided any useful information (see the link above) so this is just guessing.
If you'd pay attention to your job logs likely you should see the machine that is actually trying to connect to the host. Make sure that one can actually resolve the hostname or potentially try using the IP directly and see whether it makes any difference.

`tracert`/`traceroute` and `ping` are useful (among other tools).

**Comment by shamak** [comment]
Ok. So I tried using the IP now, and it gives me:

``` 
2016-01-14 09:49:13,334 [Thread-3] INFO  org.apache.commons.httpclient.HttpMethodDirector - I/O exception (java.net.ConnectException) caught when processing request: Connection timed out
2016-01-14 09:49:13,335 [Thread-3] INFO  org.apache.commons.httpclient.HttpMethodDirector - Retrying request
```
I can definitely access the IP from the browser when I send a HTTP request to it or even curl it. Why would I get a connection timed out request?

**Comment by costin** [comment]
The author moved the discussion to the [forum](https://discuss.elastic.co/t/unable-to-connect-to-es-cluster-on-aws-elasticsearch-service-through-hadoop/39283)
