### ISSUE TITLE
Running in Kerberized Hadoop clusters doesn't seem to be supported...

### ISSUE THREAD

**Issue by BrianGallew** [elastic/elasticsearch-hadoop#669]
... or at least is not documented.  Below is the relevant error.  I have fresh credentials, and used the to successfully run a number of jobs both before and after this failure.

```
java.io.IOException: Failed on local exception: java.io.IOException: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]; Host Details : local host is: "redacted/redacted"; destination host is: "redactedt":8020; 
    at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:772)
    at org.apache.hadoop.ipc.Client.call(Client.java:1472)
    at org.apache.hadoop.ipc.Client.call(Client.java:1399)
    at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:232)
    at com.sun.proxy.$Proxy15.getFileInfo(Unknown Source)
    at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.getFileInfo(ClientNamenodeProtocolTranslatorPB.java:752)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187)
    at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
    at com.sun.proxy.$Proxy16.getFileInfo(Unknown Source)
    at org.apache.hadoop.hdfs.DFSClient.getFileInfo(DFSClient.java:1982)
    at org.apache.hadoop.hdfs.DistributedFileSystem$18.doCall(DistributedFileSystem.java:1128)
    at org.apache.hadoop.hdfs.DistributedFileSystem$18.doCall(DistributedFileSystem.java:1124)
    at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81)
    at org.apache.hadoop.hdfs.DistributedFileSystem.getFileStatus(DistributedFileSystem.java:1124)
    at org.elasticsearch.hadoop.yarn.am.EsCluster.setupEsZipResource(EsCluster.java:236)
    at org.elasticsearch.hadoop.yarn.am.EsCluster.launchContainer(EsCluster.java:195)
    at org.elasticsearch.hadoop.yarn.am.EsCluster.start(EsCluster.java:119)
    at org.elasticsearch.hadoop.yarn.am.ApplicationMaster.run(ApplicationMaster.java:79)
    at org.elasticsearch.hadoop.yarn.am.ApplicationMaster.main(ApplicationMaster.java:104)
```

**Comment by costin** [comment]
I assume you are referring to the YARN integration.
As long as the Kerberos configuration (typically through a hadoop `Configuration`) is passed, it should be picked up automatically.
How do you typically configure your other jobs/commands?

**Comment by BrianGallew** [comment]
kinit
hadoop jar ...

I've never had to actually configure a job for Kerberos.

**Comment by jbaiera** [comment]
The Application Master requires access to HDFS in order to stat the elasticsearch distributable for properties to hand to YARN when launching containers. When launching a YARN application with security, YARN captures the user information of the submitter and runs the containers as that user. Because of this, where ever the Application Master container lands on the cluster requires to have a valid Kerberos TGT for the user creating the cluster.

I would suggest a best practice of creating a user account specifically to own the started Elasticsearch cluster processes. Creating a keytab for this account and distributing it to the available NodeManagers would allow for passwordless login through Kerberos. At the moment, the Application Master does not attempt logging in with a keytab when Kerberos is enabled, rather, it defaults to Hadoop's default Kerberos authentication method, which is to search for an available TGT in the current user's local ticket cache.

A work around for this is to run something like a cron job on the elasticsearch user to regularly kinit or to use other tooling like the Stanford k5start daemon to keep valid TGT's in the ticket cache. The Application Master would then have access to Kerberos authentication on any node.

In the long run we might want to add a keytab login on the Application Master for users to configure. Supporting token authentication is another possibility, but it seems much more complex to implement compared to the relatively simple keytab login.

I'll try and condense this research down for an update to the documentation, and I'll open another issue to discuss the aforementioned keytab stuff.

**Comment by robinisme2** [comment]
Hi, @jbaiera
I met the same problem, and I am not quite realize how to implement your suggestion.

'I would suggest a best practice of creating a user account specifically to own the started Elasticsearch cluster processes. Creating a keytab for this account and distributing it to the available NodeManagers would allow for passwordless login through Kerberos. At the moment, the Application Master does not attempt logging in with a keytab when Kerberos is enabled, rather, it defaults to Hadoop's default Kerberos authentication method, which is to search for an available TGT in the current user's local ticket cache.'

Could you take an example step by step to elaborate this section?

Thanks.

**Comment by jbaiera** [comment]
Closing this as the ES-on-YARN Beta is now deprecated and will be removed in 6.0
