### ISSUE TITLE
java.lang.ClassNotFoundException: org.elasticsearch.spark.rdd.EsPartition

### ISSUE THREAD

**Issue by nirajpatel** [elastic/elasticsearch-hadoop#692]
When running a Spring boot application locally my job executes properly and completes; however, whenever I tried to submit my job to a Spark cluster from my laptop (by setting *master* to "spark://...") my job throws the following:

```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 0.0 failed 4 times, most recent failure: Lost task 2.3 in stage 0.0 (TID 20, asthad101.wvrgroup.internal): java.lang.ClassNotFoundException: org.elasticsearch.spark.rdd.EsPartition
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.serializer.JavaDeserializationStream$$anon$1.resolveClass(JavaSerializer.scala:65)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1613)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2000)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1924)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:68)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:94)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:185)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1204) ~[api-refresh-1.0-SNAPSHOT.jar:na]
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1193) ~[api-refresh-1.0-SNAPSHOT.jar:na]
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1192) ~[api-refresh-1.0-SNAPSHOT.jar:na]
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59) ~[api-refresh-1.0-SNAPSHOT.jar:na]
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47) ~[api-refresh-1.0-SNAPSHOT.jar:na]
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1192) ~[api-refresh-1.0-SNAPSHOT.jar:na]
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:693) ~[api-refresh-1.0-SNAPSHOT.jar:na]
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:693) ~[api-refresh-1.0-SNAPSHOT.jar:na]
	at scala.Option.foreach(Option.scala:236) ~[api-refresh-1.0-SNAPSHOT.jar:na]
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:693) ~[api-refresh-1.0-SNAPSHOT.jar:na]
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1393) ~[api-refresh-1.0-SNAPSHOT.jar:na]
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1354) ~[api-refresh-1.0-SNAPSHOT.jar:na]
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48) ~[api-refresh-1.0-SNAPSHOT.jar:na]
```

I checked my jar's unzipped class list and it has EsPartition.class. Not sure where the issue lies. Any ideas?

**Comment by costin** [comment]
When deploying on a remote system one needs to supply/provision the dependencies as well since otherwise the remote VM won't have them in the classpath which results in CNFE.
The spark [documentation](http://spark.apache.org/docs/latest/) provides more information.

**Comment by nobitataj** [comment]
I had the same issue and found out the problem is that you need to include your jar file when execute the task, either by passing it as a parameter for spark-submit, or by setting SparkConf.setJar()
