### ISSUE TITLE
both log4j-over-slf4j.jar AND slf4j-log4j12.jar on the class path

### ISSUE THREAD

**Issue by bsideup** [elastic/elasticsearch-hadoop#704]
**build.gradle**
```gradle
apply plugin: "java"


repositories {
    jcenter()
}

dependencies {
    compile 'org.elasticsearch:elasticsearch-hadoop:2.2.0'
}
```

Empty app with Java context throws:

```
SLF4J: Detected both log4j-over-slf4j.jar AND slf4j-log4j12.jar on the class path, preempting StackOverflowError. 
SLF4J: See also http://www.slf4j.org/codes.html#log4jDelegationLoop for more details.
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.apache.log4j.LogManager.getRootLogger(LogManager.java:40)
	at org.apache.spark.Logging$class.initializeLogging(Logging.scala:121)
	at org.apache.spark.Logging$class.initializeIfNecessary(Logging.scala:106)
	at org.apache.spark.Logging$class.log(Logging.scala:50)
	at org.apache.spark.SparkContext.log(SparkContext.scala:79)
	at org.apache.spark.Logging$class.logInfo(Logging.scala:58)
	at org.apache.spark.SparkContext.logInfo(SparkContext.scala:79)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:211)
	at org.apache.spark.api.java.JavaSparkContext.<init>(JavaSparkContext.scala:59)
	at SparkTest.main(SparkTest.java:11)
Caused by: java.lang.IllegalStateException: Detected both log4j-over-slf4j.jar AND slf4j-log4j12.jar on the class path, preempting StackOverflowError. See also http://www.slf4j.org/codes.html#log4jDelegationLoop for more details.
	at org.apache.log4j.Log4jLoggerFactory.<clinit>(Log4jLoggerFactory.java:49)
	... 10 more
```

**Comment by costin** [comment]
Unfortunately there's not much ES-Hadoop can do here. It doesn't depend on these libraries which are actually pulled in by its runtime dependencies (in particular Storm which pulls in log4j-over-slf4j.jar).
Further more the dependencies themselves are [marked at optional](https://repo1.maven.org/maven2/org/elasticsearch/elasticsearch-hadoop/2.2.0/elasticsearch-hadoop-2.2.0.pom), which likely indicates the tool you are using (Spark's I assume) is too gready.

A quick alternative to this is to simply use the dedicated spark package (elasticsearch-spark) instead of the whole library (elasticsearch-hadoop). Notice you can find it as a spark package [as well](http://spark-packages.org/package/elastic/elasticsearch-hadoop)

**Comment by halilduygulu** [comment]
For googlers, you can just add this exclude one of them. 

`"org.elasticsearch" % "elasticsearch-spark-20_2.10" % "5.2.2"`
   ` exclude ("org.slf4j", "log4j-over-slf4j")`
