### ISSUE TITLE
Unable to add repository settings in elasticsearch.yml 

### ISSUE THREAD

**Issue by srini-daruna** [elastic/elasticsearch-hadoop#705]
I have installed hadoop-hdfs plugin and added the following configuration in elasticsearch.yml.

repositories
  hdfs:
    uri: "hdfs://localhost>:9000/"
    path: "user/config"
    load_defaults: "true"
    conf_location: "extra-cfg.xml"
    concurrent_streams: 5
    compress: "false"
    chunk_size: "10mb"

I got the below error. 

Srinivasaraos-MacBook-Pro:bin srini$ ./elasticsearch
Exception in thread "main" SettingsException[Failed to load settings from [elasticsearch.yml]]; nested: ParserException[while parsing a block mapping
 in 'reader', line 17, column 1:
    cluster.name: elk_test
    ^
expected <block end>, but found BlockMappingStart
 in 'reader', line 21, column 3:
      hdfs:
      ^
];
Likely root cause: while parsing a block mapping
 in 'reader', line 17, column 1:
    cluster.name: elk_test
    ^
expected <block end>, but found BlockMappingStart
 in 'reader', line 21, column 3:
      hdfs:
      ^

	at com.fasterxml.jackson.dataformat.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:570)
	at com.fasterxml.jackson.dataformat.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158)
	at com.fasterxml.jackson.dataformat.yaml.snakeyaml.parser.ParserImpl.getEvent(ParserImpl.java:168)
	at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:342)
	at org.elasticsearch.common.xcontent.json.JsonXContentParser.nextToken(JsonXContentParser.java:53)
	at org.elasticsearch.common.settings.loader.XContentSettingsLoader.serializeObject(XContentSettingsLoader.java:99)
	at org.elasticsearch.common.settings.loader.XContentSettingsLoader.load(XContentSettingsLoader.java:67)
	at org.elasticsearch.common.settings.loader.XContentSettingsLoader.load(XContentSettingsLoader.java:45)
	at org.elasticsearch.common.settings.loader.YamlSettingsLoader.load(YamlSettingsLoader.java:46)
	at org.elasticsearch.common.settings.Settings$Builder.loadFromStream(Settings.java:1074)
	at org.elasticsearch.common.settings.Settings$Builder.loadFromPath(Settings.java:1061)
	at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:88)
	at org.elasticsearch.common.cli.CliTool.<init>(CliTool.java:107)
	at org.elasticsearch.common.cli.CliTool.<init>(CliTool.java:100)
	at org.elasticsearch.bootstrap.BootstrapCLIParser.<init>(BootstrapCLIParser.java:48)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:241)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details.

**Comment by srini-daruna** [comment]
It was my fault. I missed colon after repositories

**Comment by volcano619** [comment]
Hi,i'm getting the same error and i haven't configured the yml yet.Is it necessary to configure the YML ??
