### ISSUE TITLE
Output as raw json fails in case a document has empty source

### ISSUE THREAD

**Issue by andreybratus** [elastic/elasticsearch-hadoop#723]
### Issue description
When output is configured to be in JSON format **(es.output.json=true)** and at least one document in the index appears with an empty "_source" the scroll fails.

### Steps to reproduce
I added one more test case in `org.elasticsearch.hadoop.serialization.ValueReaderTest`
and modified the `./mr/src/test/resources/org/elasticsearch/hadoop/serialization/scroll-test.json` to have one document with empty source.

```java
import java.io.InputStream;

import org.elasticsearch.hadoop.serialization.ScrollReader.ScrollReaderConfig;
import org.elasticsearch.hadoop.serialization.builder.JdkValueReader;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

public class ValueReaderTest {

    private InputStream in;

    @Before
    public void before() throws Exception {
        in = getClass().getResourceAsStream("scroll-test-empty-source.json");
    }

    @After
    public void after() throws Exception {
        in.close();
    }

    @Test
    public void testSimplePathReader() throws Exception {
        ScrollReader reader = new ScrollReader(new ScrollReaderConfig(new JdkValueReader()));
        reader.read(in);
    }

    @Test
    public void testSimplePathReaderJson() throws Exception {
        ScrollReaderConfig config = new ScrollReaderConfig(new JdkValueReader());
        config.returnRawJson = true;
        ScrollReader reader = new ScrollReader(config);
        reader.read(in);
    }
}
```

Strack trace:

```
org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: expected object, found FIELD_NAME

	at org.elasticsearch.hadoop.util.Assert.isTrue(Assert.java:50)
	at org.elasticsearch.hadoop.serialization.ScrollReader.readHit(ScrollReader.java:381)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:277)
	at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:250)
	at org.elasticsearch.hadoop.serialization.ValueReaderTest.testSimplePathReaderJson(ValueReaderTest.java:54)
``` 

### Version Info

OS:         :  OSX
JVM         :  Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
ES-Hadoop   :  elasticsearch-hadoop:2.2.0

**Comment by costin** [comment]
Thanks for reporting and providing the reproducing test (and PR).

P.S. By the way, your Java version is kinda a old; consider upgrading to the latest update.
