### ISSUE TITLE
EsTap 2.2.0 local scheme not respecting passed server/port when using empty Properties

### ISSUE THREAD

**Issue by duobrien** [elastic/elasticsearch-hadoop#735]
### What kind an issue is this?

- [x] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

EsTap is defaulting to localhost:9200 when I pass an empty Properties, and **does not respect the port that I pass directly to the constructor**.  It seems CascadingUtils.addDefaultsToSettings calls InitializationUtils.discoverEsVersion in a manner that does not pass the server/port as specified in the EsTap constructor.  Using 2.2.0.

### Steps to reproduce

1.  Setup an Elastic instance running locally on port 9900 instead of 9200.
2.  Create the Input File specified below, and run the code below against it.  You will see the following exception indicating it is trying to connect to port 9200 -- which happens to be the fallback/default in the code.  The bug is that it's ignoring port 9900.

Code:

    public static void main(String[] args) {
        String fileName="/Users/duobrien/data/repro.csv";

        // Create the input tap bringing this into Cascading using a FileTap
        Tap inTap = new FileTap(new TextDelimited(true, ","), fileName);
        Pipe headPipe = new Pipe("inTapToElasticPipe");
        Tap elasticOutTap = new EsTap("localhost", 9900,"myindex/mytype",Fields.ALL);

        FlowDef theFlowDef = FlowDef.flowDef()
            .setName("InTapToElasticFlow")
            .addSource(headPipe, inTap)
            .addTailSink(headPipe, elasticOutTap);

        Properties properties = new Properties();
        AppProps.setApplicationJarClass(properties, ElasticPlayground.class);
        FlowConnector flowConnector = new LocalFlowConnector(properties);
        Flow theFlow = flowConnector.connect(theFlowDef);
        theFlow.complete();
    }

Input File: HA001054:~ duobrien$ cat ~/data/repro.csv 
a,b,c
1,2,3

Strack trace:

646  [main] INFO  cascading.property.AppProps - using app.id: C0EE8B5D3FFA462398C9180D4C8C77A7
678  [main] INFO  org.elasticsearch.hadoop.cascading.EsTap - Elasticsearch Hadoop v2.2.0 [c11e37bde9] initialized
1281 [main] INFO  org.apache.commons.httpclient.HttpMethodDirector - I/O exception (java.net.ConnectException) caught when processing request: Connection refused
1281 [main] INFO  org.apache.commons.httpclient.HttpMethodDirector - Retrying request
1282 [main] INFO  org.apache.commons.httpclient.HttpMethodDirector - I/O exception (java.net.ConnectException) caught when processing request: Connection refused
1282 [main] INFO  org.apache.commons.httpclient.HttpMethodDirector - Retrying request
1282 [main] INFO  org.apache.commons.httpclient.HttpMethodDirector - I/O exception (java.net.ConnectException) caught when processing request: Connection refused
1282 [main] INFO  org.apache.commons.httpclient.HttpMethodDirector - Retrying request
1284 [main] ERROR org.elasticsearch.hadoop.rest.NetworkClient - Node [127.0.0.1:9200] failed (Connection refused); no other nodes left - aborting...
Exception in thread "main" cascading.flow.planner.PlannerException: could not build flow from assembly: [Connection error (check network and/or proxy settings)- all nodes failed; tried [[127.0.0.1:9200]] ]
	at cascading.flow.planner.FlowPlanner.handleExceptionDuringPlanning(FlowPlanner.java:590)
	at cascading.flow.local.planner.LocalPlanner.buildFlow(LocalPlanner.java:108)
	at cascading.flow.local.planner.LocalPlanner.buildFlow(LocalPlanner.java:40)
	at cascading.flow.FlowConnector.connect(FlowConnector.java:459)
	at com.homeaway.bigdata.proctor.ElasticPlayground.main(ElasticPlayground.java:71)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: org.elasticsearch.hadoop.rest.EsHadoopNoNodesLeftException: Connection error (check network and/or proxy settings)- all nodes failed; tried [[127.0.0.1:9200]] 
	at org.elasticsearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:142)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:423)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:403)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:407)
	at org.elasticsearch.hadoop.rest.RestClient.get(RestClient.java:114)
	at org.elasticsearch.hadoop.rest.RestClient.esVersion(RestClient.java:553)
	at org.elasticsearch.hadoop.rest.InitializationUtils.discoverEsVersion(InitializationUtils.java:177)
	at org.elasticsearch.hadoop.cascading.CascadingUtils.addDefaultsToSettings(CascadingUtils.java:63)
	at org.elasticsearch.hadoop.cascading.EsLocalScheme.initClient(EsLocalScheme.java:140)
	at org.elasticsearch.hadoop.cascading.EsLocalScheme.sinkConfInit(EsLocalScheme.java:134)
	at org.elasticsearch.hadoop.cascading.EsLocalScheme.sinkConfInit(EsLocalScheme.java:50)
	at cascading.tap.Tap.sinkConfInit(Tap.java:206)
	at org.elasticsearch.hadoop.cascading.EsTap.sinkConfInit(EsTap.java:134)
	at cascading.flow.local.LocalFlowStep.initTaps(LocalFlowStep.java:75)
	at cascading.flow.local.LocalFlowStep.getInitializedConfig(LocalFlowStep.java:57)
	at cascading.flow.local.LocalFlowStep.createFlowStepJob(LocalFlowStep.java:135)
	at cascading.flow.local.LocalFlowStep.createFlowStepJob(LocalFlowStep.java:38)
	at cascading.flow.planner.BaseFlowStep.getFlowStepJob(BaseFlowStep.java:829)
	at cascading.flow.BaseFlow.initializeNewJobsMap(BaseFlow.java:1239)
	at cascading.flow.BaseFlow.initialize(BaseFlow.java:214)
	at cascading.flow.local.planner.LocalPlanner.buildFlow(LocalPlanner.java:102)
	... 8 more

Process finished with exit code 1

### Version Info

OS:         :  Mac OSX
JVM         :  Oracle JDK 1.8 latest
Hadoop/Spark:  n/a running local
ES-Hadoop   :  2.2.0
ES          :  1.7.2, but I bet it happens with any ES version

**Comment by costin** [comment]
Thanks. Fixed in master and 2.2

**Comment by duobrien** [comment]
Thanks Costin - amazingly quick turnaround!
