### ISSUE TITLE
Read failure when index/alias spread among 32 or more nodes.

### ISSUE THREAD

**Issue by hronik1** [elastic/elasticsearch-hadoop#737]
### What kind an issue is this?
- [x] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.  
  The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
  Often a solution already exists! Don’t send pull requests to implement new features without 
  first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

Description

Attempting to perform a read operation accross an alias which is spread across 54 shards. On previous versions of elasticsearch(1.3.4) and elasticsear-hadoop jars(2.1.1), it would work fine, however it broke with the below error after performing an an elasticsearch and elasticsearch-hadoop upgrade to 2.1.1 and 2.2.0, respectively:

'Too many elements to create a power set 54'.

This error seems to pop up from the constructor of the PowerSet class in https://github.com/elastic/elasticsearch-hadoop/blob/2.x/mr/src/main/java/org/elasticsearch/hadoop/rest/ShardSorter.java.
### Steps to reproduce
- Create a 2.x Elasticsearch cluster, and create an index with shards that spans more than 32 nodes.
- Execute a read query using the elasticsearch-hadoop plugin, that will span across all of those nodes("match_all" would be easiest).
### Stack Trace

Exception in thread "main" org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Too many elements to create a power set 54
    at org.elasticsearch.hadoop.util.Assert.isTrue(Assert.java:50)
    at org.elasticsearch.hadoop.rest.ShardSorter$PowerSet.<init>(ShardSorter.java:218)
    at org.elasticsearch.hadoop.rest.ShardSorter.powerList(ShardSorter.java:202)
    at org.elasticsearch.hadoop.rest.ShardSorter.checkCombo(ShardSorter.java:89)
    at org.elasticsearch.hadoop.rest.ShardSorter.find(ShardSorter.java:85)
    at org.elasticsearch.hadoop.rest.RestRepository.doGetReadTargetShards(RestRepository.java:352)
    at org.elasticsearch.hadoop.rest.RestRepository.getReadTargetShards(RestRepository.java:295)
    at org.elasticsearch.hadoop.rest.RestService.findPartitions(RestService.java:253)
    at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions$lzycompute(AbstractEsRDD.scala:61)
    at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions(AbstractEsRDD.scala:60)
    at org.elasticsearch.spark.rdd.AbstractEsRDD.getPartitions(AbstractEsRDD.scala:27)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
    at scala.Option.getOrElse(Option.scala:120)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
    at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
### Version Info

Hadoop/Spark:  15.1
ES-Hadoop   :  2.2.0
ES          :  2.1.1

**Comment by costin** [comment]
The check is correct - the problem with powersets is that they are extremely large. So even if a combination can be found, one cannot go through the entire powerset.
52 shards means 2^52 combinations - more than it can fit into an integer... I guess one option would be to limit the size to 32 and try only those combinations on all 52 shards.

Without a correct combination algorithm, duplicates can result.

**Comment by hronik1** [comment]
I understand that assertion is to limit the size of the powerset.

However, what isn't so clear is why the powerset, and more generally, sorting of the shards is needed to prevent duplication in the first place. I can curl a match_all(with size > 32) query against the same alias on the same cluster, so it isn't immediately obvious why the duplication problem is present(or at least accounted for) within the elasticsearch-hadoop jar, but not when querying elasticsearch directly.

**Comment by costin** [comment]
It's because ES-Hadoop does parallel queries and when dealing with aliases it needs to avoid duplicates due to limitations to the ES REST API. See #363

**Comment by hronik1** [comment]
Yeah, I was taking a look at that issue before opening this issue. It looks like if issue https://github.com/elastic/elasticsearch/issues/9483 would have gotten through(which seems to have gotten closed in favor of issue https://github.com/elastic/elasticsearch/issues/13494), then the powerset solution would no longer be needed. Am I correct in my understanding?

I was able to get a workaround implemented, where I do a reverse lookup from alias to indices using the '/_alias' endpoint, issue the query to each index individually and then combine the results. I believe this is only a possible workaround since each index spans less than 32 nodes, though.

**Comment by costin** [comment]
relates #778 - hopefully once this gets in, this bug will be fully addressed.

**Comment by burtonator** [comment]
ETA on this? Franky this makes this completely unusable for us in production?  If you have a large cluster having 54 shards is going to happen almost immediately? 

Using a powerset is the only algorithm solution to this problem?  

Fixed in 5.x?

**Comment by jimferenczi** [comment]
@burtonator this should be fixed on 5.x since we remove the powerset stuff. You can **test** with alpha5: https://www.elastic.co/downloads/hadoop, this is not for production but at least you'll be able to confirm that your use case is solved ?

**Comment by jbaiera** [comment]
Closing this as there has been no further feedback.
