### ISSUE TITLE
PROBLEM: Failed to write data back to ES by using Spark DataFrame save() API !!

### ISSUE THREAD

**Issue by patricklu** [elastic/elasticsearch-hadoop#749]
### Issue description
No problem on reading data from ES and return a DataFrame RDD (df). 
But failed to write the df back to ES.
An error complains "Index already exists". 
But the same index has no issue adding new docs by using elasticsearch-py

### Environment:
    CentOS 7
    openjdk "1.8.0_77"
    Spark 1.6, standalone cluster.
    PySpark (1.6)
    ElasticSearch 2.2.0
    elasticsearch-hadoop-2.2.0.jar

### Code stage 1 -- load data from ES -- work fine

from pyspark import SparkContext, SparkConf
from pyspark.sql import SQLContext

conf = SparkConf()
conf.set("es.nodes", "10.202.241.45:9200")

sc = SparkContext(conf=conf)
sqlContext = SQLContext(sc)
    
df = sqlContext.read\
    .option("es.resource", "test-index")\
    .format("org.elasticsearch.spark.sql")\
    .load()
df.show()

### Code stage 1 -- output -- work fine
+------+-------+---------+-----------+-----------+---------+--------------------+
|iCount|iUrlCat|sClientIP|sDeviceName|sDomainName|sUserName|          tTimeStamp|
+------+-------+---------+-----------+-----------+---------+--------------------+
|   100|      4|  1.2.3.4|        ABC|  yahoo.com|    Sarah|2014-08-08 22:20:...|
|   100|      4|  1.2.3.4|        ABC|  yahoo.com|    Sarah|2014-08-08 22:20:...|
|   100|      4|  1.2.3.4|        ABC|  yahoo.com|    Sarah|2014-08-08 22:20:...|
|   100|      4|  1.2.3.4|        ABC|  yahoo.com|    Sarah|2014-08-08 22:20:...|
+------+-------+---------+-----------+-----------+---------+--------------------+

### Code stage 2 -- write the df back to the ES.
df.write.save("test-index", format="org.elasticsearch.spark.sql")
==> Throw exception (see below)

### Stack trace,
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/spark/python/pyspark/sql/readwriter.py", line 387, in save
    self._jwrite.save(path)
  File "/usr/local/spark/python/lib/py4j-0.9-src.zip/py4j/java_gateway.py", line 813, in __call__
  File "/usr/local/spark/python/pyspark/sql/utils.py", line 45, in deco
    return f(*a, **kw)
  File "/usr/local/spark/python/lib/py4j-0.9-src.zip/py4j/protocol.py", line 308, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o1327.save.
: org.elasticsearch.hadoop.EsHadoopIllegalStateException: Index test-index already exists
        at org.elasticsearch.spark.sql.DefaultSource.createRelation(DefaultSource.scala:76)
        at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:222)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:148)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:139)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
        at py4j.Gateway.invoke(Gateway.java:259)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:209)
        at java.lang.Thread.run(Thread.java:745)

### Index mapping in the ES
curl -i -XPUT http://10.202.241.45:9200/_template/tmpl-test?pretty -d '{
    "template" : "test*",
     "mappings" : {
        "test" : {
             "dynamic" : "strict",                                             
             "_all" : { "enabled": false },
             "_source": { "enabled": true },            
             "properties" : {
                 "tTimeStamp": {
                     "type": "date"
                 },
                 "sDeviceName": {"type" : "string", "index" : "not_analyzed"},
                 "sUserName":   {"type" : "string", "index" : "not_analyzed"},
                 "sDomainName": {"type" : "string", "index" : "not_analyzed"},
                 "sClientIP":   {"type" : "string", "index" : "not_analyzed"},
                 "iUrlCat":     {"type" : "integer"},
                 "iCount":      {"type" : "integer"}
             }
        }
    }
}'

Thanks.

Patrick.

**Comment by costin** [comment]
It doesn't look like a bug but rather an error on your side - looks like you are using Spark with `SaveMode` `ErrorIfExists` hence why saving works the first time but throws an exception the second time around.
Use `Append` or `Overwrite`.

**Comment by patricklu** [comment]
Got that. It did work after added mode="append". Thanks a bunch for clarification.
