### ISSUE TITLE
Seeing issue 239 with elasticsearch-hadoop 2.3.0

### ISSUE THREAD

**Issue by duobrien** [elastic/elasticsearch-hadoop#750]
### What kind an issue is this?

- [x] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

Seeing this issue with version 2.3.0: https://github.com/elastic/elasticsearch-hadoop/issues/239

### Steps to reproduce

Unsure how to reproduce, but here is my dependency tree

Listening for transport dt_socket at address: 5005
[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for com.homeaway.bigdata:hadoop-test-readout:jar:0.1-SNAPSHOT
[WARNING] 'dependencies.dependency.scope' for cascading:cascading-hadoop:jar must be one of [provided, compile, runtime, test, system] but is 'optional'. @ line 340, column 20
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building hadoop-test-readout 0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.9:tree (default-cli) @ hadoop-test-readout ---
[INFO] com.homeaway.bigdata:hadoop-test-readout:jar:0.1-SNAPSHOT
[INFO] +- org.springframework.boot:spring-boot-starter:jar:1.2.1.RELEASE:compile
[INFO] |  +- org.springframework:spring-core:jar:4.1.4.RELEASE:compile
[INFO] |  \- org.yaml:snakeyaml:jar:1.14:compile
[INFO] +- org.elasticsearch:elasticsearch-hadoop:jar:2.3.0:compile
[INFO] |  +- org.apache.pig:pig:jar:0.15.0:optional
[INFO] |  |  +- org.mortbay.jetty:jsp-api-2.1:jar:6.1.14:runtime
[INFO] |  |  +- org.mortbay.jetty:jsp-2.1:jar:6.1.14:runtime
[INFO] |  |  |  +- org.eclipse.jdt:core:jar:3.1.1:runtime
[INFO] |  |  |  \- ant:ant:jar:1.6.5:runtime
[INFO] |  |  +- org.mortbay.jetty:servlet-api-2.5:jar:6.1.14:runtime
[INFO] |  |  +- net.sf.kosmosfs:kfs:jar:0.3:runtime
[INFO] |  |  +- hsqldb:hsqldb:jar:1.8.0.10:runtime
[INFO] |  |  +- oro:oro:jar:2.0.8:runtime
[INFO] |  |  \- dk.brics.automaton:automaton:jar:1.11-8:runtime
[INFO] |  +- org.apache.storm:storm-core:jar:0.9.6:optional
[INFO] |  |  +- org.clojure:clojure:jar:1.5.1:runtime
[INFO] |  |  +- clj-time:clj-time:jar:0.4.1:runtime
[INFO] |  |  +- compojure:compojure:jar:1.1.3:runtime
[INFO] |  |  +- org.clojure:core.incubator:jar:0.1.0:runtime
[INFO] |  |  +- org.clojure:tools.macro:jar:0.1.0:runtime
[INFO] |  |  +- clout:clout:jar:1.0.1:runtime
[INFO] |  |  +- ring:ring-core:jar:1.1.5:runtime
[INFO] |  |  +- commons-fileupload:commons-fileupload:jar:1.2.1:runtime
[INFO] |  |  +- hiccup:hiccup:jar:0.3.6:runtime
[INFO] |  |  +- ring:ring-devel:jar:0.3.11:runtime
[INFO] |  |  +- clj-stacktrace:clj-stacktrace:jar:0.2.2:runtime
[INFO] |  |  +- ring:ring-jetty-adapter:jar:0.3.11:runtime
[INFO] |  |  +- ring:ring-servlet:jar:0.3.11:runtime
[INFO] |  |  +- org.clojure:tools.logging:jar:0.2.3:runtime
[INFO] |  |  +- org.clojure:math.numeric-tower:jar:0.0.1:runtime
[INFO] |  |  +- org.clojure:tools.cli:jar:0.2.4:runtime
[INFO] |  |  +- org.apache.commons:commons-exec:jar:1.1:runtime
[INFO] |  |  +- com.googlecode.json-simple:json-simple:jar:1.1.1:runtime
[INFO] |  |  +- com.twitter:carbonite:jar:1.4.0:runtime
[INFO] |  |  +- com.esotericsoftware.kryo:kryo:jar:2.21:runtime
[INFO] |  |  +- com.esotericsoftware.reflectasm:reflectasm:jar:shaded:1.07:runtime
[INFO] |  |  +- org.ow2.asm:asm:jar:4.0:runtime
[INFO] |  |  +- com.esotericsoftware.minlog:minlog:jar:1.2:runtime
[INFO] |  |  +- com.twitter:chill-java:jar:0.3.5:runtime
[INFO] |  |  +- com.googlecode.disruptor:disruptor:jar:2.10.4:runtime
[INFO] |  |  \- org.jgrapht:jgrapht-core:jar:0.9.0:runtime
[INFO] |  +- org.apache.spark:spark-core_2.10:jar:1.6.1:runtime
[INFO] |  |  +- com.twitter:chill_2.10:jar:0.5.0:runtime
[INFO] |  |  +- org.apache.xbean:xbean-asm5-shaded:jar:4.4:runtime
[INFO] |  |  +- org.apache.hadoop:hadoop-client:jar:2.2.0:runtime
[INFO] |  |  |  +- org.apache.hadoop:hadoop-hdfs:jar:2.2.0:runtime
[INFO] |  |  |  \- org.apache.hadoop:hadoop-mapreduce-client-jobclient:jar:2.2.0:runtime
[INFO] |  |  +- org.apache.spark:spark-launcher_2.10:jar:1.6.1:runtime
[INFO] |  |  +- org.apache.spark:spark-network-common_2.10:jar:1.6.1:runtime
[INFO] |  |  +- org.apache.spark:spark-network-shuffle_2.10:jar:1.6.1:runtime
[INFO] |  |  +- org.apache.spark:spark-unsafe_2.10:jar:1.6.1:runtime
[INFO] |  |  +- org.eclipse.jetty.orbit:javax.servlet:jar:3.0.0.v201112011016:runtime
[INFO] |  |  +- org.apache.commons:commons-lang3:jar:3.3.2:runtime
[INFO] |  |  +- com.ning:compress-lzf:jar:1.0.3:runtime
[INFO] |  |  +- net.jpountz.lz4:lz4:jar:1.3.0:runtime
[INFO] |  |  +- org.roaringbitmap:RoaringBitmap:jar:0.5.11:runtime
[INFO] |  |  +- com.typesafe.akka:akka-remote_2.10:jar:2.3.11:runtime
[INFO] |  |  |  +- com.typesafe.akka:akka-actor_2.10:jar:2.3.11:runtime
[INFO] |  |  |  |  \- com.typesafe:config:jar:1.2.1:runtime
[INFO] |  |  |  \- org.uncommons.maths:uncommons-maths:jar:1.2.2a:runtime
[INFO] |  |  +- com.typesafe.akka:akka-slf4j_2.10:jar:2.3.11:runtime
[INFO] |  |  +- org.scala-lang:scala-library:jar:2.10.5:runtime
[INFO] |  |  +- org.json4s:json4s-jackson_2.10:jar:3.2.10:runtime
[INFO] |  |  |  \- org.json4s:json4s-core_2.10:jar:3.2.10:runtime
[INFO] |  |  |     +- org.json4s:json4s-ast_2.10:jar:3.2.10:runtime
[INFO] |  |  |     \- org.scala-lang:scalap:jar:2.10.0:runtime
[INFO] |  |  |        \- org.scala-lang:scala-compiler:jar:2.10.0:runtime
[INFO] |  |  +- org.apache.mesos:mesos:jar:shaded-protobuf:0.21.1:runtime
[INFO] |  |  +- io.netty:netty-all:jar:4.0.29.Final:runtime
[INFO] |  |  +- com.clearspring.analytics:stream:jar:2.7.0:runtime
[INFO] |  |  +- io.dropwizard.metrics:metrics-core:jar:3.1.0:runtime
[INFO] |  |  +- io.dropwizard.metrics:metrics-jvm:jar:3.1.2:runtime
[INFO] |  |  +- io.dropwizard.metrics:metrics-json:jar:3.1.2:runtime
[INFO] |  |  +- io.dropwizard.metrics:metrics-graphite:jar:3.1.0:runtime
[INFO] |  |  +- com.fasterxml.jackson.module:jackson-module-scala_2.10:jar:2.4.4:runtime
[INFO] |  |  |  \- org.scala-lang:scala-reflect:jar:2.10.4:runtime
[INFO] |  |  +- org.tachyonproject:tachyon-client:jar:0.8.2:runtime
[INFO] |  |  |  +- org.tachyonproject:tachyon-underfs-hdfs:jar:0.8.2:runtime
[INFO] |  |  |  +- org.tachyonproject:tachyon-underfs-s3:jar:0.8.2:runtime
[INFO] |  |  |  \- org.tachyonproject:tachyon-underfs-local:jar:0.8.2:runtime
[INFO] |  |  +- net.razorvine:pyrolite:jar:4.9:runtime
[INFO] |  |  +- net.sf.py4j:py4j:jar:0.9:runtime
[INFO] |  |  \- org.spark-project.spark:unused:jar:1.0.0:runtime
[INFO] |  +- org.apache.spark:spark-sql_2.10:jar:1.6.1:optional
[INFO] |  |  +- org.apache.spark:spark-catalyst_2.10:jar:1.6.1:runtime
[INFO] |  |  +- org.apache.parquet:parquet-column:jar:1.7.0:runtime
[INFO] |  |  |  +- org.apache.parquet:parquet-common:jar:1.7.0:runtime
[INFO] |  |  |  \- org.apache.parquet:parquet-encoding:jar:1.7.0:runtime
[INFO] |  |  |     \- org.apache.parquet:parquet-generator:jar:1.7.0:runtime
[INFO] |  |  \- org.apache.parquet:parquet-hadoop:jar:1.7.0:runtime
[INFO] |  |     +- org.apache.parquet:parquet-format:jar:2.3.0-incubating:runtime
[INFO] |  |     \- org.apache.parquet:parquet-jackson:jar:1.7.0:runtime
[INFO] |  \- org.apache.hive:hive-service:jar:1.2.1:optional
[INFO] |     +- net.sf.jpam:jpam:jar:1.1:runtime
[INFO] |     +- org.eclipse.jetty.aggregate:jetty-all:jar:7.6.0.v20120127:runtime
[INFO] |     |  +- org.apache.geronimo.specs:geronimo-jta_1.1_spec:jar:1.1.1:runtime
[INFO] |     |  +- org.apache.geronimo.specs:geronimo-jaspic_1.0_spec:jar:1.0:runtime
[INFO] |     |  +- org.apache.geronimo.specs:geronimo-annotation_1.0_spec:jar:1.1.1:runtime
[INFO] |     |  \- asm:asm-commons:jar:3.1:runtime
[INFO] |     |     \- asm:asm-tree:jar:3.1:runtime
[INFO] |     \- org.apache.thrift:libthrift:jar:0.9.2:runtime
[INFO] +- com.homeaway:elasticsearch-client:jar:7.1:compile
[INFO] |  +- org.codehaus.groovy:groovy-all:jar:2.3.8:compile
[INFO] |  +- org.perf4j:perf4j:jar:0.9.16:compile
[INFO] |  \- org.codehaus.jackson:jackson-mapper-asl:jar:1.8.3:compile
[INFO] +- org.apache.hadoop:hadoop-mapreduce-client-app:jar:2.6.0.2.2.0.0-2041:provided
[INFO] |  +- org.apache.hadoop:hadoop-mapreduce-client-common:jar:2.6.0.2.2.0.0-2041:runtime
[INFO] |  |  +- org.apache.hadoop:hadoop-yarn-client:jar:2.6.0.2.2.0.0-2041:runtime
[INFO] |  |  \- org.apache.hadoop:hadoop-yarn-server-common:jar:2.6.0.2.2.0.0-2041:runtime
[INFO] |  |     \- org.apache.hadoop:hadoop-yarn-registry:jar:2.6.0.2.2.0.0-2041:runtime
[INFO] |  +- org.apache.hadoop:hadoop-yarn-server-web-proxy:jar:2.6.0.2.2.0.0-2041:runtime
[INFO] |  |  \- org.apache.hadoop:hadoop-yarn-api:jar:2.6.0.2.2.0.0-2041:runtime
[INFO] |  +- org.apache.hadoop:hadoop-mapreduce-client-shuffle:jar:2.6.0.2.2.0.0-2041:runtime
[INFO] |  |  +- org.apache.hadoop:hadoop-yarn-server-nodemanager:jar:2.6.0.2.2.0.0-2041:runtime
[INFO] |  |  \- org.fusesource.leveldbjni:leveldbjni-all:jar:1.8:runtime
[INFO] |  +- com.google.protobuf:protobuf-java:jar:2.5.0:runtime
[INFO] |  +- org.apache.hadoop:hadoop-annotations:jar:2.6.0.2.2.0.0-2041:runtime
[INFO] |  +- com.google.inject.extensions:guice-servlet:jar:3.0:runtime
[INFO] |  |  \- com.google.inject:guice:jar:3.0:runtime
[INFO] |  |     \- javax.inject:javax.inject:jar:1:runtime
[INFO] |  \- io.netty:netty:jar:3.6.2.Final:compile
[INFO] +- org.apache.hadoop:hadoop-mapreduce-client-core:jar:2.6.0.2.2.0.0-2041:provided
[INFO] |  \- org.apache.hadoop:hadoop-yarn-common:jar:2.6.0.2.2.0.0-2041:runtime
[INFO] |     +- javax.xml.bind:jaxb-api:jar:2.2.2:runtime
[INFO] |     |  \- javax.xml.stream:stax-api:jar:1.0-2:runtime
[INFO] |     +- com.sun.jersey:jersey-client:jar:1.9:runtime
[INFO] |     +- org.codehaus.jackson:jackson-jaxrs:jar:1.9.13:runtime
[INFO] |     +- org.codehaus.jackson:jackson-xc:jar:1.9.13:runtime
[INFO] |     \- com.sun.jersey.contribs:jersey-guice:jar:1.9:runtime
[INFO] +- org.apache.hadoop:hadoop-common:jar:2.6.0.2.2.0.0-2041:provided
[INFO] |  +- commons-cli:commons-cli:jar:1.2:runtime
[INFO] |  +- org.apache.commons:commons-math3:jar:3.1.1:runtime
[INFO] |  +- xmlenc:xmlenc:jar:0.52:runtime
[INFO] |  +- commons-httpclient:commons-httpclient:jar:3.1:runtime
[INFO] |  +- commons-codec:commons-codec:jar:1.4:runtime
[INFO] |  +- commons-net:commons-net:jar:3.1:runtime
[INFO] |  +- javax.servlet:servlet-api:jar:2.5:runtime
[INFO] |  +- org.mortbay.jetty:jetty:jar:6.1.26.hwx:compile
[INFO] |  +- org.mortbay.jetty:jetty-util:jar:6.1.26.hwx:compile
[INFO] |  +- com.sun.jersey:jersey-core:jar:1.9:runtime
[INFO] |  +- com.sun.jersey:jersey-json:jar:1.9:runtime
[INFO] |  |  +- org.codehaus.jettison:jettison:jar:1.1:runtime
[INFO] |  |  \- com.sun.xml.bind:jaxb-impl:jar:2.2.3-1:runtime
[INFO] |  +- com.sun.jersey:jersey-server:jar:1.9:runtime
[INFO] |  |  \- asm:asm:jar:3.1:runtime
[INFO] |  +- tomcat:jasper-compiler:jar:5.5.23:runtime
[INFO] |  +- tomcat:jasper-runtime:jar:5.5.23:runtime
[INFO] |  +- javax.servlet.jsp:jsp-api:jar:2.1:provided
[INFO] |  +- commons-el:commons-el:jar:1.0:runtime
[INFO] |  +- net.java.dev.jets3t:jets3t:jar:0.9.0:runtime
[INFO] |  |  +- org.apache.httpcomponents:httpclient:jar:4.3.6:runtime
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.1.2:runtime
[INFO] |  |  \- com.jamesmurty.utils:java-xmlbuilder:jar:0.4:runtime
[INFO] |  +- com.microsoft.windowsazure.storage:microsoft-windowsazure-storage-sdk:jar:0.6.0:provided
[INFO] |  +- commons-configuration:commons-configuration:jar:1.6:provided
[INFO] |  |  +- commons-digester:commons-digester:jar:2.1:provided
[INFO] |  |  |  \- commons-beanutils:commons-beanutils:jar:1.9.2:provided
[INFO] |  |  \- commons-beanutils:commons-beanutils-core:jar:1.8.0:provided
[INFO] |  +- org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile
[INFO] |  +- com.google.code.gson:gson:jar:2.3:provided
[INFO] |  +- org.apache.hadoop:hadoop-auth:jar:2.6.0.2.2.0.0-2041:provided
[INFO] |  |  \- org.apache.directory.server:apacheds-kerberos-codec:jar:2.0.0-M15:provided
[INFO] |  |     +- org.apache.directory.server:apacheds-i18n:jar:2.0.0-M15:provided
[INFO] |  |     +- org.apache.directory.api:api-asn1-api:jar:1.0.0-M20:provided
[INFO] |  |     \- org.apache.directory.api:api-util:jar:1.0.0-M20:provided
[INFO] |  +- com.jcraft:jsch:jar:0.1.42:provided
[INFO] |  +- org.apache.curator:curator-client:jar:2.6.0:runtime
[INFO] |  +- org.apache.curator:curator-recipes:jar:2.6.0:runtime
[INFO] |  +- com.google.code.findbugs:jsr305:jar:1.3.9:compile
[INFO] |  +- org.htrace:htrace-core:jar:3.0.4:provided
[INFO] |  +- org.apache.zookeeper:zookeeper:jar:3.4.6:runtime
[INFO] |  \- org.apache.commons:commons-compress:jar:1.4.1:compile
[INFO] |     \- org.tukaani:xz:jar:1.0:compile
[INFO] +- org.elasticsearch:elasticsearch:jar:1.7.2:compile
[INFO] |  +- org.apache.lucene:lucene-core:jar:4.10.4:compile
[INFO] |  +- org.apache.lucene:lucene-analyzers-common:jar:4.10.4:compile
[INFO] |  +- org.apache.lucene:lucene-queries:jar:4.10.4:compile
[INFO] |  +- org.apache.lucene:lucene-memory:jar:4.10.4:compile
[INFO] |  +- org.apache.lucene:lucene-highlighter:jar:4.10.4:compile
[INFO] |  +- org.apache.lucene:lucene-queryparser:jar:4.10.4:compile
[INFO] |  +- org.apache.lucene:lucene-sandbox:jar:4.10.4:compile
[INFO] |  +- org.apache.lucene:lucene-suggest:jar:4.10.4:compile
[INFO] |  +- org.apache.lucene:lucene-misc:jar:4.10.4:compile
[INFO] |  +- org.apache.lucene:lucene-join:jar:4.10.4:compile
[INFO] |  +- org.apache.lucene:lucene-grouping:jar:4.10.4:compile
[INFO] |  \- org.apache.lucene:lucene-spatial:jar:4.10.4:compile
[INFO] |     \- com.spatial4j:spatial4j:jar:0.4.1:compile
[INFO] +- cascading:cascading-jdbc-core:jar:2.6.0:compile
[INFO] +- org.apache.avro:avro:jar:1.7.4:compile
[INFO] |  +- com.thoughtworks.paranamer:paranamer:jar:2.3:compile
[INFO] |  \- org.xerial.snappy:snappy-java:jar:1.0.4.1:compile
[INFO] +- net.sourceforge.jtds:jtds:jar:1.2.8:compile
[INFO] +- org.apache.commons:commons-math:jar:2.2:compile
[INFO] +- javax.mail:mail:jar:1.4.1:compile
[INFO] +- javax.activation:activation:jar:1.1:compile
[INFO] +- commons-lang:commons-lang:jar:2.6:compile
[INFO] +- commons-io:commons-io:jar:2.4:compile
[INFO] +- joda-time:joda-time:jar:2.0:compile
[INFO] +- commons-collections:commons-collections:jar:3.2.1:compile
[INFO] +- com.homeaway.commons:hacommons-logging-events:jar:1.8-jdk7:compile
[INFO] |  +- org.apache.avro:avro-ipc:jar:1.7.4:compile
[INFO] |  |  +- org.apache.velocity:velocity:jar:1.7:compile
[INFO] |  |  \- org.mortbay.jetty:servlet-api:jar:2.5-20081211:compile
[INFO] |  \- org.slf4j:log4j-over-slf4j:jar:1.7.8:runtime
[INFO] +- com.fasterxml.jackson.core:jackson-databind:jar:2.1.4:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.4.4:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-core:jar:2.4.4:compile
[INFO] +- cascading:cascading-core:jar:2.7.1:compile
[INFO] |  +- riffle:riffle:jar:1.0.0:compile
[INFO] |  +- thirdparty:jgrapht-jdk1.6:jar:0.8.1:compile
[INFO] |  \- org.codehaus.janino:janino:jar:2.6.1:compile
[INFO] |     \- org.codehaus.janino:commons-compiler:jar:2.6.1:compile
[INFO] +- cascading:cascading-local:jar:2.7.1:compile
[INFO] +- cascading:cascading-hadoop2-mr1:jar:2.7.1:compile
[INFO] +- cascading.avro:avro-scheme:jar:2.5.0:compile
[INFO] |  +- org.apache.avro:avro-mapred:jar:hadoop2:1.7.6:compile
[INFO] |  +- org.apache.avro:trevni-avro:jar:1.7.6:compile
[INFO] |  |  \- org.apache.avro:avro-mapred:jar:hadoop1:1.7.6:compile
[INFO] |  |     \- org.apache.avro:avro-ipc:jar:tests:1.7.6:compile
[INFO] |  \- org.apache.avro:trevni-core:jar:1.7.6:compile
[INFO] +- cascading:cascading-platform:jar:2.7.1:test
[INFO] +- org.mockito:mockito-core:jar:1.10.8:test
[INFO] |  +- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] |  \- org.objenesis:objenesis:jar:2.1:runtime
[INFO] +- org.slf4j:slf4j-api:jar:1.7.8:compile
[INFO] +- org.slf4j:jcl-over-slf4j:jar:1.7.8:runtime
[INFO] +- org.springframework.boot:spring-boot-autoconfigure:jar:1.2.1.RELEASE:compile
[INFO] +- org.springframework:spring-context:jar:4.1.4.RELEASE:compile
[INFO] |  +- org.springframework:spring-aop:jar:4.1.4.RELEASE:compile
[INFO] |  |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  \- org.springframework:spring-expression:jar:4.1.4.RELEASE:compile
[INFO] +- org.springframework:spring-beans:jar:4.1.4.RELEASE:compile
[INFO] +- org.springframework.boot:spring-boot:jar:1.2.1.RELEASE:compile
[INFO] +- com.google.guava:guava:jar:11.0.2:compile
[INFO] +- driven:driven-plugin:jar:1.2-eap-11:provided
[INFO] +- org.springframework:spring-test:jar:4.1.4.RELEASE:test
[INFO] +- org.hamcrest:hamcrest-library:jar:1.3:test
[INFO] +- junit:junit:jar:4.12:test
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:1.2.1.RELEASE:test
[INFO] +- org.springframework.boot:spring-boot-starter-logging:jar:1.2.1.RELEASE:test
[INFO] |  +- org.slf4j:jul-to-slf4j:jar:1.7.8:runtime
[INFO] |  \- ch.qos.logback:logback-classic:jar:1.1.2:runtime
[INFO] |     \- ch.qos.logback:logback-core:jar:1.1.2:runtime
[INFO] +- org.apache.hive:hive-exec:jar:1.2.1:runtime
[INFO] |  +- org.apache.hive:hive-ant:jar:1.2.1:runtime
[INFO] |  +- org.apache.hive:hive-metastore:jar:1.2.1:runtime
[INFO] |  |  +- org.apache.hive:hive-serde:jar:1.2.1:runtime
[INFO] |  |  |  +- org.apache.hive:hive-common:jar:1.2.1:runtime
[INFO] |  |  |  |  \- org.json:json:jar:20090211:runtime
[INFO] |  |  |  +- net.sf.opencsv:opencsv:jar:2.3:runtime
[INFO] |  |  |  \- com.twitter:parquet-hadoop-bundle:jar:1.6.0:runtime
[INFO] |  |  +- com.jolbox:bonecp:jar:0.8.0.RELEASE:runtime
[INFO] |  |  +- org.apache.derby:derby:jar:10.10.2.0:runtime
[INFO] |  |  +- org.datanucleus:datanucleus-api-jdo:jar:3.2.6:runtime
[INFO] |  |  +- org.datanucleus:datanucleus-rdbms:jar:3.2.9:runtime
[INFO] |  |  +- commons-pool:commons-pool:jar:1.6:runtime
[INFO] |  |  +- commons-dbcp:commons-dbcp:jar:1.4:runtime
[INFO] |  |  \- javax.jdo:jdo-api:jar:3.0.1:runtime
[INFO] |  |     \- javax.transaction:jta:jar:1.1:runtime
[INFO] |  +- org.apache.hive:hive-shims:jar:1.2.1:runtime
[INFO] |  |  +- org.apache.hive.shims:hive-shims-common:jar:1.2.1:runtime
[INFO] |  |  +- org.apache.hive.shims:hive-shims-0.20S:jar:1.2.1:runtime
[INFO] |  |  +- org.apache.hive.shims:hive-shims-0.23:jar:1.2.1:runtime
[INFO] |  |  |  \- org.apache.hadoop:hadoop-yarn-server-resourcemanager:jar:2.6.0:runtime
[INFO] |  |  |     \- org.apache.hadoop:hadoop-yarn-server-applicationhistoryservice:jar:2.6.0:runtime
[INFO] |  |  \- org.apache.hive.shims:hive-shims-scheduler:jar:1.2.1:runtime
[INFO] |  +- log4j:apache-log4j-extras:jar:1.2.17:runtime
[INFO] |  +- org.antlr:antlr-runtime:jar:3.4:runtime
[INFO] |  |  +- org.antlr:stringtemplate:jar:3.2.1:runtime
[INFO] |  |  \- antlr:antlr:jar:2.7.7:runtime
[INFO] |  +- org.antlr:ST4:jar:4.0.4:runtime
[INFO] |  +- org.apache.ant:ant:jar:1.9.1:runtime
[INFO] |  |  \- org.apache.ant:ant-launcher:jar:1.9.1:runtime
[INFO] |  +- org.apache.thrift:libfb303:jar:0.9.2:runtime
[INFO] |  +- org.apache.ivy:ivy:jar:2.4.0:runtime
[INFO] |  +- org.apache.curator:curator-framework:jar:2.6.0:runtime
[INFO] |  +- org.apache.curator:apache-curator:pom:2.6.0:runtime
[INFO] |  +- org.datanucleus:datanucleus-core:jar:3.2.10:runtime
[INFO] |  +- org.apache.calcite:calcite-core:jar:1.2.0-incubating:runtime
[INFO] |  |  +- org.apache.calcite:calcite-linq4j:jar:1.2.0-incubating:runtime
[INFO] |  |  +- net.hydromatic:eigenbase-properties:jar:1.1.5:runtime
[INFO] |  |  \- org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde:runtime
[INFO] |  +- org.apache.calcite:calcite-avatica:jar:1.2.0-incubating:runtime
[INFO] |  +- stax:stax-api:jar:1.0.1:runtime
[INFO] |  \- jline:jline:jar:2.12:runtime
[INFO] \- cascading:cascading-hadoop:jar:2.7.1:optional
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.474 s
[INFO] Finished at: 2016-04-15T17:20:49-05:00
[INFO] Final Memory: 29M/311M
[INFO] ------------------------------------------------------------------------

Stack Trace:

7876 [main] INFO  org.elasticsearch.plugins - [Melody Guthrie] loaded [], sites []
Exception in thread "main" java.lang.NoClassDefFoundError: org/codehaus/jackson/annotate/JsonClass
	at org.codehaus.jackson.map.introspect.JacksonAnnotationIntrospector.findDeserializationType(JacksonAnnotationIntrospector.java:524)
	at org.codehaus.jackson.map.deser.BasicDeserializerFactory.modifyTypeByAnnotation(BasicDeserializerFactory.java:725)
	at org.codehaus.jackson.map.deser.BasicDeserializerFactory.createMapDeserializer(BasicDeserializerFactory.java:336)
	at org.codehaus.jackson.map.deser.StdDeserializerProvider._createDeserializer(StdDeserializerProvider.java:377)
	at org.codehaus.jackson.map.deser.StdDeserializerProvider._createAndCache2(StdDeserializerProvider.java:307)
	at org.codehaus.jackson.map.deser.StdDeserializerProvider._createAndCacheValueDeserializer(StdDeserializerProvider.java:287)
	at org.codehaus.jackson.map.deser.StdDeserializerProvider.findValueDeserializer(StdDeserializerProvider.java:136)
	at org.codehaus.jackson.map.deser.StdDeserializerProvider.findTypedValueDeserializer(StdDeserializerProvider.java:157)
	at org.codehaus.jackson.map.ObjectMapper._findRootDeserializer(ObjectMapper.java:2461)
	at org.codehaus.jackson.map.ObjectMapper._readMapAndClose(ObjectMapper.java:2395)
	at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1602)
	at com.homeaway.elasticsearch.BaseElasticSearchClientImpl.createIndex(BaseElasticSearchClientImpl.java:214)
	at com.homeaway.elasticsearch.BaseElasticSearchClientImpl.createIndex(BaseElasticSearchClientImpl.java:180)
	at com.homeaway.bigdata.utils.ElasticUtils.createIndexIfNeeded(ElasticUtils.java:70)
	at com.homeaway.bigdata.proctor.flows.ElasticOutFlow.createIndexIfNeeded(ElasticOutFlow.java:66)
	at com.homeaway.bigdata.proctor.config.LoadDataToElasticConfig$1.run(LoadDataToElasticConfig.java:70)
	at com.homeaway.bigdata.proctor.LoadDataToElasticApplication.main(LoadDataToElasticApplication.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassNotFoundException: org.codehaus.jackson.annotate.JsonClass
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 22 more
9623 [Thread-1] INFO  org.springframework.context.annotation.Annot

POM:
[pom.zip](https://github.com/elastic/elasticsearch-hadoop/files/221894/pom.zip)

### Version Info

OS:         :  OSX
JVM         :  1.8.latest
Hadoop/Spark:  See dependency tree, looks like a potential conflict, but the short answer is 2.6.0.2.2.0.0-2041
ES-Hadoop   :  2.3.0
ES          :  1.7.2

**Comment by duobrien** [comment]
Hopefully this can help someone else.

Turns out this was not an elasticsearch-hadoop issue, and in fact the referenced elasticsearch-hadoop issue helped me to solve it.  There was a case in my dependency tree where jackson-mapper-asl.jar was version 1.8.3 and jackson-core-asl.jar was 1.9.13:

[INFO] |  \- org.codehaus.jackson:jackson-mapper-asl:jar:1.8.3:compile
[INFO] |     \- (org.codehaus.jackson:jackson-core-asl:jar:1.9.13:compile - omitted for conflict with 1.8.8)

Forcing jackson-mapper-asl to 1.9.13 to match jackson-core-asl resolved my issue.  Of course I need to test that that feature has no compatibility issues with 1.9.13.
