### ISSUE TITLE
ERROR NetworkClient: Node [127.0.0.1:9200] failed (Read timed out); no other nodes left - aborting...

### ISSUE THREAD

**Issue by papasanipavan** [elastic/elasticsearch-hadoop#753]
I am new to Spark and Elasticsearch, I am trying to save RDD to ES, Currently i am using Spark 1.3 and Elasticsearch 2.3. This is the code i am using 

  def main(args: Array[String]) {
   
    val conf = new SparkConf()
    conf.set("spark.master","local[2]" )
    conf.set("spark.app.name","testing")
    conf.set("spark.es.nodes","localhost")
    conf.set("es.index.auto.create", "true")
    conf.set("spark.es.net.ssl","false")
    conf.set("spark.es.port","9200")
    conf.set("es.mapping.date.rich","false")
    conf.set("spark.es.index.read.missing.as.empty","true")
    conf.set("spark.es.batch.write.retry.count","-1")
    conf.set("spark.serializer","org.apache.spark.serializer.KryoSerializer")
    conf.set("es.nodes.discovery", "false")
    
    val sc = new SparkContext(conf)
    
    case class Trip(departure: String, arrival: String)               

    val upcomingTrip = Trip("OTP", "SFO")
    val lastWeekTrip = Trip("MUC", "OTP")

    val rdd = sc.makeRDD(Seq(upcomingTrip, lastWeekTrip))             
    EsSpark.saveToEs(rdd, "spark/docs") 

and this is my pom.xml dependencies 

	<version>0.0.1-SNAPSHOT</version>
	<dependencies>
		<dependency>
			<groupId>org.scala-lang</groupId>
			<artifactId>scala-library</artifactId>
			<version>2.10.6</version>
		</dependency>
		<dependency>
			<groupId>org.apache.spark</groupId>
			<artifactId>spark-core_2.10</artifactId>
			<version>1.3.1</version>
		</dependency>

		<dependency>
			<groupId>org.elasticsearch</groupId>
			<artifactId>elasticsearch</artifactId>
			<version>2.3.0</version>
		</dependency>
		<dependency>
			<groupId>org.elasticsearch</groupId>
			<artifactId>elasticsearch-spark_2.10</artifactId>
			<version>2.3.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.spark</groupId>
			<artifactId>spark-sql_2.10</artifactId>
			<version>1.3.1</version>
		</dependency>
		<dependency>
			<groupId>org.apache.spark</groupId>
			<artifactId>spark-hive_2.10</artifactId>
			<version>1.2.1</version>
		</dependency>
	</dependencies>

I am not sure whether i am using wrong dependencies. I am getting error which was discussed here before but I am using elasticsearch 2.3. This is the Error i am getting 

Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
16/04/24 20:42:04 INFO SparkContext: Running Spark version 1.3.1
16/04/24 20:42:05 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
16/04/24 20:42:05 INFO SecurityManager: Changing view acls to: ppapasan
16/04/24 20:42:05 INFO SecurityManager: Changing modify acls to: ppapasan
16/04/24 20:42:05 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(ppapasan); users with modify permissions: Set(ppapasan)
16/04/24 20:42:06 INFO Slf4jLogger: Slf4jLogger started
16/04/24 20:42:06 INFO Remoting: Starting remoting
16/04/24 20:42:06 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriver@PPAPASAN-F08311.cgifederal.com:50198]
16/04/24 20:42:06 INFO Utils: Successfully started service 'sparkDriver' on port 50198.
16/04/24 20:42:06 INFO SparkEnv: Registering MapOutputTracker
16/04/24 20:42:06 INFO SparkEnv: Registering BlockManagerMaster
16/04/24 20:42:06 INFO DiskBlockManager: Created local directory at C:\Temp\spark-37815e77-cc72-4bcc-ac06-67bb0ffa3c07\blockmgr-7b8cc95c-7ee9-4399-817f-9bf2cacb1abc
16/04/24 20:42:06 INFO MemoryStore: MemoryStore started with capacity 972.5 MB
16/04/24 20:42:06 INFO HttpFileServer: HTTP File server directory is C:\Temp\spark-c252fac3-f528-4560-98ae-2670ad3425eb\httpd-4637ec7b-5da5-4a51-b1a7-560ec524f253
16/04/24 20:42:06 INFO HttpServer: Starting HTTP Server
16/04/24 20:42:06 INFO Server: jetty-8.y.z-SNAPSHOT
16/04/24 20:42:06 INFO AbstractConnector: Started SocketConnector@0.0.0.0:50199
16/04/24 20:42:06 INFO Utils: Successfully started service 'HTTP file server' on port 50199.
16/04/24 20:42:06 INFO SparkEnv: Registering OutputCommitCoordinator
16/04/24 20:42:06 INFO Server: jetty-8.y.z-SNAPSHOT
16/04/24 20:42:06 INFO AbstractConnector: Started SelectChannelConnector@0.0.0.0:4040
16/04/24 20:42:06 INFO Utils: Successfully started service 'SparkUI' on port 4040.
16/04/24 20:42:06 INFO SparkUI: Started SparkUI at http://PPAPASAN-F08311.cgifederal.com:4040
16/04/24 20:42:06 INFO Executor: Starting executor ID <driver> on host localhost
16/04/24 20:42:06 INFO AkkaUtils: Connecting to HeartbeatReceiver: akka.tcp://sparkDriver@PPAPASAN-F08311.cgifederal.com:50198/user/HeartbeatReceiver
16/04/24 20:42:07 INFO NettyBlockTransferService: Server created on 50218
16/04/24 20:42:07 INFO BlockManagerMaster: Trying to register BlockManager
16/04/24 20:42:07 INFO BlockManagerMasterActor: Registering block manager localhost:50218 with 972.5 MB RAM, BlockManagerId(<driver>, localhost, 50218)
16/04/24 20:42:07 INFO BlockManagerMaster: Registered BlockManager
16/04/24 20:42:07 INFO SparkContext: Starting job: runJob at EsSpark.scala:67
16/04/24 20:42:07 INFO DAGScheduler: Got job 0 (runJob at EsSpark.scala:67) with 2 output partitions (allowLocal=false)
16/04/24 20:42:07 INFO DAGScheduler: Final stage: Stage 0(runJob at EsSpark.scala:67)
16/04/24 20:42:07 INFO DAGScheduler: Parents of final stage: List()
16/04/24 20:42:07 INFO DAGScheduler: Missing parents: List()
16/04/24 20:42:07 INFO DAGScheduler: Submitting Stage 0 (ParallelCollectionRDD[0] at makeRDD at HelloBokka.scala:38), which has no missing parents
16/04/24 20:42:07 INFO MemoryStore: ensureFreeSpace(2608) called with curMem=0, maxMem=1019782103
16/04/24 20:42:07 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 2.5 KB, free 972.5 MB)
16/04/24 20:42:07 INFO MemoryStore: ensureFreeSpace(1585) called with curMem=2608, maxMem=1019782103
16/04/24 20:42:07 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 1585.0 B, free 972.5 MB)
16/04/24 20:42:07 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on localhost:50218 (size: 1585.0 B, free: 972.5 MB)
16/04/24 20:42:07 INFO BlockManagerMaster: Updated info of block broadcast_0_piece0
16/04/24 20:42:07 INFO SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:839
16/04/24 20:42:07 INFO DAGScheduler: Submitting 2 missing tasks from Stage 0 (ParallelCollectionRDD[0] at makeRDD at HelloBokka.scala:38)
16/04/24 20:42:07 INFO TaskSchedulerImpl: Adding task set 0.0 with 2 tasks
16/04/24 20:42:07 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0, localhost, PROCESS_LOCAL, 1231 bytes)
16/04/24 20:42:07 INFO TaskSetManager: Starting task 1.0 in stage 0.0 (TID 1, localhost, PROCESS_LOCAL, 1231 bytes)
16/04/24 20:42:07 INFO Executor: Running task 0.0 in stage 0.0 (TID 0)
16/04/24 20:42:07 INFO Executor: Running task 1.0 in stage 0.0 (TID 1)
16/04/24 20:42:07 INFO Version: Elasticsearch Hadoop v2.3.0 [a2b025bf46]
16/04/24 20:42:08 INFO EsRDDWriter: Writing to [spark/docs]
16/04/24 20:42:08 INFO EsRDDWriter: Writing to [spark/docs]
16/04/24 20:43:08 ERROR NetworkClient: Node [127.0.0.1:9200] failed (Read timed out); no other nodes left - aborting...
16/04/24 20:43:08 ERROR NetworkClient: Node [127.0.0.1:9200] failed (Read timed out); no other nodes left - aborting...
16/04/24 20:43:08 ERROR Executor: Exception in task 1.0 in stage 0.0 (TID 1)
org.elasticsearch.hadoop.rest.EsHadoopNoNodesLeftException: Connection error (check network and/or proxy settings)- all nodes failed; tried [[127.0.0.1:9200]] 
	at org.elasticsearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:142)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:434)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:422)
	at org.elasticsearch.hadoop.rest.RestClient.touch(RestClient.java:525)
	at org.elasticsearch.hadoop.rest.RestRepository.touch(RestRepository.java:491)
	at org.elasticsearch.hadoop.rest.RestService.initSingleIndex(RestService.java:412)
	at org.elasticsearch.hadoop.rest.RestService.createWriter(RestService.java:400)
	at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:40)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$saveToEs$1.apply(EsSpark.scala:67)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$saveToEs$1.apply(EsSpark.scala:67)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:64)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
16/04/24 20:43:08 ERROR Executor: Exception in task 0.0 in stage 0.0 (TID 0)
org.elasticsearch.hadoop.rest.EsHadoopNoNodesLeftException: Connection error (check network and/or proxy settings)- all nodes failed; tried [[127.0.0.1:9200]] 
	at org.elasticsearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:142)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:434)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:422)
	at org.elasticsearch.hadoop.rest.RestClient.touch(RestClient.java:525)
	at org.elasticsearch.hadoop.rest.RestRepository.touch(RestRepository.java:491)
	at org.elasticsearch.hadoop.rest.RestService.initSingleIndex(RestService.java:412)
	at org.elasticsearch.hadoop.rest.RestService.createWriter(RestService.java:400)
	at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:40)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$saveToEs$1.apply(EsSpark.scala:67)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$saveToEs$1.apply(EsSpark.scala:67)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:64)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
16/04/24 20:43:08 WARN TaskSetManager: Lost task 1.0 in stage 0.0 (TID 1, localhost): org.elasticsearch.hadoop.rest.EsHadoopNoNodesLeftException: Connection error (check network and/or proxy settings)- all nodes failed; tried [[127.0.0.1:9200]] 
	at org.elasticsearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:142)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:434)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:422)
	at org.elasticsearch.hadoop.rest.RestClient.touch(RestClient.java:525)
	at org.elasticsearch.hadoop.rest.RestRepository.touch(RestRepository.java:491)
	at org.elasticsearch.hadoop.rest.RestService.initSingleIndex(RestService.java:412)
	at org.elasticsearch.hadoop.rest.RestService.createWriter(RestService.java:400)
	at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:40)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$saveToEs$1.apply(EsSpark.scala:67)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$saveToEs$1.apply(EsSpark.scala:67)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:64)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

16/04/24 20:43:08 ERROR TaskSetManager: Task 1 in stage 0.0 failed 1 times; aborting job
16/04/24 20:43:08 INFO TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0) on executor localhost: org.elasticsearch.hadoop.rest.EsHadoopNoNodesLeftException (Connection error (check network and/or proxy settings)- all nodes failed; tried [[127.0.0.1:9200]] ) [duplicate 1]
16/04/24 20:43:08 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool 
16/04/24 20:43:08 INFO TaskSchedulerImpl: Cancelling stage 0
16/04/24 20:43:08 INFO DAGScheduler: Stage 0 (runJob at EsSpark.scala:67) failed in 60.642 s
16/04/24 20:43:08 INFO DAGScheduler: Job 0 failed: runJob at EsSpark.scala:67, took 60.988982 s
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 0.0 failed 1 times, most recent failure: Lost task 1.0 in stage 0.0 (TID 1, localhost): org.elasticsearch.hadoop.rest.EsHadoopNoNodesLeftException: Connection error (check network and/or proxy settings)- all nodes failed; tried [[127.0.0.1:9200]] 
	at org.elasticsearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:142)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:434)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:422)
	at org.elasticsearch.hadoop.rest.RestClient.touch(RestClient.java:525)
	at org.elasticsearch.hadoop.rest.RestRepository.touch(RestRepository.java:491)
	at org.elasticsearch.hadoop.rest.RestService.initSingleIndex(RestService.java:412)
	at org.elasticsearch.hadoop.rest.RestService.createWriter(RestService.java:400)
	at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:40)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$saveToEs$1.apply(EsSpark.scala:67)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$saveToEs$1.apply(EsSpark.scala:67)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:61)
	at org.apache.spark.scheduler.Task.run(Task.scala:64)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:203)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1204)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1193)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1192)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1192)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:693)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:693)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:693)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1393)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1354)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)

**Comment by costin** [comment]
I am not sure what makes folks completely disregard:
- the issue template, which is there for a reason, to facilitate communication
- the clear advice to use the forum for questions and help (which in most cases already provides the answers to the questions asked), and instead use the bug tracker
- provide basic information (as asked in the template)
- formatting which is a simple yet very effective tools to increase readability.

I'm sorry but I'm closing this issue since it's invalid.

**Comment by doctor-q** [comment]
is there solution ?

**Comment by jbaiera** [comment]
@doctor-q This is a really old issue and is most likely a configuration error (The connector could not reach the local Elasticsearch instance). If you have a similar issue, I suggest opening an issue on our [forums](https://discuss.elastic.co/c/elasticsearch-and-hadoop)
