### ISSUE TITLE
Store Map as object with Pig in Elasticsearch

### ISSUE THREAD

**Issue by MohanBunny** [elastic/elasticsearch-hadoop#848]
I am having an issue with the format EsStorage to store map into Elasticsearch.
**example:**
`A: {pattern: chararray,tweets: {(lowertweets::created_at: chararray,lowertweets::id: chararray,lowertweets::id_str: chararray,lowertweets::text: chararray,lowertweets::source: chararray,lowertweets::entities: map[chararray],lowertweets::favorited: boolean,lowertweets::favorite_count: long,lowertweets::retweet_count: long,lowertweets::retweeted: boolean,lowertweets::place: map[chararray])}}`

**Script:-**
`STORE A INTO 'google_1473673952_265276863360/tweets' USING org.elasticsearch.hadoop.pig.EsStorage('es.nodes = ip:9200','es.mapping.pig.tuple.use.field.names = true');`

**Curl Script:-**
```
curl -XPUT 'http://hostname:9200/google_1473673952_265276863360/_mapping/tweets' -d '
{
    "tweets" : {
        "properties" : {
                "pattern" : {"type" : "string", "store" : true},
                "created_at" : {"type" : "string", "store" : true },
                "id" : {"type" : "string", "store" : true },
                "id_str" : {"type" : "string", "store" : true },
                "text" : {"type" : "string", "store" : true },
                "source" : {"type" : "string", "store" : true },
                "entities" : {"type" : "string", "store" : true },
                "favorited" : {"type" : "boolean", "store" : true },
                "favorite_count" : {"type" : "long", "store" : true },
                "retweet_count" : {"type" : "long", "store" : true },
                "retweeted" : {"type" : "boolean", "store" : true },
                "place" : {"type" : "string", "store" : true }
        }
    }
}'                  
```

But I am getting the error as 

Caused by: java.lang.**StringIndexOutOfBoundsException:** **String index out of range: -1** at java.lang.String.substring(String.java:1967)

Please suggest as I am completely new to this.
thank you.
Mohan.V

**Comment by jbaiera** [comment]
>But I am getting the error as

>Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1 at java.lang.String.substring(String.java:1967)

Could you post the full stacktrace please? This error message does not offer any context on what might be breaking.

**Comment by jbaiera** [comment]
Could you also post the artifact versions you are using?

**Comment by MohanBunny** [comment]
Thanks for your reply @jbaiera 

**Describe A;**
`A: {pattern: chararray,tweets: {(created_at: chararray,id: chararray,id_str: chararray,text: chararray,source: chararray,entities: map[chararray],favorited: boolean,favorite_count: long,retweet_count: long,retweeted: boolean,place: map[chararray])}}`

**ES script:-**
`STORE A INTO 'indexname/tweets' USING org.elasticsearch.hadoop.pig.EsStorage('es.nodes=localhost','es.port:9200','es.mapping.pig.tuple.use.field.names = true');`

Here is the complete **logs**,
```
016-09-23 10:48:19,260 [pool-69-thread-1] INFO  org.apache.hadoop.mapred.Merger - Merging 1 sorted segments
2016-09-23 10:48:19,260 [pool-69-thread-1] INFO  org.apache.hadoop.mapred.Merger - Down to the last merge-pass, with 1 segments left of total size: 28724 bytes
2016-09-23 10:48:19,260 [pool-69-thread-1] INFO  org.apache.hadoop.mapreduce.task.reduce.MergeManagerImpl - Merged 1 segments, 28761 bytes to disk to satisfy reduce memory limit
2016-09-23 10:48:19,260 [pool-69-thread-1] INFO  org.apache.hadoop.mapreduce.task.reduce.MergeManagerImpl - Merging 1 files, 28765 bytes from disk
2016-09-23 10:48:19,260 [pool-69-thread-1] INFO  org.apache.hadoop.mapreduce.task.reduce.MergeManagerImpl - Merging 0 segments, 0 bytes from memory into reduce
2016-09-23 10:48:19,260 [pool-69-thread-1] INFO  org.apache.hadoop.mapred.Merger - Merging 1 sorted segments
2016-09-23 10:48:19,260 [pool-69-thread-1] INFO  org.apache.hadoop.mapred.Merger - Down to the last merge-pass, with 1 segments left of total size: 28724 bytes
2016-09-23 10:48:19,261 [pool-69-thread-1] INFO  org.apache.hadoop.mapred.LocalJobRunner - 1 / 1 copied.
2016-09-23 10:48:19,264 [pool-69-thread-1] WARN  org.apache.pig.data.SchemaTupleBackend - SchemaTupleBackend has already been initialized
2016-09-23 10:48:19,266 [pool-69-thread-1] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigMapReduce$Reduce - Aliases being processed per job phase (AliasName[line,offset]): M: 1-1639[67,15] C:  R: end[67,6],tweets[67,52]
2016-09-23 10:48:19,272 [Thread-2830] INFO  org.apache.hadoop.mapred.LocalJobRunner - reduce task executor complete.
2016-09-23 10:48:19,273 [Thread-2830] WARN  org.apache.hadoop.mapred.LocalJobRunner - job_local1110765058_0021
java.lang.Exception: java.io.IOException: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:462)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:529)
Caused by: java.io.IOException: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigGenericMapReduce$Reduce.runPipeline(PigGenericMapReduce.java:479)
	at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigGenericMapReduce$Reduce.processOnePackageOutput(PigGenericMapReduce.java:442)
	at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigGenericMapReduce$Reduce.reduce(PigGenericMapReduce.java:422)
	at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigGenericMapReduce$Reduce.reduce(PigGenericMapReduce.java:269)
	at org.apache.hadoop.mapreduce.Reducer.run(Reducer.java:171)
	at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:627)
	at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:389)
	at org.apache.hadoop.mapred.LocalJobRunner$Job$ReduceTaskRunnable.run(LocalJobRunner.java:319)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at org.elasticsearch.hadoop.rest.RestClient.discoverNodes(RestClient.java:99)
	at org.elasticsearch.hadoop.rest.InitializationUtils.discoverNodesIfNeeded(InitializationUtils.java:61)
	at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.init(EsOutputFormat.java:182)
	at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.write(EsOutputFormat.java:159)
	at org.elasticsearch.hadoop.pig.EsStorage.putNext(EsStorage.java:196)
	at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigOutputFormat$PigRecordWriter.write(PigOutputFormat.java:136)
	at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigOutputFormat$PigRecordWriter.write(PigOutputFormat.java:95)
	at org.apache.hadoop.mapred.ReduceTask$NewTrackingRecordWriter.write(ReduceTask.java:558)
	at org.apache.hadoop.mapreduce.task.TaskInputOutputContextImpl.write(TaskInputOutputContextImpl.java:89)
	at org.apache.hadoop.mapreduce.lib.reduce.WrappedReducer$Context.write(WrappedReducer.java:105)
	at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigGenericMapReduce$Reduce.runPipeline(PigGenericMapReduce.java:477)
	... 12 more
2016-09-23 10:48:19,420 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - HadoopJobId: job_local1110765058_0021
2016-09-23 10:48:19,420 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - Processing aliases 1-1639,end,tweets
2016-09-23 10:48:19,420 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - detailed locations: M: 1-1639[67,15] C:  R: end[67,6],tweets[67,52]
2016-09-23 10:48:19,421 [main] WARN  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - Ooops! Some job has failed! Specify -stop_on_failure if you want Pig to stop immediately on failure.
2016-09-23 10:48:19,421 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - job job_local1110765058_0021 has failed! Stop running all dependent jobs
2016-09-23 10:48:19,421 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - 100% complete
2016-09-23 10:48:19,422 [main] INFO  org.apache.hadoop.metrics.jvm.JvmMetrics - Cannot initialize JVM Metrics with processName=JobTracker, sessionId= - already initialized
2016-09-23 10:48:19,423 [main] INFO  org.apache.hadoop.metrics.jvm.JvmMetrics - Cannot initialize JVM Metrics with processName=JobTracker, sessionId= - already initialized
2016-09-23 10:48:19,423 [main] ERROR org.apache.pig.tools.pigstats.mapreduce.MRPigStatsUtil - 1 map reduce job(s) failed!
2016-09-23 10:48:19,423 [main] INFO  org.apache.pig.tools.pigstats.mapreduce.SimplePigStats - Script Statistics: 

HadoopVersion	PigVersion	UserId	StartedAt	FinishedAt	Features
2.7.1.2.3.4.7-4	0.15.0.2.3.4.7-4	root	2016-09-23 10:48:18	2016-09-23 10:48:19	HASH_JOIN,GROUP_BY,FILTER,CROSS

Some jobs have failed! Stop running all dependent jobs

Job Stats (time in seconds):
JobId	Maps	Reduces	MaxMapTime	MinMapTime	AvgMapTime	MedianMapTime	MaxReduceTime	MinReduceTime	AvgReduceTime	MedianReducetime	Alias	Feature	Outputs
job_local488992341_0019	2	1	n/a	n/a	n/a	n/a	n/a	n/a	n/a	n/a	dictionary,extracted,lowertweets,positivetweets,ptweets,sentiment,twitter,words	HASH_JOIN	
job_local54393684_0020	2	1	n/a	n/a	n/a	n/a	n/a	n/a	n/a	n/a	A,c,companys,epoch,res		

Failed Jobs:
JobId	Alias	Feature	Message	Outputs
job_local1110765058_0021	1-1639,end,tweets	GROUP_BY	Message: Job failed!	google_1474605658_265444570440/tweets,

Input(s):
Successfully read 8221 records from: "/root/Twitter_Pipeline_Using_Pig/dictionary.txt"
Successfully read 260 records from: "/root/Twitter_Pipeline_Using_Pig/tweets/*"
Successfully read 5 records from: "/root/Twitter_Pipeline_Using_Pig/companys.txt"

Output(s):
Failed to produce result in "google_1474605658_265444570440/tweets"

Counters:
Total records written : 0
Total bytes written : 0
Spillable Memory Manager spill count : 0
Total bags proactively spilled: 0
Total records proactively spilled: 0

Job DAG:
job_local488992341_0019	->	job_local54393684_0020,
job_local54393684_0020	->	job_local1110765058_0021,
job_local1110765058_0021


2016-09-23 10:48:19,424 [main] INFO  org.apache.hadoop.metrics.jvm.JvmMetrics - Cannot initialize JVM Metrics with processName=JobTracker, sessionId= - already initialized
2016-09-23 10:48:19,424 [main] INFO  org.apache.hadoop.metrics.jvm.JvmMetrics - Cannot initialize JVM Metrics with processName=JobTracker, sessionId= - already initialized
2016-09-23 10:48:19,424 [main] INFO  org.apache.hadoop.metrics.jvm.JvmMetrics - Cannot initialize JVM Metrics with processName=JobTracker, sessionId= - already initialized
2016-09-23 10:48:19,426 [main] INFO  org.apache.hadoop.metrics.jvm.JvmMetrics - Cannot initialize JVM Metrics with processName=JobTracker, sessionId= - already initialized
2016-09-23 10:48:19,426 [main] INFO  org.apache.hadoop.metrics.jvm.JvmMetrics - Cannot initialize JVM Metrics with processName=JobTracker, sessionId= - already initialized
2016-09-23 10:48:19,427 [main] INFO  org.apache.hadoop.metrics.jvm.JvmMetrics - Cannot initialize JVM Metrics with processName=JobTracker, sessionId= - already initialized
2016-09-23 10:48:19,428 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - Some jobs have failed! Stop running all dependent jobs

```

**ES mapping Script:-**

```
curl -XPUT 'http://localhost:9200indexname/_mapping/tweets' -d '
{
    "tweets" : {
        "properties" : {
                "created_at" : {"type" : "string", "store" : true },
                "id" : {"type" : "string", "store" : true },
                "id_str" : {"type" : "string", "store" : true },
                "text" : {"type" : "string", "store" : true },
                "source" : {"type" : "string", "store" : true },
                    "entities" :{
			"type": "nested",
      			"properties": {
				"urls": {"type": "string"},
				"hashtags": {"type": "string"}, 
				"user_mentions": {"type": "string"},  
				"symbols": {"type": "string"} 
				      }
				} ,
                "favorited" : {"type" : "boolean", "store" : true },
                "favorite_count" : {"type" : "long", "store" : true },
                "retweet_count" : {"type" : "long", "store" : true },
                "retweeted" : {"type" : "boolean", "store" : true }
                
                     }
		}
}'
```

**Versions:-**

HadoopVersion	2.7.1.2.3.4.7-4
PigVersion	        0.15.0.2.3.4.7-4
Es version:-2.2.0
Es hadoop versions:-         elasticsearch-hadoop-2.2.0-rc1.jar
                                          elasticsearch-hadoop-pig-2.2.0-rc1.jar

Please help.

**Comment by jbaiera** [comment]
Thank you for posting the detailed error logs. It seems that this is an old issue with parsing IP information during the node discovery phase. I see that you are using an older candidate release. There had been significant stability improvements between v2.2.0-rc1 and v2.2.0. Upgrading to v2.2.0 should fix this.
