### ISSUE TITLE
ES 2.4 - Issue with apache storm bolt writing to ES cluster enabled with SSL and self signed cert

### ISSUE THREAD

**Issue by shoebamer** [elastic/elasticsearch-hadoop#851]
### What kind an issue is this?
- [ ] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.  
  The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
  Often a solution already exists! Don’t send pull requests to implement new features without 
  first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

Description
Using elasticsearch-hadoop jar storm bolts to write to Elasticsearch running with SSL, having self signed cert , and no authentication is not working. 

I am trying to connect using the jar and have added the keystore/trustore into the classpath as mentioned in the ES reference.

To communicate with ES I am using only keystore.
### Steps to reproduce

Code:
es.host.name=https://<IP>:PORT
es.net.ssl=true
es.net.ssl.cert.allow.self.signed=true
es.net.ssl.keystore.location=/keystore.jks (the file is in jar in the same location)
es.net.ssl.keystore.pass=<pwd for keystore>

```
Test/code snippet
```

Strack trace:
I always receive : EsIllegalArgumentException asking to set property wan.only=true but the root cause shows as follows:

```
Stack trace goes here
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
     at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:146) ~[?:1.8.0_73]
        at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131) ~[?:1.8.0_73]
        at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280) ~[?:1.8.0_73]
        at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382) ~[?:1.8.0_73]
        at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:230) ~[?:1.8.0_73]
        at sun.security.validator.Validator.validate(Validator.java:260) ~[?:1.8.0_73]
        at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[?:1.8.0_73]
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229) ~[?:1.8.0_73]
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:105) ~[?:1.8.0_73]
        at org.elasticsearch.hadoop.rest.commonshttp.SSLSocketFactory$TrustManagerDelegate.checkServerTrusted(SSLSocketFactory.java:71) ~[stormjar.jar:?]
        at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:922) ~[?:1.8.0_73]
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1491) ~[?:1.8.0_73]
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216) ~[?:1.8.0_73]
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979) ~[?:1.8.0_73]
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:914) ~[?:1.8.0_73]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062) ~[?:1.8.0_73]
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375) ~[?:1.8.0_73]
        at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:747) ~[?:1.8.0_73]
        at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123) ~[?:1.8.0_73]
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[?:1.8.0_73]
```
### Version Info

OS:         :  Linux
JVM         :  1.8
Hadoop/Spark:  
ES-Hadoop   :  2.4
ES          :  2.3.3

**Comment by jbaiera** [comment]
Self signed certificates are only trusted if the certificate chain's length is equal to 1. Considering the stack trace provided, it seems that the `es.net.ssl.cert.allow.self.signed` property was correctly picked up (`SSLSocketFactory$TrustManagerDelegate` in trace) but for the code to execute the next steps of trust verification (`checkServerTrusted` method) the Certificate chain that it is checking must not have had a length of 1. I would double check the Certificates that are being provided to ensure that they are the correct format for being self signed.

**Comment by jbaiera** [comment]
Closing this as there has been no response on the issue.
