### ISSUE TITLE
Pig to ElasticSearch Error

### ISSUE THREAD

**Issue by MohanBunny** [elastic/elasticsearch-hadoop#855]
Trying to create index of tweets in elasticsearch,
but got the **java.lang.Exception: java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.hadoop.util.Version**

Script:-
`STORE A INTO 'indexname' USING org.elasticsearch.hadoop.pig.EsStorage('es.nodes=localhost','es.port:9200','es.mapping.pig.tuple.use.field.names = true');`

```
curl -XPUT 'http://localhost:9200/indexname/_mapping/tweets' -d '
{
    "tweets" : {
        "properties" : {
                "created_at" : {"type" : "string", "store" : true },
                "id" : {"type" : "string", "store" : true },
                "id_str" : {"type" : "string", "store" : true },
                "text" : {"type" : "string", "store" : true },
                "source" : {"type" : "string", "store" : true },
                    "entities" :{
            "type": "nested",
                "properties": {
                "urls": {"type": "string"},
                "hashtags": {"type": "string"}, 
                "user_mentions": {"type": "string"},  
                "symbols": {"type": "string"} 
                      }
                } ,
                "favorited" : {"type" : "boolean", "store" : true },
                "favorite_count" : {"type" : "long", "store" : true },
                "retweet_count" : {"type" : "long", "store" : true },
                "retweeted" : {"type" : "boolean", "store" : true }

                     }
        }
}'
```

**Logs:-**

```
2016-09-26 13:03:10,571 [Thread-2455] WARN  org.apache.hadoop.mapred.LocalJobRunner - job_local417538161_0018
java.lang.Exception: java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.hadoop.util.Version
    at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:462)
    at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:529)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.hadoop.util.Version
    at org.elasticsearch.hadoop.rest.RestService.createWriter(RestService.java:372)
    at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.init(EsOutputFormat.java:173)
    at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.write(EsOutputFormat.java:149)
    at org.elasticsearch.hadoop.pig.EsStorage.putNext(EsStorage.java:192)
    at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigOutputFormat$PigRecordWriter.write(PigOutputFormat.java:136)
    at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigOutputFormat$PigRecordWriter.write(PigOutputFormat.java:95)
    at org.apache.hadoop.mapred.ReduceTask$NewTrackingRecordWriter.write(ReduceTask.java:558)
    at org.apache.hadoop.mapreduce.task.TaskInputOutputContextImpl.write(TaskInputOutputContextImpl.java:89)
    at org.apache.hadoop.mapreduce.lib.reduce.WrappedReducer$Context.write(WrappedReducer.java:105)
    at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigGenericMapReduce$Reduce.runPipeline(PigGenericMapReduce.java:477)
    at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigGenericMapReduce$Reduce.processOnePackageOutput(PigGenericMapReduce.java:442)
    at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigGenericMapReduce$Reduce.reduce(PigGenericMapReduce.java:422)
    at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigGenericMapReduce$Reduce.reduce(PigGenericMapReduce.java:269)
    at org.apache.hadoop.mapreduce.Reducer.run(Reducer.java:171)
    at org.apache.hadoop.mapred.ReduceTask.runNewReducer(ReduceTask.java:627)
    at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:389)
    at org.apache.hadoop.mapred.LocalJobRunner$Job$ReduceTaskRunnable.run(LocalJobRunner.java:319)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
2016-09-26 13:03:10,724 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - HadoopJobId: job_local417538161_0018
2016-09-26 13:03:10,724 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - Processing aliases 1-1588,end,tweets
2016-09-26 13:03:10,724 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - detailed locations: M: 1-1588[66,15] C:  R: end[66,6],tweets[66,52]
2016-09-26 13:03:10,725 [main] WARN  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - Ooops! Some job has failed! Specify -stop_on_failure if you want Pig to stop immediately on failure.
2016-09-26 13:03:10,725 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - job job_local417538161_0018 has failed! Stop running all dependent jobs
2016-09-26 13:03:10,725 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - 100% complete
2016-09-26 13:03:10,726 [main] INFO  org.apache.hadoop.metrics.jvm.JvmMetrics - Cannot initialize JVM Metrics with processName=JobTracker, sessionId= - already initialized
2016-09-26 13:03:10,727 [main] INFO  org.apache.hadoop.metrics.jvm.JvmMetrics - Cannot initialize JVM Metrics with processName=JobTracker, sessionId= - already initialized
2016-09-26 13:03:10,727 [main] ERROR org.apache.pig.tools.pigstats.mapreduce.MRPigStatsUtil - 1 map reduce job(s) failed!
2016-09-26 13:03:10,727 [main] INFO  org.apache.pig.tools.pigstats.mapreduce.SimplePigStats - Script Statistics: 

HadoopVersion   PigVersion  UserId  StartedAt   FinishedAt  Features
2.7.1.2.3.4.7-4 0.15.0.2.3.4.7-4    root    2016-09-26 13:03:09 2016-09-26 13:03:10 HASH_JOIN,GROUP_BY,FILTER,CROSS

Some jobs have failed! Stop running all dependent jobs

Job Stats (time in seconds):
JobId   Maps    Reduces MaxMapTime  MinMapTime  AvgMapTime  MedianMapTime   MaxReduceTime   MinReduceTime   AvgReduceTime   MedianReducetime    Alias   Feature Outputs
job_local1831815743_0017    2   1   n/a n/a n/a n/a n/a n/a n/a n/a A,c,companys,epoch,res      
job_local1834882115_0016    2   1   n/a n/a n/a n/a n/a n/a n/a n/a dictionary,extracted,lowertweets,positivetweets,ptweets,sentiment,twitter,words HASH_JOIN   

Failed Jobs:
JobId   Alias   Feature Message Outputs
job_local417538161_0018 1-1588,end,tweets   GROUP_BY    Message: Job failed!    indexname/tweets,

Input(s):
Successfully read 260 records from: "/root/Twitter_Pipeline_Using_Pig/tweets/*"
Successfully read 8221 records from: "/root/Twitter_Pipeline_Using_Pig/dictionary.txt"
Successfully read 5 records from: "/root/Twitter_Pipeline_Using_Pig/companys.txt"

Output(s):
Failed to produce result in "indexname/tweets"

Counters:
Total records written : 0
Total bytes written : 0
Spillable Memory Manager spill count : 0
Total bags proactively spilled: 0
Total records proactively spilled: 0

Job DAG:
job_local1834882115_0016    ->  job_local1831815743_0017,
job_local1831815743_0017    ->  job_local417538161_0018,
job_local417538161_0018


2016-09-26 13:03:10,728 [main] INFO  org.apache.hadoop.metrics.jvm.JvmMetrics - Cannot initialize JVM Metrics with processName=JobTracker, sessionId= - already initialized
2016-09-26 13:03:10,728 [main] INFO  org.apache.hadoop.metrics.jvm.JvmMetrics - Cannot initialize JVM Metrics with processName=JobTracker, sessionId= - already initialized
2016-09-26 13:03:10,728 [main] INFO  org.apache.hadoop.metrics.jvm.JvmMetrics - Cannot initialize JVM Metrics with processName=JobTracker, sessionId= - already initialized
2016-09-26 13:03:10,730 [main] INFO  org.apache.hadoop.metrics.jvm.JvmMetrics - Cannot initialize JVM Metrics with processName=JobTracker, sessionId= - already initialized
2016-09-26 13:03:10,730 [main] INFO  org.apache.hadoop.metrics.jvm.JvmMetrics - Cannot initialize JVM Metrics with processName=JobTracker, sessionId= - already initialized
2016-09-26 13:03:10,731 [main] INFO  org.apache.hadoop.metrics.jvm.JvmMetrics - Cannot initialize JVM Metrics with processName=JobTracker, sessionId= - already initialized
2016-09-26 13:03:10,732 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - Some jobs have failed! Stop running all dependent jobs
```

Pig Version:-  0.15.0.2.3.4.7-4
es-hadoop version:- elasticsearch-hadoop-pig-2.2.0.jar
es version:- elasticsearch-2.2.0

**Comment by jbaiera** [comment]
That is very strange, especially since Pig was able to load `EsStorage`, `EsOutputFormat` and the `RestService` classes just fine. I would suggest making sure that the jar is correctly downloaded by checking it's md5 and that it is installed correctly using [the steps included in the documentation](https://www.elastic.co/guide/en/elasticsearch/hadoop/current/pig.html#pig-installation).
```
$> md5 elasticsearch-hadoop-pig-2.2.0.jar 
MD5 (elasticsearch-hadoop-pig-2.2.0.jar) = b21ca1d9699f34e184288cad84331a1a
```

**Comment by ebuildy** [comment]
What version of Java do you have?

**Comment by jbaiera** [comment]
Closing due to lack of feedback.
