### ISSUE TITLE
Cannot index a child type using saveJsonToEs as resource string contains "?parent=" routing

### ISSUE THREAD

**Issue by ipande** [elastic/elasticsearch-hadoop#873]
### What kind an issue is this?

- [x] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

Description: I am trying to write a parent-child mapping to elastic-search. The API requires specifying the parent ID as a part of the [query](https://www.elastic.co/guide/en/elasticsearch/guide/current/indexing-parent-child.html).

The resource.java code throws an exception at : Cannot specify a query in the target index AND through es.query.  This is because of the [code block](https://github.com/elastic/elasticsearch-hadoop/blob/master/mr/src/main/java/org/elasticsearch/hadoop/rest/Resource.java#L49) checks for "?" in the resource string and then checks if es.query is set and throws the exception. I'm not setting "es.query" in my sparkConf.

I even tried checking whether my sparkConf contains the es.query property and got nothing.
sc.getConf.get("es.query")} => None

### Steps to reproduce

Code:
val employeeJSON = """{
                           |        "name":  "John Doe",
                           |        "dob":   "1970-10-24",
                           |        "hobby": "hiking"
                           |      }"""
     val empID = 1234
     val parentQry = "?parent=london"
     sc.makeRDD(Seq(employeeJSON)).saveJsonToEs(s"/company/employee/$empID$parentQry")

```
Test/code snippet
```

Strack trace:
resourceString=/company/employee/1234?parent=london
Trying to save employeeJSON to ES
16/10/20 15:19:30 INFO SparkContext: Starting job: runJob at EsSpark.scala:84
.....
16/10/20 15:19:31 INFO EsRDDWriter: Writing to [company/employee]
16/10/20 15:19:31 INFO EsRDDWriter: Writing to [company/employee]
16/10/20 15:19:31 ERROR Executor: Exception in task 8.0 in stage 11.0 (TID 670)
org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot specify a query in the target index AND through es.query
	at org.elasticsearch.hadoop.rest.Resource.<init>(Resource.java:48)
	at org.elasticsearch.hadoop.rest.RestRepository.<init>(RestRepository.java:109)
	at org.elasticsearch.hadoop.rest.RestService.initSingleIndex(RestService.java:410)
	at org.elasticsearch.hadoop.rest.RestService.createWriter(RestService.java:400)
	at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:40)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:84)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:84)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
16/10/20 15:19:31 ERROR Executor: Exception in task 13.0 in stage 11.0 (TID 675)
org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot specify a query in the target index AND through es.query
	at org.elasticsearch.hadoop.rest.Resource.<init>(Resource.java:48)
	at org.elasticsearch.hadoop.rest.RestRepository.<init>(RestRepository.java:109)
	at org.elasticsearch.hadoop.rest.RestService.initSingleIndex(RestService.java:410)
	at org.elasticsearch.hadoop.rest.RestService.createWriter(RestService.java:400)
	at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:40)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:84)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:84)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```
Stack trace goes here
``` 

### Version Info

OS:         :  AWS instance
JVM         :  Dont know
Hadoop/Spark: 1.6.1  
ES-Hadoop   :  2.4.+
ES          :  1.7.1

**Comment by jbaiera** [comment]
Could you fill out the rest of the template for the issue? It requests information that is vital in reproducing the problem. Thanks!

**Comment by ipande** [comment]
@jbaiera Thanks for your reply. I updated the issue description with code to reproduce the issue.
Let me know if you need any more info. Thanks :)

**Comment by jbaiera** [comment]
Ah, thank you for the added information! I'd like to point out that EsSpark does not accept the parent parameter as a part of the resource string. The resource string should be used to specify the index and type only. The value or field to use for the parent id is added as a part of the configuration instead. You can specify the name of a field to read for the id, or you can specify a constant value using the `<>` braces. Try the following:

```
val empID = 1234
val employeeJSON = s"""{
    |     "id": "$empID"
    |     "name": "John Doe",
    |     "dob": "1970-10-24",
    |     "hobby": "hiking"
    | }"""
val conf = Map("es.mapping.id" -> "id", "es.mapping.parent" -> "<london>")
sc.makeRDD(Seq(employeeJSON)).saveJsonToEs("/company/employee", conf)
```

You can also tell the connector to dynamically select one of the fields in the document as the value to use for the parent id. This allows you to control the traffic of multiple documents that may have different parents. Instead of putting the value a set of `<>` braces (to signal a constant value), you just place the name of the field to use. To wit:

```
val empID = 1234
val employeeJSON = s"""{
    |     "id": "$empID"
    |     "name": "John Doe",
    |     "dob": "1970-10-24",
    |     "hobby": "hiking",
    |     "parentField": "london"
    | }"""
val conf = Map("es.mapping.id" -> "id", "es.mapping.parent" -> "parentField")
sc.makeRDD(Seq(employeeJSON)).saveJsonToEs("/company/employee", conf)
```

 I don't believe this is a bug, just a poorly worded error message.

**Comment by ipande** [comment]
Like the first approach better, because I read the parentIDs from another source.
But it does not seem to work. In my example here's the code:
`val empID = 1234
     val employeeJSON = s"""{
                           |        "id": "$empID"
                           |        "name":  "John Doe",
                           |        "dob":   "1970-10-24",
                           |        "hobby": "hiking"
                           |      }"""

     val parent = "<london>"
     val conf = Map("ex.mapping.id" -> "id", "es.mapping.parent" -> s"$parent")
     println(s"parent=$parent conf=$conf")
     println(s"Trying to save employeeJSON to ES")
     sc.makeRDD(Seq(employeeJSON)).saveJsonToEs("/company/employee",conf)
`

I get the following stacktrace:
`parent=<london> conf=Map(ex.mapping.id -> id, es.mapping.parent -> <london>)
Trying to save employeeJSON to ES
16/10/20 17:28:44 INFO SparkContext: Starting job: runJob at EsSpark.scala:84
16/10/20 17:28:45 INFO EsRDDWriter: Writing to [company/employee]
16/10/20 17:28:45 INFO EsRDDWriter: Writing to [company/employee]
16/10/20 17:28:45 INFO EsRDDWriter: Writing to [company/employee]
16/10/20 17:28:45 INFO EsRDDWriter: Writing to [company/employee]
....
16/10/20 17:28:45 ERROR TaskContextImpl: Error in TaskCompletionListener
org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: JsonParseException[Unexpected character ('|' (code 124)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: [B@56583be0; line: 1, column: 29]]; fragment[rent":"london"}}
{
 ]
	at org.elasticsearch.hadoop.rest.RestClient.checkResponse(RestClient.java:478)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:436)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:426)
	at org.elasticsearch.hadoop.rest.RestClient.bulk(RestClient.java:153)
	at org.elasticsearch.hadoop.rest.RestRepository.tryFlush(RestRepository.java:225)
	at org.elasticsearch.hadoop.rest.RestRepository.flush(RestRepository.java:248)
	at org.elasticsearch.hadoop.rest.RestRepository.close(RestRepository.java:267)
	at org.elasticsearch.hadoop.rest.RestService$PartitionWriter.close(RestService.java:130)
	at org.elasticsearch.spark.rdd.EsRDDWriter$$anonfun$write$1.apply$mcV$sp(EsRDDWriter.scala:42)
	at org.apache.spark.TaskContextImpl$$anon$2.onTaskCompletion(TaskContextImpl.scala:68)
	at org.apache.spark.TaskContextImpl$$anonfun$markTaskCompleted$1.apply(TaskContextImpl.scala:79)
	at org.apache.spark.TaskContextImpl$$anonfun$markTaskCompleted$1.apply(TaskContextImpl.scala:77)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.TaskContextImpl.markTaskCompleted(TaskContextImpl.scala:77)
	at org.apache.spark.scheduler.Task.run(Task.scala:91)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by ipande** [comment]
@jbaiera Even the second approach is not working. Code:
` 
val employeeJSON = """{
                             |     "id": "1234"
                             |     "name": "John Doe",
                             |     "dob": "1970-10-24",
                             |     "hobby": "hiking"
                             |     "parentField": "london"
                             | }"""
      val conf = Map("es.mapping.id" -> "id", "es.mapping.parent" -> "parentField")
      println("saving employee JSON to ES")
      sc.makeRDD(Seq(employeeJSON)).saveJsonToEs("/company/employee", conf)
`

Stacktrace:
`
16/10/20 17:46:35 INFO TaskSetManager: Finished task 18.0 in stage 11.0 (TID 680) in 289 ms on localhost (31/32)
16/10/20 17:46:35 ERROR Executor: Exception in task 31.0 in stage 11.0 (TID 693)
org.elasticsearch.hadoop.serialization.EsHadoopSerializationException: org.codehaus.jackson.JsonParseException: Unexpected character ('|' (code 124)): was expecting double-quote to start field name
 at [Source: [B@5947a66b; line: 2, column: 31]
	at org.elasticsearch.hadoop.serialization.json.JacksonJsonParser.nextToken(JacksonJsonParser.java:95)
	at org.elasticsearch.hadoop.serialization.ParsingUtils.doFind(ParsingUtils.java:168)
	at org.elasticsearch.hadoop.serialization.ParsingUtils.values(ParsingUtils.java:151)
	at org.elasticsearch.hadoop.serialization.field.JsonFieldExtractors.process(JsonFieldExtractors.java:201)
	at org.elasticsearch.hadoop.serialization.bulk.JsonTemplatedBulk.preProcess(JsonTemplatedBulk.java:64)
	at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.write(TemplatedBulk.java:54)
	at org.elasticsearch.hadoop.rest.RestRepository.writeToIndex(RestRepository.java:163)
	at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:49)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:84)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:84)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

Thanks for your help in advance.

**Comment by jbaiera** [comment]
you need to add a call to `stripMargin` on the string with the JSON code in it. I'll update my response with the correct call.

**Comment by ipande** [comment]
@jbaiera thanks, waiting for it.

**Comment by jbaiera** [comment]
@ipande I've updated the original post https://github.com/elastic/elasticsearch-hadoop/issues/873#issuecomment-255160200

**Comment by ipande** [comment]
@jbaiera still does not work.
`
 val empID = 1234
      val employeeJSON = s"""{
                             |     "id": "$empID"
                             |     "name": "John Doe",
                             |     "dob": "1970-10-24",
                             |     "hobby": "hiking"
                             | }""".stripMargin
      val conf = Map("es.mapping.id" -> "id", "es.mapping.parent" -> "<london>")
      sc.makeRDD(Seq(employeeJSON)).saveJsonToEs("/company/employee", conf)
      println(s"Setting sparkConf for parent:$parentQuery")
`

Stacktrace:
`
16/10/20 18:42:21 ERROR Executor: Exception in task 31.0 in stage 11.0 (TID 692)
org.elasticsearch.hadoop.serialization.EsHadoopSerializationException: org.codehaus.jackson.JsonParseException: Unexpected character ('"' (code 34)): was expecting comma to separate OBJECT entries
 at [Source: [B@776b49e6; line: 3, column: 7]
	at org.elasticsearch.hadoop.serialization.json.JacksonJsonParser.nextToken(JacksonJsonParser.java:95)
	at org.elasticsearch.hadoop.serialization.ParsingUtils.doFind(ParsingUtils.java:168)
	at org.elasticsearch.hadoop.serialization.ParsingUtils.values(ParsingUtils.java:151)
	at org.elasticsearch.hadoop.serialization.field.JsonFieldExtractors.process(JsonFieldExtractors.java:201)
	at org.elasticsearch.hadoop.serialization.bulk.JsonTemplatedBulk.preProcess(JsonTemplatedBulk.java:64)
	at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.write(TemplatedBulk.java:54)
	at org.elasticsearch.hadoop.rest.RestRepository.writeToIndex(RestRepository.java:163)
	at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:49)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:84)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:84)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.codehaus.jackson.JsonParseException: Unexpected character ('"' (code 34)): was expecting comma to separate OBJECT entries
 at [Source: [B@776b49e6; line: 3, column: 7]
	at org.codehaus.jackson.JsonParser._constructError(JsonParser.java:1433)
	at org.codehaus.jackson.impl.JsonParserMinimalBase._reportError(JsonParserMinimalBase.java:521)
	at org.codehaus.jackson.impl.JsonParserMinimalBase._reportUnexpectedChar(JsonParserMinimalBase.java:442)
	at org.codehaus.jackson.impl.Utf8StreamParser.nextToken(Utf8StreamParser.java:482)
	at org.elasticsearch.hadoop.serialization.json.JacksonJsonParser.nextToken(JacksonJsonParser.java:93)
	... 15 more
`

**Comment by ipande** [comment]
@jbaiera Still does not work. Code:
`
      val empID = 1234
      val employeeJSON = s"""{
                             |     "id": "$empID",
                             |     "name": "John Doe",
                             |     "dob": "1970-10-24",
                             |     "hobby": "hiking"
                             | }""".stripMargin
      println(s"JSON string: ")
      val conf = Map("es.mapping.id" -> "id", "es.mapping.parent" -> "<london>")
      sc.makeRDD(Seq(employeeJSON)).saveJsonToEs("/company/employee", conf)
`

Stacktrace:

`
16/10/20 18:54:57 ERROR TaskContextImpl: Error in TaskCompletionListener
org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: JsonParseException[Unexpected character (':' (code 58)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: [B@5eb89d09; line: 1, column: 11]]; fragment[{"index":{"_id":]
	at org.elasticsearch.hadoop.rest.RestClient.checkResponse(RestClient.java:478)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:436)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:426)
	at org.elasticsearch.hadoop.rest.RestClient.bulk(RestClient.java:153)
	at org.elasticsearch.hadoop.rest.RestRepository.tryFlush(RestRepository.java:225)
	at org.elasticsearch.hadoop.rest.RestRepository.flush(RestRepository.java:248)
	at org.elasticsearch.hadoop.rest.RestRepository.close(RestRepository.java:267)
	at org.elasticsearch.hadoop.rest.RestService$PartitionWriter.close(RestService.java:130)
	at org.elasticsearch.spark.rdd.EsRDDWriter$$anonfun$write$1.apply$mcV$sp(EsRDDWriter.scala:42)
	at org.apache.spark.TaskContextImpl$$anon$2.onTaskCompletion(TaskContextImpl.scala:68)
	at org.apache.spark.TaskContextImpl$$anonfun$markTaskCompleted$1.apply(TaskContextImpl.scala:79)
	at org.apache.spark.TaskContextImpl$$anonfun$markTaskCompleted$1.apply(TaskContextImpl.scala:77)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.TaskContextImpl.markTaskCompleted(TaskContextImpl.scala:77)
	at org.apache.spark.scheduler.Task.run(Task.scala:91)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by jbaiera** [comment]
You must make sure that the json is properly formatted. if you have the triple string on multiple lines, the pipes must be removed by the `stripMargin` call. If not, then the pipes must be removed by you.

**Comment by ipande** [comment]
Seems like the string is properly formatted. This is from my sbt terminal:

scala> :paste
// Entering paste mode (ctrl-D to finish)

val employeeJSON = s"""{
                             |     "id": "1234",
                             |     "name": "John Doe",
                             |     "dob": "1970-10-24",
                             |     "hobby": "hiking"
                             | }""".stripMargin

// Exiting paste mode, now interpreting.

employeeJSON: String =
{
     "id": "1234",
     "name": "John Doe",
     "dob": "1970-10-24",
     "hobby": "hiking"
 }

**Comment by ipande** [comment]
@jbaiera I was able to figure it out.. Thanks for the help :)
Btw, the writing to a parent-child index + type combo is not documented anywhere in the elastic-search hadoop library documentation. Would probably be a good idea to do it.

Thanks,
Ishan
