### ISSUE TITLE
Using java write works but read is not working.

### ISSUE THREAD

**Issue by mozinrat** [elastic/elasticsearch-hadoop#882]
### What kind an issue is this?

BUG REPORT
### Issue description

Using java write works but read is not working.
### Steps to reproduce

Code:

```
//connecting on elasticsearch docker container locally

SparkSession spark = getSparkSession(appName, master, new String[]{jars}, hdfs);
        session.sparkContext().conf().set("es.nodes", elasticHost);
        session.sparkContext().conf().set("es.port", elasticPort);
        session.sparkContext().conf().set("es.nodes.wan.only", "true");
//reading dataset from parquet
 Dataset<Row> df = spark.sqlContext().read().parquet(params.getPath()).select(params.getColumnName()).dropDuplicates();

// saving to elasticsearch, this works fine                
JavaEsSparkSQL.saveToEs(df, "index/type_1"));

// reading dataset back from elasticsearch
 Dataset<Row> es = spark.read().format("es").load("index/type_1");

// above line while executing on spark hangs at 
BlockManagerMasterEndpoint: Registering block manager 172.18.0.8:32897 with 366.3 MB RAM, BlockManagerId(1, 172.18.0.8, 32897)

and later shows
 HttpMethodDirector: I/O exception (java.net.ConnectException) caught when processing request: Operation timed out

```

Strack trace:

```
 16/10/25 14:27:16 INFO BlockManagerMasterEndpoint: Registering block manager 172.18.0.8:32897 with 366.3 MB RAM, BlockManagerId(1, 172.18.0.8, 32897)
16/10/25 14:28:06 ERROR TaskSchedulerImpl: Lost executor 2 on 172.18.0.2: Remote RPC client disassociated. Likely due to containers exceeding thresholds, or network issues. Check driver logs for WARN messages.
16/10/25 14:28:06 INFO DAGScheduler: Executor lost: 2 (epoch 0)
16/10/25 14:28:06 INFO BlockManagerMasterEndpoint: Trying to remove executor 2 from BlockManagerMaster.
16/10/25 14:28:06 INFO BlockManagerMasterEndpoint: Removing block manager BlockManagerId(2, 172.18.0.2, 39763)
16/10/25 14:28:06 INFO BlockManagerMaster: Removed 2 successfully in removeExecutor
16/10/25 14:28:06 INFO DAGScheduler: Shuffle files lost for executor: 2 (epoch 0)
16/10/25 14:28:07 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20161025085712-0011/2 is now EXITED (Command exited with code 1)
16/10/25 14:28:07 INFO StandaloneSchedulerBackend: Executor app-20161025085712-0011/2 removed: Command exited with code 1
16/10/25 14:28:07 INFO BlockManagerMaster: Removal of executor 2 requested
16/10/25 14:28:07 INFO BlockManagerMasterEndpoint: Trying to remove executor 2 from BlockManagerMaster.
16/10/25 14:28:07 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asked to remove non-existent executor 2
16/10/25 14:28:07 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20161025085712-0011/3 on worker-20161025055112-172.18.0.2-37262 (172.18.0.2:37262) with 4 cores
16/10/25 14:28:07 INFO StandaloneSchedulerBackend: Granted executor ID app-20161025085712-0011/3 on hostPort 172.18.0.2:37262 with 4 cores, 1024.0 MB RAM
16/10/25 14:28:07 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20161025085712-0011/3 is now RUNNING
16/10/25 14:28:10 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Registered executor NettyRpcEndpointRef(null) (10.111.30.31:49239) with ID 3
16/10/25 14:28:10 INFO BlockManagerMasterEndpoint: Registering block manager 172.18.0.2:42784 with 366.3 MB RAM, BlockManagerId(3, 172.18.0.2, 42784)
16/10/25 14:28:29 INFO HttpMethodDirector: I/O exception (java.net.ConnectException) caught when processing request: Operation timed out
16/10/25 14:28:29 INFO HttpMethodDirector: Retrying request

```
### Version Info

OS:         :  mac os sierra
JVM         :  1.8
Hadoop/Spark:    spark 2.0.1, hadoop 2.7.3
ES-Hadoop   :  5.0.0-rc1
ES          :  2.3.5

**Comment by jbaiera** [comment]
@mozinrat Could you increase the logging level to `TRACE` for the `org.elasticsearch.hadoop.rest` package and post the full set of logs here?

**Comment by mozinrat** [comment]
```
16-10-26 04:49:46 TRACE HttpMethodBase:1579 - enter HttpMethodBase.processResponseHeaders(HttpState, HttpConnection)
16-10-26 04:49:46 TRACE HttpMethodBase:1615 - enter HttpMethodBase.processCookieHeaders(Header[], HttpState, HttpConnection)
16-10-26 04:49:46 TRACE HttpMethodBase:1781 - enter HttpMethodBase.readResponseBody(HttpState, HttpConnection)
16-10-26 04:49:46 TRACE HttpMethodBase:1816 - enter HttpMethodBase.readResponseBody(HttpConnection)
16-10-26 04:49:46 TRACE HttpConnection:857 - enter HttpConnection.getResponseInputStream()
16-10-26 04:49:46 TRACE HttpMethodBase:2281 - enter HttpMethodBase.canResponseHaveBody(int)
16-10-26 04:49:46 DEBUG HttpMethodBase:685 - Buffering response body
16-10-26 04:49:46 DEBUG content:84 - << "{"cluster_name":"elasticsearch","nodes":{"hw493m5wRuaXdZ4-3MelGg":{"name":"Unus the Untouchable","transport_address":"172.18.0.3:9300","host":"172.18.0.3","ip":"172.18.0.3","version":"2.3.5","build":"90f439f","http_address":"172.18.0.3:9200","http":{"bound_address":["[::]:9200"],"publish_address":"172.18.0.3:9200","max_content_length_in_bytes":104857600}}}}"
16-10-26 04:49:46 DEBUG HttpMethodBase:1024 - Resorting to protocol version default close connection policy
16-10-26 04:49:46 DEBUG HttpMethodBase:1028 - Should NOT close connection, using HTTP/1.1
16-10-26 04:49:46 TRACE HttpConnection:874 - enter HttpConnection.isResponseAvailable()
16-10-26 04:49:46 TRACE HttpConnection:1174 - enter HttpConnection.releaseConnection()
16-10-26 04:49:46 DEBUG HttpConnection:1178 - Releasing connection back to connection manager.
16-10-26 04:49:46 TRACE HttpMethodBase:2324 - enter getContentCharSet( Header contentheader )
16-10-26 04:49:46 TRACE HeaderElement:238 - enter HeaderElement.parseElements(String)
16-10-26 04:49:46 TRACE HeaderElement:194 - enter HeaderElement.parseElements(char[])
16-10-26 04:49:46 TRACE HeaderElement:279 - enter HeaderElement.getParameterByName(String)
16-10-26 04:49:46 TRACE CommonsHttpTransport:479 - Rx @[192.168.0.101] [200-OK] [{"cluster_name":"elasticsearch","nodes":{"hw493m5wRuaXdZ4-3MelGg":{"name":"Unus the Untouchable","transport_address":"172.18.0.3:9300","host":"172.18.0.3","ip":"172.18.0.3","version":"2.3.5","build":"90f439f","http_address":"172.18.0.3:9200","http":{"bound_address":["[::]:9200"],"publish_address":"172.18.0.3:9200","max_content_length_in_bytes":104857600}}}}]
16-10-26 04:49:46 DEBUG HttpMethodBase:777 - re-creating response stream from byte array
16-10-26 04:49:46 DEBUG HttpMethodBase:777 - re-creating response stream from byte array
16-10-26 04:49:46 DEBUG ScalaEsRowRDD:132 - Found data nodes [NodeInfo{id='hw493m5wRuaXdZ4-3MelGg', name='Unus the Untouchable', host='172.18.0.3', ip='172.18.0.3', publishAddress='172.18.0.3:9200', hasHttp=true, isClient=false, isData=true}]
16-10-26 04:49:46 DEBUG ScalaEsRowRDD:142 - Filtered discovered only nodes [192.168.0.101:9200, 172.18.0.3:9200] to data-only [172.18.0.3:9200]
16-10-26 04:49:46 TRACE CommonsHttpTransport:489 - Closing HTTP transport to 192.168.0.101:9200
16-10-26 04:49:46 TRACE HttpConnection:1148 - enter HttpConnection.close()
16-10-26 04:49:46 TRACE HttpConnection:1215 - enter HttpConnection.closeSockedAndStreams()
16-10-26 04:49:46 DEBUG CommonsHttpTransportFactory:19 - Creating new CommonsHttpTransport
16-10-26 04:49:46 DEBUG DefaultHttpParams:151 - Set parameter http.method.retry-handler = org.elasticsearch.hadoop.rest.commonshttp.CommonsHttpTransport$1@2154652c
16-10-26 04:49:46 DEBUG DefaultHttpParams:151 - Set parameter http.connection-manager.timeout = 60000
16-10-26 04:49:46 DEBUG DefaultHttpParams:151 - Set parameter http.socket.timeout = 60000
16-10-26 04:49:46 DEBUG DefaultHttpParams:151 - Set parameter http.protocol.credential-charset = UTF-8
16-10-26 04:49:46 DEBUG DefaultHttpParams:151 - Set parameter http.protocol.content-charset = UTF-8
16-10-26 04:49:46 DEBUG DefaultHttpParams:151 - Set parameter http.tcp.nodelay = true
16-10-26 04:49:46 TRACE CommonsHttpTransport:198 - Opening HTTP transport to 172.18.0.3:9200
16-10-26 04:49:46 TRACE CommonsHttpTransport:466 - Tx [HEAD]@[172.18.0.3:9200][6-meta/MT_HR.HR.LOCATIONS.COUNTRY_ID] w/ payload [null]
16-10-26 04:49:46 TRACE HttpClient:321 - enter HttpClient.executeMethod(HttpMethod)
16-10-26 04:49:46 TRACE HttpClient:374 - enter HttpClient.executeMethod(HostConfiguration,HttpMethod,HttpState)
16-10-26 04:49:46 TRACE HttpMethodDirector:379 - Attempt number 1 to process request
16-10-26 04:49:46 TRACE HttpConnection:685 - enter HttpConnection.open()
16-10-26 04:49:46 DEBUG HttpConnection:692 - Open connection to 172.18.0.3:9200
16-10-26 04:49:53 DEBUG Client:1107 - IPC Client (814753967) connection to /192.168.0.101:8020 from rohit: closed
16-10-26 04:49:53 DEBUG Client:904 - IPC Client (814753967) connection to /192.168.0.101:8020 from rohit: stopped, remaining connections 0
```

**Comment by mozinrat** [comment]
Also I have found one more interesting thing, 
If I use a non existing index name, it clearly says index not found. It Seems the connection is working and the raised issue is wrapped in wrong exception. Please check below logs

```
16/10/27 20:51:46 TRACE CommonsHttpTransport: Rx @[127.0.0.1] [404-Not Found] [{"error":{"root_cause":[{"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"1j-meta","index":"1j-meta"}],"type":"index_not_found_exception","reason":"no such index","resource.type":"index_or_alias","resource.id":"1j-meta","index":"1j-meta"},"status":404}]
16/10/27 20:51:46 DEBUG HttpMethodBase: re-creating response stream from byte array
16/10/27 20:51:46 DEBUG HttpMethodBase: re-creating response stream from byte array
16/10/27 20:51:46 DEBUG RestRepository: Closing repository and connection to Elasticsearch ...
16/10/27 20:51:46 TRACE CommonsHttpTransport: Closing HTTP transport to 127.0.0.1:9200
16/10/27 20:51:46 TRACE HttpConnection: enter HttpConnection.close()
16/10/27 20:51:46 TRACE HttpConnection: enter HttpConnection.closeSockedAndStreams()

org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot find mapping for 1j-meta - one is required before using Spark SQL

	at org.elasticsearch.spark.sql.SchemaUtils$.discoverMappingAsField(SchemaUtils.scala:98)
	at org.elasticsearch.spark.sql.SchemaUtils$.discoverMapping(SchemaUtils.scala:70)
	at org.elasticsearch.spark.sql.ElasticsearchRelation.lazySchema$lzycompute(DefaultSource.scala:111)
	at org.elasticsearch.spark.sql.ElasticsearchRelation.lazySchema(DefaultSource.scala:111)
	at org.elasticsearch.spark.sql.ElasticsearchRelation$$anonfun$schema$1.apply(DefaultSource.scala:115)
	at org.elasticsearch.spark.sql.ElasticsearchRelation$$anonfun$schema$1.apply(DefaultSource.scala:115)
	at scala.Option.getOrElse(Option.scala:121)
	at org.elasticsearch.spark.sql.ElasticsearchRelation.schema(DefaultSource.scala:115)
	at org.apache.spark.sql.execution.datasources.LogicalRelation.<init>(LogicalRelation.scala:40)
	at org.apache.spark.sql.SparkSession.baseRelationToDataFrame(SparkSession.scala:382)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:143)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:132)
```

**Comment by jbaiera** [comment]
@mozinrat It looks like you are able to make partial connections to Elasticsearch, since the logs indicate that the connector was able to determine the version of ES, as well as discover the nodes and decide which nodes are data nodes. Though, when the RDD goes to discover the shard locations using one of the discovered nodes, the connection to that node times out. It seems that the Spark driver program simply can't successfully establish a connection to one of your ES nodes at `172.18.0.3:9200`.

**Comment by kant111** [comment]
@jbaiera if an index name doesnt exists and I want ES to be able to auto create the index if it doesnt exits then what should I do?
