### ISSUE TITLE
SSL error when hdfs connect to elasticsearch cluster by es-hadoop ssl SparkConf

### ISSUE THREAD

**Issue by willard-kali** [elastic/elasticsearch-hadoop#904]
Bug report: 
step1: SparkConf
val conf = new SparkConf()
conf.set("es.net.ssl", "true")
conf.set("es.net.ssl.keystore.type", "JKS")
conf.set("es.net.ssl.protocol", "TLS")
conf.set("es.net.ssl.keystore.location", "keystore.jks")
conf.set("es.net.ssl.keystore.pass", "test")
conf.set("es.net.ssl.truststore.location", "truststore.jks")
conf.set("es.net.ssl.truststore.pass", "test")

step2: SparkClient
Use spark-submit command to create task to hadoop cluster. 

step3: Elasticsearch cluster use SSL. It is ok.

step4: SSL error when hdfs connect to elasticsearch cluster by es-hadoop ssl SparkConf. logs is below:
[2016-12-12 11:16:56.809][][task-result-getter-2][WARN][org.apache.spark.scheduler.TaskSetManager,71] Lost task 0.0 in stage 14.0 (TID 300, store, 2): org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot detect ES version - typically this happens if the network/Elasticsearch cluster is not accessible or when targeting a WAN/Cloud instance without the proper setting 'es.nodes.wan.only' at org.elasticsearch.hadoop.rest.InitializationUtils.discoverEsVersion(InitializationUtils.java:196) at org.elasticsearch.hadoop.rest.RestService.createWriter(RestService.java:379) at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:40) at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:84) at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:84) at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:68) at org.apache.spark.scheduler.Task.run(Task.scala:90) at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:229) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745) Caused by: org.elasticsearch.hadoop.rest.EsHadoopTransportException: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty at org.elasticsearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:116) at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:434) at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:414) at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:418) at org.elasticsearch.hadoop.rest.RestClient.get(RestClient.java:122) at org.elasticsearch.hadoop.rest.RestClient.esVersion(RestClient.java:564) at org.elasticsearch.hadoop.rest.InitializationUtils.discoverEsVersion(InitializationUtils.java:184) ... 10 more Caused by: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949) at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1906) at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1889) at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1815) at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:128) at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140) at org.apache.commons.httpclient.HttpConnection.flushRequestOutputStream(HttpConnection.java:828) at org.apache.commons.httpclient.HttpMethodBase.writeRequest(HttpMethodBase.java:2116) at org.apache.commons.httpclient.HttpMethodBase.execute(HttpMethodBase.java:1096) at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:398) at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171) at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397) at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323) at org.elasticsearch.hadoop.rest.commonshttp.CommonsHttpTransport.execute(CommonsHttpTransport.java:471) at org.elasticsearch.hadoop.rest.NetworkClient.execute(NetworkClient.java:104) ... 16 more

OS:         :  Linux
JVM         :  jdk1.8.0
Hadoop/Spark:  Spark-1.5.1
ES-Hadoop   :  elasticsearch-spark_2.10-2.4.0.jar
ES          :  Elasticsearch-2.4.0

Thanks.

**Comment by jbaiera** [comment]
This normally occurs when the configured truststore is either inaccessible or empty. I would double check the contents and accessibility of the truststores on your executor nodes.

**Comment by jbaiera** [comment]
Closing due to lack of feedback
