### ISSUE TITLE
NoSuchMethodError:  ... addOnCompleteCallback

### ISSUE THREAD

**Issue by yyrr001** [elastic/elasticsearch-hadoop#905]
I just follow the elasticsearch hadoop ducument tips  as the following 

```
object test{
  def main(args: Array[String]): Unit = {
    val conf = new SparkConf()
      .set("es.nodes", "192.168.1.3")
      .set("es.port", "9100")
      .setAppName("es_test")
      .set("es.index.auto.create", "true")

    val sc = new SparkContext(conf)

    val numbers = Map("one" -> 1, "two" -> 2, "three" -> 3)
    val airports = Map("arrival" -> "Otopeni", "SFO" -> "San Fran")

    sc.makeRDD(Seq(numbers, airports)).saveToEs("test/test")
  }
}

```

But it failed to add data to es and throw the following:

```
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 5, 192.168.1.90): java.lang.NoSuchMethodError: org.apache.spark.TaskContext.addOnCompleteCallback(Lscala/Function0;)V
	at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:42)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:84)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:84)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

```
Caused by: java.lang.NoSuchMethodError: org.apache.spark.TaskContext.addOnCompleteCallback(Lscala/Function0;)V
	at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:42)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:84)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:84)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```
spark version is 2.0.1 and es version is 2.3.2 with  elastic-hadoop-2.3.2

I found the test/test is setup  by spark but no data is added.

**Comment by jbaiera** [comment]
The `addOnCompleteCallback` method was removed from the TaskContext in Spark 2.0. Spark 2.0 is not binary compatible with previous releases. Because of this we only support Spark 2.0 in es-hadoop version 5.0 and later. Please upgrade to fix the issue.

**Comment by yyrr001** [comment]
I tried to use elasticsearch-spark-20_2.11-5.1.1.jar but failed.
may be still not support spark2.0.2 with es2.3.2 ?

**Comment by RowsPriego** [comment]
I have the same problem, my project is a maven project with the dependencies:
<dependency>
        <groupId>org.apache.spark</groupId>
        <artifactId>spark-core_2.11</artifactId>
        <version>2.1.0</version>
        <scope>provided</scope>
    </dependency>
<dependency>
         <groupId>org.elasticsearch</groupId>
         <artifactId>elasticsearch-spark_2.11</artifactId>
         <version>2.4.4</version>
     </dependency>

And im using elastic 2.3.3....

So, i'm using spark 2.0 [more]... ¿Do i need import the dependency os es-hadoop?

**Comment by yyrr001** [comment]
@RowsPriego 
just update elasticsearch-hadoop 5.1 or higher version.
I fixed this.

**Comment by RowsPriego** [comment]
Thanks!

I've replace

```
<dependency>
      <groupId>org.elasticsearch</groupId>
        <artifactId>elasticsearch-spark_2.11</artifactId>
        <version>2.4.4</version>
 </dependency>
```

with 

```
 <dependency> 
          <groupId>org.elasticsearch</groupId> 
          <artifactId>elasticsearch-hadoop</artifactId> 
          <version>5.1.2</version> 
     </dependency> 
```
