### ISSUE TITLE
Client-only routing specified but no client nodes with HTTP-enabled available issue!

### ISSUE THREAD

**Issue by bloodymind** [elastic/elasticsearch-hadoop#910]
Dear all,

i'm new to Spark and elasticSearch , i'm using Spark 2 , ES 5.0 and elasticsearch-hadoop-5.1.1.jar. 

this what i got : 

```
File "/home/spark/python/test/es-rdd.py", line 42, in <module>
"org.apache.hadoop.io.NullWritable", "org.elasticsearch.hadoop.mr.LinkedMapWritable", conf=es_conf)
File "/home/spark/python/lib/pyspark.zip/pyspark/context.py", line 675, in newAPIHadoopRDD
File "/home/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
File "/home/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
File "/home/spark/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 319, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.newAPIHadoopRDD.
: org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Client-only routing specified but no client nodes with HTTP-enabled available
```

In DEBUG log level i can see this : 
```
17/01/01 02:40:36 TRACE CommonsHttpTransport: Rx @[10.128.0.3] [200-OK] [{"_nodes":{"total":1,"successful":1,"failed":0},"cluster_name":"master-1","nodes":{"jRq8soa3SdqWVyN7cTxh-A":{"name":"node-1","transport_address":"xxx.XXX.XXX.X:9300","host":"xxx.XXX.XXX.X","ip":"xxx.XXX.XXX.X","version":"5.0.0","build_hash":"253032b","roles":["master","data","ingest"],"http":{"bound_address":["[::]:9200"],"publish_address":"xxx.XXX.XXX.X:9200","max_content_length_in_bytes":104857600}}}}]
```

This happened after trying to many solutions in old open issues, here is my final conf for spark : 
```
es_conf = {
    "es.nodes" : "xxx.xxx.xxx.x",
    "es.port" : "9200",
    "es.resource" : "avito.ma/items",
    "es.query" : '{  "query": { "match_all": {} } }',
    "es.write.ignore_exception": "true",
    "es.read.ignore_exception": "true",
    "es.nodes.client.only" : "true",
    "es.nodes.discovery" : "false",
    "es.index.auto.create" : "true",
    "es.nodes.wan.only": "false"
}

rdd = sc.newAPIHadoopRDD("org.elasticsearch.hadoop.mr.EsInputFormat",\
    "org.apache.hadoop.io.NullWritable", "org.elasticsearch.hadoop.mr.LinkedMapWritable", conf=es_conf)

```

Many thanks

**Comment by jbaiera** [comment]
It seems that you have `es.nodes.client.only` set to true. This is what is causing the issue here. The framework is only finding one node (node-1) and that node has the master, data, and ingest roles, which make it not suitable to be considered as a client node. To be considered as a client node, the node in question must perform nothing other than forwarding requests to and aggregating search results from other nodes in the cluster. If you remove the `es.nodes.client.only` property you should be able to progress.

**Comment by r0achster** [comment]
Will this work when a node is set to "roles":["data","ingest"]?

Having issues setting this up on AWS

```
{"_nodes":{"total":5,"successful":5,"failed":0},"cluster_name":"XXXXXX","nodes":{"b53SxOVTS4W4EbtwHRNJpw":{"name":"b53SxOV","version":"6.0.1","build_hash":"d951bbf","roles":["master"]},"30EygpCIT8evxLL3nf48mQ":{"name":"30EygpC","version":"6.0.1","build_hash":"d951bbf","roles":["master"]},"BQF8TF0ZQu6gjDWuiOuulg":{"name":"BQF8TF0","version":"6.0.1","build_hash":"d951bbf","roles":["master"]},"W_phdGb6Qx6KHrjtmpLDWw":{"name":"W_phdGb","version":"6.0.1","build_hash":"d951bbf","roles":["data","ingest"]},"BSaemmuTRhq76u9hXaufAQ":{"name":"BSaemmu","version":"6.0.1","build_hash":"d951bbf","roles":["data","ingest"]}}}
```


```18/01/03 15:59:57 INFO Version: Elasticsearch Hadoop v6.0.1 [db40a0c439]
Traceback (most recent call last):
  File "/home/ubuntu/pyspark/spark-test.py", line 20, in <module>
    es_rdd = sc.newAPIHadoopRDD(inputFormatClass="org.elasticsearch.hadoop.mr.EsInputFormat",keyClass="org.apache.hadoop.io.NullWritable", valueClass="org.elasticsearch.hadoop.mr.LinkedMapWritable", conf=conf)
  File "/opt/spark/python/lib/pyspark.zip/pyspark/context.py", line 702, in newAPIHadoopRDD
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 319, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.newAPIHadoopRDD.
: org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: No data nodes with HTTP-enabled available
	at org.elasticsearch.hadoop.rest.InitializationUtils.filterNonDataNodesIfNeeded(InitializationUtils.java:159)
	at org.elasticsearch.hadoop.rest.RestService.findPartitions(RestService.java:223)
	at org.elasticsearch.hadoop.mr.EsInputFormat.getSplits(EsInputFormat.java:405)
	at org.elasticsearch.hadoop.mr.EsInputFormat.getSplits(EsInputFormat.java:386)
	at org.apache.spark.rdd.NewHadoopRDD.getPartitions(NewHadoopRDD.scala:125)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
	at org.apache.spark.rdd.RDD$$anonfun$take$1.apply(RDD.scala:1333)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.RDD.take(RDD.scala:1327)
	at org.apache.spark.api.python.SerDeUtil$.pairRDDToPython(SerDeUtil.scala:203)
	at org.apache.spark.api.python.PythonRDD$.newAPIHadoopRDD(PythonRDD.scala:596)
	at org.apache.spark.api.python.PythonRDD.newAPIHadoopRDD(PythonRDD.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
```

I'm getting the same error:

```
18/01/03 15:59:57 INFO Version: Elasticsearch Hadoop v6.0.1 [db40a0c439]
Traceback (most recent call last):
  File "/home/ubuntu/pyspark/spark-test.py", line 20, in <module>
    es_rdd = sc.newAPIHadoopRDD(inputFormatClass="org.elasticsearch.hadoop.mr.EsInputFormat",keyClass="org.apache.hadoop.io.NullWritable", valueClass="org.elasticsearch.hadoop.mr.LinkedMapWritable", conf=conf)
  File "/opt/spark/python/lib/pyspark.zip/pyspark/context.py", line 702, in newAPIHadoopRDD
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/opt/spark/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 319, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.newAPIHadoopRDD.
: org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: No data nodes with HTTP-enabled available
	at org.elasticsearch.hadoop.rest.InitializationUtils.filterNonDataNodesIfNeeded(InitializationUtils.java:159)
	at org.elasticsearch.hadoop.rest.RestService.findPartitions(RestService.java:223)
	at org.elasticsearch.hadoop.mr.EsInputFormat.getSplits(EsInputFormat.java:405)
	at org.elasticsearch.hadoop.mr.EsInputFormat.getSplits(EsInputFormat.java:386)
	at org.apache.spark.rdd.NewHadoopRDD.getPartitions(NewHadoopRDD.scala:125)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
	at scala.Option.getOrElse(Option.scala:121)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
	at org.apache.spark.rdd.RDD$$anonfun$take$1.apply(RDD.scala:1333)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:362)
	at org.apache.spark.rdd.RDD.take(RDD.scala:1327)
	at org.apache.spark.api.python.SerDeUtil$.pairRDDToPython(SerDeUtil.scala:203)
	at org.apache.spark.api.python.PythonRDD$.newAPIHadoopRDD(PythonRDD.scala:596)
	at org.apache.spark.api.python.PythonRDD.newAPIHadoopRDD(PythonRDD.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
```

```
conf={
    "es.resource": "logstash/doc", 
    "es.nodes" : "XXXXXX",
    "es.port" : "80",
    "es.query": '{  "query": { "match_all": {} } }', 
    "es.write.ignore_exception": "true",
    "es.read.ignore_exception": "true",
    "es.nodes.client.only" : "false",
    "es.nodes.discovery" : "false",
    "es.index.auto.create" : "true",
    "es.nodes.wan.only": "false"
}
```

**Comment by r0achster** [comment]
Found my issue for AWS implementation wan only needs to be set to true

` "es.nodes.wan.only": "true"`

**Comment by ashvjits** [comment]
This should be present in aws-elasticsearch documentation
