### ISSUE TITLE
[Pig] Params in es.update.script.params converted to string

### ISSUE THREAD

**Issue by satish-vellanki** [elastic/elasticsearch-hadoop#911]
### Issue description

Params specified in es.update.script.params are converted to string in the API payload, even when the type is long.

### Steps to reproduce

Code:
cat test.csv
```
docId,count
a,1
b,2
c,3
```

Pig script:
```
DEFINE CSVExcelStorage org.apache.pig.piggybank.storage.CSVExcelStorage(',', 'NO_MULTILINE', 'UNIX', 'SKIP_INPUT_HEADER');
dd_info = LOAD 'test.csv' USING CSVExcelStorage() as (docId:chararray, count:long);

STORE dd_info INTO 'dd_info_test/dd_info' USING org.elasticsearch.hadoop.pig.EsStorage('es.resource=dd_info_test/dd_info', 'es.write.operation=upsert',
'es.update.script.lang=groovy', 'es.update.script=ctx._source.count += count', 'es.update.script.params=count:count',
'es.mapping.id=docId');
```

ES API call from logs:
```
PUT dd_info_test/dd_info/_bulk
{"update":{"_id":"a"}}
{"script":{"inline":"ctx._source.count += count","lang":"groovy","params":{"count":"1"}},"upsert":{"docId":"a","count":1}}
{"update":{"_id":"b"}}
{"script":{"inline":"ctx._source.count += count","lang":"groovy","params":{"count":"2"}},"upsert":{"docId":"b","count":2}}
{"update":{"_id":"c"}}
{"script":{"inline":"ctx._source.count += count","lang":"groovy","params":{"count":"3"}},"upsert":{"docId":"c","count":3}}

```
Notice how count is a string ("1") in the params. It causes the script to do string concatenation instead of adding it.
Workaround: ctx._source.count += count.toInteger()

### Version Info

OS:         :  
JVM         :  
Hadoop/Spark:  
ES-Hadoop   :  5.1.1
ES          :  

Also, instead of always specifying inline script would it be possible to use the file option?
```
"script" : {
        "file": "myscript",
        "params" : {
            "count" : 1
        }
    }
```

**Comment by satish-vellanki** [comment]
Sorry to add on to the original issue, let me know if I should be reporting this separately. Thank you.
I am also experiencing another error:
```
Failure while running task:org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Unsupported data type [bag] for field [children]; use only 'primitives' or 'tuples'
	at org.elasticsearch.hadoop.util.Assert.isTrue(Assert.java:50)
	at org.elasticsearch.hadoop.pig.PigFieldExtractor.extractField(PigFieldExtractor.java:64)
	at org.elasticsearch.hadoop.serialization.field.ConstantFieldExtractor.field(ConstantFieldExtractor.java:36)
	at org.elasticsearch.hadoop.serialization.field.AbstractDefaultParamsExtractor.field(AbstractDefaultParamsExtractor.java:52)
	at org.elasticsearch.hadoop.serialization.bulk.AbstractBulkFactory$FieldWriter.write(AbstractBulkFactory.java:94)
	at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.writeTemplate(TemplatedBulk.java:80)
	at org.elasticsearch.hadoop.serialization.bulk.TemplatedBulk.write(TemplatedBulk.java:56)
	at org.elasticsearch.hadoop.rest.RestRepository.writeToIndex(RestRepository.java:159)
	at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.write(EsOutputFormat.java:151)
	at org.elasticsearch.hadoop.pig.EsStorage.putNext(EsStorage.java:192)
```

where children is a bag of tuples. Any reason why bags cannot be part of params? Is there any workaround for this? I am grouping data in Pig script before sending it over to ES and I want to update only a few fields, some being bags.
