### ISSUE TITLE
 repository-hdfs no work with Kerberos authenticate hdfs

### ISSUE THREAD

**Issue by zcola** [elastic/elasticsearch-hadoop#921]
### Issue description

No authenticate hdfs seem to be OK，but Kerberos authenticate hdfs is faild

### Steps to reproduce
1. kinit every data node
```
 klist -e
Ticket cache: FILE:/tmp/krb5cc_1001
Default principal: elk_sa/scribe@xxxx.COM

Valid starting    Expires           Service principal
28/12/2016 15:32  30/12/2016 15:32  krbtgt/xxx@xxxM
	renew until 04/01/2017 15:32, Etype (skey, tkt): des3-cbc-sha1, des3-cbc-sha1
```
2. add  repository
```
{
  "type": "hdfs",
  "settings": {
    "path": "/es_snapshot",
    "max_restore_bytes_per_sec": "500mb",
    "compress": "true",
    "uri": "hdfs://10x0.6x0:9000",
    "max_snapshot_bytes_per_sec": "500mb",
    "conf.hdfs_config": "/home/elk/etc/hadoop/hdfs-site.xml",
    "conf.hadoop_config": "/home/elk/etc/hadoop/core-site.xml",
    "user_keytab": "/home/elk/elk_sa.keytab",
    "user_principal": "elk_sa",
    "user_principal_hostname": "scheduler"
  }
}
```
Strack trace:

```
{
  "error": {
    "root_cause": [
      {
        "type": "repository_exception",
        "reason": "[dt_backup] failed to create repository"
      }
    ],
    "type": "repository_exception",
    "reason": "[dt_backup] failed to create repository",
    "caused_by": {
      "type": "creation_exception",
      "reason": "Guice creation errors:

1) Error injecting constructor, org.apache.hadoop.security.AccessControlException: SIMPLE authentication is not enabled.  Available:[TOKEN, KERBEROS]
  at org.elasticsearch.repositories.hdfs.HdfsRepository.<init>(Unknown Source)
  while locating org.elasticsearch.repositories.hdfs.HdfsRepository
  while locating org.elasticsearch.repositories.Repository

1 error",
      "caused_by": {
        "type": "access_control_exception",
        "reason": "SIMPLE authentication is not enabled.  Available:[TOKEN, KERBEROS]",
        "caused_by": {
          "type": "remote_exception",
          "reason": "SIMPLE authentication is not enabled.  Available:[TOKEN, KERBEROS]"
        }
      }
    }
  },
  "status": 500
}
``` 
I want to use KERBEROS，why notice `SIMPLE authentication is not enabled`
### Version Info

OS:         :  debian 8
JVM         : orc java 8
Hadoop/Spark:  hadoop5.6.0-cdh2.6.0
ES-Hadoop   : elasticsearch-repository-hdfs-2.3.4.BUILD-SNAPSHOT.jar Yarn
ES          :  2.3.4

**Comment by koertkuipers** [comment]
this works for us using repository-hdfs version 2.4.3

also i saw in your config this:
```
    "user_principal": "elk_sa",
    "user_principal_hostname": "scheduler"
```
user_principal_hostname only does something if you have a _HOST placeholder in your user_principal. e.g.
```"elk_principal": "elk_sa/_HOST"```

**Comment by zcola** [comment]
@koertkuipers how to get user_principal_hostname variable?

**Comment by koertkuipers** [comment]
if you use the string "_HOST" in your user_principal it will automatically get replaced by the hostname. the hostname is automatically inferred for each machine.

you can also set explicitly the hostname that replaces _HOST in the user_principal using the variable user_principal_hostname. however i don't really see the purpose of that: if you want to set the hostname explicitly don't use _HOST but instead use the correct hostname in user_principal.

so i dont really see a reason someone would ever want to set user_principal_hostname. i think its an unnecessary and confusing variable.

**Comment by zcola** [comment]
@koertkuipers 

```
{
  "type": "hdfs",
  "settings": {
    "path": "/es_snapshot",
    "max_restore_bytes_per_sec": "500mb",
    "compress": "true",
    "uri": "hdfs://10.1x0.x.100:9000",
    "max_snapshot_bytes_per_sec": "500mb",
    "conf.hdfs_config": "/home/elk/etc/hadoop/hdfs-site.xml",
    "conf.hadoop_config": "/home/elk/etc/hadoop/core-site.xml",
    "user_keytab": "/home/elk/elk_sa.keytab",
    "user_principal": "elk_sa/_HOST"
  }
}
```
same error

**Comment by koertkuipers** [comment]
it could be the version of the plugin (i am using 2.4.3)

also you can kinit on the hosts from the keytab?
e.g. kinit -t -t /home/elk/elk_sa.keytab elk_sa/scribe

**Comment by xy-xin** [comment]
hi @zcola , have you resolved the problem? i encountered the same problem on 5.1.1.

**Comment by zcola** [comment]
@xy-xin noop

**Comment by koertkuipers** [comment]
"SIMPLE authentication is not enabled" is a confusing error. it means earlier your client failed to get a kerberos token and therefore is trying to log in without kerberos (which is called SIMPLE authentication).

so it shows your client never tried to connect to hdfs with kerberos permissions.

in the core-site.xml that you provided does it say:
```
  <property>
    <name>hadoop.security.authentication</name>
    <value>kerberos</value>
  </property>
```

**Comment by zcola** [comment]
i upgrade es 2.4.4 in testing env, open trace level log,same error
```
[2017-02-23 11:22:59,799][TRACE][cluster.service          ] [elk-edata01-102_hot] will process [put_repository [my_backup6]]
[2017-02-23 11:22:59,799][DEBUG][cluster.service          ] [elk-edata01-102_hot] processing [put_repository [my_backup6]]: execute
[2017-02-23 11:22:59,800][DEBUG][repositories             ] [elk-edata01-102_hot] creating repository [hdfs][my_backup6]
[2017-02-23 11:22:59,879][DEBUG][repositories.hdfs        ] [elk-edata01-102_hot] Login using keytab [/home/elk/elk_sa.keytab] and principal [elk_sa] (with hostname [null])
[2017-02-23 11:22:59,880][DEBUG][org.apache.hadoop.hdfs.BlockReaderLocal] dfs.client.use.legacy.blockreader.local = false
[2017-02-23 11:22:59,880][DEBUG][org.apache.hadoop.hdfs.BlockReaderLocal] dfs.client.read.shortcircuit = false
[2017-02-23 11:22:59,881][DEBUG][org.apache.hadoop.hdfs.BlockReaderLocal] dfs.client.domain.socket.data.traffic = false
[2017-02-23 11:22:59,881][DEBUG][org.apache.hadoop.hdfs.BlockReaderLocal] dfs.domain.socket.path =
[2017-02-23 11:22:59,881][DEBUG][org.apache.hadoop.io.retry.RetryUtils] multipleLinearRandomRetry = null
[2017-02-23 11:22:59,882][DEBUG][org.apache.hadoop.ipc.Client] getting client out of cache: org.apache.hadoop.ipc.Client@67509721
[2017-02-23 11:22:59,882][DEBUG][org.apache.hadoop.hdfs.protocol.datatransfer.sasl.DataTransferSaslUtil] DataTransferProtocol not using SaslPropertiesResolver, no QOP found in configuration for dfs.data.transfer.protection
[2017-02-23 11:22:59,882][DEBUG][repositories.hdfs        ] [elk-edata01-102_hot] Using file-system [DFS[DFSClient[clientName=DFSClient_NONMAPREDUCE_1976723552_29, ugi=elk (auth:SIMPLE)]]] for URI [hdfs://10.120.69.100:9000], path [hdfs://10.120.69.100:9000/es_snapshot]
[2017-02-23 11:22:59,927][TRACE][org.apache.hadoop.ipc.ProtobufRpcEngine] 29: Call -> /10.120.69.100:9000: getFileInfo {src: "/user/elk"}
[2017-02-23 11:22:59,928][DEBUG][org.apache.hadoop.ipc.Client] The ping interval is 60000 ms.
[2017-02-23 11:22:59,929][DEBUG][org.apache.hadoop.ipc.Client] Connecting to /10.120.69.100:9000
[2017-02-23 11:22:59,934][DEBUG][org.apache.hadoop.ipc.Client] IPC Client (830895739) connection to /10.120.69.100:9000 from elk: starting, having connections 1
[2017-02-23 11:22:59,934][DEBUG][org.apache.hadoop.ipc.Client] IPC Client (830895739) connection to /10.120.69.100:9000 from elk sending #4
[2017-02-23 11:22:59,936][DEBUG][org.apache.hadoop.ipc.Client] IPC Client (830895739) connection to /10.120.69.100:9000 from elk got value #-1
[2017-02-23 11:22:59,936][DEBUG][org.apache.hadoop.ipc.Client] closing ipc connection to /10.120.69.100:9000: SIMPLE authentication is not enabled.  Available:[TOKEN, KERBEROS]
org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.security.AccessControlException): SIMPLE authentication is not enabled.  Available:[TOKEN, KERBEROS]
	at org.apache.hadoop.ipc.Client$Connection.receiveRpcResponse(Client.java:1126)
	at org.apache.hadoop.ipc.Client$Connection.run(Client.java:974)
[2017-02-23 11:22:59,937][DEBUG][org.apache.hadoop.ipc.Client] IPC Client (830895739) connection to /10.120.69.100:9000 from elk: closed
[2017-02-23 11:22:59,937][DEBUG][org.apache.hadoop.ipc.Client] IPC Client (830895739) connection to /10.120.69.100:9000 from elk: stopped, remaining connections 0
[2017-02-23 11:22:59,937][TRACE][org.apache.hadoop.ipc.ProtobufRpcEngine] 29: Exception <- /10.120.69.100:9000: getFileInfo {org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.security.AccessControlException): SIMPLE authentication is not enabled.  Available:[TOKEN, KERBEROS]}
```

**Comment by koertkuipers** [comment]
does the file /home/elk/etc/hadoop/core-site.xml have the correct settings for secure hadoop?

**Comment by zcola** [comment]
@koertkuipers yes
```
  <!-- Web Interface Configuration -->
  <property>
    <name>hadoop.http.filter.initializers</name>
    <value>org.apache.hadoop.http.lib.StaticUserWebFilter,org.apache.hadoop.security.AuthenticationFilterInitializer</value>
  </property>
  <property>
    <name>hadoop.http.authentication.type</name>
    <value>kerberos</value>
  </property>
  <property>
    <name>hadoop.http.authentication.simple.anonymous.allowed</name>
    <value>true</value>
  </property>

  <!-- security setting -->
  <property>
    <name>hadoop.security.authentication</name>
    <value>kerberos</value>
  </property>
  <property>
    <name>hadoop.security.authorization</name>
    <value>true</value>
  </property>
  <property>
    <name>hadoop.security.groups.cache.secs</name>
    <value>14400</value>
  </property>
  <property>
  <name>hadoop.kerberos.kinit.command</name>
  <value>/usr/bin/kinit</val
```

**Comment by koertkuipers** [comment]
very strange. it is clear it wont work when this is being logged:
```
[2017-02-23 11:22:59,882][DEBUG][org.apache.hadoop.ipc.Client] getting client out of cache: org.apache.hadoop.ipc.Client@67509721
[2017-02-23 11:22:59,882][DEBUG][org.apache.hadoop.hdfs.protocol.datatransfer.sasl.DataTransferSaslUtil] DataTransferProtocol not using SaslPropertiesResolver, no QOP found in configuration for dfs.data.transfer.protection
[2017-02-23 11:22:59,882][DEBUG][repositories.hdfs        ] [elk-edata01-102_hot] Using file-system [DFS[DFSClient[clientName=DFSClient_NONMAPREDUCE_1976723552_29, ugi=elk (auth:SIMPLE)]]] for URI [hdfs://10.1x0.xx9.100:9000], path [hdfs://10.120.69.100:9000/es_snapshot]
[2017-02-23 11:22:59,927][TRACE][org.apache.hadoop.ipc.ProtobufRpcEngine] 29: Call -> /10.120.69.100:9000: getFileInfo {src: "/user/elk"}
```
the issue is the auth:SIMPLE

checking if we have any other settings... we have:
```load_defaults: "false" # optional - whether to load the default Hadoop configuration (default) or not```

and in elasticsearch.yml we have:
```security.manager.enabled: false```

**Comment by jbaiera** [comment]
@zcola I have run into the same issue while testing some changes to the HDFS Repository Plugin in 5.2. 

In your settings you are trying to pass configuration files to the plugin :
```
    "conf.hdfs_config": "/home/elk/etc/hadoop/hdfs-site.xml",
    "conf.hadoop_config": "/home/elk/etc/hadoop/core-site.xml"
```
but I do not believe these are affecting the underlying configuration in they way you think it might be. Instead of adding those files as sources for the configuration, these lines are just setting two properties to point to the given strings. You may be confusing those settings with the `conf_location` option.

@koertkuipers is correct in their explanation of the host property. It is best to leave this off. Its original inclusion was most likely set as an option for completeness, but is rather confusing. 

Setting the keytab information is not enough when trying to authenticate with Kerberos, and as you've seen, if the authentication mode is not changed from `SIMPLE`, then no log in will actually be performed in the code (even if we _do_ call login with the keytab info). In this case I would try setting `conf.hadoop.http.authentication.type` to `kerberos` in the plugin configuration request. This should add the property correctly to the Hadoop configuration. I'd steer clear of the `conf_location` option as it will not be available in later versions of the plugin (The plugin was re-written in 5.0).

**Comment by mikej1688** [comment]
security.manager.enabled: false
Why should the security manager be set to false?
because you added kerberos to manage the security instead, no need to let java security manager do the job? 
Up to now, I have not seen a successful case for creating hdfs repository with security manager enabled. Is it possible?

**Comment by jbaiera** [comment]
@mikej1688 Authenticating to a remote service such as Kerberos is not the same as code level security. Code level security dictates that the author of the code executing may not be you, and thus, may need to be kept from performing certain actions as you. This is different from proving you are who you say you are to an external service. The HDFS client executes quite a bit of code that requires a large number of elevated privileges to function. Running the plugin below 5.0 with the SecurityManager enabled is unlikely to succeed. In Elasticsearch 5.0, the plugin was re-written to be compliant with the installed SecurityManager. If you require the manager to be enabled, please upgrade to Elasticsearch 5.0 or higher.

**Comment by mikej1688** [comment]
Thanks for the explanation.
Currently we cannot upgrade to 5.x since there is an outstanding snapshot
creation issue even in the latest 5.2.2 version. It was said by ES
consultant that the issue might be fixed in the incoming 5.3. but we cannot
rely upon the uncertainty.
Thus my question is: in 2.x version, is it a security hole when we have
security.manager.enabled :  false?
If yes, how can we avoid it?
Another question : is the parameter, x-pack security manager in 5.x, not
related to the security.manager.enabled in 2.x?
Thus in 5.x, no any extra setting for code level security is needed in
elasticsearch.yml?


On Mar 17, 2017 5:21 PM, "James Baiera" <notifications@github.com> wrote:

@mikej1688 <https://github.com/mikej1688> Authenticating to a remote
service such as Kerberos is not the same as code level security. Code level
security dictates that the author of the code executing may not be you, and
thus, may need to be kept from performing certain actions as you. This is
different from proving you are who you say you are to an external service.
The HDFS client executes quite a bit of code that requires a large number
of elevated privileges to function. Running the plugin below 5.0 with the
SecurityManager enabled is unlikely to succeed. In Elasticsearch 5.0, the
plugin was re-written to be compliant with the installed SecurityManager.
If you require the manager to be enabled, please upgrade to Elasticsearch
5.0 or higher.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/elastic/elasticsearch-hadoop/issues/921#issuecomment-287474329>,
or mute the thread

**Comment by jbaiera** [comment]
@mikej1688 Strictly speaking, if the security manager is disabled, then yes, that could pose a potential security risk should you be loading plugins or running scripts that are not trusted and are looking to cause damage.

**Comment by jbaiera** [comment]
I'm closing this issue for the time being as the discussion has gotten off course and the original author has not responded for a while.
