### ISSUE TITLE
An error occurred while calling z:org.apache.spark.api.python.PythonRDD.newAPIHadoopRDD

### ISSUE THREAD

**Issue by aginpatrick** [elastic/elasticsearch-hadoop#922]
I run pyspark with:

    ] ./bin/pyspark --jars jars/elasticsearch-hadoop-2.2.0.jar 

    Python 2.7.9 (default, Apr  2 2015, 15:33:21) 
    [GCC 4.9.2] on linux2
    Type "help", "copyright", "credits" or "license" for more information.
    Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
    Setting default log level to "WARN".
    To adjust logging level use sc.setLogLevel(newLevel).
    17/01/20 12:54:52 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
    Welcome to
          ____              __
         / __/__  ___ _____/ /__
        _\ \/ _ \/ _ `/ __/  '_/
       /__ / .__/\_,_/_/ /_/\_\   version 2.0.1
          /_/

    Using Python version 2.7.9 (default, Apr  2 2015 15:33:21)
    SparkSession available as 'spark'.

When I try to define an elasticsearch rdd (ES 2.4.3), I get the following error:

    >>> es_read_conf = { "es.resource" : "test/docs" , "es.nodes" : "xx.xx.xx.xx","es.port" : "9200", "es.net.http.auth.user": "myusername", "es.net.http.auth.pass": "mypassword"}
    >>> es_rdd = sc.newAPIHadoopRDD(inputFormatClass="org.elasticsearch.hadoop.mr.EsInputFormat",keyClass="org.apache.hadoop.io.NullWritable", valueClass="org.elasticsearch.hadoop.mr.LinkedMapWritable", conf=es_read_conf)

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/patrick/spark-2.0.1-bin-hadoop2.7/python/pyspark/context.py", line 646, in newAPIHadoopRDD
        jconf, batchSize)
      File "/home/patrick/spark-2.0.1-bin-hadoop2.7/python/lib/py4j-0.10.3-src.zip/py4j/java_gateway.py", line 1133, in __call__
      File "/home/patrick/spark-2.0.1-bin-hadoop2.7/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
      File "/home/patrick/spark-2.0.1-bin-hadoop2.7/python/lib/py4j-0.10.3-src.zip/py4j/protocol.py", line 319, in get_return_value
    py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.newAPIHadoopRDD.
    : org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: [GET] on [_nodes/http] failed; server[xx.xx.xx.yy:9201] returned [502|Bad Gateway:]
    (...other messages)

Notice the server address in the error message, it's not the same as the host that I specified in the es.nodes key in es_read_conf dict. In this dict, I defined the host as the master node address (xx.xx.xx.**xx**) and the error refers to one of the data node (xx.xx.xx.**yy**). Actually, when I run the command again, it can raise the same error but with another data node (xx.xx.xx.**zz**). If I run the command multiple times, sometimes no error occurs (I suppose that it's when command is sent to master node only). 

    >>> es_rdd = sc.newAPIHadoopRDD(inputFormatClass="org.elasticsearch.hadoop.mr.EsInputFormat",keyClass="org.apache.hadoop.io.NullWritable", valueClass="org.elasticsearch.hadoop.mr.LinkedMapWritable", conf=es_read_conf)
    17/01/20 13:19:36 WARN EsInputFormat: Cannot determine task id...
    >>> for field in es_rdd.first()[1]:
                print field

    17/01/20 13:21:03 WARN EsInputFormat: Cannot determine task id...
    signaletic
    sourceinfo
    document

Any hint will be very appreciated.
Patrick

**Comment by aginpatrick** [comment]
I forgot to mention that same command on localhost node works well.

**Comment by aginpatrick** [comment]
FYI: simple curl works (=> I get 2 documents):
curl -u myusername:mypass -XPOST myip:9200/_search -d '{"query":{"match_all":{}},"size":2}' 

I tried in scala interactive shell:
    ] $SPARK_HOME/bin/spark-shell --master local[4] --jars ~/spark-2.0.1-bin-hadoop2.7/jars/elasticsearch-spark-20_2.11-5.1.2.jar --conf spark.es.nodes="mymaster.node" --conf spark.es.port="9200" --conf spark.es.resource="myindex/mytype" --conf spark.es.net.http.auth.pass="mypass" --conf spark.es.net.http.auth.user="myusername" --conf spark.es.nodes.client.only="true"

    scala> val df = spark.read.format("org.elasticsearch.spark.sql")
    .option("query","file:///myquery")
    .option("pushdown", "true")
    .load("myindex/mytype")
    .select("myfield")

and I get the same error : 
    (blah blah blah...) Caused by: org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: [GET] on [_nodes/http] failed; server[xx.xx.xx.xy:9200] returned [502|Bad Gateway:]

**Comment by alfredcs** [comment]
Same problem here with elasticsearch-hadoop-5.3.1.jar.

17/04/26 17:00:17 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20170426165904-0019/1 is now RUNNING
17/04/26 17:00:17 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 172.16.32.24, 32994, None)
17/04/26 17:00:17 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
Traceback (most recent call last):
  File "/glusterFS/vol1/apps/sparkCodes/estest.py", line 14, in <module>
    conf=es_read_conf)
  File "/opt/spark-2.1.0-bin-hadoop2.7/python/lib/pyspark.zip/pyspark/context.py", line 675, in newAPIHadoopRDD
  File "/opt/spark-2.1.0-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/opt/spark-2.1.0-bin-hadoop2.7/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 319, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.newAPIHadoopRDD.
: java.lang.ClassNotFoundException: org.elasticsearch.hadoop.mr.LinkedMapWritable
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.util.Utils$.classForName(Utils.scala:229)
	at org.apache.spark.api.python.PythonRDD$.newAPIHadoopRDDFromClassNames(PythonRDD.scala:593)
	at org.apache.spark.api.python.PythonRDD$.newAPIHadoopRDD(PythonRDD.scala:577)
	at org.apache.spark.api.python.PythonRDD.newAPIHadoopRDD(PythonRDD.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)

17/04/26 17:00:17 INFO SparkContext: Invoking stop() from shutdown hook
17/04/26 17:00:17 INFO ContextCleaner: Cleaned accumulator 0
17/04/26 17:00:17 INFO SparkUI: Stopped Spark web UI at http://172.16.32.24:4040
17/04/26 17:00:17 INFO StandaloneSchedulerBackend: Shutting down all executors
17/04/26 17:00:17 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down

**Comment by jbaiera** [comment]
@alfredcs Your issue in this seems to be unrelated to the original reported issue.

@aginpatrick It's possible that you are getting hit with networking issues on your cluster. Do you keep your nodes behind a proxy normally? It's possible that the connector is discovering the http addresses of your nodes and cannot reach them effectively. You may be able to get around this by enabling `es.nodes.wan.only`, as that skips the discovery phase and the node filtering phase.

**Comment by jbaiera** [comment]
Closing this as the conversation has trailed off. We can always re-open this if new information comes to light.
