### ISSUE TITLE
Fail to write to hdfs when elasticsearch-spark in classpath

### ISSUE THREAD

**Issue by mozinrat** [elastic/elasticsearch-hadoop#923]
### What kind an issue is this?

- [X] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 

### Issue description

Fail to write to hdfs when elasticsearch spark is in classpath.

### Steps to reproduce

Code:

```
Try writing to parquet on hdfs having elasticsearch-spark-20_2.11 in classpath,
nothing got written in there.
Trying to read something from parquet got below exception ,

File not exist: hdfs://astraspark0.rokittechua.com:8020/user/astra/data/1/1/SAMPLE.CRA.INFORMERS.parquet
```

Strack trace:

```
aused by: java.util.ServiceConfigurationError: org.apache.spark.sql.sources.DataSourceRegister: Provider org.elasticsearch.spark.sql.DefaultSource15 not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:43)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:247)
	at scala.collection.TraversableLike$class.filter(TraversableLike.scala:259)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
	at org.apache.spark.sql.execution.datasources.DataSource.lookupDataSource(DataSource.scala:128)
	at org.apache.spark.sql.execution.datasources.DataSource.providingClass$lzycompute(DataSource.scala:79)
	at org.apache.spark.sql.execution.datasources.DataSource.providingClass(DataSource.scala:79)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:325)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:149)
	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:439)

``` 

### Version Info

OS:         :  centos
JVM         :  1.8.0_112
Hadoop/Spark:  2.7.3/2.0.1
ES-Hadoop   :  5.1.1
ES          :  5.1.1

Possibly while running hdfs read write we use on hdfs user, may be similar configuration needed in elasticsearch-spark.

**Comment by SailLiao** [comment]
hi, i hive same issues, hive you solve it . thanks su much .

**Comment by mozinrat** [comment]
Yes, i forgot the exact details but needed to create a separate maven project for job, shade es-hadoop binaries in that. While importing this project to main project, excluse es-hadoop binaries. Play with your maven/gradle build, if you are using java. I have no hints with scala though.

**Comment by SailLiao** [comment]
i solve this , because i use the error es-spark.jar, the scala version in the classpath must be same as the scala jar in SPARK_HOME/jars , and use the right es-spark jar  https://www.elastic.co/guide/en/elasticsearch/hadoop/5.4/install.html

**Comment by jbaiera** [comment]
Closing this as it seems to not be an issue any longer.

**Comment by cesarBere** [comment]
Hi,

I know it's an old closed issue but here's our fix for anyone coming here with the same issue.

We're on Spark 2.3.0 with elasticsearch-spark-20_2.11 version 6.2.4 and the same exception, excluding any Spark related package from the import solved it (might be a bit brutal, yes) :

```
<dependency>
  <groupId>org.elasticsearch</groupId>
  <artifactId>elasticsearch-spark-20_${scala.compat.version}</artifactId>
  <version>${elasticsearch-spark.version}</version>
  <exclusions>
    <exclusion>
      <groupId>org.apache.spark</groupId>
      <artifactId>spark-*</artifactId>
    </exclusion>
  </exclusions>
</dependency>
```

Cheers
