### ISSUE TITLE
ES + Spark: setting es.scroll.limit non-negative sometimes causes NPE

### ISSUE THREAD

**Issue by ndimiduk** [elastic/elasticsearch-hadoop#925]
**Elasticsearch version**: 2.3.3 (218bdf10790eef486ff2c41a3df5cfa32dadcfde)
**Elasticsearch Hadoop version**: elasticsearch-spark_2.10 2.3.3
**Spark version**: Apache Spark 1.6.3-bin-hadoop2.6

**Plugins installed**: [ kopf 2.0.1 ]

**JVM version**:
```
java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode)
```
**OS version**: Ubuntu 14.04

**Description of the problem including expected versus actual behavior**:

Setting a non-negative value for `es.scroll.limit` will sometimes cause an NPE. I see this running Spark in local mode (`spark-submit --master "local[*]"`) and a distributed ES cluster.

Spark tasks fail with

```
2017-02-01 23:02:03,925 ERROR [Executor task launch worker-0] executor.Executor: Exception in task 0.0 in stage 0.0 (TID 0)
java.lang.NullPointerException
        at org.elasticsearch.hadoop.rest.ScrollQuery.hasNext(ScrollQuery.java:87)
        at org.elasticsearch.spark.rdd.AbstractEsRDDIterator.hasNext(AbstractEsRDDIterator.scala:43)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:144)
        at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1157)
        at scala.collection.TraversableOnce$class.aggregate(TraversableOnce.scala:201)
        at scala.collection.AbstractIterator.aggregate(Iterator.scala:1157)
        at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$23.apply(RDD.scala:1135)
        at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$23.apply(RDD.scala:1135)
        at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$24.apply(RDD.scala:1136)
        at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$24.apply(RDD.scala:1136)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by jbaiera** [comment]
@ndimiduk I'm seeing that this null pointer exception should be fixed in 5.0 and higher. I would advise upgrading to the most recent ES-Hadoop (5.2.0) as it is the most stable and up to date code, and should still be compatible with Elasticsearch 2.3.3.

**Comment by ndimiduk** [comment]
Okay I'll give it a spin. Do you have a reference ticket in which this
issue is fixed for the later version? I didn't find any tickets related to
this stack trace in my search before filing.

Thanks!

**Comment by jbaiera** [comment]
@ndimiduk I did not find any open tickets for it, but the possibility of receiving a null pointer was removed during the upgrade to 5.0. Instead, [the connector will correctly return an empty scroll instead of null](https://github.com/elastic/elasticsearch-hadoop/blob/dd1d6036fa9ee21d9a3082226a152d40cce9ede7/mr/src/main/java/org/elasticsearch/hadoop/serialization/ScrollReader.java#L274)

**Comment by ndimiduk** [comment]
What's the artifact to use? It seems the spark module is no longer
available on maven central.

https://mvnrepository.com/artifact/org.elasticsearch/elasticsearch-spark_2.10

**Comment by jbaiera** [comment]
@ndimiduk In 5.0 the spark artifact naming conventions were changed. Considering your previous comments, your version of spark will probably want : `org.elasticsearch:elasticsearch-spark-13_2.10:5.2.0`

**Comment by ndimiduk** [comment]
Ah yes, I found the details in the docs. Thanks James!

**Comment by ndimiduk** [comment]
Can I get this issue reopened?

I've upgraded to ES-Hadoop 5.1.2. Now when I apply the config setting `[spark.]es.scroll.limit=10000`, i get the following stack out of the spark tasks:

```
org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: Validation Failed: 1: scrollId is missing;
        at org.elasticsearch.hadoop.rest.RestClient.checkResponse(RestClient.java:488)
        at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:446)
        at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:436)
        at org.elasticsearch.hadoop.rest.RestClient.scroll(RestClient.java:497)
        at org.elasticsearch.hadoop.rest.RestRepository.scroll(RestRepository.java:375)
        at org.elasticsearch.hadoop.rest.ScrollQuery.hasNext(ScrollQuery.java:112)
        at org.elasticsearch.spark.rdd.AbstractEsRDDIterator.hasNext(AbstractEsRDDIterator.scala:61)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:144)
        at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1157)
        at scala.collection.TraversableOnce$class.aggregate(TraversableOnce.scala:201)
        at scala.collection.AbstractIterator.aggregate(Iterator.scala:1157)
        at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$23.apply(RDD.scala:1135)
        at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$23.apply(RDD.scala:1135)
        at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$24.apply(RDD.scala:1136)
        at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$24.apply(RDD.scala:1136)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by ndimiduk** [comment]
Any thoughts here @jbaiera ? Do I need to file a new ticket or can we continue here?

**Comment by jbaiera** [comment]
@ndimiduk seems like an issue, yeah. Lets file a new ticket. Please make sure to include the full stack trace you have listed in your last comment, as well as the versions of Spark, Elasticsearch, and ES-Hadoop you're using, and finally the settings/code you are using for setting up and executing your job (the simpler the reproduction, the faster the triaging). Thanks for your patience in this!
