### ISSUE TITLE
NullPointerException when setting “es.read.field.as.array.include” option

### ISSUE THREAD

**Issue by dustinschultz** [elastic/elasticsearch-hadoop#928]
### What kind an issue is this?

- [x] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   

### Issue description

https://discuss.elastic.co/t/nullpointerexception-when-settings-es-read-field-as-array-include-options/63223

Strack trace:

```
Caused by: java.lang.NullPointerException
        at java.lang.String.startsWith(String.java:1405)
        at java.lang.String.startsWith(String.java:1434)
        at org.elasticsearch.hadoop.serialization.field.FieldFilter.filter(FieldFilter.java:105)
        at org.elasticsearch.hadoop.serialization.field.FieldFilter.filter(FieldFilter.java:132)
        at org.elasticsearch.spark.serialization.ScalaValueReader.addToArray(ScalaValueReader.scala:177)
        at org.elasticsearch.hadoop.serialization.ScrollReader.list(ScrollReader.java:752)
        at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:699)
        at org.elasticsearch.hadoop.serialization.ScrollReader.map(ScrollReader.java:806)
        at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:704)
        at org.elasticsearch.hadoop.serialization.ScrollReader.readHitAsMap(ScrollReader.java:458)
        at org.elasticsearch.hadoop.serialization.ScrollReader.readHit(ScrollReader.java:383)
        at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:278)
        at org.elasticsearch.hadoop.serialization.ScrollReader.read(ScrollReader.java:251)
        at org.elasticsearch.hadoop.rest.RestRepository.scroll(RestRepository.java:456)
        at org.elasticsearch.hadoop.rest.ScrollQuery.hasNext(ScrollQuery.java:86)
        at org.elasticsearch.spark.rdd.AbstractEsRDDIterator.hasNext(AbstractEsRDDIterator.scala:43)
        at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:48)
        at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:84)
        at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:84)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

``` 

### Version Info

OS:         :  OS X
JVM         :  Java 8
Hadoop/Spark:  Spark version 1.6.3
ES-Hadoop   :  2.4.4
ES          :  2.4

**Comment by razaba** [comment]
I'm experiencing something similar:
**My stack:**
- ES: 2.3.5
- Spark: 2.0.2

**Data Mapping:**
```json
      "features": {
            "type": "nested",
            "properties": {
              "categories": {
                "type": "nested",
                "properties": {
                  "key": {
                    "type": "string",
                    "analyzer": "keyword"
                  },
                  "value": {
                    "type": "float"
                  },
                  "vectorType": {
                    "type": "string",
                    "analyzer": "keyword"
                  }
                }
              },
              "vectorType": {
                "type": "string",
                "analyzer": "keyword"
              }
            }
          }
```
**Data example:**
```json
{
          "features": [
            {
              "categories": [
                {
                  "value": 0.024360129,
                  "key": "male 0-2"
                },
                {
                  "value": 0.009688089,
                  "key": "female 0-2"
                }
            ],
              "vectorType": "global"
         }
     ]
}
```

Stack:
```java
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost): java.lang.NullPointerException
	at org.elasticsearch.spark.sql.ScalaEsRow.values$lzycompute(ScalaEsRow.scala:27)
	at org.elasticsearch.spark.sql.ScalaEsRow.values(ScalaEsRow.scala:27)
	at org.elasticsearch.spark.sql.ScalaEsRow.length(ScalaEsRow.scala:34)
	at org.apache.spark.sql.Row$class.size(Row.scala:124)
	at org.elasticsearch.spark.sql.ScalaEsRow.size(ScalaEsRow.scala:25)
	at org.apache.spark.sql.catalyst.CatalystTypeConverters$StructConverter.toCatalystImpl(CatalystTypeConverters.scala:258)
	at org.apache.spark.sql.catalyst.CatalystTypeConverters$StructConverter.toCatalystImpl(CatalystTypeConverters.scala:251)
	at org.apache.spark.sql.catalyst.CatalystTypeConverters$CatalystTypeConverter.toCatalyst(CatalystTypeConverters.scala:103)
	at org.apache.spark.sql.catalyst.CatalystTypeConverters$ArrayConverter$$anonfun$toCatalystImpl$2.apply(CatalystTypeConverters.scala:164)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.spark.sql.catalyst.CatalystTypeConverters$ArrayConverter.toCatalystImpl(CatalystTypeConverters.scala:164)
	at org.apache.spark.sql.catalyst.CatalystTypeConverters$ArrayConverter.toCatalystImpl(CatalystTypeConverters.scala:154)
	at org.apache.spark.sql.catalyst.CatalystTypeConverters$CatalystTypeConverter.toCatalyst(CatalystTypeConverters.scala:103)
	at org.apache.spark.sql.catalyst.CatalystTypeConverters$$anonfun$createToCatalystConverter$2.apply(CatalystTypeConverters.scala:403)
	at org.apache.spark.sql.execution.RDDConversions$$anonfun$rowToRowRdd$1$$anonfun$apply$2.apply(ExistingRDD.scala:67)
	at org.apache.spark.sql.execution.RDDConversions$$anonfun$rowToRowRdd$1$$anonfun$apply$2.apply(ExistingRDD.scala:64)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:370)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:246)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:240)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:803)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:803)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jbaiera** [comment]
Sorry for the late comments on this, but it's spring cleaning time: 

@razaba The issue you've described doesn't look related to this. If you're still having issues, please post on the [forums](https://discuss.elastic.co/c/elasticsearch-and-hadoop), as I'm unable to reproduce your error against master. 

As for the original issue on this thread, it is indeed still an issue.

**Comment by smokeriu** [comment]
> I'm experiencing something similar: **My stack:**
> 
> * ES: 2.3.5
> * ES spark: 5.2.1
> * Spark: 2.0.2
> 
> **Data Mapping:**
> 
> ```json
>       "features": {
>             "type": "nested",
>             "properties": {
>               "categories": {
>                 "type": "nested",
>                 "properties": {
>                   "key": {
>                     "type": "string",
>                     "analyzer": "keyword"
>                   },
>                   "value": {
>                     "type": "float"
>                   },
>                   "vectorType": {
>                     "type": "string",
>                     "analyzer": "keyword"
>                   }
>                 }
>               },
>               "vectorType": {
>                 "type": "string",
>                 "analyzer": "keyword"
>               }
>             }
>           }
> ```
> 
> **Data example:**
> 
> ```json
> {
>           "features": [
>             {
>               "categories": [
>                 {
>                   "value": 0.024360129,
>                   "key": "male 0-2"
>                 },
>                 {
>                   "value": 0.009688089,
>                   "key": "female 0-2"
>                 }
>             ],
>               "vectorType": "global"
>          }
>      ]
> }
> ```
> 
> Stack:
> 
> ```java
> : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 1 times, most recent failure: Lost task 0.0 in stage 0.0 (TID 0, localhost): java.lang.NullPointerException
> 	at org.elasticsearch.spark.sql.ScalaEsRow.values$lzycompute(ScalaEsRow.scala:27)
> 	at org.elasticsearch.spark.sql.ScalaEsRow.values(ScalaEsRow.scala:27)
> 	at org.elasticsearch.spark.sql.ScalaEsRow.length(ScalaEsRow.scala:34)
> 	at org.apache.spark.sql.Row$class.size(Row.scala:124)
> 	at org.elasticsearch.spark.sql.ScalaEsRow.size(ScalaEsRow.scala:25)
> 	at org.apache.spark.sql.catalyst.CatalystTypeConverters$StructConverter.toCatalystImpl(CatalystTypeConverters.scala:258)
> 	at org.apache.spark.sql.catalyst.CatalystTypeConverters$StructConverter.toCatalystImpl(CatalystTypeConverters.scala:251)
> 	at org.apache.spark.sql.catalyst.CatalystTypeConverters$CatalystTypeConverter.toCatalyst(CatalystTypeConverters.scala:103)
> 	at org.apache.spark.sql.catalyst.CatalystTypeConverters$ArrayConverter$$anonfun$toCatalystImpl$2.apply(CatalystTypeConverters.scala:164)
> 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
> 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
> 	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
> 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
> 	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
> 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
> 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
> 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
> 	at org.apache.spark.sql.catalyst.CatalystTypeConverters$ArrayConverter.toCatalystImpl(CatalystTypeConverters.scala:164)
> 	at org.apache.spark.sql.catalyst.CatalystTypeConverters$ArrayConverter.toCatalystImpl(CatalystTypeConverters.scala:154)
> 	at org.apache.spark.sql.catalyst.CatalystTypeConverters$CatalystTypeConverter.toCatalyst(CatalystTypeConverters.scala:103)
> 	at org.apache.spark.sql.catalyst.CatalystTypeConverters$$anonfun$createToCatalystConverter$2.apply(CatalystTypeConverters.scala:403)
> 	at org.apache.spark.sql.execution.RDDConversions$$anonfun$rowToRowRdd$1$$anonfun$apply$2.apply(ExistingRDD.scala:67)
> 	at org.apache.spark.sql.execution.RDDConversions$$anonfun$rowToRowRdd$1$$anonfun$apply$2.apply(ExistingRDD.scala:64)
> 	at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
> 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
> 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
> 	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:370)
> 	at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:246)
> 	at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:240)
> 	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:803)
> 	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:803)
> 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
> 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
> 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
> 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
> 	at org.apache.spark.scheduler.Task.run(Task.scala:86)
> 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:745)
> ```

Hello, I have the same problem. I can't find a solution on Google. How did you solve it?

**Comment by masseyke** [comment]
Hi @smokeriu. This issue is really old, and it sounds like the error you referenced was not reproducible and was not part of this issue. Can you create a post on https://discuss.elastic.co/ (and label it with `es-hadoop`) that includes everything needed to reproduce the problem you are seeing (versions of ES, es-hadoop, and spark, as well as data and the code to cause the problem)? Thanks.
