### ISSUE TITLE
"EsHadoopInvalidRequest: Validation Failed: 1: scrollId is missing" when es.scroll.limit=10000

### ISSUE THREAD

**Issue by ndimiduk** [elastic/elasticsearch-hadoop#935]
### Issue description

Enabling a scroll limit to a spark application results in `EsHadoopInvalidRequest: Validation Failed: 1: scrollId is missing`. 

Carried over from #925.

Strack trace:

```
org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: Validation Failed: 1: scrollId is missing;
        at org.elasticsearch.hadoop.rest.RestClient.checkResponse(RestClient.java:488)
        at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:446)
        at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:436)
        at org.elasticsearch.hadoop.rest.RestClient.scroll(RestClient.java:497)
        at org.elasticsearch.hadoop.rest.RestRepository.scroll(RestRepository.java:375)
        at org.elasticsearch.hadoop.rest.ScrollQuery.hasNext(ScrollQuery.java:112)
        at org.elasticsearch.spark.rdd.AbstractEsRDDIterator.hasNext(AbstractEsRDDIterator.scala:61)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:327)
        at scala.collection.Iterator$class.foreach(Iterator.scala:727)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
        at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:144)
        at scala.collection.AbstractIterator.foldLeft(Iterator.scala:1157)
        at scala.collection.TraversableOnce$class.aggregate(TraversableOnce.scala:201)
        at scala.collection.AbstractIterator.aggregate(Iterator.scala:1157)
        at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$23.apply(RDD.scala:1135)
        at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$23.apply(RDD.scala:1135)
        at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$24.apply(RDD.scala:1136)
        at org.apache.spark.rdd.RDD$$anonfun$treeAggregate$1$$anonfun$24.apply(RDD.scala:1136)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
        at org.apache.spark.scheduler.Task.run(Task.scala:89)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:227)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
``` 

### Version Info

OS:         :  Ubuntu 14.04
JVM         :  
```
java version "1.8.0_72"
Java(TM) SE Runtime Environment (build 1.8.0_72-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.72-b15, mixed mode) 
```
Hadoop/Spark:  Apache Spark 2.1.0-bin-hadoop2.7
ES-Hadoop   :  elasticsearch-spark-20_2.11 5.1.2
ES          :  5.1.2, c8c4c16

**Comment by ndimiduk** [comment]
Ping. Any update here?

**Comment by jbaiera** [comment]
@ndimiduk I've been having a hard time reproducing this locally with ES-Hadoop. The error you are experiencing is from Elasticsearch when a scroll request is sent without a scroll id. It seems like a previous scroll request returned an empty string for an ID and ES-Hadoop tried sending that along for the next call, but my assumption is just from looking at the code and is unconfirmed since I can't get a reproduction of it. 

Could you enable trace level logging on just the `org.elasticsearch.hadoop.rest.commonshttp` package and paste the job logs here when you encounter the failure? That should allow us to capture the response from the server and hopefully figure out why it's dropping the scroll id in the response.

**Comment by SergeVil** [comment]
I have same issue when I run 

es_read_conf = {
    "es.nodes" : "myhost",
    "es.port" : "9200",
    "es.resource" : "vertex/author",
    "es.query" : q,
    "es.scroll.limit" : "1000" 
}

es_rdd = sc.newAPIHadoopRDD(
    inputFormatClass="org.elasticsearch.hadoop.mr.EsInputFormat",
    keyClass="org.apache.hadoop.io.NullWritable", 
    valueClass="org.elasticsearch.hadoop.mr.LinkedMapWritable", 
    conf=es_read_conf)

**Comment by jbaiera** [comment]
@SergeVil Could you enable `TRACE` level logging on just the `org.elasticsearch.hadoop.rest.commonshttp` package and paste the job logs here when you encounter the failure?

I still have not been able to reproduce this bug. Hopefully the logs reveal some information about what is going on.

**Comment by SergeVil** [comment]
@jbaiera Can you provide me the example of Python code I have to run, please?

**Comment by ndimiduk** [comment]
You need to edit the log4j.properties file on the classpath of your job.

**Comment by SergeVil** [comment]
[1.txt](https://github.com/elastic/elasticsearch-hadoop/files/1044748/1.txt)

**Comment by SergeVil** [comment]
[2.txt](https://github.com/elastic/elasticsearch-hadoop/files/1045307/2.txt)

**Comment by jbaiera** [comment]
@SergeVil Perfect! Thank you for those logs. They are incredibly helpful for figuring out what is going on. 

I think I see the issue now. I'm going to retry getting a local reproduction of the bug now that I understand it better, and will hopefully get a patch in soon after that.

**Comment by SergeVil** [comment]
@jbaiera Can I use some jar from jenkins or other tool to test it in my environment?

**Comment by jbaiera** [comment]
The snapshots should be available soon, but if you would like something sooner, you can always checkout the project and just run `./gradlew build distZip install` which should create the zip directory with all the artifacts in it under the `build/distribution` directory in the project.

**Comment by SergeVil** [comment]
How often are you usually creating snapshots?
Thank you for fixing it!

**Comment by jbaiera** [comment]
@SergeVil Snapshots are cut every day for ES-Hadoop off of the master branch.

**Comment by SergeVil** [comment]
@jbaiera James, could you point me out to the snapshot, please? Many thanks!

**Comment by jbaiera** [comment]
@SergeVil It's detailed in the project README here: https://github.com/elastic/elasticsearch-hadoop#development-snapshot

**Comment by adriancole** [comment]
PS I may be wrong, but I think the fix to this caused a regression on 2.x. PTAL https://github.com/elastic/elasticsearch-hadoop/issues/1034
