### ISSUE TITLE
Why does the data come in duplicates?

### ISSUE THREAD

**Issue by rockmgh** [elastic/elasticsearch-hadoop#936]
### Issue description
my mappings structure
port is integer

"mappings": {
"data_2": {
	"properties": {
		"ip": {
			"type": "ip"
		},
		**"port": {
			"type": "integer"
		},**
		"in_byte": {
			"type": "long"
		},
		"out_byte": {
			"type": "long"
		}
	}
}
}

insert data 

{"ip":"192.168.0.89", "port":10024,  "in_byte":8910, "out_byte":349906}  is x4 duplicate insert
{"ip":"192.168.0.214", "port":"a", "in_byte":66, "out_byte":60}	 is no insert

Why does the data come in duplicates?

When testing with logstash, exactly one was entered.

### Steps to reproduce

Code:

```
sparkConf.set(ConfigurationOptions.ES_BATCH_SIZE_ENTRIES, "5000");
sparkConf.set(ConfigurationOptions.ES_BATCH_WRITE_RETRY_COUNT, "3");
sparkConf.set(ConfigurationOptions.ES_BATCH_WRITE_RETRY_WAIT, "5s");            
sparkConf.set(ConfigurationOptions.ES_BATCH_WRITE_RETRY_POLICY, "none");
sparkConf.set(ConfigurationOptions.ES_BATCH_FLUSH_MANUAL, "true");
sparkConf.set(ConfigurationOptions.ES_BATCH_WRITE_REFRESH , "false");


KafkaUtils.createDirectStream.foreachRDD()

.....

@Override
public void call(JavaRDD<String> rdd) throws Exception {					

	JavaEsSpark.saveJsonToEs(rdd, "test_2017","/data_2");       
}
```

Strack trace:

```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 8 in stage 3.0 failed 4 times, most recent failure: 
Lost task 8.3 in stage 3.0 (TID 27, test3.cc): 
org.apache.spark.util.TaskCompletionListenerException: Found unrecoverable error 
[192.168.0.3:9200] returned Bad Request(400) - failed to parse [port]; Bailing out..
	at org.apache.spark.TaskContextImpl.markTaskCompleted(TaskContextImpl.scala:105)
	at org.apache.spark.scheduler.Task.run(Task.scala:98)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1450)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1438)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1437)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1437)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
	at scala.Option.foreach(Option.scala:236)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:811)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1659)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1618)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1607)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:632)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1871)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1884)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1904)
	at org.elasticsearch.spark.rdd.EsSpark$.doSaveToEs(EsSpark.scala:102)
	at org.elasticsearch.spark.rdd.EsSpark$.saveToEs(EsSpark.scala:76)
	at org.elasticsearch.spark.rdd.EsSpark$.saveToEs(EsSpark.scala:73)
	at org.elasticsearch.spark.rdd.EsSpark$.saveJsonToEs(EsSpark.scala:106)
	at org.elasticsearch.spark.rdd.api.java.JavaEsSpark$.saveJsonToEs(JavaEsSpark.scala:62)
	at org.elasticsearch.spark.rdd.api.java.JavaEsSpark.saveJsonToEs(JavaEsSpark.scala)
	at nib.spark.save_es.FnEsSave.call(TestSave.java:87)
	at nib.spark.save_es.FnEsSave.call(TestSave.java:26)
	at org.apache.spark.streaming.api.java.JavaDStreamLike$$anonfun$foreachRDD$1.apply(JavaDStreamLike.scala:272)
	at org.apache.spark.streaming.api.java.JavaDStreamLike$$anonfun$foreachRDD$1.apply(JavaDStreamLike.scala:272)
	at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3.apply(DStream.scala:627)
	at org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3.apply(DStream.scala:627)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(ForEachDStream.scala:51)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:51)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1$$anonfun$apply$mcV$sp$1.apply(ForEachDStream.scala:51)
	at org.apache.spark.streaming.dstream.DStream.createRDDWithLocalProperties(DStream.scala:415)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply$mcV$sp(ForEachDStream.scala:50)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:50)
	at org.apache.spark.streaming.dstream.ForEachDStream$$anonfun$1.apply(ForEachDStream.scala:50)
	at scala.util.Try$.apply(Try.scala:161)
	at org.apache.spark.streaming.scheduler.Job.run(Job.scala:39)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply$mcV$sp(JobScheduler.scala:245)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:245)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler$$anonfun$run$1.apply(JobScheduler.scala:245)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
	at org.apache.spark.streaming.scheduler.JobScheduler$JobHandler.run(JobScheduler.scala:244)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
``` 

### Version Info

OS:         :  
JVM         :  1.8.0_102
Hadoop/Spark:   spark2.0
ES-Hadoop   :  elasticsearch-spark-20_2.10-5.1.2.jar
ES          :   elastic 2.4.2

**Comment by jbaiera** [comment]
@rockmgh The second document that you have outlined is using a string value `"a"` in a field meant for an integer. This is causing a failure in the job. According to your stack trace, the following is printed:
```
....(snip) Task 8 in stage 3.0 failed 4 times (snip)...
```
If the task is retried 4 times during the failure, then the first document will be retried each of the four task executions. To avoid multiple inserts in the face of task failure, it is advised to specify a field to use as the document ID.
