### ISSUE TITLE
Spark to ES error

### ISSUE THREAD

**Issue by lhsoft** [elastic/elasticsearch-hadoop#947]
### What kind an issue is this?

- [x] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.   
    The easier it is to track down the bug, the faster it is solved. 
- [ ] Feature Request. Start by telling us what problem you’re trying to solve.  
    Often a solution already exists! Don’t send pull requests to implement new features without 
    first getting our support. Sometimes we leave features out on purpose to keep the project small.

### Issue description

I used spark to write to ES and got the following error:
17/03/01 20:41:52 INFO Client:
	 client token: N/A
	 diagnostics: User class threw exception: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 9, bjyz-hadoop-2.bjyz.baidu.com, executor 2): java.lang.NoClassDefFoundError: Could not initialize class org.elasticsearch.hadoop.util.Version
	at org.elasticsearch.hadoop.rest.RestService.createWriter(RestService.java:542)
	at org.elasticsearch.spark.rdd.EsRDDWriter.write(EsRDDWriter.scala:58)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:102)
	at org.elasticsearch.spark.rdd.EsSpark$$anonfun$doSaveToEs$1.apply(EsSpark.scala:102)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:99)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

I find the class org.elasticsearch.hadoop.util.Version is the jar
My spark is running on yarn and the java version is 1.8

### Steps to reproduce

Code:

```
Test/code snippet
```

Strack trace:

```
Stack trace goes here
``` 

### Version Info

OS:         :  
JVM         :  
Hadoop/Spark:  
ES-Hadoop   :  
ES          :

**Comment by jbaiera** [comment]
Closing this as there has been no feedback
