### ISSUE TITLE
nested documents not supported in spark connector

### ISSUE THREAD

**Issue by ndimiduk** [elastic/elasticsearch-hadoop#948]
### What kind an issue is this?

- [X] Bug report.

### Issue description

Queries to indices containing arrays of [nested](https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html) objects fail. It appears the data returned for the nested documents are of type `ScalaEsRow`, which is not supported as an `Array` type by Catalyst.

Strack trace:

```
Caused by: scala.MatchError: *redacted* (of class org.elasticsearch.spark.sql.ScalaEsRow)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$ArrayConverter.toCatalystImpl(CatalystTypeConverters.scala:160)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$ArrayConverter.toCatalystImpl(CatalystTypeConverters.scala:154)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$CatalystTypeConverter.toCatalyst(CatalystTypeConverters.scala:103)
        at org.apache.spark.sql.catalyst.CatalystTypeConverters$$anonfun$createToCatalystConverter$2.apply(CatalystTypeConverters.scala:383)
        at org.apache.spark.sql.execution.RDDConversions$$anonfun$rowToRowRdd$1$$anonfun$apply$3.apply(ExistingRDD.scala:60)
        at org.apache.spark.sql.execution.RDDConversions$$anonfun$rowToRowRdd$1$$anonfun$apply$3.apply(ExistingRDD.scala:57)
        at scala.collection.Iterator$$anon$11.next(Iterator.scala:409)
        at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
        at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
        at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:377)
        at org.apache.spark.sql.execution.columnar.InMemoryRelation$$anonfun$1$$anon$1.hasNext(InMemoryRelation.scala:138)
        at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:215)
        at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:957)
        at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:948)
        at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:888)
        at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:948)
        at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:694)
        at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:334)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:285)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96)
        at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53)
        at org.apache.spark.scheduler.Task.run(Task.scala:99)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

### Version Info

OS:         :  
JVM         :  
Hadoop/Spark:  Apache Spark 2.1.0
ES-Hadoop   :  elasticsearch-spark-20_2.11 5.1.2
ES          :  5.1.2 / c8c4c16

**Comment by sujee81** [comment]
I encountered the same issue for nested documents. For now, I used         options.put("es.read.field.exclude", "field_name"); to exclude the nested field.

Spark version: 2.1.0
es-hadoop: 5.2.2

**Comment by ndimiduk** [comment]
Unfortunately excluding these arrays is not an option for my use-case.

**Comment by ndimiduk** [comment]
Ping. Any update here?

**Comment by rlebreto** [comment]
Same issue for me...

**Comment by prabhushrikant** [comment]
Same issue for me too. What's the alternate solution?

**Comment by freethejazz** [comment]
@prabhushrikant I'm not experiencing this issue so I can't verify this works, but have you tried using `es.read.as.array.include`? https://www.elastic.co/guide/en/elasticsearch/hadoop/current/configuration.html#cfg-field-info

**Comment by prabhushrikant** [comment]
Yes I have tried it and I always get null for Categories field in following schema{"userId": 402885,
{
            "userUuid": "F2896A1F1A7D411A69",
            "affiliations": [
                {
                    "org": {
                        "orgName": "Dick's Sporting Goods",
                        "categories": [
                            65,
                            68,
                            85
                        ],
                    },
}
],
}
Do I have to any other library installed apart from org.elasticsearch.spark.sql , may be org.elasticsearch.hadoop.sql

**Comment by freethejazz** [comment]
Aaah, @prabhushrikant I think your issue may be different. OP was specifically calling out the nested object data type that Elasticsearch supports (see his inline link). It may be worth opening a new issue with the data you posted above, the elasticsearch mappings, and the specific error you're getting (or just that it's always null if that's the only thing happening.

**Comment by freethejazz** [comment]
@ndimiduk Have you tried using `es.read.as.array.include`? (https://github.com/elastic/elasticsearch-hadoop/issues/948#issuecomment-324066209)

**Comment by jbaiera** [comment]
@ndimiduk Are you still experiencing this? I'm doing some spring cleaning and attempted a reproduction and could not get the error to manifest on the master branch:

```scala
val mapping =
      s"""
         |{
         |  "properties": {
         |    "name": { "type": "text"},
         |    "description": {"type": "text"},
         |    "employees": {
         |      "type": "nested",
         |      "properties": {
         |        "name": {"type": "text"},
         |        "salary": {"type": "long"}
         |      }
         |    }
         |  }
         |}
      """.stripMargin

    val index = "sparksql-struct-index"
    val typeName = "doc"
    val indexAndType = index + "/" + typeName

    try {
      RestUtils.delete(index)
    } catch {
      case _: Throwable => // what ever
    }

    RestUtils.touch(index)
    RestUtils.putMapping(index, typeName, mapping.getBytes())
    RestUtils.postData(indexAndType,
      """
        |{
        |  "name": "FakeCo",
        |  "description": "Fake it til we make it",
        |  "employees": [
        |    {
        |      "name": "Zerb",
        |      "salary": 1
        |    },
        |    {
        |      "name": "Ping",
        |      "salary": 3
        |    }
        |  ]
        |}
      """.stripMargin.getBytes())
    RestUtils.refresh(index)

    val resolvedMapping = RestUtils.getMapping(indexAndType)
    println(resolvedMapping)
    println()
    val flattened: Map[String, FieldType] = resolvedMapping.flatten()
    flattened.foreach(println(_))
    println()

    println("Settings:")
    sql.getAllConfs.filter(_._1.startsWith("es")).foreach(println(_))

    val df = sql.read.format("es").load(indexAndType)

    df.select(df("employees")).show()
    df.select(df("employees.name")).show()
```

Gives me:
```
...
doc=[description=TEXT, employees=[name=TEXT, salary=LONG], name=TEXT]

(description,TEXT)
(employees,NESTED)
(employees.name,TEXT)
(employees.salary,LONG)
(name,TEXT)

Settings:
(es.batch.write.retry.wait,1s)
(es.batch.size.bytes,1kb)
(es.batch.size.entries,3)
(es.storm.bolt.flush.entries.size,1)
(es.nodes,localhost:9500)
...
+--------------------+
|           employees|
+--------------------+
|[[Zerb,1], [Ping,3]]|
+--------------------+
...
+------------+
|        name|
+------------+
|[Zerb, Ping]|
+------------+
```

Let me know if there's anything missing for this reproduction.

**Comment by ndimiduk** [comment]
Thanks for looking into it James. I haven't tried this recently, so if it's
working on master I'll take your word for it.

**Comment by jbaiera** [comment]
Cheers, feel free to post here if you are still running into issues. If there's a problem we can re-open.
