### ISSUE TITLE
Date filters are not push-down

### ISSUE THREAD

**Issue by sujee81** [elastic/elasticsearch-hadoop#950]
- [x] Bug report

### Issue description

- Date filters are not pushed down to ES query when java.sql.Date is used.
- Filters with java.sql.Timestamp are pushed down but fails due to ES "strict_date" format.

### Steps to reproduce

ES:
```
PUT date-test
{
   "mappings": {
      "customer": {
         "properties": {
            "name": {
               "type": "text"
            },
            "dateOfBirth": {
               "type": "date",
               "format": "strict_date"
            }
         }
      }
   }
}

POST /date-test/customer/1
{
    "name": "Customer1",
    "dateOfBirth": "1988-08-28"
}
```

Spark (Java):
```
Dataset<Row> ds = sqlContext.read().format("org.elasticsearch.spark.sql").load("date-test/customer");
ds.filter(ds.col("dateOfBirth").leq(Date.valueOf(LocalDate.of(2017, 3, 8)))).count();
```

As shown in the log below, "leq" is not pushdown.
```
DEBUG DataSource:166 - Pushing down filters [IsNotNull(dateOfBirth)]
``` 

However java.sql.Timestamp filters are pushed down.
```
ds.filter(ds.col("dateOfBirth").leq(Timestamp.valueOf(LocalDate.of(2017, 3, 8).atStartOfDay()))).count();
```
```
DEBUG DataSource:166 - Pushing down filters [IsNotNull(dateOfBirth),LessThanOrEqual(dateOfBirth,2017-03-08 00:00:00.0)]
```

But fails to execute at ES level due to "strict_date" format
```
Exception in thread "main" org.apache.spark.sql.catalyst.errors.package$TreeNodeException: execute, tree:
Exchange SinglePartition
+- *HashAggregate(keys=[], functions=[partial_count(1)], output=[count#14L])
   +- *Project
      +- *Filter (isnotnull(dateOfBirth#0) && (dateOfBirth#0 <= 1488884400000000))
         +- *Scan ElasticsearchRelation(Map(es.resource -> date-test/customer),org.apache.spark.sql.SQLContext@41f4039e,None) [dateOfBirth#0] PushedFilters: [IsNotNull(dateOfBirth), LessThanOrEqual(dateOfBirth,2017-03-08 00:00:00.0)], ReadSchema: struct<>

	at org.apache.spark.sql.catalyst.errors.package$.attachTree(package.scala:56)
	at org.apache.spark.sql.execution.exchange.ShuffleExchange.doExecute(ShuffleExchange.scala:112)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:135)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:132)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:113)
	at org.apache.spark.sql.execution.InputAdapter.inputRDDs(WholeStageCodegenExec.scala:235)
	at org.apache.spark.sql.execution.aggregate.HashAggregateExec.inputRDDs(HashAggregateExec.scala:141)
	at org.apache.spark.sql.execution.WholeStageCodegenExec.doExecute(WholeStageCodegenExec.scala:368)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:114)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:135)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:132)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:113)
	at org.apache.spark.sql.execution.SparkPlan.getByteArrayRdd(SparkPlan.scala:225)
	at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:272)
	at org.apache.spark.sql.Dataset$$anonfun$org$apache$spark$sql$Dataset$$execute$1$1.apply(Dataset.scala:2371)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:57)
	at org.apache.spark.sql.Dataset.withNewExecutionId(Dataset.scala:2765)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$execute$1(Dataset.scala:2370)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collect(Dataset.scala:2377)
	at org.apache.spark.sql.Dataset$$anonfun$count$1.apply(Dataset.scala:2405)
	at org.apache.spark.sql.Dataset$$anonfun$count$1.apply(Dataset.scala:2404)
	at org.apache.spark.sql.Dataset.withCallback(Dataset.scala:2778)
	at org.apache.spark.sql.Dataset.count(Dataset.scala:2404)
	at Main.main(Main.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: org.elasticsearch.hadoop.rest.EsHadoopInvalidRequest: failed to parse date field [2017-03-08T00:00:00+13:00] with format [strict_date]
{"query":{"bool":{"must":[{"match_all":{}}],"filter":[{"exists":{"field":"dateOfBirth"}},{"range":{"dateOfBirth":{"lte":"2017-03-08T00:00:00+13:00"}}}]}}}
	at org.elasticsearch.hadoop.rest.RestClient.checkResponse(RestClient.java:488)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:446)
	at org.elasticsearch.hadoop.rest.RestClient.execute(RestClient.java:436)
	at org.elasticsearch.hadoop.rest.RestClient.countInES5X(RestClient.java:574)
	at org.elasticsearch.hadoop.rest.RestClient.count(RestClient.java:552)
	at org.elasticsearch.hadoop.rest.RestService.findSlicePartitions(RestService.java:332)
	at org.elasticsearch.hadoop.rest.RestService.findPartitions(RestService.java:267)
	at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions$lzycompute(AbstractEsRDD.scala:77)
	at org.elasticsearch.spark.rdd.AbstractEsRDD.esPartitions(AbstractEsRDD.scala:76)
	at org.elasticsearch.spark.rdd.AbstractEsRDD.getPartitions(AbstractEsRDD.scala:44)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:252)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:250)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:250)
	at org.apache.spark.ShuffleDependency.<init>(Dependency.scala:91)
	at org.apache.spark.sql.execution.exchange.ShuffleExchange$.prepareShuffleDependency(ShuffleExchange.scala:261)
	at org.apache.spark.sql.execution.exchange.ShuffleExchange.prepareShuffleDependency(ShuffleExchange.scala:84)
	at org.apache.spark.sql.execution.exchange.ShuffleExchange$$anonfun$doExecute$1.apply(ShuffleExchange.scala:121)
	at org.apache.spark.sql.execution.exchange.ShuffleExchange$$anonfun$doExecute$1.apply(ShuffleExchange.scala:112)
	at org.apache.spark.sql.catalyst.errors.package$.attachTree(package.scala:52)
	... 33 more
```

### Version Info

OS:         :  Mac Sierra
JVM         :  Java-8
Hadoop/Spark:  2.1.0
ES-Hadoop   :  5.2.2
ES          :  5.1.2

**Comment by jbaiera** [comment]
The reason in this case that the Timestamp field pushdown fails is because ES-Hadoop only supports the `date_time_no_millis` format in Elasticsearch.

As for the reason for why java.sql.Date does not push down, this seems to be an issue with how Spark performs compatibility casting. When reading data from Elasticsearch in order to discover the mapping of a field, the schema notes that the `dateOfBirth` field is a `TimestampType` field in Spark. After running a debugging cycle, I've found that for some reason, Spark casts both sides of the `LEQ` operation into strings and tries to perform less than or equal on their values. The filter never makes it to the connector for pushdown translation. There's probably a good reason for this in the Spark world, though it is not immediately apparent to me. Perhaps someone on that project may be able to comment.

That being said, I was able to change the code to get it to operate successfully. Instead of :
```
df.filter(df.col("dateOfBirth").leq(Date.valueOf(LocalDate.of(2017, 3, 8)))).count()
```
I rewrote it as:
```
df.filter(df.col("dateOfBirth").leq(Timestamp.from(LocalDate.of(2017, 3, 8).atStartOfDay().toInstant(ZoneOffset.UTC)))).count()
```
and now the filter is correctly pushed down.

The mapping must also be changed to use format `date_time_no_millis` in Elasticsearch.

**Comment by sujee81** [comment]
Thank you @jbaiera 
Yes, I also noticed the casting when using Date filter. Any plans to support other ES date formats like "strict_date" ?

**Comment by jbaiera** [comment]
@sujee81 I'm sorry, but for the time being there are no plans to extend the date formatting logic. Date parsing and formatting is an incredibly difficult problem that we've historically taken a hardline stance on not trying to make overly complicated in the connector. Elasticsearch maintains it's own logic for the handling of dates, which we do not depend on for purposes of keeping the connector simple.

**Comment by sujee81** [comment]
Thank you @jbaiera. I understand the reason of keeping the connector simple.

**Comment by jbaiera** [comment]
Since this looks more like an issue with Spark than the connector, I'll be closing this.
