### ISSUE TITLE
TaskCompletionListenerException: Failed to parse request body

### ISSUE THREAD

**Issue by coding2012** [elastic/elasticsearch-hadoop#955]
### What kind an issue is this?

- [x] Bug report. If you’ve found a bug, please provide a code snippet or test to reproduce it below.

### Issue description

Using Spark 2.10, and sc.esJsonRDD("data/test"), an exception is thrown. This started happening immediately when I upgraded to 5.3 (both Elasticsearch and the Spark JAR file).

Other notes: When I downgrade the JAR and ES to 5.2.2 everything works as expected.

Description

### Steps to reproduce

Create Document (Kibana/DevTools is easiest)
Code:
```
POST /data/test/1
{
  "sample": "document"
}
```

Run Spark Job (using Zeppelin)
Code:

```
import org.elasticsearch.spark.sql._
import org.elasticsearch.spark._
import org.apache.spark.sql._
val df = sc.esJsonRDD("data/test")
    .toDF("id", "json")
    .show()
```

Strack trace:

```
rg.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 9.0 failed 1 times, most recent failure: Lost task 1.0 in stage 9.0 (TID 21, localhost, executor driver): org.apache.spark.util.TaskCompletionListenerException: Failed to parse request body
DXF1ZXJ5QW5kRmV0Y2gBAAAAAAAABA0WaDIyYVVjU2JTZnlUNEFVZXZuNlpFUQ==
	at org.apache.spark.TaskContextImpl.markTaskCompleted(TaskContextImpl.scala:105)
	at org.apache.spark.scheduler.Task.run(Task.scala:112)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Driver stacktrace:
  at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1435)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1423)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1422)
  at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
  at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
  at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1422)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
  at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:802)
  at scala.Option.foreach(Option.scala:257)
  at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:802)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1650)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1605)
  at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1594)
  at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
  at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:628)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:1918)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:1931)
  at org.apache.spark.SparkContext.runJob(SparkContext.scala:1944)
  at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:333)
  at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:38)
  at org.apache.spark.sql.Dataset$$anonfun$org$apache$spark$sql$Dataset$$execute$1$1.apply(Dataset.scala:2371)
  at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:57)
  at org.apache.spark.sql.Dataset.withNewExecutionId(Dataset.scala:2765)
  at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$execute$1(Dataset.scala:2370)
  at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collect(Dataset.scala:2377)
  at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2113)
  at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:2112)
  at org.apache.spark.sql.Dataset.withTypedCallback(Dataset.scala:2795)
  at org.apache.spark.sql.Dataset.head(Dataset.scala:2112)
  at org.apache.spark.sql.Dataset.take(Dataset.scala:2327)
  at org.apache.spark.sql.Dataset.showString(Dataset.scala:248)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:636)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:595)
  at org.apache.spark.sql.Dataset.show(Dataset.scala:604)
  ... 88 elided
Caused by: org.apache.spark.util.TaskCompletionListenerException: Failed to parse request body
DXF1ZXJ5QW5kRmV0Y2gBAAAAAAAABA0WaDIyYVVjU2JTZnlUNEFVZXZuNlpFUQ==
  at org.apache.spark.TaskContextImpl.markTaskCompleted(TaskContextImpl.scala:105)
  at org.apache.spark.scheduler.Task.run(Task.scala:112)
  at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:282)
  ... 3 more``` 


### Version Info

OS:         :  Linux (using Docker on OSX with Docker image: SEBP/ELK:5.3.0)
JVM         :  openjdk-8-jdk
Hadoop/Spark:  Spark 2.10 / Scala 2.11
ES-Hadoop   :  na
ES          :  5.3

**Comment by jbaiera** [comment]
@coding2012 Could you provide trace level logging at the executor side for the `org.elasticsearch` packages and post the resulting logs here? This will help narrow down what is causing the problem. I would also double check that your spark executors are also using ES-Hadoop artifacts for version 5.3 and higher, and not just the driver.

**Comment by coding2012** [comment]
I was trying to reproduce today, and instead of getting the error again, I am successfully reading the JSON documents now. Only thing I can think of is I had to reset my computer today, not sure why that would have an affect on anything, but you never know.

**Comment by jbaiera** [comment]
Thanks for the update. Probably some sort of jar caching with Spark that expired. Closing this for now, let us know if it pops back up again.
