### ISSUE TITLE
ERROR Executor: Exception in task 0.0 in stage 44.0 (TID 50) java.lang.IndexOutOfBoundsException: 200 not in [0,200)

### ISSUE THREAD

**Issue by Supriya-Pasham** [elastic/elasticsearch-hadoop#967]
Issue : I am creating a Training and Testing model for predicting some data. I successfully created a Training model and running it, but when i run Testing code below exceptions is thrown. 

I am supplying input data limit correctly, even though **indexoutofbound** is displayed. Request someone to suggest an solution.

Strack trace:

```
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
17/05/01 18:49:57 ERROR Executor: Exception in task 0.0 in stage 44.0 (TID 50)
java.lang.IndexOutOfBoundsException: 200 not in [0,200)
	at breeze.linalg.SparseVector$mcD$sp.apply$mcD$sp(SparseVector.scala:74)
	at breeze.linalg.SparseVector$mcD$sp.apply(SparseVector.scala:73)
	at breeze.linalg.SparseVector$mcD$sp.apply(SparseVector.scala:49)
	at breeze.linalg.TensorLike$class.apply$mcID$sp(Tensor.scala:94)
	at breeze.linalg.SparseVector.apply$mcID$sp(SparseVector.scala:49)
	at org.apache.spark.ml.linalg.Vector$class.apply(Vectors.scala:102)
	at org.apache.spark.ml.linalg.SparseVector.apply(Vectors.scala:558)
	at org.apache.spark.ml.tree.ContinuousSplit.shouldGoLeft(Split.scala:161)
	at org.apache.spark.ml.tree.InternalNode.predictImpl(Node.scala:171)
	at org.apache.spark.ml.tree.InternalNode.predictImpl(Node.scala:172)
	at org.apache.spark.ml.tree.InternalNode.predictImpl(Node.scala:172)
	at org.apache.spark.ml.tree.InternalNode.predictImpl(Node.scala:172)
	at org.apache.spark.ml.tree.InternalNode.predictImpl(Node.scala:172)
	at org.apache.spark.ml.tree.InternalNode.predictImpl(Node.scala:172)
	at org.apache.spark.ml.tree.InternalNode.predictImpl(Node.scala:172)
	at org.apache.spark.ml.tree.InternalNode.predictImpl(Node.scala:172)
	at org.apache.spark.ml.tree.InternalNode.predictImpl(Node.scala:172)
	at org.apache.spark.ml.tree.InternalNode.predictImpl(Node.scala:172)
	at org.apache.spark.ml.classification.RandomForestClassificationModel$$anonfun$predictRaw$1.apply(RandomForestClassifier.scala:193)
	at org.apache.spark.ml.classification.RandomForestClassificationModel$$anonfun$predictRaw$1.apply(RandomForestClassifier.scala:192)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.IndexedSeqLike$$anon$1.foreach(IndexedSeqLike.scala:52)
	at org.apache.spark.ml.classification.RandomForestClassificationModel.predictRaw(RandomForestClassifier.scala:192)
	at org.apache.spark.ml.classification.RandomForestClassificationModel.predictRaw(RandomForestClassifier.scala:148)
	at org.apache.spark.ml.classification.ProbabilisticClassificationModel$$anonfun$1.apply(ProbabilisticClassifier.scala:112)
	at org.apache.spark.ml.classification.ProbabilisticClassificationModel$$anonfun$1.apply(ProbabilisticClassifier.scala:111)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:370)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:246)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:240)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:784)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:784)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:85)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
17/05/01 18:49:57 ERROR TaskSetManager: Task 0 in stage 44.0 failed 1 times; aborting job
Exception in thread "main" org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 44.0 failed 1 times, most recent failure: Lost task 0.0 in stage 44.0 (TID 50, localhost): java.lang.IndexOutOfBoundsException: 200 not in [0,200)
	at breeze.linalg.SparseVector$mcD$sp.apply$mcD$sp(SparseVector.scala:74)
	at breeze.linalg.SparseVector$mcD$sp.apply(SparseVector.scala:73)
	at breeze.linalg.SparseVector$mcD$sp.apply(SparseVector.scala:49)
	at breeze.linalg.TensorLike$class.apply$mcID$sp(Tensor.scala:94)
	at breeze.linalg.SparseVector.apply$mcID$sp(SparseVector.scala:49)
	at org.apache.spark.ml.linalg.Vector$class.apply(Vectors.scala:102)
	at org.apache.spark.ml.linalg.SparseVector.apply(Vectors.scala:558)
	at org.apache.spark.ml.tree.ContinuousSplit.shouldGoLeft(Split.scala:161)
	at org.apache.spark.ml.tree.InternalNode.predictImpl(Node.scala:171)
	at org.apache.spark.ml.tree.InternalNode.predictImpl(Node.scala:172)
	at org.apache.spark.ml.tree.InternalNode.predictImpl(Node.scala:172)
	at org.apache.spark.ml.tree.InternalNode.predictImpl(Node.scala:172)
	at org.apache.spark.ml.tree.InternalNode.predictImpl(Node.scala:172)
	at org.apache.spark.ml.tree.InternalNode.predictImpl(Node.scala:172)
	at org.apache.spark.ml.tree.InternalNode.predictImpl(Node.scala:172)
	at org.apache.spark.ml.tree.InternalNode.predictImpl(Node.scala:172)
	at org.apache.spark.ml.tree.InternalNode.predictImpl(Node.scala:172)
	at org.apache.spark.ml.tree.InternalNode.predictImpl(Node.scala:172)
	at org.apache.spark.ml.classification.RandomForestClassificationModel$$anonfun$predictRaw$1.apply(RandomForestClassifier.scala:193)
	at org.apache.spark.ml.classification.RandomForestClassificationModel$$anonfun$predictRaw$1.apply(RandomForestClassifier.scala:192)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.IndexedSeqLike$$anon$1.foreach(IndexedSeqLike.scala:52)
	at org.apache.spark.ml.classification.RandomForestClassificationModel.predictRaw(RandomForestClassifier.scala:192)
	at org.apache.spark.ml.classification.RandomForestClassificationModel.predictRaw(RandomForestClassifier.scala:148)
	at org.apache.spark.ml.classification.ProbabilisticClassificationModel$$anonfun$1.apply(ProbabilisticClassifier.scala:112)
	at org.apache.spark.ml.classification.ProbabilisticClassificationModel$$anonfun$1.apply(ProbabilisticClassifier.scala:111)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:370)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:246)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:240)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:784)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:784)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:85)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1450)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1438)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1437)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1437)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:811)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1659)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1618)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1607)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:632)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1871)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1884)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1897)
	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:347)
	at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:39)
	at org.apache.spark.sql.Dataset$$anonfun$org$apache$spark$sql$Dataset$$execute$1$1.apply(Dataset.scala:2183)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:57)
	at org.apache.spark.sql.Dataset.withNewExecutionId(Dataset.scala:2532)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$execute$1(Dataset.scala:2182)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collect(Dataset.scala:2189)
	at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:1925)
	at org.apache.spark.sql.Dataset$$anonfun$head$1.apply(Dataset.scala:1924)
	at org.apache.spark.sql.Dataset.withTypedCallback(Dataset.scala:2562)
	at org.apache.spark.sql.Dataset.head(Dataset.scala:1924)
	at org.apache.spark.sql.Dataset.take(Dataset.scala:2139)
	at org.apache.spark.sql.Dataset.showString(Dataset.scala:239)
	at org.apache.spark.sql.Dataset.show(Dataset.scala:526)
	at org.apache.spark.sql.Dataset.show(Dataset.scala:486)
	at org.apache.spark.sql.Dataset.show(Dataset.scala:495)
	at org.cognizant.spark.ml.model.TriageBot_RFTest$.main(TriageBot_RFTest.scala:87)
	at org.cognizant.spark.ml.model.TriageBot_RFTest.main(TriageBot_RFTest.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.IndexOutOfBoundsException: 200 not in [0,200)
	at breeze.linalg.SparseVector$mcD$sp.apply$mcD$sp(SparseVector.scala:74)
	at breeze.linalg.SparseVector$mcD$sp.apply(SparseVector.scala:73)
	at breeze.linalg.SparseVector$mcD$sp.apply(SparseVector.scala:49)
	at breeze.linalg.TensorLike$class.apply$mcID$sp(Tensor.scala:94)
	at breeze.linalg.SparseVector.apply$mcID$sp(SparseVector.scala:49)
	at org.apache.spark.ml.linalg.Vector$class.apply(Vectors.scala:102)
	at org.apache.spark.ml.linalg.SparseVector.apply(Vectors.scala:558)
	at org.apache.spark.ml.tree.ContinuousSplit.shouldGoLeft(Split.scala:161)
	at org.apache.spark.ml.tree.InternalNode.predictImpl(Node.scala:171)
	at org.apache.spark.ml.tree.InternalNode.predictImpl(Node.scala:172)
	at org.apache.spark.ml.tree.InternalNode.predictImpl(Node.scala:172)
	at org.apache.spark.ml.tree.InternalNode.predictImpl(Node.scala:172)
	at org.apache.spark.ml.tree.InternalNode.predictImpl(Node.scala:172)
	at org.apache.spark.ml.tree.InternalNode.predictImpl(Node.scala:172)
	at org.apache.spark.ml.tree.InternalNode.predictImpl(Node.scala:172)
	at org.apache.spark.ml.tree.InternalNode.predictImpl(Node.scala:172)
	at org.apache.spark.ml.tree.InternalNode.predictImpl(Node.scala:172)
	at org.apache.spark.ml.tree.InternalNode.predictImpl(Node.scala:172)
	at org.apache.spark.ml.classification.RandomForestClassificationModel$$anonfun$predictRaw$1.apply(RandomForestClassifier.scala:193)
	at org.apache.spark.ml.classification.RandomForestClassificationModel$$anonfun$predictRaw$1.apply(RandomForestClassifier.scala:192)
	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.IndexedSeqLike$$anon$1.foreach(IndexedSeqLike.scala:52)
	at org.apache.spark.ml.classification.RandomForestClassificationModel.predictRaw(RandomForestClassifier.scala:192)
	at org.apache.spark.ml.classification.RandomForestClassificationModel.predictRaw(RandomForestClassifier.scala:148)
	at org.apache.spark.ml.classification.ProbabilisticClassificationModel$$anonfun$1.apply(ProbabilisticClassifier.scala:112)
	at org.apache.spark.ml.classification.ProbabilisticClassificationModel$$anonfun$1.apply(ProbabilisticClassifier.scala:111)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIterator.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$8$$anon$1.hasNext(WholeStageCodegenExec.scala:370)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:246)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$4.apply(SparkPlan.scala:240)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:784)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsInternal$1$$anonfun$apply$24.apply(RDD.scala:784)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:85)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

Process finished with exit code 1

``` 

### Version Info

OS:         :  
JVM         :  
Hadoop/Spark:  
ES-Hadoop   :  
ES          :

**Comment by jbaiera** [comment]
@Supriya-Pasham This does not seem to be an ES-Hadoop related problem. Could you update the ticket with the required information from the template and a description of the problem you're running into?

**Comment by jbaiera** [comment]
This does not look germane to this project and there has been no response. If there are any questions about errors that you are seeing in the framework, we'd prefer that people discuss them on the [forums](https://discuss.elastic.co/c/elasticsearch-and-hadoop) before making a bug ticket.
