### ISSUE TITLE
org.apache.pig.backend.executionengine.ExecException

### ISSUE THREAD

**Issue by bitian** [elastic/elasticsearch-hadoop#983]
An error occurred while I was running the following program. I found that the error was caused by the red line.The version I installed is as follows:hadoop2.8,pig0.16.0,elasticsearch-hadoop-5.3.2,elasticsearch5.3.2,and I put elasticsearch-hadoop.* jar files in the pig folder.
![image](https://cloud.githubusercontent.com/assets/14858638/25770127/a44e4e62-325f-11e7-88ef-a36b49b7252a.png)
the error logs as below:
2017-05-05 22:07:01,986 [LocalJobRunner Map Task Executor #0] INFO  org.apache.pig.builtin.TextLoader - Using PigTextInputFormat
2017-05-05 22:07:02,065 [LocalJobRunner Map Task Executor #0] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigRecordReader - Current split being processed file:/home/data_program/access2.log:0+460
2017-05-05 22:07:02,398 [LocalJobRunner Map Task Executor #0] INFO  org.apache.pig.impl.util.SpillableMemoryManager - Selected heap (Tenured Gen) of size 699072512 to monitor. collectionUsageThreshold = 489350752, usageThreshold = 489350752
2017-05-05 22:07:02,452 [LocalJobRunner Map Task Executor #0] INFO  org.apache.pig.data.SchemaTupleBackend - Key [pig.schematuple] was not set... will not generate code.
2017-05-05 22:07:02,706 [LocalJobRunner Map Task Executor #0] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigMapOnly$Map - Aliases being processed per job phase (AliasName[line,offset]): M: RAW_LOGS[4,11],LOGS_BASE[-1,-1],A[19,4] C:  R: 
2017-05-05 22:07:03,142 [LocalJobRunner Map Task Executor #0] INFO  org.elasticsearch.hadoop.util.Version - Elasticsearch Hadoop v5.3.2 [d4a72b6494]
2017-05-05 22:07:03,408 [Thread-20] INFO  org.apache.hadoop.mapred.LocalJobRunner - map task executor complete.
2017-05-05 22:07:03,517 [Thread-20] WARN  org.apache.hadoop.mapred.LocalJobRunner - job_local1019515973_0001
java.lang.Exception: java.lang.NoClassDefFoundError: org/apache/commons/httpclient/protocol/ProtocolSocketFactory
	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:489)
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:549)
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/httpclient/protocol/ProtocolSocketFactory
	at org.elasticsearch.hadoop.rest.commonshttp.CommonsHttpTransportFactory.create(CommonsHttpTransportFactory.java:39)
	at org.elasticsearch.hadoop.rest.NetworkClient.selectNextNode(NetworkClient.java:99)
	at org.elasticsearch.hadoop.rest.NetworkClient.<init>(NetworkClient.java:82)
	at org.elasticsearch.hadoop.rest.NetworkClient.<init>(NetworkClient.java:59)
	at org.elasticsearch.hadoop.rest.RestClient.<init>(RestClient.java:92)
	at org.elasticsearch.hadoop.rest.InitializationUtils.discoverEsVersion(InitializationUtils.java:240)
	at org.elasticsearch.hadoop.rest.RestService.createWriter(RestService.java:546)
	at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.init(EsOutputFormat.java:173)
	at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.write(EsOutputFormat.java:149)
	at org.elasticsearch.hadoop.pig.EsStorage.putNext(EsStorage.java:192)
	at org.apache.pig.backend.hadoop.executionengine.physicalLayer.relationalOperators.StoreFuncDecorator.putNext(StoreFuncDecorator.java:75)
	at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigOutputFormat$PigRecordWriter.write(PigOutputFormat.java:144)
	at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigOutputFormat$PigRecordWriter.write(PigOutputFormat.java:97)
	at org.apache.hadoop.mapred.MapTask$NewDirectOutputCollector.write(MapTask.java:658)
	at org.apache.hadoop.mapreduce.task.TaskInputOutputContextImpl.write(TaskInputOutputContextImpl.java:89)
	at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.write(WrappedMapper.java:112)
	at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigMapOnly$Map.collect(PigMapOnly.java:48)
	at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigGenericMapBase.runPipeline(PigGenericMapBase.java:282)
	at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigGenericMapBase.map(PigGenericMapBase.java:275)
	at org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.PigGenericMapBase.map(PigGenericMapBase.java:65)
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:146)
	at org.apache.hadoop.mapred.MapTask.runNewMapper(MapTask.java:787)
	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:341)
	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:270)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.httpclient.protocol.ProtocolSocketFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 29 more
2017-05-05 22:07:03,806 [main] WARN  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - Ooops! Some job has failed! Specify -stop_on_failure if you want Pig to stop immediately on failure.
2017-05-05 22:07:03,806 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - job job_local1019515973_0001 has failed! Stop running all dependent jobs
2017-05-05 22:07:03,807 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - 100% complete
2017-05-05 22:07:03,848 [main] INFO  org.apache.hadoop.metrics.jvm.JvmMetrics - Cannot initialize JVM Metrics with processName=JobTracker, sessionId= - already initialized
2017-05-05 22:07:03,948 [main] INFO  org.apache.hadoop.metrics.jvm.JvmMetrics - Cannot initialize JVM Metrics with processName=JobTracker, sessionId= - already initialized
2017-05-05 22:07:03,969 [main] ERROR org.apache.pig.tools.pigstats.mapreduce.MRPigStatsUtil - 1 map reduce job(s) failed!
2017-05-05 22:07:04,018 [main] INFO  org.apache.pig.tools.pigstats.mapreduce.SimplePigStats - Script Statistics: 

HadoopVersion	PigVersion	UserId	StartedAt	FinishedAt	Features
2.8.0	0.16.0	root	2017-05-05 22:06:46	2017-05-05 22:07:03	UNKNOWN

Failed!

Failed Jobs:
JobId	Alias	Feature	Message	Outputs
job_local1019515973_0001	A,LOGS_BASE,RAW_LOGS	MAP_ONLY	Message: Job failed!	home/data_program/log,

Input(s):
Failed to read data from "/home/data_program/access2.log"

Output(s):
Failed to produce result in "home/data_program/log"

Counters:
Total records written : 0
Total bytes written : 0
Spillable Memory Manager spill count : 0
Total bags proactively spilled: 0
Total records proactively spilled: 0

Job DAG:
job_local1019515973_0001

2017-05-05 22:07:04,024 [main] INFO  org.apache.pig.backend.hadoop.executionengine.mapReduceLayer.MapReduceLauncher - Failed!
2017-05-05 22:07:04,176 [main] ERROR org.apache.pig.tools.grunt.GruntParser - ERROR 2244: Job job_local1019515973_0001 failed, hadoop does not return any error message
Details at logfile: /home/data_program/pig_1494047176088.log
2017-05-05 22:07:04,658 [main] INFO  org.apache.pig.Main - Pig script completed in 1 minute, 2 seconds and 559 milliseconds (62559 ms)

inthe logfile(/home/data_program/pig_1494047176088.log),contents as below:
![image](https://cloud.githubusercontent.com/assets/14858638/25770176/43d6e11e-3261-11e7-96dc-6507927b9862.png)

I don't know what went wrong. Can you help me?thanks!

**Comment by jbaiera** [comment]
@bitian Could you link which version of the Apache HttpClient you are using?

**Comment by bitian** [comment]
I don't know how to use Apache HttpClient,I only put commons-httpclient-3.1.jar file in the pig folder which contain all elasticsearch-hadoop.* jar files.Is that a error?

**Comment by jbaiera** [comment]
Could you try with commons-httpclient version 3.0.1? My concern here is that you are using Hadoop 2.8 which is a minor release above what we currently test on for the project. Do you see the same problems if executing against a cluster based on Hadoop 2.7.1?

**Comment by jbaiera** [comment]
Sorry, that issue close was a mis-click on my part.

**Comment by zackehh** [comment]
I also saw issues with `httpclient` classes missing on 2.8.x, works just fine on 2.7.x:

```
java.lang.Exception: java.lang.NoClassDefFoundError: org/apache/commons/httpclient/HttpConnectionManager
    at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:489)
    at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:556)
Caused by: java.lang.NoClassDefFoundError: org/apache/commons/httpclient/HttpConnectionManager
    at org.elasticsearch.hadoop.rest.commonshttp.CommonsHttpTransportFactory.create(CommonsHttpTransportFactory.java:39)
    at org.elasticsearch.hadoop.rest.NetworkClient.selectNextNode(NetworkClient.java:99)
    at org.elasticsearch.hadoop.rest.NetworkClient.<init>(NetworkClient.java:82)
    at org.elasticsearch.hadoop.rest.NetworkClient.<init>(NetworkClient.java:59)
    at org.elasticsearch.hadoop.rest.RestClient.<init>(RestClient.java:92)
    at org.elasticsearch.hadoop.rest.InitializationUtils.discoverEsVersion(InitializationUtils.java:273)
    at org.elasticsearch.hadoop.rest.RestService.createWriter(RestService.java:572)
    at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.init(EsOutputFormat.java:173)
    at org.elasticsearch.hadoop.mr.EsOutputFormat$EsRecordWriter.write(EsOutputFormat.java:149)
    at org.apache.hadoop.mapred.ReduceTask$NewTrackingRecordWriter.write(ReduceTask.java:558)
    at org.apache.hadoop.mapreduce.task.TaskInputOutputContextImpl.write(TaskInputOutputContextImpl.java:89)
    at org.apache.hadoop.mapreduce.lib.reduce.WrappedReducer$Context.write(WrappedReducer.java:105)
```

**Comment by jbaiera** [comment]
Hadoop 2.8 has removed apache httpclient as a provided dependency, and thus the connector is going to fail on that version due to the lack of libraries. I'll open a ticket to address this, as we do not yet support Hadoop 2.8.

**Comment by jbaiera** [comment]
I openned #1004 to track this issue.

**Comment by zackehh** [comment]
Cool, thanks @jbaiera!

**Comment by vkg0312** [comment]
Resolved the issue by downloading a org.apache.commons.httpclien jar from my drive:
https://drive.google.com/file/d/1Ws8R75qZlpnbM1aTsyEOnqxHPGXcs3Aq/view?usp=sharing
create an ext_jars folder inside your hadoop/share/hadoop

unzip it and copy paste jar into the haddoop/share/hadoop/ext_jars
and also add the jar into hadoop/share/hadoop/yarn and hadoop/share/hadoop/mapreduce too
I think this will fix the issue
